cdap-ui/app/directives/navbar/navbar.html, cdap-ui/app/styles/themes/cdap/header.less
*  Adds white background to entire dropdown toggle
*  Fixes padding issue affecting focus state of Settings dropdown
*  Adds caret to Settings dropdown on smaller devices
*  Caret now transitions/rotates -90deg when dropdowns are expanded
=> fixes padding issue affecting Settings dropdown

cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/viewconfig.html
=> [CDAP-3098] add download button for adapter config

cdap-cli/bin/cdap-cli.bat, cdap-data-fabric/bin/tx-debugger.bat, cdap-standalone/bin/cdap.bat, cdap-standalone/bin/cdap.sh
Updates shell scripts to use java 8.
=> CDAP-3074 java versions to support Java 8

cdap-docs/developers-manual/build.sh, cdap-docs/developers-manual/source/building-blocks/index.rst, cdap-docs/developers-manual/source/building-blocks/workflows.rst, cdap-docs/reference-manual/source/http-restful-api/index.rst, cdap-docs/reference-manual/source/http-restful-api/workflow.rst
Documentation for Workflow Tokens
The RESTful API examples need updated samples of the returned tokens.
- [Developers' Manual: Workflow](http://docs-staging.cask.co/cdap/3.1.0-SNAPSHOT-feature-r3.1_3015/en/developers-manual/building-blocks/workflows.html)
- [Ref Manual: Workflow RESTful API](http://docs-staging.cask.co/cdap/3.1.0-SNAPSHOT-feature-r3.1_3015/en/reference-manual/http-restful-api/workflow.html)
=> Issue 3015: Add Workflow Token documentation

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java
https://issues.cask.co/browse/CDAP-3106
http://builds.cask.co/browse/CDAP-DUT2381
Integration test ExploreTest passed against a CDH 5.4.2 cluster.
=> CDAP-3106: Improve locating hive-exec.jar

cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateDatasetInstanceCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/util/ArgumentParser.java
https://issues.cask.co/browse/CDAP-2925
http://builds.cask.co/browse/CDAP-RBT381
=> CDAP-2925: Document how to create dataset with properties better

cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js
*  Moves Settings icon to the top of the right group side panel
=> moves Settings icon to top of panel

cdap-ui/app/features/adapters/routes.js
=> [CDAP-3098] fix breadcrumb label for already created etl apps

cdap-ui/app/features/adapters/controllers/create-new-ctrl.js, cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/services/plumber/my-plumb-service.js
*  Adds custom class to adapter modals
*  Moves all adapter modal styling under new helper class to prevent unwanted styling of modals in other parts of the UI
*  Changes width (on md. width devices and larger) to 75% to accommodate responsive resizing
=> adds custom class to adapter modals

cdap-ui/app/features/adapters/adapters.less, cdap-ui/app/features/adapters/templates/create.html
=> add ETL type on canvas

cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html, cdap-ui/templates/ETLRealtime/Kafka.json
=> ui fix for kafka source

cdap-ui/app/services/plumber/my-plumb-service.js
=> stack plugins when multiple are added

cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/index.rst, cdap-docs/examples-manual/source/examples/log-analysis.rst
- All the commands in the docs has been tested. 
- There is no support for stopping wokflow from CLI at this point.
=> CDAP-2705: LogAnalysisApp documentation

cdap-ui/app/directives/group-side-panel/group-side-panel.less, cdap-ui/app/directives/plumb/my-plumb.html, cdap-ui/app/features/adapters/services/adapter-error-factory.js, cdap-ui/app/features/adapters/templates/create.html, cdap-ui/app/services/plumber/my-plumb-service.js, cdap-ui/app/styles/themes/cdap/theme.less
- Show ETL type on draft
- Validate name to only contain alphabets, numbers, and underscore
- Input Schema tooltip break-word
- Initialize instance/schedule
- Node error tooltip color change
- Fix circular connection validation
=> [CDAP-3149] Fix/ui adapter fixes post merge

cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.html, cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.js, cdap-ui/app/features/adapters/module.js, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html, cdap-ui/app/services/plumber/my-plumb-service.js
=> add clf and syslog implicit schema

cdap-examples/deploy_pom.xml
JIRA: https://issues.cask.co/browse/CDAP-3151
=> Use JDK 1.7

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreServiceUtilsTest.java
JIRA - https://issues.cask.co/browse/CDAP-3148
=> CDAP-3148 Fix mapreduce.application.classpath for HDP 2.2.x clusters for explore

cdap-distributions/bin/build_parcel.sh
=> fix typo in component name

cdap-common/src/main/java/co/cask/cdap/common/zookeeper/coordination/ResourceCoordinator.java
- Instead of using the old set of discoverables in performAssignment, always use the live ServiceDiscovered to get the latest sets of discoverables
- This fixes the case where the coordinator needs to fetch the old assignment while the set is empty, followed by an update in the set of discoverables to become non-empty.
=> (CDAP-3145) Fix a bug in ResourceCoordinator.

cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/overview/templates/data-apps.html
*  Updates application type
*  Updates corresponding icons
=> updates application types and icons

cdap-api/src/main/java/co/cask/cdap/api/workflow/NodeValue.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/Value.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowToken.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowTokenTest.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/resources/cdap-default.xml
Build: http://builds.cask.co/browse/CDAP-RBT389
Jira: [CDAP-2895](https://issues.cask.co/browse/CDAP-2895)
=> [CDAP-2895] Add a max permissible size for Workflow Token

cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
=> fix required fields

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreServiceUtilsTest.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
JIRA - https://issues.cask.co/browse/CDAP-3148
=> CDAP-3148 Create temp dir in master's local data dir

cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html, cdap-ui/app/services/plumber/my-plumb-service.js
=> propagate implicit schema

cdap-ui/app/features/adapters/controllers/create-new-ctrl.js, cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/partial/confirm.html, cdap-ui/app/services/modal-confirm.js, cdap-ui/app/services/plumber/my-plumb-service.js
=> add confirm if user cancel after editing plugin

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/developers-manual/source/data-exploration/index.rst
Fix for https://issues.cask.co/browse/CDAP-3162
Staged at: [Installation](http://docs-staging.cask.co/staging/cdap/3.1.0-SNAPSHOT-feature-r3.1_Secure_Explore/en/admin-manual/installation/installation.html#configuration)
=> Setting up the Explore Service on Secure Hadoop Clusters

cdap-docs/application-templates/source/etl/templates/sources/batch/file.rst, cdap-docs/application-templates/source/etl/templates/sources/real-time/amazonsqs.rst, cdap-docs/application-templates/source/etl/templates/transformations/logparser.rst
JIRA - https://issues.cask.co/browse/CDAP-3156, https://issues.cask.co/browse/CDAP-3157, https://issues.cask.co/browse/CDAP-3158.
Added documentation for FileBatchSource, LogParserTransform, and SqsSource.
=> Add ETL Doc use cases and examples

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java
https://issues.cask.co/browse/CDAP-2918
build : http://builds.cask.co/browse/CDAP-RBT400-1
=> exclude all hive jars from hive's mapreduce containers

cdap-docs/admin-manual/source/installation/installation.rst
JIRA - https://issues.cask.co/browse/CDAP-3173
=> CDAP-3173 Update upgrade document

cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java
JIRA https://issues.cask.co/browse/CDAP-3173
=> CDAP-3173 Add fastutil classes to transaction co-processor jar

cdap-ui/app/features/adapters/templates/detail.html, cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/styles/themes/cdap/theme.less
=> fix tooltip for long app name

cdap-ui/app/features/adapters/controllers/create/plugin-property-edit-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
Adds docs html page to the plugin modal.
=> Adds the info button to plugin modal to show the docs page for each plugin

cdap-ui/app/features/adapters/templates/list.html, cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/overview/templates/data-apps.html
=> fix icons for ETLBatch and ETLRealtime

cdap-ui/app/directives/maxlength/maxlength.js, cdap-ui/app/features/adapters/templates/create/metadata.html, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
=> [CDAP-3209] [CDAP-3193] Fix/ui adapter fix bugs

cdap-ui/app/features/adapters/module.js
Otherwise writing to TPFSAvro sink fails.
=> CDAP-3230 fix the order of clf fields

cdap-ui/app/features/adapters/module.js
JIRA : https://issues.cask.co/browse/CDAP-3235
=> Fix syslog schema field order

cdap-docs/integrations/source/partners/cloudera/configuring.rst, cdap-docs/integrations/source/partners/cloudera/step-by-step-cloudera.rst
Staged at:
- [Configuring and Installing CDAP using Cloudera Manager](http://docs-staging.cask.co/staging/cdap/3.1.0-SNAPSHOT-feature-r3.1_Cloudera/en/integrations/partners/cloudera/configuring.html)
- [Cloudera Add Service Wizard, Step-by-Step](http://docs-staging.cask.co/staging/cdap/3.1.0-SNAPSHOT-feature-r3.1_Cloudera/en/integrations/partners/cloudera/step-by-step-cloudera.html)
=> Improve Cloudera instructions.

cdap-ui/app/directives/view-queries/view-queries.html, cdap-ui/app/directives/view-queries/view-queries.js, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js, cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.js, cdap-ui/app/features/workflows/templates/tabs/schedules.html, cdap-ui/app/main.js, cdap-ui/app/services/plumber/my-plumb-service.js, cdap-ui/server/express.js
- Fix downloading large query
- Fix missing description on created apps
- Fix nullable schema propagation
- Fix workflow schedules view when there is no schedule
=> [CDAP-3188] [CDAP-3231] [CDAP-3236] [CDAP-3245] Fix/ui explore download queries

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/kafka/Kafka08SimpleApiConsumer.java
Currently we use hacky classloader way to instantiate Apache Twill ZKBrokerService helper class in
Kafka08SimpleApiConsumer class because the constructor was package private.
With updated dependency on Apache Twill in CDAP we now could just simply call the constructor.
=> [CDAP-3251] Remove classloader approach to create instance of Apache Twill ZKBrokerService class

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/ElementType.java
https://issues.cask.co/browse/CDAP-3147
http://builds.cask.co/browse/CDAP-DUT2443
=> CDAP-3147: CLI stop workflow

cdap-docs/reference-manual/source/release-notes.rst
Re-organzied and added sub-sections to "New Features".
[Staged Release Notes](http://docs-staging.cask.co/staging/cdap/3.1.0-feature-r3.1_Release_Notes_Revised/en/reference-manual/release-notes.html#new-features)
=> Revised Release Notes

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/KafkaMessageCallback.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaver.java
* # of processed messages
* lag of processing, in ms
=> CDAP-1936: Minimal instrumentation of logs processing

cdap-api/src/main/java/co/cask/cdap/api/data/format/Formats.java, cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java, cdap-cli/src/main/java/co/cask/cdap/cli/DefaultCompleters.java, cdap-cli/src/main/java/co/cask/cdap/cli/completer/StringsCompleter.java
https://issues.cask.co/browse/CDAP-2521
http://builds.cask.co/browse/CDAP-DUT2442
=> CDAP-2521: CLI autocomplete for stream format

cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.html, cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.js, cdap-ui/templates/common/Projection.json
=> [CDAP-2723] remove delimiters from view for projection transform

cdap-notifications/src/test/java/co/cask/cdap/notifications/NotificationTest.java, cdap-notifications/src/test/java/co/cask/cdap/notifications/kafka/KafkaNotificationTest.java
- Cleanup highly duplicated code
- Make assertions thread safe
=> Refactor notification test code to speed up test

cdap-ui/app/features/admin/admin.less, cdap-ui/app/styles/fonts.less, cdap-ui/app/styles/themes/cdap/buttons.less
*  Modifies .btn-styles mixin to fix issue where \<button> elements were getting "stuck" in active/focus state
*  Adds correct default styling for .btn-default class
=> modifies .btn-styles mixin to fix button state styling

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
https://issues.cask.co/browse/CDAP-1697
http://builds.cask.co/browse/CDAP-DUT2471
Part 1/2 for addressing CDAP-1697.
=> CDAP-1697: Fix exception handling to close transaction, hive session, and hive operation

cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaver.java
=> use proper system namespace id

cdap-ui/app/directives/error/error-popover.html, cdap-ui/app/services/alert.js
=> [CDAP-2809] add date to error message

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
https://issues.cask.co/browse/CDAP-2331
http://builds.cask.co/browse/CDAP-DUT2470
=> CDAP-2331: Respond with 404 when listing apps in non-existent namespace

cdap-ui/app/features/adapters/controllers/create-new-ctrl.js, cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js, cdap-ui/app/services/plumber/my-plumb-service.js
=> [CDAP-3305] add confirmation when exiting adapter create with unsaved changes

cdap-docs/deploy.sh
This includes SSH host key checking fix.
=> Copy deploy.sh from develop

cdap-ui/app/features/login/routes.js, cdap-ui/app/services/auth.js
secure cluster: secure22477-1000
=> [CDAP-3313] fix reroute issue on refresh

cdap-ui/app/directives/fileselect/fileselect.js, cdap-ui/app/features/flows/templates/tabs/runs/streams/detail.html, cdap-ui/app/services/app-uploader.js, cdap-ui/app/services/file-uploader.js, cdap-ui/app/services/streams/my-streams-service.js
=> [CDAP-2514] add upload csv to streams

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/ElasticsearchSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/sink/RealtimeElasticsearchSink.java
In response to https://issues.cask.co/browse/CDAP-3352.
=> Updated Elasticsearch plugin documentation

cdap-cli/README.rst
https://issues.cask.co/browse/CDAP-3357
=> CDAP-3357: Documentation for developing CLI

cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java, cdap-docs/reference-manual/source/release-notes.rst, cdap-proto/src/main/java/co/cask/cdap/proto/ApplicationRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/DatasetRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/StreamRecord.java
=> Revert "CDAP-3356 remove deprecated 'id' field from RESTful APIs"

cdap-cli/src/main/java/co/cask/cdap/cli/command/SetStreamFormatCommand.java, cdap-docs/reference-manual/source/cli-api.rst
https://issues.cask.co/browse/CDAP-3270
http://builds.cask.co/browse/CDAP-DUT2497
=> CDAP-3270: CLI set stream format documentation

cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js, cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.js, cdap-ui/app/features/adapters/controllers/create-new-ctrl.js, cdap-ui/app/features/adapters/controllers/create/plugin-property-edit-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
=> [CDAP-3332] add ability to clear output schema

cdap-ui/templates/ETLRealtime/Stream.json
This fix can go in to 3.1.1 if/when we release them.
=> fix json for stream ETLRealtime

cdap-ui/app/directives/group-side-panel/group-side-panel.less
*  Adds media query to set dynamic height on item body of Source, Transform, and Sink
*  Adds media query to adjust height of right side panel item headings (collapsed state)
=> adds media queries to adjust height of side panels

cdap-ui/app/directives/widget-container/widget-dataset-selector/widget-dataset-selector.js, cdap-ui/app/features/admin/controllers/namespace/templates-ctrl.js, cdap-ui/app/features/admin/routes.js, cdap-ui/app/features/admin/templates/namespace/templates-list.html, cdap-ui/app/features/admin/templates/namespace/templates.html
=> [CDAP-3333] Predefined Plugins Phase 2

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
* Cherry picking changes for logback container fix CDAP-3362 into release/3.0
=> Use the correct API to check for file existence.

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java
https://issues.cask.co/browse/CDAP-2428
http://builds.cask.co/browse/CDAP-DUT2514
=> CDAP-2428: Suppress logback logging in CLI

cdap-docs/reference-manual/source/release-notes.rst
Staged at: [Release Notes](http://docs-staging.cask.co/staging/cdap/3.1.0-feature-r3.1.1_release_notes/en/reference-manual/release-notes.html)
Building...
=> Release 3.1.1. Release Notes.

cdap-ui/server/express.js
-Fixes the app upload api url in node server.
=> Fixes url construction for uploading an app in express server

cdap-ui/app/features/adapters/controllers/tabs/runs/tabs/status-ctrl.js
- Hide empty table header in adapter metrics view
=> [CDAP-3397] Fixes empty table headers for adapter metrics in adapter detailed view

cdap-distributions/bin/build_artifact_upload.sh
applying build-related ssh hostkey fix to release branch
=> turn off host key check on initial ssh

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
- Added filter to only pickup @Plugin class only without loading every classes inside a JAR.
=> Improve logic for plugin inspection

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ArtifactClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java
Artifact deletion can be unsafe and it is assumed the user knows
exactly what they are doing.
=> CDAP-3367 add a way to delete artifacts

cdap-distributions/pom.xml, pom.xml
Also, make copyright lines consistent and all using `©`
=> Improve package descriptions for RPM/DEB

cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowSpecification.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowStatsSLAHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/WorkflowDataset.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowStatsSLAHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/PercentileInformation.java, cdap-proto/src/main/java/co/cask/cdap/proto/WorkflowStatistics.java
This PR is a WIP. It just has the implementation for the first endpoint, which is the /statistics endpoint. 
https://wiki.cask.co/display/CE/Workflow+Diagnostics+Tool
http://builds.cask.co/browse/CDAP-DUT2494
https://issues.cask.co/browse/CDAP-3371
=> Workflow Stats SLA's

cdap-docs/_common/_themes/cdap/search.html, cdap-docs/_common/_themes/cdap/static/searchtools.js_t
Fixes https://issues.cask.co/browse/CDAP-3438
Removes commented-out HTML and Javascript code that was not being used, and that created a duplicate message that wasn't being used.
Corrected the Javascript that produced a message that was being used when a search failed to produce any results.
Example of current message: [Search with Error Message](http://docs-staging.cask.co/staging/cdap/3.2.0-SNAPSHOT/en/search.html?q=common-&check_keywords=yes&area=default)
Example of revised message: [Search with Error Message](http://docs-staging.cask.co/staging/cdap/3.2.0-SNAPSHOT-feature-3.2_3438_Search_Error/en/search.html?q=common-&check_keywords=yes&area=default)
Currently building...
=> Improve Documentation Search Error Response

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/ActiveOperationRemovalHandler.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12CDH5ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive13ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive14ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/InactiveOperationInfo.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/OperationInfo.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/ReadOnlyOperationInfo.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/ReadWriteOperationInfo.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceInvalidateTxTest.java
https://issues.cask.co/browse/CDAP-1697
http://builds.cask.co/browse/CDAP-DUT2481
=> CDAP-1697: Explore Service commits transaction even when operation fails

cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/increment/hbase94/IncrementSummingScanner.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementSummingScannerTest.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScanner.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScannerTest.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScanner.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScannerTest.java
JIRA - https://issues.cask.co/browse/CDAP-3449
Porting changes from https://github.com/caskdata/cdap/pull/3645 to 3.0 branch.
=> CDAP-3449 Handle previous increment in all cases in readless increment co-processor

cdap-docs/reference-manual/source/release-notes.rst
=> Draft release notes for Release 3.0.4.

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java
* Fixed cases where the upgrade tool doesn't update versions for all tables.
=> Upgrade tool fix

cdap-docs/admin-manual/source/operations/tx-maintenance.rst
This needs to be ported to 3.1 and develop.
=> Update transaction service maintenance page

cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScanner.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScannerTest.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScanner.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScannerTest.java, cdap-hbase-compat-1.0-cdh/src/main/java/co/cask/cdap/data2/increment/hbase10cdh/IncrementSummingScanner.java, cdap-hbase-compat-1.0-cdh/src/test/java/co/cask/cdap/data2/increment/hbase10cdh/IncrementSummingScannerTest.java, cdap-hbase-compat-1.0/src/main/java/co/cask/cdap/data2/increment/hbase10/IncrementSummingScanner.java, cdap-hbase-compat-1.0/src/test/java/co/cask/cdap/data2/increment/hbase10/IncrementSummingScannerTest.java
JIRA contains details of the fix - https://issues.cask.co/browse/CDAP-3449
=> Handle previous increment in all cases in readless increment co-processor

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
Otherwise, we get the highest version.
=> Fetch specified SDK for VM

cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/template/etl/realtime/RealtimeElasticsearchSinkTest.java
Elasticsearch Realtime test was failing because it timed out before the records were written, so I increased the time. This is a temporary fix and will be resolved once adapters more fully become applications and thus have access to metrics.
https://issues.cask.co/browse/CDAP-3459
http://builds.cask.co/browse/CDAP-DUT2582-2
=> Changed timeout to avoid ES realtime test failures

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
=> Update mirror to OSUOSL

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java
* Porting the upgrade tool fix for 3.0.4 into release/3.1
=> Upgrade tool fix from 3.0.4 to release/3.1

cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java, cdap-master/src/main/java/co/cask/cdap/data/tools/SimpleHBaseQueueDebugger.java, cdap-master/src/test/java/co/cask/cdap/data/tools/flow/HBaseQueueDebuggerTest.java
https://issues.cask.co/browse/CDAP-3419
http://builds.cask.co/browse/CDAP-RBT415
=> CDAP-3419: Record min write pointer in HBaseQueueDebugger

cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
- Remove alerts from no runs workflow (cursor already showing disabled)
=> [CDAP-3142] Remove blue alerts from workflow

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ApplicationLifecycleServiceTest.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
The upgrade will create artifacts from existing applications and
update application metadata to point to those artifacts
=> CDAP-3451 adding CDAP upgrade to v.3.2 for apps

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java
* Port upgrade tool fix to develop
=> Port upgrade tool fix to develop

cdap-ui/app/features/adapters/controllers/create/plugin-property-edit-ctrl.js, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
Adding validation for unique fields in plugin edit output schema
=> [CDAP-3248] add validation schema for unique fields

cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
=> remove unused variable

cdap-ui/app/directives/error/error-popover.html, cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/services/alert.js
**Should be merged after #3722**
=> [CDAP-3512] Fix/ui error order

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextProvider.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java
- In MapReduceContextProvider, we should always get the MapReduceClassLoader from hConf, not Confer
- Do proper resource cleanup for the artifact plugin instantiator
=> Fixed two MR bugs:

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-explore/src/main/java/co/cask/cdap/hive/datasets/DatasetStorageHandler.java, cdap-explore/src/main/java/co/cask/cdap/hive/stream/StreamStorageHandler.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreServiceUtilsTest.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterTwillApplication.java
https://issues.cask.co/browse/CDAP-3452
http://builds.cask.co/browse/CDAP-RBT416
* Also adds some more useful DEBUG logging
* Tested and working using ExploreTest integration test in multi node distributed cluster running secure Hadoop (HDP 2.2.4.2, which has Hive 0.14) and secure CDAP
=> CDAP-3452: Make HiveAuthFactory.loginFromKeytab a no-op

cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/tabs/runs/tabs/status.html
=> remove padding for adapter metrics last column

cdap-ui/app/features/services/controllers/tabs/runs-ctrl.js, cdap-ui/app/features/services/templates/tabs/data.html, cdap-ui/app/features/services/templates/tabs/history.html
*  Removes data and history templates (in lieu of directives used in template defined in runs-ctrl)
=> removes history and data templates

cdap-ui/app/features/services/services.less, cdap-ui/app/styles/themes/cdap.less
*  Adds proper spacing around program description
*  Fixes some button border and color issues
*  Adds right border to the run level row
*  Adds width to runid text so that layout doesn't break when runid text exceeds a certain length
*  Top aligns status color circle and down caret in runid dropdown
=> fixes some minor styling issues in the program detail header + UI view

cdap-docs/admin-manual/source/index.rst, cdap-docs/admin-manual/source/operations/index.rst, cdap-docs/admin-manual/source/operations/tx-maintenance.rst
Port of https://github.com/caskdata/cdap/pull/3744
=> Port PR 3744 (Tx Manager Changes) to 3.1.

cdap-docs/admin-manual/source/index.rst, cdap-docs/admin-manual/source/operations/index.rst, cdap-docs/admin-manual/source/operations/tx-maintenance.rst
Cherry-picking https://github.com/caskdata/cdap/pull/3756 to 3.2.
=> Port PR https://github.com/caskdata/cdap/pull/3744 to 3.2

cdap-docs/developers-manual/source/advanced/class-loading.rst
Fixes per comments in https://github.com/caskdata/cdap/pull/3636.
=> Documentation on Class Loading in CDAP

cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/data-cleansing.rst, cdap-examples/DataCleansing/src/main/java/co/cask/cdap/examples/datacleansing/DataCleansing.java
Update md5 of recently updated files to fix the docs build.
=> Update md5 of recently updated files to fix the docs build.

cdap-ui/app/features/adapters/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/adapters/controllers/create/plugin-edit-form-ctrl.js, cdap-ui/app/features/adapters/controllers/create/rightpanel-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-config-form.html, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-form.html, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-input-schema.html, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-noconfig-form.html, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-noproperty-form.html, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-output-schema.html, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-properties-template.html, cdap-ui/app/services/app/my-app-dag-service.js
Re-organizes plugin edit modal popover to be a little organized.
=> Cleansup plugin modal popover to be a little bit more organized.

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java
Check that dataset service is up, in addition to /system/services/status.
http://builds.cask.co/browse/CDAP-DUT2691-1
=> Check that dataset service is up, in addition to system services' status

cdap-ui/app/directives/breadcrumbs/breadcrumbs.less, cdap-ui/app/features/adapters/controllers/detail-ctrl.js, cdap-ui/app/features/adapters/templates/detail.html, cdap-ui/app/features/flows/controllers/tabs/runs-ctrl.js, cdap-ui/app/features/flows/routes.js, cdap-ui/app/features/flows/templates/detail.html, cdap-ui/app/features/mapreduce/controllers/tabs/run-ctrl.js, cdap-ui/app/features/mapreduce/routes.js, cdap-ui/app/features/mapreduce/templates/detail.html, cdap-ui/app/features/services/controllers/tabs/runs-ctrl.js, cdap-ui/app/features/services/routes.js, cdap-ui/app/features/services/templates/detail.html, cdap-ui/app/features/spark/controllers/tabs/runs-ctrl.js, cdap-ui/app/features/spark/routes.js, cdap-ui/app/features/spark/templates/detail.html, cdap-ui/app/features/workers/controllers/tabs/runs-ctrl.js, cdap-ui/app/features/workers/routes.js, cdap-ui/app/features/workers/templates/detail.html, cdap-ui/app/features/workflows/controllers/tabs/runs-ctrl.js, cdap-ui/app/features/workflows/routes.js, cdap-ui/app/features/workflows/templates/detail.html
*  Adds description to program detail views
*  Adds breadcrumb box shadow
=> adds description to program detail views

cdap-ui/app/features/services/services.less, cdap-ui/app/styles/themes/cdap.less
*  Adds box shadow to button bar
*  Adds green background to Services -> Make Request button when not disabled
=> adds box shadow and background-color to program buttons

cdap-ui/app/styles/themes/cdap.less, cdap-ui/app/styles/themes/cdap/theme.less, cdap-ui/app/styles/variables.less
*  Changes color of program-test variable
*  Adjusts size of program tags
*  Adds correct color for text-success and text-danger
=> fixes colors and tag button padding

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
When doing fix for CDAP-3374 we added access to transaction within transaction to reduce logging messages which cause problems.
This PR removes the nested the call to transactions inside a transaction (call to retrieveProgramIdForRunRecord actually cause call to dataStore which has transaction) for the running run records fixer thread.
Add additional log to debug run records cleaning. Cache the program ids for run ids when filtering for valid program type.
=> CDAP-3435 Program status shows Running even after it is stopped.

cdap-docs/application-templates/source/etl/index.rst, cdap-docs/application-templates/source/etl/templates/transformations/validator.rst, cdap-docs/application-templates/source/etl/templates/validators/core.rst, cdap-docs/application-templates/source/etl/templates/validators/index.rst
Fixes formatting issues of the CoreValidator function table (removed non-ASCII characters).
Added links between the example Validator transform and the CoreValidator.
Added table entries that were missing.
Added text explaining use of the CoreValidator in configuration and Javascript.
=> Fix CoreValidator Table

cdap-ui/app/features/workers/controllers/tabs/runs/tabs/log-ctrl.js, cdap-ui/app/features/workers/templates/detail.html
*  Changes "worker" to "workers" in my-start-stop-button and my-program-status directives
=> fixes data requests for workers

cdap-docs/reference-manual/source/release-notes.rst
Built:
[Release Notes](http://docs-staging.cask.co/staging/cdap/3.1.2-feature-r3.1.2_release_notes/en/reference-manual/release-notes.html#release-3-1-2)
=> Release 3.1.2 release notes.

cdap-docs/reference-manual/source/release-notes.rst
Built:
[Release Notes](http://docs-staging.cask.co/staging/cdap/3.0.5-feature-r3.0.5_release_notes/en/reference-manual/release-notes.html#release-3-0-5)
=> Release notes for Release 3.0.5

cdap-api/src/main/java/co/cask/cdap/api/workflow/AbstractWorkflowAction.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowAction.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowActionConfigurer.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowActionConfigurer.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/WorkflowNodeCreator.java, cdap-app-fabric/src/test/java/co/cask/cdap/SleepingWorkflowApp.java
Build : http://builds.cask.co/browse/CDAP-DUT2705
JIRA : https://issues.cask.co/browse/CDAP-2956
=> CDAP-2956 Switching to configurer style API for WorkflowAction

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryConfigurator.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ApplicationClientTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
has json syntax error
Build : http://builds.cask.co/browse/CDAP-DUT2740
=> CDAP-2869 throw invalid argument exception if the given configuration string

cdap-client-tests/src/test/java/co/cask/cdap/client/ArtifactClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java
Missed a couple places where isSystem was still being used.
Also modifying the test to make sure scope is used.
=> CDAP-3560 changing isSystem to scope in artifact client

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/WorkflowDataset.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointManager.java
also change all places where we check whether result is null
=> [CDAP-2864] add @Nonnull to Table's get methods

cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreHttpClient.java, cdap-explore-client/src/main/java/co/cask/cdap/explore/service/Explore.java, cdap-explore/src/main/java/co/cask/cdap/explore/executor/NamespacedQueryExecutorHttpHandler.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/InactiveOperationInfo.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/OperationInfo.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/ReadOnlyOperationInfo.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/ReadWriteOperationInfo.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceTestRun.java
https://issues.cask.co/browse/CDAP-3514
http://builds.cask.co/browse/CDAP-DUT2657
=> CDAP-3514: Add endpoint to get total count of all queries

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12ExploreService.java
JIRA - https://issues.cask.co/browse/CDAP-3574
=> CDAP-3574 Fix session start in HDP Hive 0.12

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimePartitionedFileSetArguments.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLTPFSTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TPFSSinkConfig.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetAvroSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetParquetSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/Properties.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDefinition.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java, cdap-docs/application-templates/source/etl/templates/sinks/batch/tpfsavro.rst, cdap-docs/application-templates/source/etl/templates/sinks/batch/tpfsparquet.rst, cdap-ui/templates/ETLBatch/TPFSAvro.json, cdap-ui/templates/ETLBatch/TPFSParquet.json
http://builds.cask.co/browse/CDAP-DUT2655-8
=> Allow users to customize how the partitions are stored in directories

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/snapshot/SnapshotCodecCompatibilityTest.java, pom.xml
Build: http://builds.cask.co/browse/CDAP-DUT2687-2
=> Make cdap depend on tephra 0.6.2

cdap-distributions/bin/build_artifact_upload.sh
This brings package bundles to the main upload.
=> Port #3723 to release/3.0

cdap-distributions/bin/build_artifact_upload.sh
This brings package bundles to the main upload.
=> Port #3723 to release/3.1

cdap-docs-gen/pom.xml, cdap-docs-gen/src/main/java/co/cask/cdap/docgen/cli/GenerateCLIDocsTable.java, cdap-docs-gen/src/main/java/co/cask/cdap/docgen/cli/GenerateCLIDocsTableCommand.java, cdap-docs-gen/src/main/java/co/cask/cdap/docgen/client/GenerateClientUsageExample.java, cdap-docs/reference-manual/source/java-client-api.rst, pom.xml
https://issues.cask.co/browse/CDAP-2965
http://builds.cask.co/browse/CDAP-DUT2640
=> CDAP-2965: Update docs to reflect new cdap-client API

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerDriver.java
Build : http://builds.cask.co/browse/CDAP-DUT2738
=> CDAP-2434 More Worker logs

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
Per our discussions, we would like to avoid using NamespacedId.toString for the row key due to possible inconsistencies.
To do this, add new methods to convert from NamespacedId to String and vice versa.
=> Add methods to convert NamespacedId to String and vice versa for Business Metadata dataset.

pom.xml
http://builds.cask.co/browse/CDAP-DUT2785
=> Use common-cli 0.8.0

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/AccessType.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/Lineage.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetDefinition.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/Relation.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageServiceTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
JIRA - https://issues.cask.co/browse/CDAP-3519
TODO: Will add more extensive tests in a follow-up PR.
=> CDAP-3519 First cut of Lineage computation based on Dataset accesses by a Program

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageServiceTest.java
Wrapping Lineage Dataset in a Lineage Store to handle transactions.
=>  CDAP-3519 Adding lineage store

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/SnapshotFileBatchAvroSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/SnapshotFileBatchParquetSink.java
http://builds.cask.co/browse/CDAP-DUT2804-1
RAT : http://builds.cask.co/browse/CDAP-DRC2633-1
=> Fix Checkstyle

cdap-docs/developers-manual/source/data-exploration/streams.rst, cdap-formats/src/main/java/co/cask/cdap/format/DelimitedStringsRecordFormat.java, cdap-formats/src/test/java/co/cask/cdap/format/DelimitedStringsRecordFormatTest.java
https://issues.cask.co/browse/CDAP-3626
http://builds.cask.co/browse/CDAP-DUT2795
=> CDAP-3626: Text wrangler format

cdap-docs/application-templates/source/etl/templates/sinks/batch/snapshotavro.rst, cdap-docs/application-templates/source/etl/templates/sinks/batch/snapshotparquet.rst
Docs for https://github.com/caskdata/cdap/pull/3859
=> Docs for Snapshot File Set Sink

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataRecord.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/BusinessMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/MetadataSearchResultRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/MetadataSearchTargetType.java
CDAP-3523 Add new endpoint of REST APIs for searching metadata using value and key=value to metadata handler.
CDAP-3522 Add IndexedTable based search to the Business Metadata dataset.
Add more descriptive name for internal IndexedTable for business metadata dataset.
=> [CDAP-3523] [CDAP-3522] Implement REST APIs for searching Metadata

cdap-common/src/main/resources/cdap-default.xml
Build:http://builds.cask.co/browse/CDAP-DUT2762-2
=> Add SnapshotCodecV4 in cdap-default

cdap-docs/reference-manual/source/glossary.rst, cdap-docs/reference-manual/source/http-restful-api/metrics.rst
Additions to glossary, and additions to metrics.
Fix for https://issues.cask.co/browse/CDAP-3277
Building:
- Metrics RESTful API
- Glossary
=> Add details on Consumer Context to documentation

cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/app/etl/batch/ETLMapReduce.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/app/etl/batch/BaseETLBatchTest.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/app/etl/batch/ETLMapReduceTest.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/Constants.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/PipelineRegisterer.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/SinkInfo.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetAvroSink.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/app/etl/realtime/ETLWorker.java
JIRA : https://issues.cask.co/browse/CDAP-3480
=> CDAP-3480 integration error dataset for transforms and sinks for ETLBatch

cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/DistributedMRJobInfoFetcher.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/LocalMRJobInfoFetcher.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/MRJobClient.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/MRJobInfoFetcher.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java, cdap-common/src/main/java/co/cask/cdap/common/HttpExceptionHandler.java, cdap-common/src/main/java/co/cask/cdap/common/NotFoundException.java, cdap-common/src/main/java/co/cask/cdap/common/NotImplementedException.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultWorkflowManager.java, cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricStore.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
- Removed redundant exception throwing for some methods and dependent methods in ProgramLifecycleHttpHandler
- Changed handlers exceptions goes through HttpExceptionHandler
Changes for handlers: 
- getMapReduceInfo
- getStatus
Opening for some feedback and will proceed with others.
=> CDAP-3107: Initial log cleanup and refactoring of ProgramLifecycleHttpHandler for review

cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
JIRA - https://issues.cask.co/browse/CDAP-3656
=> Fix TestFrameworkTestRun random failure

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/BusinessMetadataStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriter.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageServiceTest.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataRecord.java
Also add REST endpoint to retrieve metadata for a run.
=> CDAP-3583 CDAP-3521 Add app, program and data metadata while recording access

cdap-proto/src/main/java/co/cask/cdap/proto/Id.java, cdap-proto/src/test/java/co/cask/cdap/proto/IdTest.java
https://issues.cask.co/browse/CDAP-3658
http://builds.cask.co/browse/CDAP-DUT2858
=> CDAP-3658: Fix Id.Program hierarchy

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
The metric was introduced a long time ago before filesets were
added. The metric is incorrect, and it requires read permissions
on hbase directory which we might not always have. Removing it
until there is a better way to calculate it.
=> CDAP-3563 removing cdap cluster disk usage metric

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/my-dag-factory.js, cdap-ui/app/features/adapters/services/adapter-error-factory.js, cdap-ui/app/features/adapters/services/canvas-factory.js, cdap-ui/app/features/apps/controllers/tabs/status-ctrl.js, cdap-ui/app/services/app/my-app-dag-service.js
=> add ability for multiple sinks

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java
we were missing the route to streams lineage.
=> add missing route to streams lineage in RouterPathLookup

cdap-common/bin/common.sh, cdap-common/bin/service, pom.xml
...and update package dependencies to pull it in on RHEL/UBUNTU
=> CDAP-3690 Fail fast on missing xmllint

cdap-ui/app/features/adapters/controllers/create/plugin-edit-form-ctrl.js
=> Fix bad plugins path

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/service/inmemory/InMemoryNotificationService.java
JIRA: https://issues.cask.co/browse/CDAP-3400
Build: http://builds.cask.co/browse/CDAP-RBT433-1
=> CDAP-3400 Do not log error when the Notification service is not yet started.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
=> Only localize plugin artifact jar if there is plugin being used for an application.

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTest.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractDistributedMasterServiceManager.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/MetadataServiceManager.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/run/InMemoryMetadataServiceManager.java
https://issues.cask.co/browse/CDAP-3635
http://builds.cask.co/browse/CDAP-RBT446
=> CDAP-3635: Make metadata service monitorable as a system service

cdap-ui/app/features/adapters/controllers/create/toppanel-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/popovers/viewconfig.html, cdap-ui/app/features/adapters/templates/create/toppanel.html
=> change behavior for export modal in hydrator

cdap-ui/app/directives/navbar-hydrator/navbar.html, cdap-ui/app/directives/navbar-hydrator/navbar.less
* Removes search HTML and associated styling from Hydrator navbar
=> removes search from Hydrator navbar

cdap-ui/app/services/app/my-app-dag-service.js
*  Adjusts top offset of DAG node placement on Hydrator canvas
=> reduces top offset of dag node placement

cdap-ui/app/directives/validators/validator-ctrl.js
=> change construction of object getting returned by the ui in validator

cdap-ui/app/features/adapters/templates/detail.html, cdap-ui/app/features/adapters/toppanel.less
- fix styling for pipeline metadata
- add link to CDAP
=> fix styling for pipeline metadata

cdap-ui/app/directives/widget-container/widget-dataset-selector/widget-dataset-selector.js, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js
=> changing format when using stream-selector

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/serialize/LineageRecord.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java, cdap-common/src/main/java/co/cask/cdap/common/utils/TimeMathParser.java
https://issues.cask.co/browse/CDAP-3676
http://builds.cask.co/browse/CDAP-RBT436
=> CDAP-3676: Metadata HTTP RESTful API should support 'now'

cdap-ui/app/services/app/my-app-dag-service.js
=> add message when publishing pipeline in hydrator

cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLRealtimeApplication.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
Build : http://builds.cask.co/browse/CDAP-RBT465
=> Set worker instances and worker resources from the ETLWorker Config

cdap-common/src/main/resources/cdap-default.xml
Verified that this was the only mismatch.
=> (CDAP-3734) Turn publishing off by default

cdap-ui/app/directives/navbar-hydrator/navbar.html, cdap-ui/app/directives/navbar-hydrator/navbar.less
*  Moves navbar links to center
*  Moves return to CDAP link to right
=> changes layout of hydrator header

cdap-ui/app/features/adapters/toppanel.less
*  Increases length of metadata name input in edit mode
*  Left aligns metadata name container so fix left padding issue
*  Hides pencil from display in edit mode
=> increases width of metadata name input

cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js, cdap-ui/app/features/adapters/controllers/create/partials/nodeconfig-ctrl.js, cdap-ui/app/features/adapters/controllers/create/plugin-edit-form-ctrl.js, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-output-schema.html, cdap-ui/app/services/app/my-app-dag-service.js
- Fixes schema propagation.
- Disables save and reset when the user opens the node configuration and makes no change.
=> Fixes schema propagation + editing outputschema on plugins saveable

cdap-ui/app/features/adapters/controllers/detail-ctrl.js, cdap-ui/app/features/adapters/templates/detail.html, cdap-ui/app/features/adapters/toppanel.less
=> fix timing issue with buttons in hydrator details

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationManager.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java, cdap-app-fabric/src/test/java/co/cask/cdap/WordCountMinusFlowApp.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
As part of Application update, need to delete all metadata related to no longer exist program in an application.
This is done in ```DeletedProgramHandlerStage.process```
=> [CDAP-3718] Add metadata cleaner in the DeletedProgramHandlerStage.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
when one of the workflow node fails in the workflow, we would set workflow status to be completed so we do not restart the workflow.
We want the workflow stats to be recorded only for successfully completed workflow runs, so if there is a workflow node run whose status is not completed, we skip writing stats.
https://issues.cask.co/browse/CDAP-3460
build : http://builds.cask.co/browse/CDAP-RBT475-1
=> bugfix for skipping workflow stats when workflow node has failed

cdap-api/src/main/java/co/cask/cdap/internal/api/DefaultDatasetConfigurer.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultPluginConfigurer.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithDuplicateStreams.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/artifacts/plugins/ToStringPlugin.java
plugins with same name in same/different programs.
Punting the more detailed error message to next release (JIRA : https://issues.cask.co/browse/CDAP-3729)
Build : http://builds.cask.co/browse/CDAP-RBT477
=> Throw an error if an application tries to add streams, datasets,

cdap-ui/app/features/adapters/toppanel.less
*  Changes placeholder text color to gray
*  Changes cursor to auto on hover
=> adds more intuitive styling to edit metadata box

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/BatchETLDBTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/DBSource.java
Note: This just tests verifies current behavior. The test will have to be modified when we fix [CDAP-3749](https://issues.cask.co/browse/CDAP-3749)
Build: http://builds.cask.co/browse/CDAP-RBT480-2
=> Added a test to verify username/password combinations

cdap-ui/app/features/adapters/controllers/detail-ctrl.js, cdap-ui/app/features/adapters/templates/list.html, cdap-ui/app/features/adapters/templates/tabs/datasets.html, cdap-ui/app/features/adapters/templates/tabs/status.html
- Switch all 'N/A' to '-'
- Datasets list in Detail view links to CDAP
- 'Starting' and 'Stopping' becomes 'STARTING' and 'STOPPING'
=> [CDAP-3770] [CDAP-3774] [CDAP-3775] fix consistency issue in messages

cdap-ui/app/features/adapters/controllers/create-ctrl.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create.html
=> implement new design for predefined templates

cdap-ui/app/features/adapters/services/console-tab-service.js, cdap-ui/app/features/adapters/templates/partial/console.html
*  Adds timestamp to console messages
=> adds timestamps to console messages

cdap-docs/reference-manual/source/cli-api.rst
Fixes a problem in the table generation. This, however, will probably not be easy to fix in the Java code that generates this.
=> Fix CLI examples.

cdap-docs/developers-manual/source/testing/testing.rst
=> add some docs about using application and plugin artifacts in

cdap-ui/app/features/adapters/templates/detail.html, cdap-ui/app/features/adapters/toppanel.less
*  Adds font size and makes pipeline type consistent with how it appears in studio view
=> fixes font size of pipeline type

cdap-cli/src/main/java/co/cask/cdap/cli/command/app/CreateAppCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/LoadArtifactCommand.java
Fixes some minor spelling and word-usage in the CLI Help.
=> Minor edits to CLI help

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/features/apps/applications.less, cdap-ui/app/features/apps/templates/tabs/status.html
=> [CDAP-3763] [CDAP-3797] fix center of dag in apps status view

cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/features/adapters/leftpanel.less
*  Adds badge with total item count to opened group in left side panel
=> adds item count to opened group

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/features/adapters/services/adapter-error-factory.js, cdap-ui/app/services/app/my-app-dag-service.js, cdap-ui/app/services/constants.js
=> [CDAP-3795] surfacing error for nonexistant plugin

cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/features/adapters/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/templates-ctrl.js, cdap-ui/app/features/admin/templates/namespace/templates.html, cdap-ui/app/services/constants.js
- Adding description to plugin template
- Change icons in left sidebar to be plugin base type
- fix fetch list of plugins based on templates and type
- renaming a plugin template name will not create a new one
=> [CDAP-3782] [CDAP-3780] [CDAP-3781] Fix/ui plugin templates fixes

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/realtime/kafka/Kafka08SimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/realtime/source/KafkaSource.java, cdap-docs/included-applications/build.sh, cdap-docs/included-applications/source/etl/plugins/realtimesources/kafka.rst
Document the change of ``kafka.default.offset`` to ``kafka.initial.offset``, fixing Javadocs, messages and documentation HTML.
Building at: http://builds.cask.co/browse/CDAP-DDB14-1
=> Document kafka koughing

cdap-docs/included-applications/build.sh
This reverts commit 3c1090d56f47108c318727a503989cb68798fd94.
Trying to resolve conflicts between release and develop. Will bring these changes back in after merging release to develop.
=> Revert "Update build.sh"

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/reference-manual/source/release-notes.rst
Building at: http://builds.cask.co/browse/CDAP-DDB19-1
Fix for: https://issues.cask.co/browse/CDAP-3703
=> Release notes for 3.2.0

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/guice/TypeResolver.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/guice/TypeVisitor.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/guice/Types.java
- This should be compilable with both Java 7 and 8
=> (CDAP-3645) Copy the latest TypeResolver and related classes from Guava

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationManager.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ApplicationVerificationStage.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkAppUsingFileSet.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkAppUsingGetDataset.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunnerTest.java, cdap-app-fabric/src/test/scala/co/cask/cdap/internal/app/runtime/spark/ScalaSparkLogParserProgram.scala
Also removed some unused code.
Build: http://builds.cask.co/browse/CDAP-DUT2910-1
=> (CDAP-2988) Added tests for Spark using getDataset() directly.

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/DBSink.java
https://issues.cask.co/browse/CDAP-3807
http://builds.cask.co/browse/CDAP-DUT2912
=> CDAP-3807: Fix case sensitivity handling in DBSink

cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowFailureInForkApp.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
JIRA: https://issues.cask.co/browse/CDAP-3542
Build: http://builds.cask.co/browse/CDAP-DUT2914-1
=> CDAP-3542 Unit test case for the failure in the Workflow fork.

cdap-notifications-api/src/main/java/co/cask/cdap/notifications/feeds/service/NotificationFeedStore.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/feeds/service/InMemoryNotificationFeedStore.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/feeds/service/MDSNotificationFeedStore.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/feeds/service/NotificationFeedService.java, cdap-notifications/src/test/java/co/cask/cdap/notifications/NotificationTest.java, cdap-notifications/src/test/java/co/cask/cdap/notifications/inmemory/InMemoryNotificationTest.java, cdap-notifications/src/test/java/co/cask/cdap/notifications/kafka/KafkaNotificationTest.java
JIRA : https://issues.cask.co/browse/CDAP-3886
=> CDAP-3886 fix how rowkey is constructued for writing/deleting/listing feed entries

cdap-ui/app/directives/validators/validators.html, cdap-ui/app/features/adapters/bottompanel.less, cdap-ui/app/features/admin/admin.less, cdap-ui/app/features/admin/templates/namespace/stream-metadata.html, cdap-ui/app/features/admin/templates/namespace/templates.html, cdap-ui/app/features/dashboard/templates/partials/addwdgt.html, cdap-ui/app/features/dashboard/widgets.less, cdap-ui/app/styles/themes/cdap.less, cdap-ui/app/styles/themes/cdap/mixins.less
*  Replaces native browser styling of select dropdowns with custom styling
=> improves styling of select in ff, safari

cdap-ui/app/features/hydrator/controllers/create/partials/settings-ctrl.js, cdap-ui/app/features/hydrator/templates/partial/settings.html
=> remove the angular cron directive from realtime etl

cdap-ui/app/features/adapters/controllers/create/toppanel-ctrl.js
Fixes a number of simple errors in the UI messages. Adds periods, removes spaces, restructures one of the messages...
=> Fix messages.

cdap-docs/developers-manual/build.sh, cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/spark-page-rank.rst, cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java
=> Fix SparkPageRank docs to use just one service

cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/PersistedMessageCallback.java
Reopening : https://github.com/caskdata/cdap/pull/4183
=> CDAP-3832 - persisting kafka offset only after metrics are processed

cdap-ui/app/directives/navbar-hydrator/navbar.html, cdap-ui/app/directives/navbar-hydrator/navbar.less
*  Moves actives class assignment via ng-class from list item to anchor
*  Adjusts styling of nav elements accordingly
=> moves active class to list item from anchor

cdap-ui/app/features/hydrator/templates/list.html
=> [CDAP-3841] add color indicator to last finished run status

cdap-ui/app/features/adapters/templates/list.html
=> [CDAP-3841] Fix/ui hydrator list last finished for 3.2

cdap-ui/app/directives/breadcrumbs/breadcrumbs.less
*  Fixes positioning issue affecting namespace dropdown (breadcrumbs directive) on device widths ranging from 992px - 1200px
=> fixes ns dropdown on smaller devices

cdap-ui/Gulpfile.js, cdap-ui/app/features/flows/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/main.js, cdap-ui/app/services/data/datasource.js, cdap-ui/app/services/data/socket.js, cdap-ui/bower.json, cdap-ui/npm-shrinkwrap.json, cdap-ui/package.json, cdap-ui/server/aggregator.js
=> Avoids sending unchanged response from backend to browser in aggregator

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLBatchApplication.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLMapReduce.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLWorkflow.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLRealtimeApplication.java
Replaces the default descriptions used in the ETLBatch and ETLRealtime applications with updated text.
Replaces usage of "Application Template" and its ilk.
Build and Test running at: http://builds.cask.co/browse/CDAP-RBT496
Passed build and test.
=> Replace default descriptions.

cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/controllers/list-ctrl.js, cdap-ui/app/features/hydrator/controllers/tabs/status-ctrl.js, cdap-ui/app/features/hydrator/templates/tabs/status.html, cdap-ui/app/services/workers/my-workers-api.js, cdap-ui/app/services/workflows/my-workflow-api.js
=> [CDAP-3838] adding last finished info on hydrator detail status tab

cdap-ui/app/features/adapters/bottompanel.less, cdap-ui/app/features/adapters/controllers/list-ctrl.js, cdap-ui/app/features/adapters/controllers/tabs/status-ctrl.js, cdap-ui/app/features/adapters/templates/tabs/status.html, cdap-ui/app/services/workers/my-workers-api.js, cdap-ui/app/services/workflows/my-workflow-api.js
=> [CDAP-3838] adding last finished info on hydrator detail status tab for 3.2

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/my-dag-factory.js
=> [CDAP-3943] fix rendering issue on published hydrator pipeline with 3 or more sinks

cdap-ui/app/features/adapters/controllers/detail-ctrl.js, cdap-ui/app/features/adapters/services/adapter-detail-factory.js, cdap-ui/app/features/adapters/templates/tabs/instance.html, cdap-ui/app/features/adapters/templates/tabs/schedule.html
=> [CDAP-3836] add schedule and instance to published pipeline

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DatasetModulesDeployer.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DatasetTypeManager.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/StaticDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
- Just use the application jar for dataset module deployment.
=> Remove unnecessary logic for building dataset jar

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/scheduler/DatasetBasedTimeScheduleStoreTest.java
Issue: https://issues.cask.co/browse/CDAP-3678
Build: http://builds.cask.co/browse/CDAP-DUT2945-1
=> CDAP-3678: unit test for removeJob in DatasetBasedTimeScheduleStore

cdap-ui/app/directives/program-status/program-status.html
*  Modifies ng-if logic within duration cell to prevent emdash from appearing underneath text
=> fixes duration cell rendering issue

cdap-ui/app/directives/error/error-popover.html, cdap-ui/app/directives/error/error.less
*  Adds correct background to alert rows (via .alert-danger class)
*  Adds additional styling to make my-error more consistent with the UI
I
=> fixes styling of alert rows

cdap-ui/app/directives/program-status/program-status.html
Replica of https://github.com/caskdata/cdap/pull/4287 for 3.2.1
=> Fix/ui program status duration 3.2

cdap-ui/app/features/adapters/bottompanel.less, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-config-form.html
*  Shrinks column with for input and output columns (both studio and pipeline detail views)
=> changes node config tab columb widths

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/BatchETLDBTest.java
http://builds.cask.co/browse/CDAP-DUT2975-2
=> Add test case for DBSource, pulling from multiple tables.

cdap-common/bin/service
This simply adds an echo to go to a newline after stopping output.
=> Improve stopping output

cdap-ui/app/directives/program-history/program-history.js, cdap-ui/app/features/adapters/controllers/tabs/history-ctrl.js, cdap-ui/app/features/adapters/controllers/tabs/metrics-ctrl.js, cdap-ui/app/services/mapreduce/my-mapreduce-api.js, cdap-ui/app/services/workers/my-workers-api.js
- Reduces the poll interval for polling latest runs from 10 seconds to 2 seconds.
- Modifies request to poll for logs and metrics based on latest run and program type.
=> Fixes polling latest runs in hydrator detailed view for metrics, logs and runs count

cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/PersistedMessageCallback.java
porting : https://github.com/caskdata/cdap/pull/4186 to 3.1
=> CDAP-3832 persist the offset only after the metrics are processed (Porting)

cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-config-form.html
*  Adds correct grid class names to template file
Source:
Transform:
Sink:
=> fixes boostrap columns in node config tab

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-common/src/main/java/co/cask/cdap/common/guice/LocationRuntimeModule.java, cdap-common/src/main/java/co/cask/cdap/common/io/FileContextLocation.java, cdap-common/src/main/java/co/cask/cdap/common/io/FileContextLocationFactory.java, cdap-common/src/main/java/co/cask/cdap/common/io/Locations.java, cdap-common/src/main/java/co/cask/cdap/common/lang/FunctionWithException.java, cdap-common/src/test/java/co/cask/cdap/common/io/DFSSeekableInputStreamTest.java, cdap-common/src/test/java/co/cask/cdap/common/io/FileContextLocationFactoryTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSMultiLiveStreamFileReaderTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSStreamDataFileTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSStreamFileJanitorTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSTimePartitionedStreamTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClientTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/DFSConcurrentStreamWriterTest.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TokenSecureStoreUpdater.java
- Switch to use FileContextLocationFactory instead of HDFSLocationFactory
=> Added a FileContextLocationFactory that uses FileContext to perform Location operations

cdap-ui/app/features/adapters/controllers/create/plugin-edit-form-ctrl.js, cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-form.html, cdap-ui/app/services/app/my-app-dag-service.js, cdap-ui/app/services/constants.js, cdap-ui/server/aggregator.js
Same PR as (https://github.com/caskdata/cdap/pull/4311) but for 3.2.1
=> Fix/ui json errors plugin templates 3.2

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/AbstractDatasetProvider.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetProvider.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DefaultDatasetProvider.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Reviewed here: https://github.com/caskdata/cdap/pull/4325
=> CDAP-3902: Remove unnecessary remote calls when getting a dataset instance

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
JIRA: https://issues.cask.co/browse/CDAP-4040
=> CDAP-4040 Check if the security is enabled before adding the tokens.

cdap-ui/app/features/adapters/bottompanel.less, cdap-ui/app/features/adapters/templates/partial/node-config.html, cdap-ui/app/features/adapters/templates/partial/reference-tab.html
*  Changes Node Config tab message when pipeline is already published
*  Fixes Schedule tab dropdown cursor behavior on hover
=> corrects behavior of bottom panel in adapters detail view

cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/templates/partial/node-config.html, cdap-ui/app/features/hydrator/templates/partial/reference-tab.html
*  Changes Node Config tab message when pipeline is already published
*  Fixes Schedule tab dropdown cursor behavior on hover
=> corrects behavior of bottom panel in pipeline detail view

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/S3BatchSink.java, cdap-docs/included-applications/build.sh
Fixes documentation build.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB21-1).
=> Fix a description, and fix an MD5 hash.

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/transform/ScriptTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/transform/ValidatorTransform.java
https://issues.cask.co/browse/CDAP-4016
http://builds.cask.co/browse/CDAP-DUT3023
- Ran ScriptTransformTest, ScriptFilterTransformTest, and ValidatorTransformTest with Java 8.
=> CDAP-4016: Java 8 support for ScriptTransform

cdap-ui/app/features/apps/controllers/tabs/status-ctrl.js, cdap-ui/app/features/apps/routes.js, cdap-ui/app/features/flows/routes.js, cdap-ui/app/features/login/routes.js, cdap-ui/app/features/mapreduce/routes.js, cdap-ui/app/features/services/routes.js, cdap-ui/app/features/spark/routes.js, cdap-ui/app/features/streams/controllers/tabs/status-ctrl.js, cdap-ui/app/features/streams/routes.js, cdap-ui/app/features/workers/routes.js, cdap-ui/app/features/workflows/routes.js, cdap-ui/app/services/auth.js
- Fixes reload on any state
- Fixes undefined resource (apps, programs) to redirect to 404 state when not found.
=> Fix/ui fix reloads+nodatafrombackend

cdap-ui/app/styles/themes/cdap/theme.less
*  Adds cursor: pointer on hover to table links
I
=> adds cursor on hover to table links

cdap-ui/app/features/admin/templates/namespace/create.html, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-output-schema.html
- Fixes typo
- Fixes namespace create modal to have 'create' button disabled until the user types something in the name field.
=> Fixes typo + disables create button until user enters name in namespace create modal

cdap-app-templates/cdap-etl/cdap-etl-common/src/main/java/co/cask/cdap/etl/common/RecordConverter.java
Missed this while moving the class in this PR : https://github.com/caskdata/cdap/pull/4362
=> Make the transform method public

cdap-docs/included-applications/build.sh
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB25-1).
=> Update MD5 hashes.

cdap-docs/integrations/source/ambari/index.rst
[Quick Build](http://builds.cask.co/browse/CDAP-DQBP30-3)
=> Added note about Spark to Ambari Docs

cdap-distributions/bin/build_apt_repo.sh
This creates an APT repository artifact which can be extracted to create an APT repository, including signing key.
=> APT repository script

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ProgramClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java, cdap-proto/src/main/java/co/cask/cdap/proto/BatchProgram.java, cdap-proto/src/main/java/co/cask/cdap/proto/BatchProgramResult.java, cdap-proto/src/main/java/co/cask/cdap/proto/BatchProgramStart.java, cdap-proto/src/main/java/co/cask/cdap/proto/BatchProgramStatus.java
Adding restful apis to start and stop multiple programs in the
same request. Also adding corresponding methods to ProgramClient,
as well as a convenience method to wait for a batch of programs
to be in a specified state.
=> CDAP-4022 add batch start and stop rest apis for programs

cdap-common/src/main/java/co/cask/cdap/common/lang/ProgramResources.java, cdap-common/src/test/java/co/cask/cdap/common/lang/FilterClassLoaderTest.java
- Includes resources that are inside the same set of jars with classes that are visible
through the ProgramClassLoader
=> (CDAP-4127) Make non class file resources available through ProgramClassLoader

cdap-app-templates/cdap-data-quality/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-realtime/pom.xml, cdap-app-templates/cdap-etl/pom.xml
- Also replace Export-Package with _exportcontents
- This will reduce the jar size a bit since it
does copy classes, but rather just include jars.
=> Fix app templates pom.

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/AbstractDatasetProvider.java
https://issues.cask.co/browse/CDAP-4097
http://builds.cask.co/browse/CDAP-DUT3043
=> CDAP-4097: Fix AbstractDatasetProvider.getOrCreate

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
JIRA: https://issues.cask.co/browse/CDAP-4119
Merging PR #4404 on release/3.1
=> CDAP-4119 Cherry pick from 3.0 release and resolved conflicts.

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
Cherry pick from #4082 
JIRA: https://issues.cask.co/browse/CDAP-3660
=> CDAP-3660 Do keytab login earlier when master starts up

cdap-docs/admin-manual/source/index.rst, cdap-docs/admin-manual/source/installation/index.rst, cdap-docs/admin-manual/source/installation/installation-note.txt, cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/installation/quick-start.rst, cdap-docs/developers-manual/source/getting-started/standalone/index.rst, cdap-docs/integrations/source/index.rst, cdap-docs/integrations/source/mapr/index.rst, cdap-docs/integrations/source/table-of-contents.rst
Passes [Quick Build](https://builds.cask.co/browse/CDAP-DOB30).
- [Introduction](http://builds.cask.co/artifact/CDAP-DOB30/shared/build-2/Docs-HTML/3.2.1/en/admin-manual/index.html)
- [Installation](http://builds.cask.co/artifact/CDAP-DOB30/shared/build-2/Docs-HTML/3.2.1/en/admin-manual/installation/index.html)
- [Quick Start](http://builds.cask.co/artifact/CDAP-DOB30/shared/build-2/Docs-HTML/3.2.1/en/admin-manual/installation/quick-start.html)
- [Installation Details](http://builds.cask.co/artifact/CDAP-DOB30/shared/build-2/Docs-HTML/3.2.1/en/admin-manual/installation/installation.html)
Fix for https://issues.cask.co/browse/CDAP-4093
=> Add links and warnings about using Cloudera and Ambari.

cdap-docs/admin-manual/source/index.rst, cdap-docs/admin-manual/source/installation/index.rst, cdap-docs/admin-manual/source/installation/installation-note.txt, cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/installation/quick-start.rst, cdap-docs/developers-manual/source/getting-started/standalone/index.rst
Fix for https://issues.cask.co/browse/CDAP-4093
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DQBP33-1)
=> Port of PR #4434, edited to remove MapR references.

cdap-ui/app/features/workflows/controllers/tabs/runs-ctrl.js
*  Fixes issue where run status wasn't accurately reflecting in run level section of the UI and history modal
=> fixes run status update issue

pom.xml
JIRA- https://issues.cask.co/browse/CDAP-4181
=> CDAP-4181 Upgraded Tephra to 0.4.3-SNAPSHOT version.

cdap-ui/app/features/services/controllers/tabs/runs/tabs/status/make-request-ctrl.js, cdap-ui/app/features/services/services.less, cdap-ui/app/features/services/templates/tabs/runs/tabs/status/make-request.html
=> [CDAP-2908] add loading icon to the make request button in service program

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
JIRA: https://issues.cask.co/browse/CDAP-3563
Back porting PR #3955 and some cleanup to 3.0.6
=> CDAP-3563 Backporting the fix from 3.2 to 3.0

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceClassLoader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
1. In MapReduceClassLoader.close(), don’t create a new MapReduceContextProvider if it hasn’t been created
2. In MapReduceRuntimeService, when cleaning up resources, it should delete Location recursively
=> Two bugs are fixed:

cdap-cli/bin/cdap-cli.bat, cdap-cli/bin/cdap-cli.sh, cdap-docs/integrations/source/jdbc.rst, cdap-standalone/pom.xml
- Those are uber jar, which affect correctness of program class loader construction
=> Move cdap-cli and cdap-explore-jdbc out of SDK lib directory

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
https://issues.cask.co/browse/CDAP-4076
http://builds.cask.co/browse/CDAP-DUT3010
=> CDAP-4076: Remove usage of Transactional in Store

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/AbstractDatasetProvider.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetCache.java
- Always switch the context class loader to the CDAP system one
one performing DatasetContext.getDataset().
- This should make loading dataset class from the user program context
correct.
- This fix doesn’t address dataset class loading from non-user program context.
That would be addressed in CDAP-4189
=> (CDAP-4112) A temporary fix on dataset class loading

cdap-docs/included-applications/source/etl/plugins/transforms/script.rst, cdap-docs/included-applications/source/etl/plugins/transforms/scriptfilter.rst, cdap-docs/included-applications/source/etl/plugins/transforms/validator.rst
https://issues.cask.co/browse/CDAP-4170
=> CDAP-4170: Lookup transform docs

pom.xml
JIRA - https://issues.cask.co/browse/CDAP-4181
=> Upgraded tephra version to 0.4.4

cdap-distributions/bin/build_apt_repo.sh, cdap-distributions/bin/build_yum_repo.sh
This is a backport of #4484 to release/3.0
=> Accept GPG key name/passphrase as arguments

cdap-docs/reference-manual/source/release-notes.rst
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DQBP32-2).
[Release Notes](http://builds.cask.co/artifact/CDAP-DQBP32/shared/build-2/Docs-HTML/3.0.5/en/reference-manual/release-notes.html#release-3-0-6)
=> Release 3.0.6 release notes.

cdap-docs/admin-manual/source/installation/cdap-site.rst
Running [Quick Build](http://builds.cask.co/browse/CDAP-DQBP37-1): Passed.
[New table](http://builds.cask.co/artifact/CDAP-DQBP37/shared/build-1/Docs-HTML/3.0.6/en/admin-manual/installation/cdap-site.html#appendix-cdap-site-xml)
=> Update table describing cdap-site.xml.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStoreTest.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
- Store triggers with its state through custom serialization of TriggerStatusV2
- Upgraded TriggerStatus to TriggerStatusV2
Issue: https://issues.cask.co/browse/CDAP-3733
Build: http://builds.cask.co/browse/CDAP-DUT2956-6
Tested on Cluster.
=> CDAP-3733: DatasetBasedTimeScheduleStore store triggers with custom serialization and upgrade for it

cdap-docs/examples-manual/build.sh, cdap-docs/included-applications/build.sh, cdap-docs/included-applications/source/etl/plugins/transforms/script.rst, cdap-docs/included-applications/source/etl/plugins/transforms/scriptfilter.rst, cdap-docs/included-applications/source/etl/plugins/transforms/validator.rst
Fixes documentation build.
Running [Quick Build](http://builds.cask.co/browse/CDAP-DOB40-1)
=> Update files for changes and MD5 hashes.

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java, cdap-common/src/main/java/co/cask/cdap/common/HttpExceptionHandler.java, cdap-common/src/main/java/co/cask/cdap/common/MethodNotAllowed.java, cdap-common/src/main/java/co/cask/cdap/common/MethodNotAllowedException.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultApplicationManager.java
Some more log cleanup in ProgramLifecycleHttpHandler
Build: http://builds.cask.co/browse/CDAP-DUT3000-1
=> Log cleanup for program operation in ProgramLifecycleHTTPHandler

cdap-watchdog/src/test/java/co/cask/cdap/logging/KafkaTestBase.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java
JIRA - https://issues.cask.co/browse/CDAP-4070
Build - http://builds.cask.co/browse/CDAP-DUT3128-2
=> CDAP-4070 Wait for Kafka server to startup before starting LogSaver tests

cdap-ui/app/features/hydrator/controllers/detail/tabs/metrics-ctrl.js, cdap-ui/app/features/hydrator/services/detail/actions/pipeline-detail-metrics-actions.js
- Fix to load metrics in adapter detailed view on refreshing the browser.
=> Fixes loading metrics on refresh on adapter detailed view

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/org/apache/twill/internal/ServiceMain.java, cdap-app-fabric/src/main/java/org/apache/twill/internal/appmaster/ApplicationMasterMain.java, cdap-app-fabric/src/main/java/org/apache/twill/launcher/TwillLauncher.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/java/co/cask/cdap/common/guice/TwillModule.java, cdap-common/src/main/resources/cdap-default.xml, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
- This is a workaround for MapR.
=> (CDAP-4045) Optionally disable Kafka in AM.

cdap-docs/included-applications/source/data-quality/index.rst
Fix for issue https://issues.cask.co/browse/CDAP-4083.
=> Fix names for two functions.

cdap-docs/reference-manual/source/http-restful-api/query.rst
Fix for https://issues.cask.co/browse/CDAP-3514
=> Add "count of queries" endpoint.

cdap-watchdog/src/test/java/co/cask/cdap/logging/save/CountingLogAppender.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java
JIRA - https://issues.cask.co/browse/CDAP-4070
Build - http://builds.cask.co/browse/CDAP-DUT3155-2
=> CDAP-4070 Instrumenting log appender in LogSaverTest to find race condition

cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java
JIRA - https://issues.cask.co/browse/CDAP-4070
Build - http://builds.cask.co/browse/CDAP-DUT3159-1
=> CDAP-4070 Instrumenting log appender in LogSaverPluginTest 

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/view/ViewAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamAdmin.java
- Added a method to check if view exists or not from StreamAdmin
- This is needed to check view existence while adding view metadata
=> Add viewExists method

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/EntityValidator.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java, cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/KeyHelper.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsValueKey.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-proto/src/main/java/co/cask/cdap/proto/codec/NamespacedIdCodec.java
Adding rest apis for adding metadata tags and properties to an
artifact. This functions just like metadata for other entities.
=> CDAP-4280 add metadata for artifacts

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/my-dag-factory.js, cdap-ui/app/directives/dag/my-dag.html, cdap-ui/app/directives/dag/services/actions/nodes-actions.js, cdap-ui/app/directives/dag/services/stores/nodes-store.js, cdap-ui/app/features/hydrator/controllers/detail/canvas-ctrl.js, cdap-ui/app/features/hydrator/services/hydrator-service.js
Initial PR for re-render graph. Disabled state not yet added
=> add ability to render dag from a config

cdap-ui/app/directives/escape-close/escape-close.js, cdap-ui/app/directives/metadata-tags/metadata-tags.html, cdap-ui/app/directives/metadata-tags/metadata-tags.js, cdap-ui/app/directives/metadata-tags/metadata-tags.less
*  Adds escape button functionality (on escape, metadata input removed from display)
*  Adds autofocus to metadata input display
=> adds functionality and style fixes to input + tags

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json, cdap-distributions/src/packer/scripts/fill-maven-cache.sh
Build: http://builds.cask.co/browse/CDAP-BUT814-24
Diff from `cdap-sdk-ubuntu12.json`:
```diff
--- cdap-sdk-ubuntu12.json	2015-11-11 15:03:20.000000000 -0500
+++ cdap-sdk-ubuntu12-with-uri.json	2015-11-20 13:10:25.000000000 -0500
@@ -1,6 +1,6 @@
{
"variables": {
-    "sdk_version": "3.2.0"
+    "sdk_version": "3.3.0"
},
"builders": [
{
@@ -28,8 +28,10 @@
"keyboard-configuration/variant=USA console-setup/ask_detect=false ",
"initrd=/install/initrd.gz -- <enter>"
],
+      "vboxmanage": [
+        ["modifyvm", "{{ .Name }}", "--memory", "4096"]
+      ],
"vboxmanage_post": [
-        ["modifyvm", "{{ .Name }}", "--memory", "4096"],
["modifyvm", "{{ .Name }}", "--clipboard", "bidirectional"],
["modifyvm", "{{ .Name }}", "--accelerate2dvideo", "on"],
["modifyvm", "{{ .Name }}", …
```
=> Packer config w/ SDK URI for VM

cdap-distributions/src/packer/scripts/lxde.sh
=> Remove xterm from VM session, caused confusion

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json, cdap-distributions/src/packer/scripts/fill-maven-cache.sh
Backport #4592 to this branch and update version to next release on this branch
=> Backport #4592

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/DefaultMetadataStore.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Jira: [CDAP-4297](https://issues.cask.co/browse/CDAP-4297)
Build: http://builds.cask.co/browse/CDAP-DUT3207
=> (CDAP-4297) Added an upgrade step for business metadata dataset

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AppFabricServiceManager.java, cdap-proto/src/main/java/co/cask/cdap/proto/Containers.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/run/InMemoryAppFabricServiceManager.java
Cherry-pick from #4429 and resolved conflicts.
=> Fix/cherry pick 4133 to 3.2.0

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java
Build : http://builds.cask.co/browse/CDAP-DUT3224
=> Fix metadata path for view and artifact

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/scheduler/SchedulerQueueResolver.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/PreferencesHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/PropertiesResolver.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/stream/store/MDSStreamMetaStoreTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/store/DefaultNamespaceStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/store/NamespaceMDS.java, cdap-data-fabric/src/main/java/co/cask/cdap/store/NamespaceStore.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12CDH5ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive13ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive14ExploreService.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreDisabledTest.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/InMemoryExploreServiceTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/id/ProgramId.java
https://issues.cask.co/browse/CDAP-4299
http://builds.cask.co/browse/CDAP-DUT3184
=> CDAP-4299: Move namespace code in Store to its own module

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/MultiThreadDatasetCache.java, cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java, cdap-master/src/main/java/co/cask/cdap/data/tools/flow/FlowQueuePendingCorrector.java
https://issues.cask.co/browse/CDAP-4315
http://builds.cask.co/browse/CDAP-DUT3211
=> CDAP-4315: Dataset objects in Store should not be cached

cdap-authorization-dataset-plugin/pom.xml, cdap-authorization-dataset-plugin/src/main/java/co/cask/cdap/security/authorization/ACLDataset.java, cdap-authorization-dataset-plugin/src/main/java/co/cask/cdap/security/authorization/DatasetAuthorizationPlugin.java, cdap-authorization-dataset-plugin/src/test/java/co/cask/cdap/security/authorization/ACLDatasetTest.java, cdap-authorization-dataset-plugin/src/test/java/co/cask/cdap/security/authorization/DatasetAuthorizationPluginTest.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/resources/cdap-default.xml, cdap-proto/src/main/java/co/cask/cdap/proto/id/EntityId.java, cdap-proto/src/test/java/co/cask/cdap/proto/id/EntityIdTest.java, cdap-security/src/main/java/co/cask/cdap/security/authorization/Action.java, cdap-security/src/main/java/co/cask/cdap/security/authorization/AllowAllAuthorizationPlugin.java, cdap-security/src/main/java/co/cask/cdap/security/authorization/AuthorizationHandlerProvider.java, cdap-security/src/main/java/co/cask/cdap/security/authorization/AuthorizationPlugin.java, cdap-security/src/test/java/co/cask/cdap/security/authorization/AuthorizationHandlerTest.java, pom.xml
https://issues.cask.co/browse/CDAP-4235
http://builds.cask.co/browse/CDAP-DUT3148
=> CDAP-4235: Authorization handler interface

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataHistoryEntry.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
Issue: https://issues.cask.co/browse/CDAP-4295
Build: http://builds.cask.co/browse/CDAP-DUT3230-5
=> Metadata dataset does not serialize scope now

cdap-authorization-dataset-plugin/pom.xml, cdap-security/pom.xml
http://builds.cask.co/browse/CDAP-DUT3237
=> Fix cdap-security test-jar dependency

cdap-client-tests/src/test/java/co/cask/cdap/client/ProgramClientTestRun.java
JIRA: https://issues.cask.co/browse/CDAP-4254
When workflow is started, it takes some time to make the workflow http service discoverable even after it is marked as running. The workflow http service is responsible for serving the 'current' endpoint. When service is not discoverable it throws NotFoundException. Added retry logic in the test to handle the case when the 'current' endpoint is not discoverable.
Build is running here - http://builds.cask.co/browse/CDAP-DUT3235-1
=> CDAP-4254 Added retry if the 'current' endpoint is not discoverable.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ExploreServiceTwillRunnable.java
http://builds.cask.co/browse/CDAP-DUT3239
=> Add NamespaceStore binding everywhere there's a Store binding

cdap-ui/app/features/hydrator/templates/create.html, cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json, cdap-ui/templates/apps/predefined/KafkaToHBase.json, cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json, cdap-ui/templates/apps/predefined/KafkaToStream.json, cdap-ui/templates/apps/predefined/StreamToHBase.json, cdap-ui/templates/apps/predefined/TwitterToHBase.json, cdap-ui/templates/apps/predefined/TwitterToStream.json, cdap-ui/templates/apps/predefined/config.json
Corrected the case and text for Hydrator labels and descriptions. See attached images for revisions in-place.
=> Fix UI Labels and Descriptions

cdap-docs/admin-manual/source/index.rst, cdap-docs/admin-manual/source/installation/index.rst, cdap-docs/admin-manual/source/operations/index.rst, cdap-docs/developers-manual/source/building-blocks/workflows.rst
[Passes Quick Build](http://builds.cask.co/browse/CDAP-DOB60-1).
Fixes broken links in release/3.2.
=> Fix broken links

cdap-ui/app/directives/widget-container/widget-factory.js, cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.html, cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.js, cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.less
=> add option to keyvalue widget to have value field as dropdown

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/my-dag-factory.js, cdap-ui/app/directives/dag/my-dag.js
=> Centering and Scaling DAG to fit screen

cdap-ui/app/directives/dag/my-dag-ctrl.js
When DAG is disabled:
- Cannot drag node (only drag canvas)
- Cannot remove node
- Cannot detach connection
=> add ability to disable dag

cdap-ui/app/directives/dag/my-dag.less, cdap-ui/app/features/apps/applications.less, cdap-ui/app/features/hydrator/adapters.less, cdap-ui/app/features/hydrator/templates/detail.html
- Set my-dag container to be position relative
- Reduce z-index of the buttons
=> [CDAP-4334] fix bounding of zoom control and z-index issue

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/my-dag.js, cdap-ui/app/features/hydrator/controllers/create/canvas-ctrl.js, cdap-ui/app/features/hydrator/controllers/detail/canvas-ctrl.js, cdap-ui/app/features/hydrator/services/hydrator-service.js, cdap-ui/app/features/hydrator/templates/create/canvas.html, cdap-ui/app/features/hydrator/templates/detail/canvas.html, cdap-ui/app/features/hydrator/templates/partial/schema-popover.html
note: The entire edge connection is clickable
=> add schema on edge for Hydrator

cdap-api/src/main/java/co/cask/cdap/api/service/http/HttpContentProducer.java, cdap-app-templates/cdap-data-quality/src/main/java/co/cask/cdap/dq/DataQualityApp.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchConfigurable.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchContext.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchRuntimeContext.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduceTestRun.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/test/sink/MetaKVTableSink.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/test/source/MetaKVTableSource.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceBatchContext.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceRuntimeContext.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceSinkContext.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceSourceContext.java
- Arguments can be set during prepareRun and is accessible in
initialize() method of source and sink.
=> (CDAP-351) Added method to BatchContext to set extra arguments

cdap-ui/app/directives/metadata-tags/metadata-tags.html, cdap-ui/app/directives/metadata-tags/metadata-tags.less
*  Adds new styling to add metadata input and metadata tags
*  Removes "X" button from metadata input
=> adds new styles to metadata input + tags

cdap-cli/src/main/java/co/cask/cdap/cli/CommandCategory.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/CheckActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/GrantActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DefaultCommands.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/SecurityCommands.java, cdap-client/src/main/java/co/cask/cdap/client/AuthorizationClient.java, cdap-proto/src/main/java/co/cask/cdap/proto/id/EntityId.java
https://issues.cask.co/browse/CDAP-4287
http://builds.cask.co/browse/CDAP-DUT3265
=> CDAP-4287: CLI for ACL management

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AuthorizationHandler.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/java/co/cask/cdap/common/http/AuthenticationChannelHandler.java, cdap-common/src/main/java/co/cask/cdap/common/http/SecurityRequestContext.java, cdap-common/src/main/java/co/cask/cdap/common/logging/AuditLogEntry.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/SecurityAuthenticationHttpHandler.java, cdap-proto/src/main/java/co/cask/cdap/proto/security/AuthorizationRequest.java, cdap-proto/src/main/java/co/cask/cdap/proto/security/CheckAuthorizedRequest.java, cdap-proto/src/main/java/co/cask/cdap/proto/security/RevokeRequest.java
Build : http://builds.cask.co/browse/CDAP-DUT3272
=> CDAP-4290 Enabling Authorization access audit logging

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-common/src/main/java/co/cask/cdap/common/security/YarnTokenUtils.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TokenSecureStoreUpdater.java
- Adds delegation token for all RM addresses when launching twill app.
=> (CDAP-4373) Fix HA-RM in secure cluster

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-common/src/main/java/co/cask/cdap/common/security/YarnTokenUtils.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TokenSecureStoreUpdater.java
- Adds delegation token for all RM addresses when launching twill app.
=> Cherry pick PR#4676 to release/3.2

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelineRegisterer.java
we currently perform validation in linear way, has to be refactored after we introduced DAG in Transforms. 
currently we are disabling this and have a JIRA to refactor it later : 
https://issues.cask.co/browse/CDAP-4387
Build : http://builds.cask.co/browse/CDAP-DUT3288
=> removed validate stages/types in PipelineRegisterer 

cdap-app-fabric/src/test/java/co/cask/cdap/AppWithSchedule.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
Build is running here - http://builds.cask.co/browse/CDAP-DUT3233-6
JIRA: https://issues.cask.co/browse/CDAP-3696
=> CDAP-3696 Made the schedule frequency to be 15 seconds.

cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/lineage/GetDatasetLineageCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/lineage/GetStreamLineageCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/AddMetadataPropertiesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/AddMetadataTagsCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataPropertiesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataTagsCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/RemoveMetadataCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/RemoveMetadataPropertiesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/RemoveMetadataPropertyCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/RemoveMetadataTagCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/RemoveMetadataTagsCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/CheckActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/GrantActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DefaultCommands.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/LineageCommands.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/MetadataCommands.java, cdap-cli/src/main/java/co/cask/cdap/cli/util/AbstractCommand.java, cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java
https://issues.cask.co/browse/CDAP-4270
http://builds.cask.co/browse/CDAP-DUT3296
=> CDAP-4270: CLI for metadata and lineage

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/resources/cdap-etl-lib.json, cdap-master/pom.xml, cdap-standalone/pom.xml
=> Revert "enhance build to create the config json for cdap-etl-lib"

cdap-client-tests/src/test/java/co/cask/cdap/client/StreamViewClientTestRun.java
https://issues.cask.co/browse/CDAP-4000
http://builds.cask.co/browse/CDAP-DUT3301
=> CDAP-4000: Can't fully delete stream that has views

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/services/actions/nodes-actions.js, cdap-ui/app/directives/dag/services/stores/nodes-store.js, cdap-ui/app/features/hydrator/adapters.less, cdap-ui/app/features/hydrator/controllers/create/leftpanel-ctrl.js
=> [CDAP-4332] Hydrator Diagram: Initial Node Placements

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/KeyHelper.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsValueKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/Metadata.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
Build - http://builds.cask.co/browse/CDAP-RBT529-1
=> CDAP-4274 Renaming MetadataHistoryEntry to Metadata, and other minor refactoring

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/directives/dag/my-dag-factory.js, cdap-ui/app/directives/dag/my-dag.html
=> Hydrator Diagram Control: Align & Fit To Screen

cdap-ui/app/directives/navbar-hydrator/namespace.html, cdap-ui/app/directives/navbar-hydrator/navbar.html, cdap-ui/app/directives/navbar-hydrator/navbar.js, cdap-ui/app/directives/navbar-hydrator/navbar.less, cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/templates/create/toppanel.html, cdap-ui/app/features/hydrator/templates/detail/top-panel.html, cdap-ui/app/features/hydrator/toppanel.less, cdap-ui/app/styles/themes/cdap/theme.less
*  Adds namespace dropdown to Hydrator header/navbar
*  Updates nav links (My Pipelines, Create Pipeline) to account for namespace
*  Adjusts z-indexes to ensure proper stacking (i.e., maximized console, top panel tooltips, etc.)
=> adds namespace dropdown to header

cdap-ui/app/directives/dag/my-dag.less
*  Changes border width of selected nodes to match border radius value (6px)
*  Adjusts line height and positioning of child elements to offset "selected" border value
*  Adds transition to smooth background-color/border width change
=> adjusts node border width to fix fine pixel issue

cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml, cdap-examples/deploy_pom.xml, cdap-examples/pom.xml
https://issues.cask.co/browse/CDAP-4399
http://builds.cask.co/browse/CDAP-RBT525-1
=> CDAP-4399 Remove repository.continuuity.com from archetypes and examples

cdap-app-fabric/pom.xml, cdap-app-fabric/src/main/java/co/cask/cdap/hive/ExploreUtils.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/security/TokenSecureStoreUpdater.java, cdap-app-fabric/src/main/java/co/cask/cdap/security/hive/HiveTokenUtils.java, cdap-app-fabric/src/main/java/co/cask/cdap/security/hive/JobHistoryServerTokenUtils.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
Porting this to 3.2. 
The PR was reviewed here: https://github.com/caskdata/cdap/pull/4738
Build: http://builds.cask.co/browse/CDAP-RT323-1
=> CDAP-4421: Provide Hive tokens to twill containers

cdap-distributions/bin/build_parcel.sh
backport of https://github.com/caskdata/cdap/pull/4744 via cherry-pick
=> add ability to override parcel version

cdap-ui/app/directives/flow-graph/flow-ctrl.js, cdap-ui/app/directives/flow-graph/flow-factories.js
Extract the centering and scaling value to the controller instead of inside the render function.
=> [CDAP-4185] fix workflow and flow diagram snapping back to center

cdap-common/bin/common.sh
Improve `get_conf` support and make `xmllint` optional.
- Improve failure if missing `xmllint` during `get_conf`
- Skip `get_conf` calls:
- Allow setting Kerberos config using CDAP_PRINCIPAL and CDAP_KEYTAB, and KERBEROS_ENABLED
- Allow setting Explore config using EXPLORE_ENABLED
=> CDAP-4444 Make xmllint dependency optional

cdap-ui/app/directives/dag/my-dag-ctrl.js
=> [CDAP-4336] Feature/ui hydrator multiselect fix

cdap-ui/app/features/datasets/templates/tabs/status.html, cdap-ui/app/features/streams/templates/tabs/status.html
*  Removes schema name sort from status view of streams and datasets
=> removes name sort from status views

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/NettyRouter.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/IdleEventProcessor.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/OutboundHandler.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/NettyRouterTestBase.java
JIRA - https://issues.cask.co/browse/CDAP-3887
Build - http://builds.cask.co/browse/CDAP-RBT542-9
Need to port this to 2.8 branch too.
=> Fix Router exceptions

pom.xml
https://issues.cask.co/browse/CDAP-4468
=> CDAP-4468: Fix co.cask.hbase hbase packaging

cdap-common/src/main/java/co/cask/cdap/common/collect/AllPairCollector.java, cdap-common/src/main/java/co/cask/cdap/common/collect/PairCollector.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/queue/ConsumerConfig.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/AbstractQueueConsumer.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueEntryRow.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseConsumerStateStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueClientFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/QueueBarrier.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/ShardedHBaseQueueStrategy.java, cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java, cdap-master/src/main/java/co/cask/cdap/data/tools/SimpleHBaseQueueDebugger.java, cdap-master/src/test/java/co/cask/cdap/data/tools/flow/HBaseQueueDebuggerTest.java
https://issues.cask.co/browse/CDAP-2105
http://builds.cask.co/browse/CDAP-RBT543
Cherry-picked from https://github.com/caskdata/cdap/pull/2290
```
/etc/init.d/cdap-master run co.cask.cdap.data.tools.HBaseQueueDebugger
```
or, to show details
```
java -cp `/etc/init.d/cdap-master classpath` -Dshow.progress=true co.cask.cdap.data.tools.HBaseQueueDebugger
```
=> HBaseQueueDebugger

cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/controllers/detail/tabs/pipeline-config-tab-ctrl.js, cdap-ui/app/features/hydrator/templates/detail/tabs/configuration.html
*  Adds ability to export pipeline configuration in Hydrator detail view
=> adds Export button to Configuration tab

cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-form.html
=> [CDAP-4503] add node version to node config

cdap-ui/app/directives/flow-graph/flow-ctrl.js, cdap-ui/app/directives/flow-graph/flow-factories.js, cdap-ui/app/directives/flow-graph/flow.js, cdap-ui/app/directives/flow-graph/workflow.js
Refactor flow-graph by extracting things that need to happen only once to ```prepareGraph()```.
=> [CDAP-4184] fix rendering tooltip issue

cdap-ui/app/directives/dag/my-dag-ctrl.js
=> [CDAP-4507] center DAG on clone

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamViewHttpHandler.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamViewHttpHandlerTest.java
https://issues.cask.co/browse/CDAP-4318
http://builds.cask.co/browse/CDAP-RBT526
=> CDAP-4318: Create view REST API should respond with 400 when the body is not provided

cdap-ui/app/features/apps/applications.less, cdap-ui/app/features/apps/templates/detail.html
*  Adds styling to Hydrator button in app detail view
=> adds styling to Hydrator button in app detail view

cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.html, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.less, cdap-ui/app/features/hydrator/bottompanel.less
*  Adds outline to active output schema table cells as well as focused form inputs
=> adds active cell/input highlighting to node config fields

cdap-distributions/src/hdinsight/install.sh
=> update hdinsight installer for 3.3.0 release

cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json, cdap-ui/templates/apps/predefined/KafkaToHBase.json, cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json, cdap-ui/templates/apps/predefined/KafkaToStream.json, cdap-ui/templates/apps/predefined/StreamToHBase.json, cdap-ui/templates/apps/predefined/TwitterToHBase.json, cdap-ui/templates/apps/predefined/TwitterToStream.json
Based on this [GIST](https://gist.github.com/ajainarayanan/612d54d00f7675272c80.js) I have modified only the version and artifact name in all predefined apps.
=> Changes artifact name and version for predefined apps in hydrator

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java
- Spark doesn’t do the localization, hence we need to do it by ourselves
Cherry-picked to 3.2 : https://github.com/caskdata/cdap/pull/4829
=> (CDAP-4553) Localize spark metrics con file

cdap-api/src/main/java/co/cask/cdap/internal/UserErrors.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java, cdap-app-fabric/src/main/resources/UserMessages.properties
Related: https://issues.cask.co/browse/CDAP-4304
Build: http://builds.cask.co/browse/CDAP-RBT550-3
=> Fix and clean up error messages.

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamViewHttpHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
https://issues.cask.co/browse/CDAP-4366
http://builds.cask.co/browse/CDAP-RBT527
=> CDAP-4366: Stream Views RESTful API throws IAE instead of returning 404

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
Release build failed because of this flaky test : http://builds.cask.co/browse/CDAP-RBT-JOB1-1013/test/case/24136713
JIRA : https://issues.cask.co/browse/CDAP-4562
Build : http://builds.cask.co/browse/CDAP-RBT567
=> Wait until runrecord count is 1 before trying to read it

cdap-docs/admin-manual/build.sh
[Passes Quick Build](http://builds.cask.co/browse/CDAP-DOB80-1)
=> Update MD5 hash. No material changes in the guarded file.

cdap-common/bin/common.sh, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersionSpecificFactory.java
JIRA: https://issues.cask.co/browse/CDAP-4301
=> CDAP-4301 Copied HBaseVersion class from tephra to CDAP.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java
- Create a jar with logback.xml inside.
- Localize the jar and make sure it’s the first in the classpath
=> (CDAP-4569) Localize logback.xml correctly for MR and Spark.

cdap-common/src/main/java/co/cask/cdap/common/ServiceBindException.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/NettyRouter.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterMain.java, cdap-security/src/main/java/co/cask/cdap/security/runtime/AuthenticationServerMain.java, cdap-security/src/main/java/co/cask/cdap/security/server/ExternalAuthenticationServer.java, cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
- ExternalAuthenticationServer
- NettyRouter
https://issues.cask.co/browse/CDAP-4514
http://builds.cask.co/browse/CDAP-RBT564
=> CDAP-4514: Log error message instead of stack trace when failing to bind to port

cdap-master/src/main/java/co/cask/cdap/master/startup/YarnCheck.java
some version of hadoop return a null resources object instead of
an object that contains zeros for its memory and vcores.
Perform null checks to handle this scenario, and also try to
error proof against a bad vcores number.
=> CDAP-4565 handle nulls in yarn resources check

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-common/src/main/resources/cdap-default.xml, cdap-docs/developers-manual/source/building-blocks/artifacts.rst, cdap-docs/developers-manual/source/building-blocks/plugins.rst, cdap-standalone/src/main/resources/cdap-site.xml
Support for system plugins being picked up from multiple directories.
https://issues.cask.co/browse/CDAP-4571
http://builds.cask.co/browse/CDAP-RBT575-2
=> CDAP-4571 Multiple system artifact directories.

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ClientVersions.java
=> CDAP-4577: Fix Kafka version check

cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseTableExporter.java
JIRA: https://issues.cask.co/browse/CDAP-4555
HBaseExportUtility was not working on HBase 0.96 since the class ``KeyValueImporter`` used in the utility was package private in HBase 0.96. In this PR using custom ``KeyValueImporter`` class.
Verified the fix works on HBase 0.96.
Testing on the other HBase versions as well.
=> CDAP-4555 Using custom KeyValueImporter to write KeyValues.

cdap-docs/admin-manual/build.sh
[Passes Quick Build.](http://builds.cask.co/browse/CDAP-DOB81-1)
=> Updated MD5 hash for cdap-default.xml. No material changes in file.

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/runtime/FlowTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/runtime/app/PendingMetricTestApp.java
JIRA : https://issues.cask.co/browse/CDAP-4357
Build : http://builds.cask.co/browse/CDAP-RBT568
=> CDAP-4357 Fix the expected count of pending queue events

cdap-common/bin/common.sh, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueUtilFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtilFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersionSpecificFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HTableNameConverterFactory.java, cdap-data-fabric/src/test/java/co/cask/cdap/data/hbase/HBaseTestFactory.java, cdap-hbase-compat-1.0-cdh5.5.0/pom.xml, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementFilter.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementHandler.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementSummingScanner.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase10cdh550/DefaultTransactionProcessor.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase10cdh550/DequeueFilter.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase10cdh550/DequeueScanObserver.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase10cdh550/HBaseQueueRegionObserver.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBase10CDH550QueueConsumer.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBase10CDH550QueueUtil.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/util/hbase/HBase10CDH550TableUtil.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/util/hbase/HTable10CDH550NameConverter.java, cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data/hbase/HBase10CDH550Test.java, cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementHandlerTest.java, cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementSummingScannerTest.java, cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase10CDH550QueueTest.java, cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data2/util/hbase/HBase10CDH550TableUtilTest.java, cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data2/util/hbase/HTable10CDH550NameConverterTest.java, cdap-master/pom.xml, pom.xml
JIRA: https://issues.cask.co/browse/CDAP-4301
=> Support for CDH 5.5.0

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsValueKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
- Removes the concept of MetadataType
Issue: https://issues.cask.co/browse/CDAP-4590
Build: http://builds.cask.co/browse/CDAP-RBT580-1
@poornachandra @bdmogal : Please review.
=> CDAP-4590: Remove MetadataType from MetadataDataset

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java, cdap-master/src/main/java/co/cask/cdap/data/tools/AbstractQueueUpgrader.java, cdap-master/src/main/java/co/cask/cdap/data/tools/StreamStateStoreUpgrader.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
- Upgrade stream state store for Id.Stream.toString changes
=> CDAP-3974: Add upgrade step for changes in Id serialization

cdap-ui/app/directives/flow-graph/flow-factories.js
Fixes overflowing node names in workflow diagrams.
=> Fixes overlapping node names in workflow diagram

cdap-ui/app/directives/dag/my-dag.html, cdap-ui/app/directives/dag/my-dag.js, cdap-ui/app/directives/log-viewer/log-viewer.js, cdap-ui/app/features/apps/templates/tabs/status.html, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-noconfig-form.html, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-properties-template.html
- Disable select state on Apps status page
- Only show 'provide required information' error after validate only
- Fix duplicate logs
=> [CDAP-4598] [CDAP-4610] [CDAP-4611] Feature/ui hydrator fixes

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
JIRAs: 
https://issues.cask.co/browse/CDAP-4529
https://issues.cask.co/browse/CDAP-4246
Build: http://builds.cask.co/browse/CDAP-RBT585-3
=> CDAP-4246 CDAP-3831 Add a buffer to run stop time while reading logs

cdap-common/bin/common.sh, cdap-common/src/main/resources/cdap-default.xml, cdap-docs/admin-manual/build.sh, cdap-docs/admin-manual/source/_includes/installation/configuration.txt, cdap-docs/admin-manual/source/installation/ambari/installing-cdap.rst, cdap-docs/admin-manual/source/installation/cloudera/installation.rst, cdap-docs/admin-manual/source/installation/cloudera/step-by-step-cloudera.rst, cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java, cdap-standalone/src/main/resources/cdap-site.xml, cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java
https://issues.cask.co/browse/CDAP-4355
TODO:
- Relevant changes to CSD and Ambari.
- Test on cluster
=> CDAP-4355 Change 'explore.enabled' to 'true' by default

cdap-ui/app/index.html, cdap-ui/app/main.js
=> [CDAP-4600] change copyright date to just get current year

cdap-ui/app/features/overview/overview.html, cdap-ui/app/services/service-status-factory.js
=> [CDAP-3706] fix system health updates

cdap-archetypes/cdap-app-archetype/README.rst, cdap-archetypes/cdap-app-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/pom.xml, cdap-archetypes/cdap-spark-java-archetype/README.rst, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml, cdap-archetypes/cdap-spark-scala-archetype/README.rst, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml, cdap-archetypes/pom.xml, cdap-docs/developers-manual/source/building-blocks/mapreduce-programs.rst, cdap-docs/developers-manual/source/getting-started/dev-env.rst
Jira: https://issues.cask.co/browse/CDAP-4573
This is to help people set up a MapReduce app with the correct dependencies and excludes.
=> [CDAP-4573] MapReduce archetype and documentation

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/KeyHelper.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsHistoryKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetDefinition.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchTargetType.java
- Implementation of new Metadata Storage and Search https://issues.cask.co/browse/CDAP-4591
- Added more unit test for metadata search to cover different cases
- Fixed bug in tag search: https://issues.cask.co/browse/CDAP-4393
- Fixed bug in mixed case metadata storage and search https://issues.cask.co/browse/CDAP-4331
Design Doc: https://wiki.cask.co/display/CE/Improvements+to+Metadata+Search+and+System+Metadata
Build: http://builds.cask.co/browse/CDAP-RBT584-4
=> CDAP-4591: New Metadata storage and search

cdap-ui/app/features/mapreduce/templates/tabs/runs/tabs/status.html
=> [CDAP-3665] change progress bar color to red when state is not completed or running

cdap-docs/cdap-apps/source/hydrator/creating.rst, cdap-docs/integrations/source/partners/cloudera/ingesting.rst
Updating docs with latest ETLConfig changes. 
JIRA: https://issues.cask.co/browse/CDAP-4349
=> CDAP-4349:updating ETLConfig in docs

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableTest.java, cdap-docs/developers-manual/source/building-blocks/datasets/table.rst
Jira: https://issues.cask.co/browse/CDAP-4650
=> [cdap 4650] Add documentation and test that Table as a batch writable always ignores the key

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreTest.java
JIRA - https://issues.cask.co/browse/CDAP-4628
Build - http://builds.cask.co/browse/CDAP-RBT601-3
=> CDAP-4628 Tokenize metadata search query

cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/features/admin/controllers/namespace/templates-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/templates-list-ctrl.js, cdap-ui/app/features/admin/templates/namespace/templates-list.html, cdap-ui/app/features/admin/templates/namespace/templates.html, cdap-ui/app/features/hydrator/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/hydrator/services/create/actions/plugin-actions.js, cdap-ui/app/features/hydrator/services/create/stores/left-panel-store.js, cdap-ui/app/features/hydrator/services/plugin-config-factory.js, cdap-ui/app/features/hydrator/templates/create/popovers/leftpanel-plugin-popover.html, cdap-ui/app/services/helpers.js
=> The Revival of Plugin Templates

cdap-ui/app/directives/dag/my-dag-ctrl.js, cdap-ui/app/features/hydrator/services/detail/actions/pipeline-detail-metrics-actions.js
=> [CDAP-4601] Feature/ui hydrator records out tooltip

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Upgrade for metadata properties and tags to new format of storage.
Tested on cluster initially.
Testing on cluster again as I made some changes to code. 
Issue: https://issues.cask.co/browse/CDAP-4396
Build: http://builds.cask.co/browse/CDAP-RBT598-3
Tested on cluster
=> CDAP-4396 Upgrade for new Metadata Storage

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
I merged two Metadata PR back to back (build has passed on both) and Github was not smart enough to fail the second merge because of  merge conflicts.
=> Fix conflicts among metadata pr

cdap-ui/app/directives/log-viewer/log-viewer.js, cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/controllers/detail/tabs/history-ctrl.js, cdap-ui/app/features/hydrator/controllers/detail/top-panel-ctrl.js, cdap-ui/app/features/hydrator/services/create/actions/config-actions.js, cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-runs-store.js, cdap-ui/app/features/hydrator/templates/detail/tabs/history.html, cdap-ui/app/features/hydrator/templates/detail/top-panel.html
1. Logs not appearing on next run
2. History not getting updated for first run
3. Fix color of status (COMPLETED and STARTING)
4. Error message on publish should not be json object
5. Console message should wrap
=> [CDAP-4666] [CDAP-4675] [CDAP-4676] [CDAP-4678] UI Multiple Fixes

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/resources/cdap-default.xml
- Supported different log level.
=> Optionally pipe application container logs to master process log

cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-nonruns-store.js
=> [CDAP-4683] fix clone issue on stream

cdap-ui/app/features/hydrator/controllers/create/toppanel-ctrl.js, cdap-ui/app/features/hydrator/controllers/detail/top-panel-ctrl.js, cdap-ui/app/features/hydrator/templates/create/toppanel.html, cdap-ui/app/features/hydrator/templates/detail/top-panel.html, cdap-ui/app/features/hydrator/toppanel.less
*  Removes my-maxlength attribute from metadata description
*  Replaces line breaks in the description with a space
Create View:
Detail View:
Long Tooltip:
=> fixes pipeline description rendering issues

cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/SchemaIndexer.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/indexer/SchemaIndexerTest.java, cdap-docs/reference-manual/source/http-restful-api/metadata.rst
JIRA: https://issues.cask.co/browse/CDAP-4592
Build: http://builds.cask.co/browse/CDAP-RBT603-13
Doc Build: http://builds.cask.co/browse/CDAP-DDB30-4
Doc link for verification - http://builds.cask.co/artifact/CDAP-DDB30/shared/build-4/Docs-HTML/3.3.0-SNAPSHOT/en/reference-manual/http-restful-api/metadata.html#searching-for-metadata
=> CDAP-4592 Metadata schema indexer

cdap-distributions/bin/build_parcel.sh
=> include cdh5.5.0 compat module in parcel

cdap-ui/app/services/streams/my-streams-service.js
*  Adds correct alert positioning to stream upload success
=> adds new alert styling/positioning to Stream upload

cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java, cdap-docs/developers-manual/source/building-blocks/metadata-lineage.rst
JIRA: https://issues.cask.co/browse/CDAP-4705
Build: http://builds.cask.co/browse/CDAP-RBT614-1
Docs Build: http://builds.cask.co/browse/CDAP-DDB31-2
Docs link for verification - http://builds.cask.co/artifact/CDAP-DDB31/shared/build-2/Docs-HTML/3.3.0-SNAPSHOT/en/developers-manual/building-blocks/metadata-lineage.html#system-metadata
=> CDAP-4705 Tagging Datasets as batch or explore

cdap-common/src/main/resources/cdap-default.xml, cdap-docs/admin-manual/build.sh, cdap-docs/faqs/build.sh, cdap-docs/faqs/source/cdap.rst, cdap-docs/faqs/source/general.rst
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB90-1).
=> Fixing hashes and small updates.

cdap-docs/reference-manual/source/release-notes.rst
=> Release notes for 3.3

cdap-docs/reference-manual/source/release-notes.rst
Fix space introduced by: https://github.com/caskdata/cdap/pull/4990
=> Remove space

cdap-docs/reference-manual/source/release-notes.rst
Fixed formatting
Moved CDH 5.5 support to improvements
=> Fix rst format

cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/util/hbase/AbstractHBaseTableUtilTest.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/util/hbase/HBase96TableUtil.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/util/hbase/HBase98TableUtil.java, cdap-hbase-compat-1.0-cdh/src/main/java/co/cask/cdap/data2/util/hbase/HBase10CDHTableUtil.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/util/hbase/HBase10CDH550TableUtil.java, cdap-hbase-compat-1.0/src/main/java/co/cask/cdap/data2/util/hbase/HBase10TableUtil.java, cdap-hbase-compat-1.1/src/main/java/co/cask/cdap/data2/util/hbase/HBase11TableUtil.java
- Table creation/drop can be done in parallel.
=> Make HBaseTableUtil test slightly faster

cdap-docs/reference-manual/source/release-notes.rst
Fixes.
Passed [Quick Build](http://builds.cask.co/browse/CDAP-DOB93-1)
[Release Notes](http://builds.cask.co/artifact/CDAP-DOB93/shared/build-1/Docs-HTML/3.3.0/en/reference-manual/release-notes.html#release-3-3-0)
=> Release Notes for 3.3.0

cdap-distributions/bin/build_apt_repo.sh, cdap-distributions/bin/build_parcel_repo.sh, cdap-distributions/bin/build_yum_repo.sh
This is a backport of the latest changes from develop for these scripts, used in the build pipeline.
=> Backport repo script changes from develop

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json
Update IntelliJ version for VM... backported from release/3.3
=> Update IDEA version to 15.0.2

cdap-distributions/bin/build_yum_repo.sh
=> Check for RPM files in target directory

cdap-docs/reference-manual/source/release-notes.rst
Quick build: http://builds.cask.co/browse/CDAP-DQBP39-2
=> Release notes for CDAP v.2.8.3

cdap-docs/admin-manual/source/operations/index.rst, cdap-docs/build.sh, cdap-docs/developers-manual/source/building-blocks/workflows.rst, cdap-docs/examples-manual/source/apps-packs.rst, cdap-docs/integrations/source/index.rst, cdap-docs/integrations/source/partners/cloudera/index.rst, cdap-docs/integrations/source/partners/cloudera/ingesting.rst, cdap-ui/app/features/hydrator/services/plugin-config-factory.js, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-form.html, cdap-ui/app/services/constants.js
=> Revert "Merge release 3.3 into develop"

cdap-ui/app/features/hydrator/controllers/list-ctrl.js, cdap-ui/app/features/hydrator/routes.js, cdap-ui/app/features/hydrator/services/create/actions/config-actions.js, cdap-ui/app/features/hydrator/services/create/stores/config-store.js, cdap-ui/app/features/hydrator/templates/list.html
- Prevents drafts from being overwritten. Update should be possible but not overwritten.
=> Feature/ui hydrator 3.3.1 issues 1

cdap-docs/cdap-apps/source/hydrator/custom.rst, cdap-docs/faqs/source/hydrator.rst, cdap-docs/faqs/source/index.rst, cdap-docs/faqs/source/table-of-contents.rst
Docs-quick-Build: http://builds.cask.co/browse/CDAP-DOB95
=> Adds the initial FAQ documentation for Hydrator UI

cdap-ui/app/features/hydrator/controllers/create-ctrl.js, cdap-ui/app/features/hydrator/services/non-store-pipeline-error-factory.js, cdap-ui/app/services/constants.js
- Adds validation during JSON import in hydrator.
=> Adds validation for imported JSON in hydrator

cdap-ui/app/directives/app-level-loading-icon/loading.js, cdap-ui/app/main.js
Was causing js error and prevented from automatically refreshing browser when node server came up
=> Removes socket closed event alert message. 

cdap-ui/Gulpfile.js, cdap-ui/app/directives/flow-graph/flow-ctrl.js, cdap-ui/app/directives/flow-graph/flow-factories.js, cdap-ui/app/directives/flow-graph/flow.js, cdap-ui/app/directives/flow-graph/flow.less, cdap-ui/app/directives/flow-graph/workflow.js, cdap-ui/bower.json
- Fix tooltip issue not showing on Firefox
- Fix vertical centering issue on large DAG
=> [CDAP-4613] [CDAP-4758] Feature/ui flow diagram tooltips

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
JIRA : https://issues.cask.co/browse/CDAP-4741
Build : http://builds.cask.co/browse/CDAP-RBT620-1
=> CDAP-4741, delete metadata when deleting artifacts and its properties

cdap-docs/cdap-apps/source/_includes/hydrator-plugins/shared-plugins/core.rst, cdap-docs/cdap-apps/source/hydrator/custom.rst, cdap-docs/reference-manual/source/http-restful-api/artifact.rst, cdap-docs/reference-manual/source/release-notes.rst, cdap-examples/resources/weblog-analytics-config.json
=> Five Files with Typos.

cdap-docs/developers-manual/source/building-blocks/spark-programs.rst
Issue: https://issues.cask.co/browse/CDAP-3118
=> CDAP-3118 Add SparkSQL documentation

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
Improve the logging when there are failures to create the stream
heartbeats feed, and when there are issues subscribing to the
feed. The actual error will be logged as a warning the first time
the failure is seen. Subsequent retry failures are logged at
debug level.
This allows users to see what caused the failure, and also
prevents spamming the log at info level if there is some
non-recoverable error, such as app fabric being on an unreachable host.
=> CDAP-4773 improve logging on notification feed failures

cdap-ui/app/features/login/routes.js
Related JIRA: https://issues.cask.co/browse/CDAP-4725
=> Prevents UI from showing any authentication errors in alert after login

cdap-ui/app/features/hydrator/templates/detail/top-panel.html
=> [CDAP-4802] change next run subtitle when the pipeline is not scheduled

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TwillLogEntryAdapter.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TwillLogThrowableAdapter.java
=> CDAP-4771: YARN container logs go to stdout file in Cloudera Manager

cdap-docs/cdap-apps/build.sh
Building [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB107-1)
=> Removed two plugins that were moved in the Hydrator repo.

cdap-docs/developers-manual/source/building-blocks/metadata-lineage.rst
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB108-1)
=> Minor edits to Metadata and Lineage Documentation

cdap-docs/developers-manual/source/data-exploration/filesets.rst
Fix for [CDAP-4310](https://issues.cask.co/browse/CDAP-4310). (Note that the branch number is incorrect.)
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB109-1)
[Revised page](http://builds.cask.co/artifact/CDAP-DOB109/shared/build-1/Docs-HTML/3.3.1-SNAPSHOT/en/developers-manual/data-exploration/filesets.html)
=> Update to Filesets documentation

cdap-ui/Gulpfile.js, cdap-ui/app/directives/validators/validator-ctrl.js, cdap-ui/app/directives/validators/validators.html, cdap-ui/app/directives/validators/validators.js, cdap-ui/app/directives/validators/validators.less, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js, cdap-ui/app/features/hydrator/services/create/stores/config-store.js, cdap-ui/app/features/hydrator/services/hydrator-service.js, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-properties-template.html, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-validator-transform.html, cdap-ui/bower.json
- Add label for validator
- Add JavaScript Beautifier to format the created script
- Fix broken generated validation function script
=> [CDAP-4829] [CDAP-4837] Feature/ui validator transform fixes

cdap-ui/app/features/hydrator/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/hydrator/services/create/stores/config-store.js, cdap-ui/app/features/hydrator/services/create/stores/left-panel-store.js
Related JIRA: https://issues.cask.co/browse/CDAP-4830
=> Fixes bottom panel to not pull up when the user adds a node from the left panel

cdap-ui/app/directives/validators/validators.html, cdap-ui/app/features/hydrator/controllers/create/partials/nodeconfig-ctrl.js, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-properties-template.html
This https://github.com/caskdata/hydrator-plugins/pull/143 has to be merged for this to work.
=> Surface errorDatasetName in plugins that has 'hasErrorDataset' flag set in the node config

cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetServiceManager.java, cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Main PR: https://github.com/caskdata/cdap/pull/5110
This is just to merge it against 3.3
=> CDAP 4708: Upgrade step to generate system metadata for existing entities in 3.

cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json, cdap-ui/templates/apps/predefined/KafkaToHBase.json, cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json, cdap-ui/templates/apps/predefined/KafkaToStream.json, cdap-ui/templates/apps/predefined/StreamToHBase.json, cdap-ui/templates/apps/predefined/TwitterToHBase.json, cdap-ui/templates/apps/predefined/TwitterToStream.json
Bump Hydrator version in predefined templates.
=> Bump Hydrator version in predefined templates.

cdap-docs/faqs/source/cloudera-manager.rst
Fix for https://issues.cask.co/browse/CDAP-4948
[Quick Build 1](http://builds.cask.co/browse/CDAP-DOB114-1)
[Cloudera FAQ](http://builds.cask.co/artifact/CDAP-DOB114/shared/build-1/Docs-HTML/3.3.1-SNAPSHOT/en/faqs/cloudera-manager.html#i-d-like-to-directly-access-the-parcels-how-do-i-do-that)
=> Update parcel FAQ.

cdap-docs/tools/cdap-xml-files.txt, cdap-docs/tools/doc-cdap-default.py
Additional files that can be checked, moved static variables out of methods so other methods can use them, and factored out duplicated code. Tested; successful on the listed files and URLs.
=> Improve the cdap-defaults tool

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/RowColumns.java, cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/UpgradeTool.java, cdap-client/src/main/java/co/cask/cdap/client/config/ClientConfig.java, cdap-common/src/main/resources/cdap-default.xml, cdap-docs/_common/_source/index.rst, cdap-docs/admin-manual/build.sh, cdap-docs/build.sh, cdap-docs/developers-manual/source/building-blocks/metadata-lineage.rst, cdap-docs/faqs/source/cloudera-manager.rst, cdap-docs/integrations/source/conf.py, cdap-docs/integrations/source/index.rst, cdap-docs/integrations/source/partners/cloudera/index.rst, cdap-docs/integrations/source/partners/cloudera/navigator-integration.rst, cdap-docs/reference-manual/source/cli-api.rst, cdap-docs/reference-manual/source/licenses/index.rst, cdap-docs/tools/cdap-xml-files.txt, cdap-docs/tools/doc-cdap-default.py, cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreConnection.java, cdap-ui/app/features/hydrator/controllers/create/partials/reference-tab-ctrl.js, cdap-ui/app/features/hydrator/services/plugin-config-factory.js
Resolved conflicts in the following files:
cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json
cdap-ui/templates/apps/predefined/KafkaToHBase.json
cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json
cdap-ui/templates/apps/predefined/KafkaToStream.json
cdap-ui/templates/apps/predefined/StreamToHBase.json
cdap-ui/templates/apps/predefined/TwitterToHBase.json
cdap-ui/templates/apps/predefined/TwitterToStream.json
Build passed locally.
=> Merge release/3.3 to develop

cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/Filters.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementHandler.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementTxFilter.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase96/DefaultTransactionProcessor.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/Filters.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementHandler.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementTxFilter.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase98/DefaultTransactionProcessor.java, cdap-hbase-compat-1.0-cdh/src/main/java/co/cask/cdap/data2/increment/hbase10cdh/Filters.java, cdap-hbase-compat-1.0-cdh/src/main/java/co/cask/cdap/data2/increment/hbase10cdh/IncrementHandler.java, cdap-hbase-compat-1.0-cdh/src/main/java/co/cask/cdap/data2/increment/hbase10cdh/IncrementTxFilter.java, cdap-hbase-compat-1.0-cdh/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase10cdh/DefaultTransactionProcessor.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/increment/hbase10cdh550/Filters.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementHandler.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/increment/hbase10cdh550/IncrementTxFilter.java, cdap-hbase-compat-1.0-cdh5.5.0/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase10cdh550/DefaultTransactionProcessor.java, cdap-hbase-compat-1.0/src/main/java/co/cask/cdap/data2/increment/hbase10/Filters.java, cdap-hbase-compat-1.0/src/main/java/co/cask/cdap/data2/increment/hbase10/IncrementHandler.java, cdap-hbase-compat-1.0/src/main/java/co/cask/cdap/data2/increment/hbase10/IncrementTxFilter.java, cdap-hbase-compat-1.0/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase10/DefaultTransactionProcessor.java, cdap-hbase-compat-1.1/src/main/java/co/cask/cdap/data2/increment/hbase11/Filters.java, cdap-hbase-compat-1.1/src/main/java/co/cask/cdap/data2/increment/hbase11/IncrementHandler.java, cdap-hbase-compat-1.1/src/main/java/co/cask/cdap/data2/increment/hbase11/IncrementTxFilter.java, cdap-hbase-compat-1.1/src/main/java/co/cask/cdap/data2/transaction/coprocessor/hbase11/DefaultTransactionProcessor.java, pom.xml
JIRA - https://issues.cask.co/browse/CDAP-4602.
This should be merged on the corresponding tephra PR https://github.com/caskdata/tephra/pull/111 is merged.
=> CDAP-4602 Upgrade CDAP with Tephra 0.6.5

cdap-docs/reference-manual/source/release-notes.rst
Passed [Quick Build 6](http://builds.cask.co/browse/CDAP-DOB111-6)
[Release Notes](http://builds.cask.co/artifact/CDAP-DOB111/shared/build-6/Docs-HTML/3.3.1-SNAPSHOT/en/reference-manual/release-notes.html#release-3-3-1)
=> 3.3.1 Release Notes

cdap-docs/admin-manual/build.sh
Passes a [Quick Build](http://builds.cask.co/browse/CDAP-DOB117-1).
=> Fix MD5 hash.

cdap-ui/app/features/admin/controllers/namespace/app-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/app-metadata-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/create-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/dataset-metadata-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/datasets-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/settings-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/stream-metadata-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/streams-create-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/templates-ctrl.js, cdap-ui/app/features/admin/controllers/namespace/templates-list-ctrl.js, cdap-ui/app/features/admin/routes.js, cdap-ui/app/features/hydrator/controllers/create/toppanel-ctrl.js, cdap-ui/app/features/hydrator/controllers/detail/top-panel-ctrl.js, cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/services/alert-on-valium/alert-on-valium.js, cdap-ui/app/services/streams/my-streams-service.js
- Success message only stay for 3 seconds
- Fix success message bug on admin
=> [CDAP-4765] Feature/ui fix alert banner

cdap-app-fabric/src/main/java/co/cask/cdap/security/TokenSecureStoreUpdater.java, cdap-common/src/main/java/co/cask/cdap/common/security/YarnTokenUtils.java, cdap-common/src/main/java/org/apache/twill/internal/yarn/Hadoop21YarnAppClient.java
CDAP-4767 Give every application its own delegation tokens so that cancellation of delegation tokens of one application does not affect another application
Build - http://builds.cask.co/browse/CDAP-RBT644-3
=> CDAP-4975 Fix HA RM delegation token format

cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/main/java/SparkPageRankApp.java, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/main/java/SparkPageRankProgram.java, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/test/java/SparkPageRankAppTest.java, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/main/scala/SparkKMeansApp.java, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/main/scala/SparkKMeansProgram.scala, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/test/java/SparkKMeansAppTest.java, cdap-examples/SparkKMeans/src/main/java/co/cask/cdap/examples/sparkkmeans/Point.java, cdap-examples/SparkKMeans/src/main/java/co/cask/cdap/examples/sparkkmeans/SparkKMeansApp.java, cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java, cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankProgram.java, cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java
Update archetypes, based upon their corresponding sources.
=> Copy the source files to archetype files and replace the package name.

cdap-docs/admin-manual/source/installation/cloudera.rst
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB118-2)
[Cloudera Installation Page](http://builds.cask.co/artifact/CDAP-DOB118/shared/build-2/Docs-HTML/3.3.1/en/admin-manual/installation/cloudera.html#preparing-the-cluster)
See the item #3.
=> Add setting the YARN Application Classpath.

cdap-app-fabric/src/main/java/org/apache/twill/yarn/YarnTwillPreparer.java
When merging back to develop branch, this file must be removed, otherwise there will be compilation error.
=> Copy the TWILL-154 patch for YarnTwillPreparer

cdap-docs/developers-manual/build.sh, cdap-docs/developers-manual/source/building-blocks/spark-programs.rst, cdap-docs/examples-manual/build.sh
Fix docs build. Also needed to change the referencing line numbers.
Quick Build: http://builds.cask.co/browse/CDAP-DOB119-1
=> Fix docs build. Also needed to change the referencing line numbers.

cdap-examples/SparkKMeans/src/main/scala/co/cask/cdap/examples/sparkkmeans/SparkKMeansProgram.scala
- Move static methods/variables to companion object
- This reduce the serialization scope, which is causing issue
- There is some ArrayList instance deep inside the serialization tree that causing concurrent modification issue (race condition).
- This maybe a bug in Spark, nevertheless, reducing the closure scope helps.
It fixes this failure
http://builds.cask.co/browse/CDAP-DUT-1241/test
```
java.lang.AssertionError: expected:<200> but was:<204>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at co.cask.cdap.examples.sparkkmeans.SparkKMeansAppTest.requestService(SparkKMeansAppTest.java:97)
at …
```
=> Fix the flaky SparkKMeans test

cdap-ui/app/features/hydrator/adapters.less, cdap-ui/app/features/hydrator/controllers/create-ctrl.js, cdap-ui/app/features/hydrator/controllers/create/preconfigured-ctrl.js, cdap-ui/app/features/hydrator/routes.js, cdap-ui/app/features/hydrator/templates/create.html, cdap-ui/app/features/hydrator/templates/preconfigured-list.html
The goal of this PR is to make browser's back button function as expected when you are at preconfigured pipeline page.
=> [CDAP-4859] make preconfigured pipeline page as a standalone state

cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/controllers/create/partials/nodeconfig-ctrl.js, cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-output-schema.html
=> [CDAP-4665] make confirmation button in new line

cdap-client-tests/src/test/java/co/cask/cdap/client/WorkflowClientTestRun.java
- Poll for the result to avoid race condition
=> Fix the flaky WorkflowClientTest

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramWrapper.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkUtils.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
- NPE in CM cluster when running with Spark 1.4+
Verified in CM cluster with Spark 1.4.1 and 1.5.1
=> (CDAP-5019) Workaround for the SPARK-13441 bug

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramWrapper.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkUtils.java, cdap-common/src/main/java/co/cask/cdap/common/lang/jar/BundleJarUtil.java, cdap-common/src/test/java/co/cask/cdap/common/lang/jar/BundleJarUtilTest.java
An improvement on the original fix to make it more fool proof.
=> (CDAP-5019) Ship all files under HADOOP_CONF_DIR from Master to Spark container

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java
- Some properties are passed in as system properties, which should get erased
- e.g. spark.executor.extraJavaOptions=-Dhdp.version=…
=> Only cleanup system properties set by SparkSubmit

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java, cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java, cdap-integration-test/src/test/java/co/cask/cdap/test/IntegrationTestBaseTest.java, cdap-integration-test/src/test/java/co/cask/cdap/test/TestApplication.java, cdap-integration-test/src/test/java/co/cask/cdap/test/TestFlow.java, cdap-integration-test/src/test/java/co/cask/cdap/test/TestFlowlet.java, cdap-test/src/main/java/co/cask/cdap/test/TestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/ApplicationManagerFactory.java
Build: http://builds.cask.co/browse/CDAP-DUT3597-4
=> Adding getApplicationManager() method to IntegrationTestBase

cdap-ui/app/features/tracker/controllers/entity-ctrl.js, cdap-ui/app/features/tracker/controllers/metadata-ctrl.js, cdap-ui/app/features/tracker/controllers/results-ctrl.js, cdap-ui/app/features/tracker/routes.js, cdap-ui/app/features/tracker/services/my-tracker-api.js, cdap-ui/app/features/tracker/templates/entity.html, cdap-ui/app/features/tracker/templates/lineage.html, cdap-ui/app/features/tracker/templates/metadata.html, cdap-ui/app/features/tracker/templates/results.html, cdap-ui/app/features/tracker/tracker.less
No truncation, no copy on popup
=> [CDAP-5007] Feature/ui tracker entity detail

cdap-docs/_common/_themes/cdap/layout.html
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB129-1).
Final part of fix for https://issues.cask.co/browse/CDAP-5048.
=> Remove Amazon SQS tracking.

cdap-api/src/main/java/co/cask/cdap/api/RuntimeContext.java, cdap-app-fabric/pom.xml, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java, pom.xml
- Also move the scala compiler plugin management to top level pom
=> (CDAP-5074) Make RunId available through RuntimeContext

cdap-docs/reference-manual/source/http-restful-api/lifecycle.rst
- Add documentation of retrieving details of a program, with an example of a flow included.
- Fixed additional errors:
- removed "schedules" included in program-types in error in certain APIs
- re-orgarnized program-types to be in a consistent, close-to alphabetical order
- removed extraneous copy
- tightened up certain titles
- fixed an incorrect heading level
Fix for https://issues.cask.co/browse/CDAP-5005.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB128-1).
Updated [Lifecycle HTTP RESTful API](http://builds.cask.co/artifact/CDAP-DOB128/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/lifecycle.html)
=> CDAP-5005: Documenting Missing RESTful API for retrieving Flow details

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkSubmitter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/DistributedSparkSubmitter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunner.java
Verified on cluster.
Create https://issues.cask.co/browse/CDAP-5143 for creating integration test.
=> (CDAP-5137) Submit Spark job based on the scheduler queue setting

cdap-client-tests/src/test/java/co/cask/cdap/client/QueryClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/QueryClient.java, cdap-client/src/main/java/co/cask/cdap/client/config/ClientConfig.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/resources/cdap-default.xml, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java, cdap-explore-client/src/main/java/co/cask/cdap/explore/client/DiscoveryExploreClient.java, cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreHttpClient.java, cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreDriver.java
https://issues.cask.co/browse/CDAP-5045
http://builds.cask.co/browse/CDAP-RBT645
=> CDAP-5045: Timeout when enabling explore on app deploy

cdap-proto/src/main/java/co/cask/cdap/proto/audit/AuditMessage.java, cdap-proto/src/main/java/co/cask/cdap/proto/audit/AuditPayload.java, cdap-proto/src/main/java/co/cask/cdap/proto/audit/MessageType.java, cdap-proto/src/main/java/co/cask/cdap/proto/audit/payload/access/AccessPayload.java, cdap-proto/src/main/java/co/cask/cdap/proto/audit/payload/access/AccessType.java, cdap-proto/src/main/java/co/cask/cdap/proto/audit/payload/metadata/MetadataPayload.java, cdap-proto/src/main/java/co/cask/cdap/proto/audit/payload/metadata/MetadataRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/codec/AuditMessageTypeAdapter.java, cdap-proto/src/test/java/co/cask/cdap/proto/audit/AuditMessageTest.java
JIRA - https://issues.cask.co/browse/CDAP-5108
Build - http://builds.cask.co/browse/CDAP-DUT3624-1
=> CDAP-5108 Classes to define audit message

cdap-docs/admin-manual/build.sh
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB136-1)
Fix for broken build https://builds.cask.co/browse/CDAP-DRBDE3-80/log
=> Updates hash. Verified file changes in guarded file.

cdap-app-fabric/pom.xml, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml, cdap-examples/LogAnalysis/pom.xml, cdap-examples/SparkKMeans/pom.xml, cdap-examples/WikipediaPipeline/pom.xml, cdap-examples/deploy_pom.xml, pom.xml
- It is needed in order to generate scaladoc jar.
=> Update to use the latest maven scala plugin

cdap-docs/reference-manual/source/cli-api.rst
I ran:
```
mvn clean package -pl cdap-docs-gen -am -DskipTests
java -cp cdap-docs-gen/target/classes:cdap-cli/target/cdap-cli-3.3.2.jar co.cask.cdap.docgen.cli.GenerateCLIDocsTable
```
and copied the output to `cdap-docs/reference-manual/source/cli-api.rst`
Quick Build: http://builds.cask.co/browse/CDAP-DOB137-1
=> Update CLI docs

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceClassLoader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceTaskContextProvider.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/StreamDecoderDetectionTest.java
- We don’t need the guice Injector.
- We only need four system services, which all of them are singleton
=> (CDAP-5117) Refactor MR TaskContextProvider.

cdap-docs/admin-manual/build.sh
[Quick Build](http://builds.cask.co/browse/CDAP-DOB141-1)
=> Fix md5 hash of cdap-default.xml

cdap-api-spark/pom.xml, cdap-api-spark/src/main/java/co/cask/cdap/api/spark/AbstractSparkHttpServiceHandler.java, cdap-api-spark/src/main/java/co/cask/cdap/api/spark/JavaSparkExecutionContext.java, cdap-api-spark/src/main/java/co/cask/cdap/api/spark/JavaSparkMain.java, cdap-api-spark/src/main/java/co/cask/cdap/api/spark/SparkHttpServiceContext.java, cdap-api-spark/src/main/scala/co/cask/cdap/api/spark/SparkExecutionContext.scala, cdap-api-spark/src/main/scala/co/cask/cdap/api/spark/SparkMain.scala, pom.xml
- A new API module for Spark programs to depend on
- Includes both native Scala and Java API
=> (CDAP-5084) Add the new cdap-api-spark module

cdap-ui/app/features/tracker/controllers/lineage-ctrl.js, cdap-ui/app/features/tracker/directives/lineage/flux/lineage-actions.js, cdap-ui/app/features/tracker/directives/lineage/flux/lineage-store.js, cdap-ui/app/features/tracker/directives/lineage/lineage.html, cdap-ui/app/features/tracker/directives/lineage/lineage.js, cdap-ui/app/features/tracker/directives/lineage/lineage.less, cdap-ui/app/features/tracker/routes.js, cdap-ui/app/features/tracker/services/my-lineage-service.js, cdap-ui/app/features/tracker/templates/lineage.html, cdap-ui/app/features/tracker/templates/metadata.html, cdap-ui/app/features/tracker/templates/results.html
- Add query parameters for lineage
- Remove schema from system properties
- Ability to click open an element in new tab
- Query found in -> Search term found in
- Lineage multiple methods (duplicate or not) as query params to lineage
=> [CDAP-5101] [CDAP-5189] [CDAP-5188] [CDAP-5148] Tracker Iterations 1

cdap-ui/package.json
Fixing broken autobuild for release/3.0 branch
=> update main bower files version to be specific

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminService.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
Build - http://builds.cask.co/browse/CDAP-DUT3664-1
Integration test - http://builds.cask.co/browse/CDAP-ITCC-145
=> CDAP-5108 Refactor dataset admin service

cdap-ui/app/directives/explore/explore.js, cdap-ui/app/directives/explore/explore.less
*  Adds CSS fix to prevent long explore queries from squishing the Action column buttons
=> adds layout fix to account for long epxlore queries

cdap-app-fabric/src/test/java/co/cask/cdap/internal/audit/AuditPublishTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/StreamAdminTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/hbase/HBaseFileStreamAdminTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/leveldb/LevelDBFileStreamAdminTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/AuditModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/AuditPublishers.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/InMemoryAuditPublisher.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
Build - http://builds.cask.co/browse/CDAP-DUT3669-4
=> CDAP-5108 Publish audit information from stream admin

cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/AuditPublishers.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
Build - http://builds.cask.co/browse/CDAP-DUT3685-2
=> CDAP-5108 Publish access audit only when audit publisher is not null

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreTest.java
Build - http://builds.cask.co/browse/CDAP-DUT3686-5
=> CDAP-5108 Metadata audit publish tests

cdap-app-fabric/src/test/java/co/cask/cdap/internal/audit/AuditPublishTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/StreamAdminTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreTest.java
Build - http://builds.cask.co/browse/CDAP-DUT3680-10
TODO: https://issues.cask.co/browse/CDAP-5221
=> CDAP-5108 Publishing Dataset audit information

cdap-ui/app/features/hydrator/services/hydrator-service.js, cdap-ui/app/features/tracker/controllers/entity-ctrl.js, cdap-ui/app/features/tracker/directives/jump/jump.html, cdap-ui/app/features/tracker/directives/jump/jump.js, cdap-ui/app/features/tracker/directives/jump/jump.less, cdap-ui/app/features/tracker/services/my-jump-factory.js, cdap-ui/app/features/tracker/services/my-tracker-api.js, cdap-ui/app/features/tracker/templates/entity.html, cdap-ui/app/features/tracker/templates/results.html, cdap-ui/app/features/tracker/tracker.less
Merge **after** #5269 
Part 1 of Jump Button implementation:
- Stream batch source
- Stream real-time sink
- Stream view in CDAP
- Dataset view in CDAP
- Table, KVTable batch source
- Table, KVTable batch sink
- hide for Stream Views
=> [CDAP-5033] Feature/ui tracker jump button

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorkflow.java, cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowAppWithLocalDatasets.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteWorkflowLocalDatasetsCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/GetWorkflowLocalDatasetsCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/WorkflowCommandSet.java, cdap-client-tests/src/test/java/co/cask/cdap/client/WorkflowClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/WorkflowClient.java
JIRA: https://issues.cask.co/browse/CDAP-5119
=> CDAP-5119 Added http endpoints for listing and deleting the local datasets in the Workflow.

cdap-docs/developers-manual/source/building-blocks/datasets/index.rst
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB151-1)
=> Fix broken link.

cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.html, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.less, cdap-ui/app/features/hydrator/services/create/stores/config-store.js, cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-nonruns-store.js, cdap-ui/app/features/hydrator/services/hydrator-service.js
- Fixes output schema for Streamsource to have `ts` & `headers` while cloning a pipeline.
- Fixes pipeline export to show input & output schema in export popup
=> [CDAP-5028] - Fix/ui streamsource outputschema clone

cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/payload/builder/MetadataPayloadBuilder.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreTest.java, cdap-docs/reference-manual/source/http-restful-api/metadata.rst, cdap-proto/src/main/java/co/cask/cdap/proto/audit/payload/metadata/MetadataPayload.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/Metadata.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataChangeRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataScope.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchResultRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchTargetType.java, cdap-proto/src/test/java/co/cask/cdap/proto/audit/AuditMessageTest.java
JIRA - https://issues.cask.co/browse/CDAP-4274
Build - http://builds.cask.co/browse/CDAP-DUT3687-11
Integration tests - http://builds.cask.co/browse/CDAP-ITCC9-9
=> CDAP-4274 Add metadata to search results

cdap-ui/app/directives/error/error-popover.html, cdap-ui/app/directives/error/error.less, cdap-ui/app/directives/my-global-navbar/my-global-navbar.html, cdap-ui/app/directives/my-global-navbar/my-global-navbar.js, cdap-ui/app/directives/my-global-navbar/my-global-navbar.less
*  Fixes border issue affecting error popover arrow
*  Fixes padding/alignment of badge notification numbers within error popover
=> fixes minor styling issues affecting error popover in global navbar

cdap-docs/reference-manual/source/http-restful-api/metadata.rst
Doc build - http://builds.cask.co/browse/CDAP-DOB153-3
Changes rendered - http://builds.cask.co/artifact/CDAP-DOB153/shared/build-3/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/metadata.html#http-restful-api-metadata-searching
=> Update metadata doc with new search result format

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/Aggregator.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchAggregator.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchAggregatorContext.java
Adding the aggregator apis for the new plugin type.
All aggregator apis are marked as beta and are subject to change.
=> CDAP-5146 add aggregator apis

cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AuthorizationHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/InMemoryAuthorizer.java, cdap-cli-tests/pom.xml, cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/AddRoleToPrincipalCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/CreateRoleCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/DropRoleCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/GrantActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/ListPrivilegesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/ListRolesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RemoveRoleFromPrincipalCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeActionCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeActionForPrincipalCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeEntityCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/SecurityCommands.java, cdap-standalone/pom.xml, cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java
- Add CLI commands for Authorization Role Management for Role Based Control System
- Added CLI unit test for all Authorization commands
Issue: https://issues.cask.co/browse/CDAP-5155
Build: http://builds.cask.co/browse/CDAP-DUT3720-3
=> CDAP-5155: Role Management CLI Support

cdap-api/src/main/java/co/cask/cdap/api/data/stream/Stream.java, cdap-api/src/main/java/co/cask/cdap/api/data/stream/StreamSpecification.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/CreateStreamsStage.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/StreamCreator.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStage.java, cdap-app-fabric/src/test/java/co/cask/cdap/AllProgramsApp.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AppSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ArtifactSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ProgramSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/StreamSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/SystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ViewSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java, cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java
Build - http://builds.cask.co/browse/CDAP-DUT3734-6
Integration test - http://builds.cask.co/browse/CDAP-ITCC-161
TODO: 
* Update existing apps to add description - https://issues.cask.co/browse/CDAP-5329
* Allow setting description through REST API - https://issues.cask.co/browse/CDAP-5330
=> CDAP-4670 Add stream description and create time metadata

cdap-api/src/main/java/co/cask/cdap/api/workflow/AbstractWorkflow.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/Workflow.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-client-tests/src/main/java/co/cask/cdap/client/app/FakeWorkflow.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowAppWithLocalDatasets.java
JIRA: https://issues.cask.co/browse/CDAP-4075
=> CDAP-4075 Added checks for handling pre 3.4 Workflow applications.

cdap-common/src/main/java/co/cask/cdap/common/conf/PluginClassDeserializer.java
check if endpoints field exists before getting the JSON array for endpoints.
introduced by this merge: https://github.com/caskdata/cdap/pull/5264
=> bugfix : endpoints is not an required field in artifacts

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java, cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java
JIRA - https://issues.cask.co/browse/CDAP-5241
Build - http://builds.cask.co/browse/CDAP-DUT3740-10
Integration test - http://builds.cask.co/browse/CDAP-ITCC-168
=> CDAP-5241 Moving dataset system metadata write to service

cdap-docs/developers-manual/source/building-blocks/datasets/index.rst
=> [CDAP-5059] improve documentation for discardDataset()

cdap-ui/app/directives/group-side-panel/group-side-panel-ctrl.js, cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/directives/group-side-panel/group-side-panel.less, cdap-ui/app/features/hydratorplusplus/controllers/create/canvas-ctrl.js, cdap-ui/app/features/hydratorplusplus/controllers/create/create-studio-ctrl.js, cdap-ui/app/features/hydratorplusplus/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/routes.js, cdap-ui/app/features/hydratorplusplus/services/create/stores/config-store.js, cdap-ui/app/features/hydratorplusplus/templates/create/popovers/canvas-overwrite-confirmation.html, cdap-ui/app/services/constants.js
- Fixes spacing in error messages in the console
- Adds the ability to show a confirmation whenever the user has made some changes in the canvas and switching to templates, importing a config or changing the artifact.
- Fixes left side panel to have one panel open all the time (removes intermediate state of having all open at the same time)
Bamboo build: http://builds.cask.co/browse/CDAP-DRC3509-3
=> Feature/ui hydrator++ bugfixes

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
Build is green here - http://builds.cask.co/browse/CDAP-DUT3789-1
=> Wait in test case till the runs are recorded.

cdap-ui/app/features/tracker/controllers/container-ctrl.js, cdap-ui/app/features/tracker/controllers/entity-ctrl.js, cdap-ui/app/features/tracker/directives/lineage/lineage.html, cdap-ui/app/features/tracker/directives/lineage/lineage.js, cdap-ui/app/features/tracker/directives/lineage/lineage.less, cdap-ui/app/features/tracker/routes.js, cdap-ui/app/features/tracker/services/my-lineage-service.js, cdap-ui/app/features/tracker/templates/audit.html, cdap-ui/app/features/tracker/templates/container.html, cdap-ui/app/features/tracker/templates/entity.html, cdap-ui/app/features/tracker/templates/results.html, cdap-ui/app/features/tracker/tracker.less
- Centering and scaling lineage diagram
- Lineage diagram improvements: continuous anchors, unknown access type to be write
- Access Type in Audit Log to come from payload
- Back to search results button
- Add search suggestion
=> [CDAP-5071] [CDAP-5381] [CDAP-5379] [CDAP-5286] [CDAP-5401] Feature/ui tracker improvements part 2

cdap-app-fabric/src/main/java/org/apache/hadoop/fs/ftp/FTPInputStream.java
This PR is required to add FTP Batch Source in hydrator-plugins.
JIRA : https://issues.cask.co/browse/CDAP-5191
Build : http://builds.cask.co/browse/CDAP-DUT3760
=> CDAP-5191 Adding modified FTPInputStream that doesn't throw an exception for trivial cases

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json
Suggested here (for Vagrant, but same end result)...
http://superuser.com/questions/850357/how-to-fix-extremely-slow-virtualbox-network-download-speed
=> Use virtio Paravirtualized Linux driver

cdap-api/src/main/java/co/cask/cdap/api/dataset/DatasetProperties.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/DatasetSpecification.java, cdap-app-fabric/src/test/java/co/cask/cdap/AllProgramsApp.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java, cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateDatasetInstanceCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/ListDatasetInstancesCommand.java, cdap-client-tests/src/test/java/co/cask/cdap/client/DatasetClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/DatasetClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetType.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/ConversionHelpers.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetOpExecutor.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/InMemoryDatasetOpExecutor.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/InternalDatasetCreationParams.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/RemoteDatasetOpExecutor.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/TestModule2.java, cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java, cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java, cdap-proto/src/main/java/co/cask/cdap/proto/DatasetInstanceConfiguration.java, cdap-proto/src/main/java/co/cask/cdap/proto/DatasetSpecificationSummary.java
Build - http://builds.cask.co/browse/CDAP-DUT3777-8
Integration test - http://builds.cask.co/browse/CDAP-ITCC-174
TODO: Rest API documentation (https://issues.cask.co/browse/CDAP-5329)
=> CDAP-4670 Add description and create time to dataset metadata

cdap-ui/app/features/hydrator/controllers/create/partials/nodeconfig-ctrl.js, cdap-ui/app/features/hydrator/services/create/stores/config-store.js, cdap-ui/app/features/hydratorplusplus/services/create/stores/config-store.js
-Fixes schema propagation to stop on a node with implicit schema.
Bamboo build: http://builds.cask.co/browse/CDAP-DRC3512-2
=> Prevents propagating schema beyond a node that has an implicit outputschema

cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/directives/plugin-templates/plugin-templates-ctrl.js, cdap-ui/app/features/hydrator/bottompanel.less, cdap-ui/app/features/hydrator/controllers/create/bottompanel-ctrl.js, cdap-ui/app/features/hydrator/leftpanel.less, cdap-ui/app/features/hydratorplusplus/adapters.less, cdap-ui/app/features/hydratorplusplus/controllers/create/bottompanel-ctrl.js, cdap-ui/app/features/hydratorplusplus/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/services/create/actions/plugin-actions.js, cdap-ui/app/features/hydratorplusplus/services/create/stores/left-panel-store.js, cdap-ui/app/features/hydratorplusplus/services/hydrator-plus-ordering-factory.js, cdap-ui/app/features/hydratorplusplus/templates/create/leftpanel.html, cdap-ui/app/features/hydratorplusplus/templates/create/popovers/leftpanel-plugin-popover.html, cdap-ui/app/features/hydratorplusplus/toppanel.less
- Modifies left panel + top panel layout in hydrator++ to mimic close to mock
- Fixes bottom panel behavior
- Modifies styling for popover in left panel based on mocks
Bamboo build: http://builds.cask.co/browse/CDAP-DRC3528-4
=> Modifies styling left panel in Hydrator++ 

cdap-ui/app/directives/widget-container/widget-function-dropdown-with-alias/widget-function-dropdown-with-alias.html, cdap-ui/app/directives/widget-container/widget-function-dropdown-with-alias/widget-function-dropdown-with-alias.less, cdap-ui/app/features/hydratorplusplus/services/detail/stores/pipeline-detail-runs-store.js, cdap-ui/app/features/hydratorplusplus/toppanel.less
This PR is branched off from [PR#5396](https://github.com/caskdata/cdap/pull/5396).
- Fixes the function dropdown in GroupByAggregate plugin to have 'as' label + placeholders for appropriate input elements.
- Fixes pipeline name in detailed view.
- Fixes logs to be available in detailed view.
=> Feature/ui hydrator++ bugfix

cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/AuditModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java, cdap-standalone/pom.xml, cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
JIRA - https://issues.cask.co/browse/CDAP-5437
Build - http://builds.cask.co/browse/CDAP-DUT3816-4
=> CDAP-5437 Starting Zookeeper and Kafka clients in standalone mode when audit publishing is enabled

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageCollapserTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java, cdap-client/src/main/java/co/cask/cdap/client/LineageClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/CollapsedRelation.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageCollapser.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageSerializer.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/CollapseType.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/RelationRecord.java
JIRA - https://issues.cask.co/browse/CDAP-3623
Build - http://builds.cask.co/browse/CDAP-DUT3830-1
=> CDAP-3623 Collapse lineage relations

cdap-ui/app/directives/log-viewer/log-viewer.js, cdap-ui/app/features/hydrator/controllers/list-ctrl.js
- Fix log viewer to not escape html
- Fix hydrator list view status for DataPipeline
=> [CDAP-5395] Feature/ui logs quote fix

cdap-ui/app/features/tracker/services/my-lineage-service.js, cdap-ui/app/features/tracker/services/my-tracker-api.js
=> update lineage parser to account for backend changes

cdap-ui/app/directives/dag-plus/my-dag-ctrl.js, cdap-ui/app/directives/dag-plus/my-dag.html, cdap-ui/app/directives/plugin-templates/plugin-templates-ctrl.js, cdap-ui/app/features/hydratorplusplus/routes.js, cdap-ui/app/features/hydratorplusplus/templates/partial/node-config.html
- Fixes dragging/dropping of pipeline DAGs in app detailed view.
- Fixes creating templates for `batchaggregator` plugin types.
- Modifies `ETLDataPipeline` as the default artifact when the user creates pipeline using hydrator++
=> Feature/ui hydrator++ bug fix 2

cdap-ui/app/features/hydratorplusplus/bottompanel.less, cdap-ui/app/features/hydratorplusplus/controllers/detail/bottom-panel-ctrl.js, cdap-ui/app/features/hydratorplusplus/templates/detail/tabs/configuration.html
- Fixes minimize/maximize panel in detailed view.
- Fixes bottom panel configuration tab styling
=> Feature/ui hydrator++ bottom panel

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
JIRA: https://issues.cask.co/browse/CDAP-5460
=> CDAP-5460 Fix to update Spark program's status when it is running as a part of Workflow.

cdap-ui/app/features/hydratorplusplus/services/detail/actions/pipeline-detail-metrics-actions.js
Fixes displaying workflow metrics in pipelines based on the new config json.
=> Fixes displaying metrics in UI based on the new config json in hydrator++

cdap-data-fabric/src/test/java/co/cask/cdap/kafka/KafkaTester.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java
Changing waitForKafkaStartup to wait until Kafka messages are published and Adding instrumentation to print kafka messages on checkpoint test assert failure.
Issue: https://issues.cask.co/browse/CDAP-4070
Build: http://builds.cask.co/browse/CDAP-DUT3823-6
=> Changing waitForKafkaStartup in KafkaTester to wait until kafka can publish messages

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
Build - http://builds.cask.co/browse/CDAP-DUT3843-1
=> Restrict metadata fuzzy scan filter using start and stop keys

cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java
Disabling LogSaver tests in LogSaverPluginTest.
Issue: https://issues.cask.co/browse/CDAP-4070
Build: http://builds.cask.co/browse/CDAP-DUT3845-2
=> LogSaverPluginTest changes for LogSaver flaky tests

cdap-ui/app/directives/dag-plus/services/stores/nodes-store.js, cdap-ui/app/features/hydratorplusplus/templates/detail/tabs/metrics.html
- Adds node type in metrics table in pipeline detailed view.
=> Fix node type in metrics table

cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/CustomActionExecutor.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowStatusTestApp.java
JIRA - https://issues.cask.co/browse/CDAP-4075
=> Implementation to get status of Workflow from WorkflowContext.

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithMapReduceUsingAvroDynamicPartitioner.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriterTest.java
JIRA - https://issues.cask.co/browse/CDAP-5322
Build - http://builds.cask.co/browse/CDAP-DUT3851-3
=> CDAP-5322 Resolve schema for existing filesets using a heuristic

cdap-common/src/main/java/co/cask/cdap/common/io/Locations.java, cdap-common/src/main/java/org/apache/twill/filesystem/FileContextLocation.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/read/AvroFileReader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/write/AvroFileWriter.java
Same changes as [this](https://github.com/caskdata/cdap/pull/5334) with bug fix.
Issue: https://issues.cask.co/browse/CDAP-5029
Build: http://builds.cask.co/browse/CDAP-DUT3869-7
=> CDAP-5029Changes to show logs on UI on mapreduce failure

cdap-ui/app/directives/group-side-panel/group-side-panel-ctrl.js, cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/directives/group-side-panel/group-side-panel.js, cdap-ui/app/directives/group-side-panel/group-side-panel.less, cdap-ui/app/features/hydrator/leftpanel.less, cdap-ui/app/features/hydratorplusplus/adapters.less, cdap-ui/app/features/hydratorplusplus/bottompanel.less, cdap-ui/app/features/hydratorplusplus/controllers/create/create-studio-ctrl.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/templates/create/leftpanel.html, cdap-ui/app/features/hydratorplusplus/templates/create/studio.html, cdap-ui/app/features/hydratorplusplus/toppanel.less
- Modifies leftpanel based on mocks
- Fixes expand/collapse behavior in left panel
=> Feature/ui hydrator++ leftpanel toggle

cdap-docs/examples-manual/build.sh, cdap-examples/DataCleansing/src/main/java/co/cask/cdap/examples/datacleansing/DataCleansing.java
A very minor change, but it improves the presentation of this example in the documentation.
=> Fix comment so that it wraps better for the documentation.

cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/StreamSystemMetadataWriter.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriterTest.java
Delete non-relevant system metadata on update, fix bug in metadata delete and rename system metadata keys
Build - http://builds.cask.co/browse/CDAP-DUT3902-7
=> CDAP-5561 CDAP-5436 CDAP-5332 Misc system metadata fixes

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
JIRA - https://issues.cask.co/browse/CDAP-5513
Build - http://builds.cask.co/browse/CDAP-DUT3905-2
=> CDAP-5513 Delete old indexes for a metadata key on update

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/BufferingTable.java
- include table and column name in warning message for empty values
- throttle that message to prevent flooding the logs
=> [CDAP-5559] better logging when an empty value is written

cdap-examples/deploy_pom.xml, cdap-examples/pom.xml
=> CDAP-5592 exclude old version of asm

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStage.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ProgramSystemMetadataWriter.java, cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java
Jira: [CDAP-4766](https://issues.cask.co/browse/CDAP-4766)
Build: http://builds.cask.co/browse/CDAP-DUT3911-3
=> (CDAP-4766) Skip fork node names in system tags for workflows

cdap-ui/app/directives/group-side-panel/group-side-panel-ctrl.js, cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/directives/group-side-panel/group-side-panel.less, cdap-ui/app/features/hydratorplusplus/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/hydratorplusplus/controllers/create/popovers/load-artifact-ctrl.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/templates/create/leftpanel.html, cdap-ui/app/features/hydratorplusplus/templates/create/popovers/load-artifact.html, cdap-ui/app/features/hydratorplusplus/templates/create/toppanel.html, cdap-ui/app/services/app-uploader.js, cdap-ui/app/services/constants.js, cdap-ui/app/services/file-uploader.js, cdap-ui/app/services/hydrator/my-pipeline-api.js, cdap-ui/app/services/streams/my-streams-service.js
- Adds '+' button on the left panel
- Fixes issues in styling on left panel
- Fixes `myFileUploader` service to accept custom headers to be sent as part of the request
- Fixes all references of `myFileUploader` to pass in 'headers' in case if it needs to. 
- Renames `cdap-data-pipeline` to `cdap-etl-data-pipeline` as part backend name change.
=> Adds 'Add Plugin' feature in UI + Renames cdap-data-pipeline

cdap-ui/app/directives/flow-graph/workflow.js, cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/services/workflows/my-workflow-api.js
~~TODO: need to test with an App with Custom Action~~
=> [CDAP-4060] modify workflow status to poll from single API

cdap-ui/app/directives/my-global-navbar/my-global-navbar.html, cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/hydrator/templates/list.html, cdap-ui/app/features/overview/overview.html, cdap-ui/app/features/overview/templates/data-apps.html, cdap-ui/app/features/tracker/services/my-jump-factory.js
- Removes all links to old hydrator UI and replaces it with hydrator++
- This PR does not remove the hydrator feature but just the reference. Removing the hydrator feature will come in a separate PR.
=> Removes reference of old hydrator and replaces it with hydrator++ in UI

cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema-modal.html, cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema.html, cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema.js, cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema.less, cdap-ui/app/directives/plugin-functions/plugin-functions-factory.js, cdap-ui/app/directives/plugin-functions/plugin-functions.js, cdap-ui/app/features/hydratorplusplus/hydrator-modal.less, cdap-ui/app/features/hydratorplusplus/templates/create/popovers/plugin-edit-properties-template.html, cdap-ui/app/services/hydrator/my-pipeline-api.js
relates to: https://github.com/caskdata/hydrator-plugins/pull/204
=> [CDAP-4970] Feature/ui database function

cdap-ui/app/features/hydratorplusplus/controllers/create/leftpanel-ctrl.js, cdap-ui/app/features/hydratorplusplus/services/non-store-pipeline-error-factory.js
- Adds back validation during pipeline import.
- Removes validations done for <3.3 pipeline configs
- Modifies validations based on backend api change.
=> [CDAP-5575] Adds validation to import pipeline in hydrator++

cdap-app-fabric-tests/src/test/java/co/cask/cdap/runtime/WorkflowTest.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkClassLoader.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRunner.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkTransactionService.java, cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala, cdap-spark-core/src/test/java/co/cask/cdap/app/runtime/spark/SparkTransactionServiceTest.java
- Use the hostname as determined from the running YARN container to be 
the hostname of the SparkTransactionService.
=> Fix Spark in distributed mode

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
JIRA : https://issues.cask.co/browse/CDAP-5131
=> CDAP-5131 bugfix for filtering plugin class by type in artifactStore

cdap-app-fabric/src/main/java/co/cask/cdap/security/TokenSecureStoreUpdater.java
Same as PR https://github.com/caskdata/cdap/pull/5540, but against release/3.4. Only difference is that we moved FileContextLocationFactory to Twill, so it is now in the org.apache.twill package.
=> [CDAP-5350] Workaround to obtain KMS delegation token in encryption-enabled clusters

cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkClassLoader.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtils.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
- We should change both the context ClassLoader and the
ClassLoader inside hConf to the SparkClassLoader when
calling user methods.
=> Set the Context ClassLoader properly in all cases

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceClassLoader.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/WorkflowProgramLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
JIRA: https://issues.cask.co/browse/CDAP-4644
Spark changes still need to be implemented.
=> CDAP-4644 Implementation to add MapReduce logs in the Workflow.

cdap-proto/src/main/java/co/cask/cdap/proto/audit/AuditMessage.java, cdap-proto/src/test/java/co/cask/cdap/proto/audit/AuditMessageTest.java
https://issues.cask.co/browse/CDAP-5609
build: http://builds.cask.co/browse/CDAP-DUT3952-1
=> Cdap 5609 add version audit log

cdap-ui/app/features/hydratorplusplus/templates/create/leftpanel.html
*  Renames "Plugins Templates" to "Template Gallery"
=> renames plugin templates label

cdap-ui/app/features/hydratorplusplus/adapters.less
*  Reduces top offset of dag control box to match the old offset amount
=> reduces top offset of dag control box

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/PluginService.java
addressing a missed comment : https://github.com/caskdata/cdap/pull/5528#discussion_r59825668
=> set size and weigher for plugin service cache

cdap-ui/app/directives/breadcrumbs/breadcrumbs.html, cdap-ui/app/directives/breadcrumbs/breadcrumbs.less, cdap-ui/app/features/dashboard/routes.js, cdap-ui/app/features/dashboard/style.less, cdap-ui/app/features/dashboard/templates/dashboard.html
*  Aligns breadcrumbs with global navbar links
*  Removes breadcrumbs from Operations
*  Adds new styling for single breadcrumb (used in Management home)
*  Adds left box shadow to single breadcrumb scenario
Reduced margin Dashboard state:
=> [CDAP-5373] changes alignment and layout of breadcrumbs

cdap-ui/app/features/hydratorplusplus/leftpanel.less
*  Adds box shadow to left panel plugins
*  Adds correct background color to left panel body and item headings
*  Increases bottom margin of plugins by 2px
=> [CDAP-5641] changes some background-color and box-shadow properties

cdap-docs/developers-manual/build.sh, cdap-docs/developers-manual/source/building-blocks/mapreduce-programs.rst, cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/purchase.rst
Fix for changed file: a line was removed, so reduce line counts by one, and update the MD5 hash.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB173-1)
=> Fix Broken Doc Build, and updates the MD5 hashes.

cdap-ui/app/features/tracker/controllers/integrations-ctrl.js, cdap-ui/app/features/tracker/templates/integrations.html, cdap-ui/app/features/tracker/templates/partial/integrations-setup-popover.html, cdap-ui/app/features/tracker/tracker.less
- Add optional settings to cloudera navigator config
- Add ability to edit configuration
=> [CDAP-5338] [CDAP-5294] Feature/ui tracker navigator config

cdap-ui/Gulpfile.js, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.html, cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js, cdap-ui/app/features/hydratorplusplus/controllers/create/partials/nodeconfig-ctrl.js, cdap-ui/app/features/hydratorplusplus/templates/create/popovers/plugin-edit-input-schema.html, cdap-ui/app/main.js, cdap-ui/bower.json
- Adds infinite scrolling directive to be used in large schemas in input/output of plugins.
- Lazy loads initial 15 and on subsequent scroll loads every 10 as users scrolls till the end.
=> [CDAP-5634] Adds performance improvements for importschema in hydrator++

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceWithPartitionedTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java, cdap-examples/LogAnalysis/src/main/java/co/cask/cdap/examples/loganalysis/LogAnalysisApp.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTestRun.java
=> [CDAP 5643] Fix test cases that parse dates without a locale

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json
=> Use latest IntelliJ version (backport from 3.4)

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
JIRA: https://issues.cask.co/browse/CDAP-5553
=> CDAP-5553 Upgrade Workflow run records to separate out Workflow token and node states.

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorkflow.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/GetWorkflowStateCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/WorkflowCommandSet.java, cdap-client-tests/src/test/java/co/cask/cdap/client/WorkflowClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/WorkflowClient.java, cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteWorkflowManager.java, cdap-test/src/main/java/co/cask/cdap/test/WorkflowManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultWorkflowManager.java
JIRA: https://issues.cask.co/browse/CDAP-5652
Sample command output:
```java
cdap (http://localhost:10000/namespace:default)> get workflow state PurchaseHistory.PurchaseHistoryWorkflow b48355a2-0599-11e6-8ace-da6a50dd7318
+============================================================================================+
| node id                | node status | runid                                | failurecause |
+============================================================================================+
| PurchaseHistoryBuilder | COMPLETED   | b4b1b8a3-0599-11e6-9e55-da6a50dd7318 |              |
+============================================================================================+
```
=> CDAP-5652 CLI command to get Workflow node states.

cdap-distributions/bin/build_parcel.sh
=> add latest hbase modules to parcel build script

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/KeyHelper.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Jira: [CDAP-5513](https://issues.cask.co/browse/CDAP-5513)
Build: http://builds.cask.co/browse/CDAP-DUT3958
=> (CDAP-5513) Rebuild metadata indexes during upgrade

cdap-kafka/pom.xml, cdap-standalone/pom.xml, cdap-standalone/src/main/java/co/cask/cdap/ExternalJavaProcessExecutor.java, cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java, cdap-standalone/src/main/resources/cdap-site.xml
JIRAs : https://issues.cask.co/browse/CDAP-5183
https://issues.cask.co/browse/CDAP-5475
Build : http://builds.cask.co/browse/CDAP-DUT3921
=> CDAP-5183 Start zookeeper and kafka processes in Standalone if audit is enabled

cdap-docs/developers-manual/build.sh, cdap-docs/developers-manual/source/building-blocks/spark-programs.rst, cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/count-random.rst, cdap-docs/examples-manual/source/examples/hello-world.rst, cdap-docs/examples-manual/source/examples/log-analysis.rst, cdap-docs/examples-manual/source/examples/purchase.rst, cdap-docs/examples-manual/source/examples/spark-k-means.rst, cdap-docs/examples-manual/source/examples/spark-page-rank.rst, cdap-docs/examples-manual/source/examples/user-profiles.rst, cdap-docs/examples-manual/source/examples/web-analytics.rst, cdap-docs/examples-manual/source/examples/wikipedia-data-pipeline.rst, cdap-docs/examples-manual/source/examples/word-count.rst, cdap-docs/reference-manual/source/http-restful-api/dataset.rst, cdap-examples/CountRandom/src/main/java/co/cask/cdap/examples/countrandom/CountRandom.java, cdap-examples/DataCleansing/src/main/java/co/cask/cdap/examples/datacleansing/DataCleansing.java, cdap-examples/FileSetExample/src/main/java/co/cask/cdap/examples/fileset/FileSetExample.java, cdap-examples/HelloWorld/src/main/java/co/cask/cdap/examples/helloworld/HelloWorld.java, cdap-examples/LogAnalysis/src/main/java/co/cask/cdap/examples/loganalysis/LogAnalysisApp.java, cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseApp.java, cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseHistoryStore.java, cdap-examples/SparkKMeans/src/main/java/co/cask/cdap/examples/sparkkmeans/SparkKMeansApp.java, cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java, cdap-examples/SportResults/src/main/java/co/cask/cdap/examples/sportresults/SportResults.java, cdap-examples/StreamConversion/src/main/java/co/cask/cdap/examples/streamconversion/StreamConversionApp.java, cdap-examples/UserProfiles/src/main/java/co/cask/cdap/examples/profiles/UserProfiles.java, cdap-examples/WebAnalytics/src/main/java/co/cask/cdap/examples/webanalytics/WebAnalytics.java, cdap-examples/WikipediaPipeline/src/main/java/co/cask/cdap/examples/wikipedia/WikipediaPipelineApp.java, cdap-examples/WordCount/src/main/java/co/cask/cdap/examples/wordcount/WordCount.java
JIRA : https://issues.cask.co/browse/CDAP-5329
Passes Quick Build 3 : http://builds.cask.co/browse/CDAP-DOB182-3
=> CDAP-5329 Dataset description docs

cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/src/main/java/HelloWorld.java, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/main/java/SparkPageRankApp.java, cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/main/java/SparkPageRankProgram.java, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/main/scala/SparkKMeansApp.java, cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/main/scala/SparkKMeansProgram.scala, cdap-examples/SparkKMeans/src/main/scala/co/cask/cdap/examples/sparkkmeans/SparkKMeansProgram.scala, cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankProgram.java
Simply copy over the example classes to the archetypes which are based on these apps.
https://issues.cask.co/browse/CDAP-5532
http://builds.cask.co/browse/CDAP-DUT4001
=> Update archetypes based upon changes to examples they're based off of.

cdap-ui/app/features/hydratorplusplus/adapters.less
*  Adjusts top offset of DAG controls in pipeline detail view
=> fixes position of dag controls in detail view

cdap-ui/app/features/hydratorplusplus/templates/create/toppanel.html, cdap-ui/app/features/hydratorplusplus/toppanel.less
*  Adjusts position of "edit" icon when hovering over metadata container
=> changes position of edit icon on hover

cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
=> Fixes fitToScreen on editing/cloning pipelines in hydrator++

cdap-ui/app/directives/group-side-panel/group-side-panel-ctrl.js, cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/directives/group-side-panel/group-side-panel.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/routes.js, cdap-ui/app/features/hydratorplusplus/templates/create/leftpanel.html, cdap-ui/app/services/constants.js
- CDAP-5662 : If no system artifacts the UI should show appropriate error messages.
- Fixes side panel to show no artifacts/plugins found message when no artifacts or plugins are present.
=> [CDAP-5662] -Hydrator++ bug fix 5

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDS.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
JIRA: https://issues.cask.co/browse/CDAP-5120
=> CDAP-5120 Hide local datasets from list call.

cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema.js, cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema-modal.html, cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.html, cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.js, cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.less, cdap-ui/app/directives/plugin-functions/plugin-functions-factory.js, cdap-ui/app/directives/plugin-functions/plugin-functions.js, cdap-ui/app/services/hydrator/my-pipeline-api.js
- Adds outputSchema widget to be used in `groupByAggregate` plugin
- Modifies `get-schema` widget to account for parameters passed from widget json (like method, plugin-method etc.,)
This PR depends on this to be merged [Hydrator-plugins PR #237](https://github.com/caskdata/hydrator-plugins/pull/237)
=> Add plugin method in GroupByAggregate plugin

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLWorkflowTestRun.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ExternalDatasets.java, cdap-proto/src/main/java/co/cask/cdap/proto/id/DatasetId.java, cdap-proto/src/main/java/co/cask/cdap/proto/id/EntityId.java, cdap-proto/src/test/java/co/cask/cdap/proto/id/EntityIdTest.java
JIRAs : 
https://issues.cask.co/browse/CDAP-5664 (resulting from the discussion on this PR : https://github.com/caskdata/hydrator-plugins/pull/235)
https://issues.cask.co/browse/CDAP-5728
Build : http://builds.cask.co/browse/CDAP-DUT4022
=> CDAP-5664 and CDAP-5728 : DatasetId correctness verification and removal of hydrator-ext prefix

cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
Copy of [Log Handler PR](https://github.com/caskdata/cdap/pull/5552).
Issue: https://issues.cask.co/browse/CDAP-5508
Build: http://builds.cask.co/browse/CDAP-DUT4026-4
=> Changes to LogHandler to fix /log endpoint

cdap-ui/app/features/hydratorplusplus/bottompanel.less, cdap-ui/app/features/hydratorplusplus/controllers/detail/bottom-panel-ctrl.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/services/create/stores/config-store.js, cdap-ui/app/features/hydratorplusplus/templates/detail/tabs/postactions-detail.html, cdap-ui/app/features/hydratorplusplus/templates/partial/postactions.html, cdap-ui/app/features/overview/templates/data-apps.html
*  Reduces top offset of maximized bottom panel so that it occupies viewport up to the global navbar
*  Fixes margins of left panel top section buttons so that they're aligned evenly when left panel is both expanded and collapsed
*  Removes Pipelines button from data/apps section of dev start
Maximized bottom panel: 
Left panel expanding and collapsing:
Even margins of top panel buttons when expanded:
Pipelines button removed:
=> fixes studio left panel height/positioning issues

cdap-docs/developers-manual/build.sh, cdap-docs/developers-manual/source/building-blocks/spark-programs.rst, cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/spark-page-rank.rst
Updating doc references and hashes based upon: https://github.com/caskdata/cdap/pull/5641
=> Update docs based upon pull #5641

cdap-ui/app/features/hydratorplusplus/controllers/detail/canvas-ctrl.js, cdap-ui/app/features/hydratorplusplus/services/create/stores/left-panel-store.js, cdap-ui/app/features/hydratorplusplus/services/hydrator-service.js
CDAP-5749 - Fixes occasional JS error happening while updating default version of plugins.
CDAP-5750 - Fixes schema icon in detailed view to show schema popup post publish.
=> Bug fix in Hydrator++ (JS error on clone + schema popup in detailed view)

cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoader.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtils.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java, cdap-spark-core/src/test/java/co/cask/cdap/app/runtime/spark/distributed/SparkExecutionServiceTest.java
- Thread leak can causes ClassLoader leak
- Also fixed some wrong constants
This PR Depends on #5633
=> (CDAP-5530) Fix thread leak from Spark Streaming

cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/README.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/docs/StringCase-transform.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/docs/TextFileSet-batchsink.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/docs/TextFileSet-batchsource.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/docs/WordCount-batchaggregator.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/docs/WordCount-sparkcompute.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/docs/WordCount-sparksink.md, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/StringCaseTransform.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/TextFileSetSink.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/TextFileSetSource.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/WordCount.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/WordCountAggregator.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/WordCountCompute.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/main/java/WordCountSink.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/src/test/java/PipelineTest.java, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/widgets/StringCase-transform.json, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/widgets/TextFileSet-batchsink.json, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/widgets/TextFileSet-batchsource.json, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/widgets/WordCount-batchaggregator.json, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/widgets/WordCount-sparkcompute.json, cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/widgets/WordCount-sparksink.json, cdap-app-templates/cdap-etl/cdap-etl-archetypes/pom.xml
Adding an archetype for batch plugins for the data pipeline app.
The archetype includes functioning batchsource, batchsink,
transform, batchaggregator, sparkcompute, and sparksink plugins,
as well as a unit test for each plugin.
=> CDAP-5720 add a data pipeline plugins archetype

cdap-docs/admin-manual/source/_includes/installation/configuration.txt
Fix for https://issues.cask.co/browse/CDAP-5776
=> CDAP-5776 Correct explore property.

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Tables.java
https://issues.cask.co/browse/CDAP-4956
=> CDAP-4956 Tables API docs - ttl fix

pom.xml
JIRA: https://issues.cask.co/browse/CDAP-5779
=> CDAP-5779 Upgrade tephra version to 0.7.1

cdap-common/src/main/resources/cdap-default.xml
https://issues.cask.co/browse/CDAP-5760
=> enable audit log by default

cdap-ui/app/directives/dag-plus/my-dag-ctrl.js, cdap-ui/app/directives/dag-plus/my-dag-factory.js, cdap-ui/app/directives/dag-plus/my-dag.js, cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/directives/widget-container/widget-js-editor/widget-js-editor.js, cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/hydrator/templates/list.html, cdap-ui/app/features/hydratorplusplus/controllers/create/create-studio-ctrl.js, cdap-ui/app/features/hydratorplusplus/leftpanel.less, cdap-ui/app/features/hydratorplusplus/services/hydrator-service.js, cdap-ui/app/features/hydratorplusplus/templates/create/canvas.html, cdap-ui/app/features/hydratorplusplus/templates/create/popovers/pre-configured-batch-list.html, cdap-ui/app/features/overview/templates/data-apps.html, cdap-ui/app/services/constants.js
- Reduce padding on plugin list (to accommodate longer plugin name)
- Modify ACE Editor to have tab size 2
- DAG connections in studio view should be shorter
- Fix fit to screen function to make sure the DAG is properly centered (it was offsetting to the right before)
- Modal header for Templates Gallery should be consistent
- Data Pipeline List view
=> [CDAP-5792] [CDAP-5799] hydrator improvements

cdap-app-fabric-tests/pom.xml, cdap-client-tests/src/test/java/co/cask/cdap/client/app/AllProgramsApp.java, cdap-client-tests/src/test/java/co/cask/cdap/client/app/NoOpSparkProgram.java, cdap-common/src/main/java/co/cask/cdap/internal/test/AppJarHelper.java, cdap-data-fabric/src/test/java/co/cask/cdap/kafka/KafkaTester.java, cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoader.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtils.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java, cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/submit/LocalSparkSubmitter.java, cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala, cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkMainWrapper.scala, cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkRuntimeEnv.scala, cdap-unit-test/pom.xml, cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java, cdap-unit-test/src/test/java/co/cask/cdap/security/AuthorizationTest.java, cdap-unit-test/src/test/java/co/cask/cdap/spark/SparkStreamingTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/SparkCSVToSpaceProgram.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowAppWithLocalDatasets.java, cdap-unit-test/src/test/java/co/cask/cdap/test/base/TestFrameworkTestSuite.java, cdap-unit-test/src/test/scala/co/cask/cdap/spark/app/ExplicitTransactionSpark.scala, cdap-unit-test/src/test/scala/co/cask/cdap/spark/app/KafkaSparkStreaming.scala, cdap-unit-test/src/test/scala/co/cask/cdap/spark/app/TestSparkApp.scala
- Added a unit-test for Kafka Spark Streaming
- Also made improvement on stopping Spark program.
=> (CDAP-5791) Fixed not able to run Kafka Spark streaming in unit-test

cdap-docs/admin-manual/build.sh
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB192-1)
=> Fix broken doc build.

cdap-ui/app/directives/group-side-panel/group-side-panel.html, cdap-ui/app/features/hydratorplusplus/routes.js, cdap-ui/app/features/hydratorplusplus/services/hydrator-plus-ordering-factory.js
[CDAP-5773](https://issues.cask.co/browse/CDAP-5773) - Renames `Aggregator` to `SparkML` to `Aggregate` and `Model`
[CDAP-5796](https://issues.cask.co/browse/CDAP-5796) - List artifacts whose artifact version matches with the current CDAP version.
=> Feature/ui change plugintype label hydrator++

cdap-docs/faqs/source/cdap.rst
This issue (https://issues.cask.co/browse/CDAP-3817) has been fixed, as of CDAP 3.3.0. This FAQ comment should be removed.
=> Remove closed issue.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkUtils.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
JIRA - https://issues.cask.co/browse/CDAP-5504
Build - http://builds.cask.co/browse/CDAP-DUT4016-2
=> CDAP-5504 Explore with Spark engine

cdap-common/bin/common.sh, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
JIRA: https://issues.cask.co/browse/CDAP-5707.
Verified on secure and insecure cluster.
=> CDAP-5707 Added support for Hive on Tez.

cdap-ui/app/features/hydratorplusplus/bottompanel.less, cdap-ui/app/features/hydratorplusplus/controllers/create/partials/postactions-ctrl.js, cdap-ui/app/features/hydratorplusplus/templates/partial/postactions.html, cdap-ui/app/services/constants.js
- Creates a UI presentable name map for post action runs in Hydrator++
=> [CDAP-5287] - Creates alias for post action runs in Hydrator++ UI

pom.xml
Update package for Application Template Packages.
Running as http://builds.cask.co/browse/CDAP-DDB39-1
=> Fix Javadocs

cdap-docs/developers-manual/source/building-blocks/workflows.rst, cdap-docs/reference-manual/source/http-restful-api/workflow.rst
JIRA: https://issues.cask.co/browse/CDAP-5713
=> CDAP-5713 Added documentation for local datasets, workflow lifecycle methods and node state api.

cdap-docs/developers-manual/build.sh, cdap-docs/developers-manual/source/building-blocks/spark-programs.rst, cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/_includes/_stopping-spark-service-removing-application.txt, cdap-docs/examples-manual/source/examples/_includes/_stopping-spark.txt, cdap-docs/examples-manual/source/examples/index.rst, cdap-docs/examples-manual/source/examples/spam-classifier.rst, cdap-examples/SpamClassifier/pom.xml, cdap-examples/SpamClassifier/src/main/java/co/cask/cdap/examples/sparkstreaming/SpamClassifier.java, cdap-examples/SpamClassifier/src/main/scala/co/cask/cdap/examples/sparkstreaming/SpamClassifierProgram.scala, cdap-examples/SpamClassifier/src/test/java/co/cask/cdap/examples/sparkstreaming/SpamClassifierTest.java, cdap-examples/SpamClassifier/src/test/resources/trainingData.txt, cdap-examples/deploy_pom.xml, cdap-examples/pom.xml
- A Spark Streaming example application
- Reads training data of messages labeled as spam or ham. Dataset: https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection
- Builds a Spark MlLib NaiveBayes model for spam classification
- Reads kafka message in realtime through spark streaming and classifies them as spam/ham by predicting based on the above model.
- Writes the message id and spam/ham label to dataset  which is queries through a service.
To Do:
Issue: https://issues.cask.co/browse/CDAP-5446
Build : http://builds.cask.co/browse/CDAP-DUT4058-1
Docs Build: http://builds.cask.co/browse/CDAP-DOB202-3
Example: 
- [Examples Index](http://builds.cask.co/artifact/CDAP-DOB202/shared/build-3/Docs-HTML/3.4.0-SNAPSHOT/en/examples-manual/examples/index.html)
- [Spark Streaming …
=> CDAP-5446 SpamClassifier: A Spark Streaming Example

cdap-docs/developers-manual/source/data-exploration/hive-execution-engines.rst, cdap-docs/developers-manual/source/data-exploration/index.rst
… as execution engines for CDAP Explore
Jira: [CDAP-5820](https://issues.cask.co/browse/CDAP-5820)
Quick Build: http://builds.cask.co/browse/CDAP-DOB199-5
Page of interest:
- [Data Exploration](http://builds.cask.co/artifact/CDAP-DOB199/shared/build-5/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/data-exploration/index.html)
- [Hive Execution Engines](http://builds.cask.co/artifact/CDAP-DOB199/shared/build-5/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/data-exploration/hive-execution-engines.html)
=> (CDAP-5820) Added documentation for Spark and Tez

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
Changes for spark driver to use more perm memory.
Issue: https://issues.cask.co/browse/CDAP-5768
Build: http://builds.cask.co/browse/CDAP-DUT4064-1
=> Changes for spark driver to use more Perm memory

cdap-app-fabric/src/main/java/org/apache/twill/internal/yarn/AbstractYarnTwillService.java
https://issues.cask.co/browse/CDAP-5844
Workaround for: https://issues.apache.org/jira/browse/HDFS-9276
http://builds.cask.co/browse/CDAP-DUT4080-1
=> CDAP-5844 Update HDFS delegation token properly for HA mode

cdap-examples/LogAnalysis/pom.xml, cdap-examples/SpamClassifier/pom.xml, cdap-examples/SparkKMeans/pom.xml, cdap-examples/SparkPageRank/pom.xml, cdap-examples/WikipediaPipeline/pom.xml
Issue : https://issues.cask.co/browse/CDAP-5845
Working on testing it.
=> CDAP-5845 Do not package spark-core with examples

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
JIRA - https://issues.cask.co/browse/CDAP-5855
Tested on cluster.
=> CDAP-5855 Prevent RM from cancelling delegation tokens after Explore query MR job is complete

cdap-client/src/main/java/co/cask/cdap/client/NamespaceClient.java, cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataRecord.java
Jira: [CDAP-4866](https://issues.cask.co/browse/CDAP-4866)
Build: http://builds.cask.co/browse/CDAP-DUT4086
=> (CDAP-4866) Removed deprecated code from MetadataRecord and NamespaceClient
