cdap-distributions/bin/build_artifact_upload.sh

Porting (merged) CDAP-3437 to 3.1, 3.0, 2.8.
This only affects build artifacts upload.

need the quotes to force string comparison

---

cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/templates/create/metadata.html
cdap-ui/app/features/adapters/templates/create/settings.html
cdap-ui/bower.json
cdap-ui/pom.xml

- Updates angular gridster 
Right now we have jserror when we switch tabs. angular-gridster internally nullifies grid data when we switch tab which causes issue (https://github.com/ManifestWebDesign/angular-gridster/issues/262). Hence the upgrade.
- Fixes adapter modal right buttons when browser size is reduced.

Fix/ui adapter modal+gridsterupdate

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ApplicationClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ArtifactClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/common/ClientTestBase.java
cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java
cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java
cdap-proto/src/main/java/co/cask/cdap/proto/ApplicationDetail.java
cdap-proto/src/main/java/co/cask/cdap/proto/ApplicationRecord.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ApplicationClassInfo.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ApplicationClassSummary.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactSummary.java
cdap-ui/app/features/apps/templates/list.html

adding rows to the ArtifactStore metatable for application classes
found in artifacts to allow efficient lookup of app classes in
a namespace and for a given class name. This functionality is
exposed through the ArtifactRepository and through the http
handler.
Filling in the REST endpoint for getting application classes in
a namespace and by classname. Also adding artifact name and version
filters to the get apps REST endpoint.
Finally, also added methods to ArtifactClient corresponding to the
new REST APIs, and a new method to ApplicationClient for filtering
applications by artifact.

CDAP-3283 index application class information and expose it

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/template/etl/api/batch/BatchContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/main/java/co/cask/cdap/app/etl/batch/ETLBatchApplication.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/main/java/co/cask/cdap/app/etl/batch/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/main/java/co/cask/cdap/app/etl/batch/ETLWorkflow.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/main/java/co/cask/cdap/app/etl/batch/config/ETLBatchConfig.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/BaseETLBatchTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/BatchCubeSinkTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/BatchETLDBAdapterTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/ETLESTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/ETLMapReduceTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/ETLStreamConversionTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/etl/batch/ETLTPFSTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/test/sink/MetaKVTableSink.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/co/cask/cdap/app/test/source/MetaKVTableSource.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/java/org/apache/hadoop/fs/s3native/S3NInMemoryFileSystem.java
cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/test/resources/logback-test.xml
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/batch/BatchTransformContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/batch/MapReduceBatchContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/AdapterPipelineConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/ETLApplication.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/ETLConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/PipelineValidator.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/template/etl/common/PipelineValidatorTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/TimePartitionedFileSetDatasetAvroSource.java
cdap-app-templates/cdap-etl/pom.xml

Creating the application version of ETLBatch. This will replace
the ETLBatch ApplicationTemplate, but we can't remove the template
until the UI is moved off templates and adapters.

CDAP-3488 create etl batch application

---

pom.xml

JSON doesn't allow comments, so there's no license header.

Exclude JSON template from RAT

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/MockAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

MockConfigurer is required so that we don't have to pass in ArtifactRepository/PluginInstantiator. Moreover it is logically not possible since the artifact itself is not available and thus instantiating plugins before that won't be possible. Hence deployApplication method itself won't work for applications using plugins. Users will have to resort to using addArtifact, addPluginArtifact, addApplication route
Also, Close the ArtifactPluginInstantiator in Worker, ServiceHandler
Build : http://builds.cask.co/browse/CDAP-DUT2634

Use MockAppConfigurer instead of DefaultAppConfigurer to get the name of the App

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java

https://issues.cask.co/browse/CDAP-3432
http://builds.cask.co/browse/CDAP-DUT2675

CDAP-3432: CLI prompt doesn't show the namespace name when passed from URI

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileReader.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamInputFormat.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamInputSplit.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamInputSplitFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamRecordReader.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/main/java/co/cask/cdap/hive/stream/HiveStreamInputFormat.java
cdap-explore/src/main/java/co/cask/cdap/hive/stream/StreamInputSplit.java
cdap-explore/src/main/java/co/cask/cdap/hive/stream/StreamRecordReader.java
cdap-explore/src/main/java/co/cask/cdap/hive/stream/StreamSerDe.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceStreamTest.java

- Detach it from StreamConfig so that different stream table view can have different format spec
- Modify the InputFormat/RecordRecord to use the FormatSpecification from the SerDe instead of reading from StreamConfig.

(CDAP-3387) Store the stream format specification as part of SerDe property

---

cdap-client/src/main/java/co/cask/cdap/client/NamespaceClient.java

#3751 broke backward compatibility for 2 methods in ``NamespaceClient``. This PR adds back support for them.
Build: http://builds.cask.co/browse/CDAP-DUT2679

Maintain backward compatibility in NamespaceClient

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java

Now that apps are created from artifacts, this is bad behavior.
We don't have to delete the app jar since other apps may be using
it, and since futures apps may want to use it.

CDAP-3559 dont delete the app archive when deleting an app

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java

JIRA: https://issues.cask.co/browse/CDAP-3542
When program on one of the fork branches fails, after shutting down the executor service for the nodes executing on the other branches, wait till the shutdown complete, so that the RunRecord of the underlying program gets updated correctly.

CDAP-3542 Wait till the executor shutdown is completed

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ProgramGenerationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ApplicationLifecycleServiceTest.java

Fixing an issue where the upgrade tool would choke on apps that
have the wrong location stored for the application archive. Not
sure how that can happen, it is probably a sign on multiple
cdap upgrades and one of those upgrades going wrong.
In any case, check the location exists. If not, try to find it
at the expected location. If that doesn't exist, just continue
on and log a message.

CDAP-3539 fixing upgrade to handle bad app metadata

---

cdap-api/src/main/java/co/cask/cdap/api/Config.java
cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginConfig.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginInstantiator.java

Moving PluginProperties to ``PluginConfig`` from ``Config``
Build : http://builds.cask.co/browse/CDAP-DUT2682

CDAP-3561: PluginProperties should be in PluginConfig

---

cdap-distributions/pom.xml
pom.xml

This tells `fpm` to send the `--target noarch-unknown-linux` option to `rpmbuild` which allows packages to be built on OSX and installed on Linux.

Allow RPM builds on OSX and other non-Linux systems

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java
cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java

- Locking is only required when modifying the runtimeInfos map, no need to lock the entire time inside the run() method
- If we lock the whole run() method, it’s possible that the program finish very fast such that while run() is holding the lock, the ProgramController listener.completed() method is triggered (from another thread), which also tries to acquire the lock to modify the runtimeInfos map, causing a deadlock.

(CDAP-3579) Reduce locking scope of the AbstractProgramRuntimeService.run() method

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-common/src/main/java/co/cask/cdap/common/io/CaseInsensitiveEnumTypeAdapterFactory.java
cdap-common/src/test/java/co/cask/cdap/common/io/CaseInsensitiveEnumTypeAdapterFactoryTest.java

Adding a type adapter factory for deserializing enums in a case
insensitive way and serializing enums in lowercase. This makes it
a little easier to use the deploy app api since artifact scope
no longer needs to be all caps.

CDAP-3580 deserialize scope enum in a case insensitive way

---

cdap-docs/reference-manual/source/licenses/index.rst

This is a one-word change to the license file included in the documentation. This license is the standard text used in the Apache License, which was intended to be placed at the top of a source code *file*; and so it uses the word *file*.
But our usage here is slightly different; we are referring to the CDAP *product*, and hence the one-word change.

Change the word "file" to "product" in the license description.

---

cdap-ui/app/directives/breadcrumbs/breadcrumbs.html
cdap-ui/app/directives/breadcrumbs/breadcrumbs.less
cdap-ui/app/directives/breadcrumbs/namespace.html

1. Limit namespace in breadcrumb to 24.
2. Adjust the drop down size to 24
3. Sort the namespace list.

CDAP-3599 Breadcrumb namespace width to 24

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ApplicationClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java
cdap-proto/src/main/java/co/cask/cdap/proto/ApplicationDetail.java

Extending the get apps rest api to allow specifying a comma
separated list of artifact names. The endpoint will return all
apps that use an artifact whose name is in that set of names.
Also performing some refactoring along the way, moving logic from
the http handler into the service. This allows us to remove the
usage of Store in the http handler.

CDAP-3582 allow filtering apps by multiple artifact names

---

cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
cdap-unit-test/src/test/java/co/cask/cdap/partitioned/AppWithMapReduceConsumingPartitions.java
cdap-unit-test/src/test/java/co/cask/cdap/partitioned/MapReducePartitionConsumingTestRun.java

This allows adding an OutputFormatProvider as an output onto the MapReduceContext.
Previously, only Datasets were allowed.
http://builds.cask.co/browse/CDAP-DUT2743-4

Support for adding OutputFormatProvider as output of MR

---

cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/main/java/co/cask/cdap/app/etl/batch/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/template/etl/batch/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/Constants.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/DefaultEmitter.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/Pipeline.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/PipelineRegisterer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/TransformDetail.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/TransformExecutor.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/TransformInfo.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/TransformResponse.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/template/etl/common/TransformExecutorTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime-app/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-realtime-app/src/main/java/co/cask/cdap/app/etl/realtime/ETLWorker.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/template/etl/realtime/ETLWorker.java

we want to user to be able to write to an error dataset from validator transform for invalid records. 
this PR contains implementation for ETL Realtime. 
JIRA: https://issues.cask.co/browse/CDAP-3479
Build: http://builds.cask.co/browse/CDAP-DUT2735-1

CDAP-3479- Integrate error dataset transformation - ETL Realtime

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataRecord.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java

This PR is created to help share internally about the new datasets for Business Metadata.
Added new system dataset for Business Metadata called BusinessMetadataDataset that internally backed by IndexedTable to support inverted index search for value and key:value columns.

CDAP-3527 Add first drop of Business Metadata dataset.

---

cdap-app-templates/cdap-data-quality/src/main/java/co/cask/cdap/dq/DataQualityApp.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/template/etl/api/batch/BatchSinkContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/batch/MapReduceSinkContext.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/BatchElasticsearchSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/BatchWritableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/DBSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetSink.java

This changes the sink contexts to use addOutput() instead of
setOutput() in preparation of allowing multiple output sinks.

CDAP-3593 move sinks to new addOutput() apis in cdap mapreduce

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/AbstractSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DistributedSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/LocalSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AdapterService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ScheduleClientTestRun.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java

This PR does the following: 
- CDAP 2892 : When a new app is deployed with workflow its schedules are in disabled state unless resumed by the user manually. This is true for both time and stream size based schedule.
- Gets rid of lazyStart() hack which was required to deploy schedules with a stopped scheduler to ensure that they are in paused state.
Approach:
The way achieve paused triggers in Quartz scheduler is through groups. [More Details] (https://issues.cask.co/browse/CDAP-2892?focusedCommentId=17594&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17594)
- During initialization of scheduler we create add an empty job within a group. This is needed as I was not able to find any direct way to create a group.
- This group is then paused which guarantees …

CDAP 2892 : Deploy schedule triggers in paused state and get rid of lazyStart() scheduler hack

---

cdap-app-templates/cdap-etl/cdap-etl-batch-app/src/main/java/co/cask/cdap/app/etl/batch/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/Constants.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/ETLConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/ETLTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/Pipeline.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/PipelineRegisterer.java
cdap-app-templates/cdap-etl/cdap-etl-realtime-app/src/main/java/co/cask/cdap/app/etl/realtime/ETLWorker.java
cdap-app-templates/cdap-etl/cdap-etl-realtime-app/src/main/java/co/cask/cdap/app/etl/realtime/config/ETLRealtimeConfig.java
cdap-app-templates/cdap-etl/cdap-etl-realtime-app/src/test/java/co/cask/cdap/app/etl/realtime/ETLWorkerTest.java

Adding the ability to write to multiple sinks in the etl realtime
application. The exact same data will be written to all sinks.
If transactional sinks are used, a failure to write to one sink
will cause that write to other sinks to fail. If non-transactional
sinks are used, a write to one sink can succeed while a write to
another sink can fail.

CDAP-3591 ability to write to multiple sinks in etl realtime

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/motd.sh

This maps `127.0.0.1:2222` on the host to `22` on the VM.

CDAP-3549 Enable SSH forwarding

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/stream/view/DescribeStreamViewCommand.java
cdap-client-tests/src/test/java/co/cask/cdap/client/StreamViewClientTestRun.java
cdap-common/src/main/java/co/cask/cdap/internal/explore/ExploreTableNaming.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/view/ViewAdmin.java
cdap-data-fabric/src/test/java/co/cask/cdap/data/stream/view/StreamViewHttpHandlerTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/ViewSpecification.java

- "tableName" can now be passed into the HTTP endpoint for
creating/updating a stream view so the user can specify what
the name of the Hive table will be
- default table name for stream views changed from
`streams_<stream-id>_views_<view-id>` to
`stream_<stream-id>_<view_id>`
https://issues.cask.co/browse/CDAP-3625
http://builds.cask.co/browse/CDAP-DUT2775

CDAP-3625: Improved table naming for stream views

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/DistributedMRJobInfoFetcher.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/MRJobClient.java

If Hadoop Job History Server has permission issues reading some files, the JobClient#getJob(JobId) method returns null.
So, instead of throwing NullPointerException, throw a NotFoundException, which will be caught by DistributedMRJobInfoFetcher#getMRJobInfo and fall back to the localMRJobInfoFetcher.
https://issues.cask.co/browse/CDAP-3621
http://builds.cask.co/browse/CDAP-DUT2797-2

CDAP-3621-throw-IllegalStateException-instead-of-NPE

---

cdap-common/bin/common.sh

Fixes CDAP-3219 by allowing a user to set HBASE_VERSION and CDAP respecting the setting.

CDAP-3219 Allow setting HBASE_VERSION

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextProvider.java
cdap-common/src/main/java/co/cask/cdap/common/conf/CConfiguration.java
cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractMasterTwillRunnable.java
cdap-common/src/test/java/co/cask/cdap/gateway/handlers/ConfigServiceTest.java
cdap-explore/src/main/java/co/cask/cdap/hive/context/CConfCodec.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/run/LogSaverTwillRunnable.java

JIRA: https://issues.cask.co/browse/CDAP-3189
In order to pass the cdap configurations (cdap-default.xml and cdap-site.xml) to the mapper and reducer tasks, they are serialized into the hConf under property name "hconf.cconf".
While deserializing, we first create the new `CConfiguration` object which includes the cdap-default.xml and cdap-site.xml. Then to this object we add the value of "hconf.cconf" property as a new resource. This results in the `CConfiguration` object to contain duplicate configurations. 
As a result we see lot of warning messages when the MapReduce program is run:
```java
2015-09-11 09:23:00,407 - WARN  [LocalJobRunner Map Task Executor #5:c.c.c.c.c.Configuration@1748] - java.io.ByteArrayInputStream@6158ab02:an attempt to override final parameter: …
```

CDAP-3189 Avoid adding cdap-default.xml multiple times to the configuration.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/serialize/DataProto.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/serialize/LineageProto.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/serialize/ProgramProto.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/serialize/RelationProto.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/BusinessMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/ProgramContextAware.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageServiceTest.java

Only recording lineage for datasets from flowlets in this PR to keep changes minimal. I'll add recording for streams and other program types in an upcoming PR.
Also, the following TODOs will be fixed in an upcoming PR:
1. Avoid duplicate writes of lineage for a dataset instance.
2. Add complete metadata and tags when recording lineage.
The PR looks big due to refactoring of tests and new classes for serializing lineage over HTTP.

CDAP-3521 Recording lineage information for a dataset accessed by a flowlet

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java

This fixes a bug where system artifacts could never be deleted,
which is problematic if one is somehow deployed incorrectly.

CDAP-3647 fix bug to allow deletion of system artifacts

---

cdap-docs/admin-manual/source/operations/index.rst
cdap-docs/admin-manual/source/operations/preferences.rst

Adds a section on preferences and runtime arguments in the CDAP-UI, links to examples demonstrating use of preferences, and added bolding to highlight examples in text.
Corrects capitalization and spelling errors, and adds Spark to the list of elements with preferences.
Fix for https://issues.cask.co/browse/CDAP-3353
Built: http://builds.cask.co/browse/CDAP-DDBD569-1
[Administration Manual: Operations](http://builds.cask.co/artifact/CDAP-DDBD569/shared/build-1/Docs-HTML/3.2.0-SNAPSHOT/en/admin-manual/operations/index.html)
[Preferences and Runtime Arguments](http://builds.cask.co/artifact/CDAP-DDBD569/shared/build-1/Docs-HTML/3.2.0-SNAPSHOT/en/admin-manual/operations/preferences.html)

Documentation of Preferences and Runtime Arguments

---

cdap-common/bin/common-env.sh
cdap-common/bin/common.sh
cdap-common/bin/service

This is mostly a style/syntax update. There's not much refactoring done and little functionality change. It's mostly the following:
- Adding braces to variables
- Simplify setting variables
- Use Bash variable expansion capabilities
- Reduce shell-outs (cat/grep)
- Functions `return` instead of `exit`
- Use `$( )` rather than backticks

Clean up scripts, simplify coding, use more bash internals

---

cdap-docs/_common/common-build.sh
cdap-docs/developers-manual/build.sh
cdap-docs/developers-manual/source/building-blocks/mapreduce-programs.rst
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/data-cleansing.rst
cdap-docs/examples-manual/source/examples/purchase.rst

Removes duplicate messages in the warnings in the doc build log.
Fixes the included files, both for line numbers and MD5 hashes.
Built successfully: http://builds.cask.co/browse/CDAP-DDBD571-1

Fix Doc Build: example includes

---

cdap-common/src/main/java/co/cask/cdap/common/HttpExceptionHandler.java

JIRA: https://issues.cask.co/browse/CDAP-2966
Build: http://builds.cask.co/browse/CDAP-DUT2853-1
In `DatasetServiceClient`, we call http handlers for the desired functionality and check the response code. If the response code is not `OK`, we throw `DatasetManagementException` with response body as a part of exception message. However `HttpExceptionHandler` while sending the `INTERNAL_SERVER_ERROR` response, sends an empty message in the response string. This causes the appropriate message to be not propagated till the UI.

CDAP-2966 In case of internal server error while handling the request send more information in the response body.

---

cdap-docs/_common/common-build.sh
cdap-docs/developers-manual/source/building-blocks/index.rst
cdap-docs/developers-manual/source/building-blocks/namespaces.rst
cdap-docs/reference-manual/source/glossary.rst
cdap-docs/vars

- Replace "physical" with "logical" for namespaces in three files.
- Set the parent branch explicitly for the documentation build to get it to build with new "docs" prefix.
Fixes: https://issues.cask.co/browse/CDAP-3664 (namespaces)
Building at: http://builds.cask.co/browse/CDAP-DDBD572-1

Fix Documentation Build and Namespaces description

---

cdap-common/bin/common.sh

This allows the functionality to be reused in other scripts and functions without otherwise modifying the environment.

Move kinit code to cdap_kinit function

---

cdap-docs/admin-manual/source/installation/installation.rst

This updates the Kerberos section of our installation documents. It removes some sections which are best left up to the individual distributions to document and only documents the changes required for CDAP, specifically.

CDAP-3406 Update Kerberos docs

---

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStore.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageServiceTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriterTest.java
cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java

* Renaming lineage REST enpoint /metadata/accesses to /metadata
* Adding test to verify duplicate access record filtering
It would be easier to review them as separate commits.

Misc lineage fixes

---

cdap-distributions/src/packer/scripts/network-cleanup.sh

This prevents the persistent network generator rules from running, removes any previously created rules, removes any DHCP and UDEV cached data, and adds a two second delay after interface is up before starting DHCP (copied from chef/bento's networking scripts).

Improve network handling for CDAP VM

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSStreamFileJanitorTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClientTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceClientTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/BusinessMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/DefaultBusinessMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/NoOpBusinessMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/publisher/MetadataKafkaTestBase.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Intercept the entity deletion of App, Program, Dataset, and Stream so it also remove the corresponding business metadata (property and tags).
Move BusinessMetadataStore to interface and add new implementations for in memory and distributed mode.
For UpgradeTool I bind the BusinessMetadataStore to in-memory since it seems like it will have dataset service ready at the time of the upgrade.
Use Modules.override to change the binding for the DatasetsModule to make BusinessMetadataStore bind to in-memory for some tests that do not need business metadata store testing and does not have DatasetService and TransactionManager running.

CDAP-3605 Entity deletion should remove its metadata.

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/TableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/TableSinkConfig.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/TableSourceConfig.java

Fixes a bug where the row key was required for table source.
Row key is only required for table sink when we write. For a
source it is ok if we never read anything from the rowkey.

CDAP-3326 row key should not be required for table source

---

cdap-ui/app/directives/group-side-panel/group-side-panel.html
cdap-ui/app/features/adapters/controllers/create/leftpanel-ctrl.js
cdap-ui/app/features/adapters/leftpanel.less

Removes the following from Hydrator left panel item headings:
*  Plugin type icons
* Chevon-left and chevron-right
.2

 removes icons + chevrons from item headings

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/app/etl/batch/ETLMapReduceTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/LogParserTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ProjectionTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ScriptFilterTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ScriptTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ValidatorTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/transform/ValidatorTransformTest.java

Moved logic in transforms that validate config settings from
initialize into configurePipeline so that invalid configs fail
early at application creation instead of at runtime.

CDAP-3603 make invalid transform configs fail app creation

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/app/etl/batch/ETLSnapshotTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/SnapshotFileBatchAvroSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/SnapshotFileBatchParquetSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/SnapshotFileBatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetAvroSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetParquetSink.java

Adding avro and parquet schema settings as arguments passed to
the filesets so that they can be used for the correct output when
multiple sinks are configured.

CDAP-3691 fix snapshot filesets to work with multiple sinks

---

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/resources/cdap-default.xml
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/publisher/KafkaMetadataChangePublisher.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/publisher/MetadataKafkaTestBase.java

https://issues.cask.co/browse/CDAP-3662
http://builds.cask.co/browse/CDAP-RBT424

CDAP-3662: Metadata notifications should always only be published to external Kafka

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/scheduler/DatasetBasedTimeScheduleStoreTest.java

Issue: https://issues.cask.co/browse/CDAP-3618
- This fixes the bug in DatasetBasedTimeScheduleStore which while retrieving triggers back from the store used to retrieve triggers only in normal state and skip all others. We cannot skip schedules in suspended state (triggers in paused state) as this will cause them not be added to the scheduler while its being started back again. 
- The executePersist should always persist with its state. 
- After we read the schedules (triggers) from the persistence store we need to check its state which we have saved and if it was paused we need to pause it back. Since the scheduler has not actually been started at this point its fine to call pause like this as schedule cannot get fired before paused is called on it.
- Added test case to check schedule …

CDAP-3618: Fix to not lose suspended schedules on master restart

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryConfigurator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/Artifacts.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/app/InvalidConfigApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java

Fixes a bug where application deployment would fail if a config
was given to an Application class that extends AbstractApplication
without any special config object.

CDAP-3442 fix deploy failures when a config is given to plain app

---

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-common/src/main/java/co/cask/cdap/common/InvalidMetadataException.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/resources/cdap-default.xml
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java

Wire the CDAP-3571 to addProperties and addTags for checking.
Add validation for non existence entities. Update unit tests.

[CDAP-3571] Adding validation to business metadata creation

---

cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml

* Change default log back container to info so that the INFO messages for customer apps are collected by default.

Change default log back to INFO

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDefinition.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java

Support metadata search with case insensitive. So search for value "value" and "VaLue" should yields same result.
To do this, we are introducing new column on the metadata index table column to store lower case value and key:value combo.

[ CDAP-3634] Add support for case insensitive search for metadata

---

cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java

Currently the metadata search using prefix scan search by default.
So search for value will return for value, value1, value2, and value21.
With the change search for value will return value, search for value2* will return value2 and value21.
Merge changes from #4004 for testing.

Add support for both prefix scan search via * and keyword specific search

---

cdap-ui/app/features/adapters/controllers/create-ctrl.js
cdap-ui/app/features/adapters/controllers/create/leftpanel-ctrl.js
cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/templates/create.html

* Add predefined templates to wizard view
* Remove templates from left side panel
TODO:
* May need to add a way to go back from list of templates to the original create state (need to confirm with Brady) [DONE]

add option for predefined templates in wizard view

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java

We need to remove this requirement because there are 3rd party
jars that include this attribute in their manifest.

CDAP-3714 remove requirement that main class is an application

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/app/CreateAppCommand.java

comes from a config field in the file contents. This lets us
extend the object if we have more arguments in the future, and it
also makes it so that the same file can be used to create an app
through curl and the CLI

fix create app command so that the config sent in the request

---

cdap-app-fabric/src/test/java/co/cask/cdap/SleepingWorkflowApp.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionRowRecordReader.java

Also modifying couple of test cases to check explore that explore works when the row key field is of type nullable simple and when it is of simple type
JIRA : https://issues.cask.co/browse/CDAP-3239
Build : http://builds.cask.co/browse/CDAP-RBT445-3

CDAP-3239 Check if the rowfield type is simple or nullable simple

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java

- Remove unnecessary synchronize method
- Always update the in memory runtimeInfos from the controller callback thread
- Remove bunch of unused code

(CDAP-3716) Refactor code that causes deadlock

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/TransactionManagerDebuggerMain.java

- Prints checkpoints array for SnapshotCodecV4
- Prints Empty array for version below 4.
Tested with TransactionSnapshot dumped for version 3 and 4 from unit tests.
Output: https://issues.cask.co/browse/CDAP-3610?focusedCommentId=18591&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18591

CDAP-3610: TransactionManagerDebuggerMain prints checkpoints

---

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsValueKey.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/BusinessMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/DefaultBusinessMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/service/NoOpBusinessMetadataStore.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java

Right now, when search done on value or key:value the returned entities are not filtered by active namespace.
We now add namespace as prefix on the value and key:value index columns in the IndexedTable for BusinessMetadataDataset.
Updated tests accordingly.

[CDAP-3722] Add filtering search metadata on active namespace.

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/save/AbstractKafkaLogProcessor.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckPointWriter.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointManager.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointingLogFileWriter.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogMetricsPlugin.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/write/FileMetaDataManager.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestDistributedLogReader.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java

we now Use TransactionExecutor instead of Transactional to avoid having many connections open to  HBase while writing in an transaction.
we have also added few improvements to reduce the number of transactions by sending the partition and the checkpoint in a map and having them written in one transaction, rather than creating a new transaction for each partition and checkpoint.
we also skip writing to table if the checkpoints have not changed by comparing with a local map of the past checkpoint.
JIRA: https://issues.cask.co/browse/CDAP-3700

CDAP-3700 Reduce LogSaver connections to HBase

---

cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java

- It was working before because we didn’t block on the stop, so if we get
lucky, the DS service is still running.

(CDAP-3723) Should stop the service after usage of it is done

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java

- This is needed since the individual program run records is written
from the thread inside the executor.

Make sure the fork executor terminates before the Workflow completed

---

cdap-docs/developers-manual/source/building-blocks/spark-programs.rst

Remove beta, standalone restriction, and version information on Spark.

Fix Spark Documentation

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStore.java

JIRA: https://issues.cask.co/browse/CDAP-3721
`TriggerStatus` class implements `Serializable` interface. As a part of #3966 we did modifications to the this class (made the member variables `final`), this failed initialization of the scheduler with `InvalidClassException`. 
Filed https://issues.cask.co/browse/CDAP-3733 to remove this limitation.

CDAP-3721 Reverted the modifications done to the TriggerStatus class.

---

cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java

Fixed by making all services bind to 127.0.0.1 in standalone. 
Tested multiple times on my laptop. 
Tested listing apps and programs, running apps, getting metrics, getting logs executing queries.
Also tested that I works fine after network drops. 
Also tested that everything works fine after the network comes back.

[CDAP-3709] Standalone fails after network connection drops

---

cdap-ui/app/features/adapters/bottompanel.less

*  Adds right padding to select dropdown to prevent overflowing text

fixes padding issue on select dropdown

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
cdap-common/src/main/resources/cdap-default.xml

The previous implementation tried to enforce ordering by sorting
on the artifacts, with parents ordered larger than children. The
problem was the comparison make sense when 2 artifacts were being
compared, but it wasn't a natural ordering. That is, there could
be a scenario where A < B, B < C, but A > C.
Instead, since we enforce only 1 level of dependencies, just
adding all parents first, then adding the children.

CDAP-3727 fix bug with order of system artifact loading

---

cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/templates/list.html

*  Removes Add+ button from empty pipeline list template
*  Adds a small top margin to the empty well to be consistent with table margin in list view
I

removes add button from list template

---

cdap-ui/app/services/app/my-app-dag-service.js
cdap-ui/templates/cdap-etl-realtime/Kafka.json

- Converts all numbers or any other types to be string for plugin properties before publishing it to backend.
- Fixes Kafka.json file (offset, partition and schema) to have proper default values.

Fixes converting numbers while saving pipeline + Kafka.json configuration fixes

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java

JIRA: https://issues.cask.co/browse/CDAP-3753
This will not log warnings such as `security.auth.server.address is deprecated. Instead, use security.auth.server.bind.address` while starting up the standalone.

CDAP-3753 Removed use of depreacted variable AUTH_SERVER_ADDRESS.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRangeTest.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/src/main/java/Sink.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/src/main/java/Source.java
cdap-common/src/main/java/co/cask/cdap/common/conf/ArtifactConfig.java
cdap-docs/developers-manual/source/building-blocks/plugins.rst
cdap-docs/developers-manual/source/getting-started/quick-start.rst
cdap-docs/included-applications/source/etl/creating.rst
cdap-docs/included-applications/source/etl/custom.rst
cdap-docs/included-applications/source/etl/plugins/third-party.rst
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactRange.java

then walk through an example. Also moving some of the deployment
docs from custom etl plugins doc to the general plugins doc and
fixing errors.

restructure plugin doc to first describe plugins and capabilities,

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/realtime/source/JmsSource.java

Similar to JDBC plugin error message, the JSM realtime source plugin also have mileading error message when the plugin class could not be found.

Fix misleading error message when trying to load JMS connector plugin.

---

cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.html
cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.less
cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.html
cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.less
cdap-ui/app/features/adapters/bottompanel.less

*  Adds 2px bottom margin to rows in keyvalue-container and dsv-container
*  Adds auto height to schema container textarea

adds 2px bottom margin to input rows

---

cdap-ui/app/features/adapters/etlapps.less

add margin right to pagination in history tab (hydrator detail view)

---

cdap-ui/app/features/adapters/bottompanel.less
cdap-ui/app/features/adapters/etlapps.less

* Resize the studio window
* On bigger screen the top canvas is 40% and bottom is 60%
* On smaller screen the top canvas is 60% and bottom is 40%
* Used absolute height as 800px to determine big vs small screen

Resize studio window based on browser height

---

cdap-ui/app/directives/dag/my-dag-ctrl.js
cdap-ui/app/directives/dag/my-dag-factory.js
cdap-ui/app/directives/dag/my-dag.html
cdap-ui/app/directives/navbar-hydrator/navbar.html
cdap-ui/app/features/adapters/controllers/create/plugin-edit-form-ctrl.js
cdap-ui/app/features/adapters/controllers/detail-ctrl.js
cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-config-form.html
cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-output-schema.html
cdap-ui/app/features/adapters/templates/detail.html
cdap-ui/app/features/adapters/templates/tabs/node-configuration.html
cdap-ui/app/features/home/routes.js

- Adds Node Configuration to detailed view
- Removes Schema on Edge in detailed view (as the schema information is not consistently available in UI)
- Fixes hydrator and cdap header to highlight appropriate options.

Adds node configuration of each node in detailed view(non-editable)

---

cdap-docs/developers-manual/source/building-blocks/datasets/datasets-mapreduce.rst
cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst
cdap-docs/developers-manual/source/building-blocks/mapreduce-programs.rst
cdap-docs/included-applications/build.sh

Documentation for:
1) Multiple Output Datasets of a MapReduce program.
2) Dynamic Partitioning of PartitionedFileSet, as output of a MapReduce program.
https://issues.cask.co/browse/CDAP-3687

Multiple Output Datasets & Dynamic Partitioning of PartitionedFileSet

---

cdap-ui/app/directives/dag/my-dag-ctrl.js
cdap-ui/app/features/adapters/controllers/create/partials/nodeconfig-ctrl.js
cdap-ui/app/features/adapters/controllers/create/plugin-edit-form-ctrl.js
cdap-ui/app/features/adapters/controllers/create/toppanel-ctrl.js
cdap-ui/app/features/adapters/services/node-config-service.js
cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-form.html
cdap-ui/app/services/app/my-app-dag-service.js
cdap-ui/app/services/constants.js

- Fixes studio to throw an error while publishing/validating a pipeline if there are un-saved node configurations.

Fixes UI to show console error when un-saved node config exists while publishing a pipeline

---

cdap-docs/integrations/source/partners/cloudera/configuring.rst

update to Cloudera docs to reflect that ``app.template.dir`` is now ``app.artifact.dir``

update to reflect app.artifact.dir instead of app.template.dir

---

cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-config-form.html
cdap-ui/templates/common/Database.json

- Removes output schema for sinks if it doesn't have a schema property.
FIXME: 
Need to confirm about implicit-schema. If there is implicit-schema should we display the output schema or hide it?

Hides schema for sinks when it doesn't have a schema property

---

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-realtime/pom.xml
cdap-app-templates/cdap-etl/pom.xml

This will change it as a direct dependency in etl-realtime app and have Export-Package of "javax.jms.*".
Need to revert this hack and introduce a proper plugin class loading model like we used to have in 3.1.
See: https://issues.cask.co/browse/CDAP-3810

Move the dependency of geronimo-jms_1.1_spec as quick fix in 3.2

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/DelayedHttpServiceResponder.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

In case of exception while accessing the service handler, instead of returning entire stack trace, just return the root cause message.

Instead of returning stack trace just return the rootcause message.

---

cdap-docs/admin-manual/source/installation/installation.rst
cdap-docs/reference-manual/source/release-notes.rst

This documents the workaround for CDAP-3817.  We instruct the user to create the ``tx.snapshot`` directory prior to starting cdap, to avoid the potential for it getting created with improper permissions.

documenting workaround for CDAP-3817

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java

Since the tags actually will be stored as comma delimited strings, when searching
for one of the tags doing both prefix and keyword match will not work well
if an entity has more than one tags.
Assume a program has tags: tag1,tag2,tag3 then search on tags:tag2 will not yield
any result nor search on tags:tag2*.
Need to add special handling for searching tags for key:value format.

[CDAP-3830] Fix the metadata search on tags

---

cdap-docs/included-applications/source/conf.py
cdap-docs/included-applications/source/etl/plugins/batchsinks/database.rst

Add a conditional text block to the database sink reference page as these changes do not take affect until 3.2.1.
The PR that was merged yesterday fixed the documentation build, but it inadvertently added a change that doesn't take affect until 3.2.1. To allow the documentation to be built as "3.2.0", yet contain the changes required for 3.2.1, this adds a conditional test for including the affected paragraph. Once the version changes to greater than 3.2.0, the paragraph will be included.
If other documentation manuals need fixes such as this, this code could be moved to the common conf.py and accessed from all.
Building at: http://builds.cask.co/browse/CDAP-DDB23-1

Fix Documentation for 3.2.0

---

cdap-ui/app/features/dashboard/controllers/userdashboard-ctrl.js
cdap-ui/app/features/dashboard/templates/userdashboard.html

In Ops dashboard, on change in frequency or duration the polling should automatically change without forcing the user to stop and restart the polling again.

Fixes to continue polling when frequence or duration is changed

---

cdap-ui/app/directives/dag/my-dag-ctrl.js
cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-config-form.html

- Removes output schema for sinks that doesn't have a 'schema' property.
- Adds red asterisk to output schema for sinks that has a required schema property.
- Adds output schema for sink if the node configuration has an implicit schema attached to it.

Fix for output schema for sinks

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/read/FileLogReader.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/read/FileLogReaderTest.java

JIRA: https://issues.cask.co/browse/CDAP-3900
Build: http://builds.cask.co/browse/CDAP-DUT2925-1
It is possible that the log files for the requested range are already deleted, in case of old program runs. For such requests both the start and toTimeMs will fall outside the range sortedFiles. In that case return empty list.

CDAP-3900 Return empty list in case of logs are requested for the deleted program runs.

---

cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowFailureInForkApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java

JIRA: https://issues.cask.co/browse/CDAP-3696
Following two changes made in this PR:
1. Updated the `testWorkflowTokenPut` to verify that the Workflow run is completed before checking the status of the underlying programs.
2. Added synchronization in the `WorkflowFailureInForkApp` so that the exception in MapReduce program is thrown only when the run record for the MapReduce program running in other branch is generated.

CDAP-3696 Potential fix for the flaky test.

---

cdap-ui/app/features/adapters/controllers/create/toppanel-ctrl.js

This fix is in response to [a comment](https://github.com/caskdata/cdap/pull/4215/files#r40985750) in a previous PR (https://github.com/caskdata/cdap/pull/4215).

Remove usage of 'adapter'.

---

cdap-examples/README.rst
cdap-standalone/pom.xml
cdap-standalone/src/dist/README

This adds project version and filtering to the CDAP SDK /examples README.
To the main SDK README, it adds some additional instances of using the versioning to set correct paths to the website based on the version. This will help people end up at the correct version of the examples and the documentation for the version of the SDK that they are using.
It adds additional and updated descriptions of the examples to reflect recent changes, and includes a description for all but the CubeService (which is not a complete example; it will be dealt with in another PR.)
Building at: http://builds.cask.co/browse/CDAP-RBT498-1

Add project versioning to READMEs

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java

JIRA: https://issues.cask.co/browse/CDAP-3696
This test case tests that the failure of one MapReduce program in the Workflow fork should cause the MapReduce program running in other branch to get marked as killed by interrupting it. However the test case is flaky and the outcome depends on the timing of when the interrupt is generated. Disabling the test till we have the robust way of verification.

CDAP-3696 Disabling the flaky test till its fixed.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedStreamSizeScheduleStore.java

JIRA: https://issues.cask.co/browse/CDAP-3695
`StreamSizeSchedulerTest.testStreamSizeSchedule` fails on the bamboo.
Following execution sequence leads to the failure:
1. Assume two threads, Thread1 (corresponding to the "SampleSchedule1") and Thread2 (corresponding to the "SampleSchedule2"), start executing the `StreamSizeScheduleTask.receivedPollingInformation` method concurrently. 
2. Thread1 updates the store with base run for the SampleSchedule1. Since this is inside the `synchronized` block, Thread2 will be blocked till the updates by Thread1 happens. 
3. Thread2 now acquires the lock and try to update the base run for the SampleSchedule2.
4. Meanwhile Thread1 runs the program and try to update the last run outside the synchronization block. For this the new transaction is started …

CDAP-3695 Synchronize the store updates for the last schedule run.

---

cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh
cdap-docs/developers-manual/build.sh

Move new "app.program.extra.classpath" to the correct alphabetical location.
Update hashes.
Quick Build: [Results](http://builds.cask.co/browse/CDAP-DOB10-1) passed.

Fix docs for new "app.program.extra.classpath"

---

cdap-app-fabric/pom.xml
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ClientTestsSuite.java
cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetClient.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetModuleClient.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetTypeClient.java
cdap-client/src/main/java/co/cask/cdap/client/LineageClient.java
cdap-client/src/main/java/co/cask/cdap/client/MetaClient.java
cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java
cdap-client/src/main/java/co/cask/cdap/client/MonitorClient.java
cdap-client/src/main/java/co/cask/cdap/client/NamespaceClient.java
cdap-client/src/main/java/co/cask/cdap/client/PreferencesClient.java
cdap-client/src/main/java/co/cask/cdap/client/QueryClient.java
cdap-client/src/main/java/co/cask/cdap/client/ScheduleClient.java
cdap-client/src/main/java/co/cask/cdap/client/ServiceClient.java
cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java
cdap-client/src/main/java/co/cask/cdap/client/StreamViewClient.java

Implement `MetadataClient` and `LineageClient`.
Update metadata/lineage test cases to utilize these.
Update `MetadataHttpHandler` to respond with 400 (instead of 500), if null metadata is given in request.
The methods exposed in `MetadataClient` are:
`searchMetadata`
For each of the following program entity types: `Application`, `DatasetInstance`, `Stream`, `Program`:
`getMetadata`
`addTags`
`addProperties`
`removeProperties`
`removeTags`
`removeMetadata`
https://issues.cask.co/browse/CDAP-3889
http://builds.cask.co/browse/CDAP-DUT2918-4

Metadata and Lineage clients

---

cdap-docs/reference-manual/source/http-restful-api/index.rst

Corrects the order of the RESTful APIs on the index page and left sidebar, and adds a thematic index in addition to the alphabetical one.
Passed [Quick Build](http://builds.cask.co/browse/CDAP-DOB7-2): Here's the [revised index page](http://builds.cask.co/artifact/CDAP-DOB7/shared/build-2/Docs-HTML/3.2.0/en/reference-manual/http-restful-api/index.html).
Fix for https://issues.cask.co/browse/CDAP-3892 (the order of the left sidebar did not match the index page)

Change the RESTful APIs Index page

---

cdap-master/pom.xml

Otherwise, users will experience problems if they do not explicitly install all of the compat packages.

CDAP-3961 Update dependencies to include cdap-hbase-compat-1.1

---

cdap-ui/Gulpfile.js
cdap-ui/app/directives/metric-picker/metric-picker.html
cdap-ui/app/directives/metric-picker/metric-picker.js
cdap-ui/app/directives/metric-picker/metric-picker.less
cdap-ui/app/features/dashboard/controllers/addwdgt-ctrl.js
cdap-ui/app/features/dashboard/routes.js
cdap-ui/app/features/dashboard/style.less
cdap-ui/app/features/dashboard/templates/dashboard.html
cdap-ui/app/features/dashboard/templates/partials/addwdgt.html
cdap-ui/app/features/dashboard/widgets.less
cdap-ui/app/main.js
cdap-ui/bower.json

- Disables adding more than 12 widgets per dashboard.
- Modifies the label in add widget modal 
- Modifies the 'Add All' option and adds a tooltip to the plus button in the modal
Existing modal: 
Modified Modal: 
GIF of how it works:

Disables user to add more than 12 widgets on a given dashboard

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ApplicationLifecycleServiceTest.java

Improving the failure handling for the API call that creates an
artifact and application in the same call. If the artifact was
added successfully, but the application failed to deploy,
remove the newly added artifact so that deployment can be
re-tried. If the artifact already exists, give a more detailed
error message explaining how to deploy the app.

CDAP-3939 improve error handling with artifact and app deployment

---

cdap-common/src/test/java/co/cask/cdap/common/zookeeper/coordination/ResourceCoordinatorTest.java

Add longer timeout for blocking Queue for getting changes of resource partition tests.

[CDAP-3883] Fix ResourceCoordinatorTest testAssignment test is flaky

---

cdap-standalone/bin/cdap.sh

Increase the startup memory for the SDK to allow the WikipediaPipeline Example (and others) to run.
Fixes: https://issues.cask.co/browse/CDAP-3949

Increase the startup memory of the SDK

---

cdap-docs/developers-manual/source/getting-started/standalone/index.rst

Quick Build passed: http://builds.cask.co/browse/CDAP-DOB13-1
[Updated CDAP SDK docs](http://builds.cask.co/artifact/CDAP-DOB13/shared/build-1/Docs-HTML/3.2.0/en/developers-manual/getting-started/standalone/index.html#standalone-index)
Fix for https://issues.cask.co/browse/CDAP-3952

Update CDAP SDK docs for Windows

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/scheduler/DatasetBasedTimeScheduleStoreTest.java

Issue: https://issues.cask.co/browse/CDAP-3677
Build: http://builds.cask.co/browse/CDAP-DUT2947-1
- implementing overriding method storeJobsAndTriggers in DatasetBasedTimeScheduleStore which will support storing multiple jobs and triggers as one operation. This does not had any implementation before.
- This will help to solve the issue in which while deploying multiple triggers of a job the failure of one trigger will fail the deployment of all as the sanity check is done before hand. 
- The bulk deployment will be done during the refactoring of the Scheduler: https://issues.cask.co/browse/CDAP-3598
- It will also allow us to add all the triggers with a job in one go rather than iterating over all schedules and adding them one by one.

CDAP-3677: implement storeJobsandTriggers

---

cdap-ui/app/directives/instance-control/instance-control.html
cdap-ui/app/directives/instance-control/instance-control.less

*  Fixes instance control (number input) in Service detail view
*  As styling of the number input is only possible with webkit, non-webkit browsers will default to their native styling for this element (see graphics below)
Safari:
Chrome:
Firefox:

fixes instance control styling in Safari

---

cdap-api/src/main/java/co/cask/cdap/internal/api/DefaultDatasetConfigurer.java
cdap-api/src/main/java/co/cask/cdap/internal/dataset/DatasetCreationSpec.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/DefaultDatasetConfigurerTest.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithDuplicateData.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

Fixed a bug where the dataset configurer would error out if the
same dataset instance or module was added multiple times.
Enhancing the logic to check for equality, so that an exception
is only thrown if the same instance or module is added with a
different value.

CDAP-3990 allow adding the same dataset instance or module

---

cdap-standalone/pom.xml

We have been including in the SDK's ``examples`` directories files that are not required. For example, in 3.2.0 SDK's *Purchase* example *target* directory:
```
Purchase-3.2.0-javadoc.jar
Purchase-3.2.0-sources.jar
Purchase-3.2.0.jar
apidocs
stage-packaging
stage-packaging-deb
```
Only the first three JARs are required; ``apidocs`` just has GIFs, and the ``stage-packaging`` directories has copies of the ``bin`` scripts included higher up.
This PR fixes that by excluding these directories, and reduces the file size of the ZIP...

Improve SDK packaging

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/etl/realtime/source/KafkaSourceTest.java
cdap-notifications/src/test/java/co/cask/cdap/notifications/kafka/KafkaNotificationTest.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/StringPartitioner.java
pom.xml

Upgrade kafka version to 0.8.2.2 to include the fix for https://issues.apache.org/jira/browse/KAFKA-1228.
Tested on SDK, this resolves the issue we were facing in CDAP-3963.
Will test on cluster shortly.
https://issues.cask.co/browse/CDAP-3963
http://builds.cask.co/browse/CDAP-RBT507-4

Upgrade kafka version to 0.8.2.2 to include the fix for KAFKA-1228

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetMetaProvider.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetProvider.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DefaultDatasetProvider.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/LocalDatasetProvider.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

- Added DatasetProvider and DatasetMetaProvider
- Made UsageRegistry obtain the usage registry dataset instance by using
DatasetProvider instead of DatasetFramework
- Removed namespace existence check in DatasetInstanceService.get()
https://issues.cask.co/browse/CDAP-3902
http://builds.cask.co/browse/CDAP-DUT2980
* Distributed CDAP cluster with 3 slaves
* N threads concurrently doing a single get dataset operation with 1 owner
* Before changes, the get dataset RPC should cause the dataset service to make 2 extra RPCs: one for getting the usage registry dataset and another for checking namespace existence
* After changes, the get dataset RPC should cause the dataset service to make 0 extra RPCs
cdap-site.xml:
```
<property>
<name>dataset.service.exec.threads</name>
<value>300</value> …
```

CDAP-3902: Remove unnecessary remote calls when getting a dataset instance

---

cdap-ui/app/directives/dag/my-dag.html
cdap-ui/app/directives/dag/my-dag.less

* Adds character limit to display of node label name in DAG
*  Removes overflow-x scrolling of node label name

fixes issues with node label dag display

---

cdap-api/src/main/java/co/cask/cdap/api/RuntimeContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppUsingNamespace.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

this makes it possible for a program to get its namespace at
runtime. This is useful for a variety of use cases. For example,
you could have a worker that makes program lifecycle calls,
which need namespace in the url. Or you could call some program
that makes an external call to some http endpoint, and needs the
namespace to uniquely identify itself.

CDAP-3982 add method to RuntimeContext to get namespace

---

pom.xml

Commons-logging should not be included in the dependency of CDAP. it should come from the hadoop dependency which will be provided in the cluster.
Verified this change by installing CDAP on a cluster and running programs

Remove commons-logging dependency

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/BaseETLBatchTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLSnapshotTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLTPFSTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/SnapshotFileBatchParquetSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/SnapshotFileBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/TimePartitionedFileSetDatasetParquetSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/TimePartitionedFileSetSource.java
cdap-docs/included-applications/source/etl/plugins/batchsources/index.rst
cdap-docs/included-applications/source/etl/plugins/batchsources/snapshotparquet.rst
cdap-docs/included-applications/source/etl/plugins/batchsources/tpfsparquet.rst

Adding matching parquet sources for the parquet sinks. As part of
this, doing some refactoring so that avro and parquet tpfs sources
can share most of their code.

CDAP-4038 adding tpfs and snapshot parquet sources.

---

cdap-docs/admin-manual/source/operations/resource-guarantees.rst

app.scheduler.name -> apps.scheduler.name

Fix the parameter name in docs

---

cdap-app-fabric/src/main/java/org/apache/twill/internal/ServiceMain.java

Copying the ServiceMain class from Twill for CDAP 3.2.1 release. This should be removed after we upgrade to twill 0.7.0
https://issues.cask.co/browse/CDAP-4052

Copy ServiceMain class from twill

---

cdap-ui/app/features/adapters/controllers/detail-ctrl.js
cdap-ui/app/features/adapters/templates/detail.html

Surfacing errors (if any) in published pipeline. This is an intermittent work around (rather than not showing anything). In 3.3 we need to design a way to show error/info/success messages in a different way.

Show error message (if any) while running once in relatime pipeline or starting a schedule in batch pipeline

---

cdap-common/bin/common.sh

When the CSD starts up CDAP processes, the CSD control script (found [here](https://github.com/caskdata/cm_csd/blob/develop/src/scripts/cdap-control.sh)) sources the common init scripts and invokes some its functions.  As we plan to refactor these init scripts this can be dangerous to overlook.
This PR just adds comments to the required function headers pointing this out, to help avoid potential CSD breakage

adding comments to call out shared init functions with the CSD

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/features/admin/controllers/namespace/stream-metadata-ctrl.js
cdap-ui/app/features/admin/controllers/namespace/streams-create-ctrl.js
cdap-ui/app/features/admin/controllers/namespace/templates-ctrl.js
cdap-ui/app/features/admin/controllers/preferences-ctrl.js
cdap-ui/app/features/admin/templates/namespace/streamscreate.html
cdap-ui/app/features/dashboard/controllers/userdashboard-ctrl.js
cdap-ui/app/features/hydrator/controllers/list-ctrl.js
cdap-ui/app/features/login/routes.js
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/services/alert-on-valium/alert-on-valium.js
cdap-ui/app/services/file-uploader.js
cdap-ui/app/services/service-status-factory.js
cdap-ui/app/services/status-factory.js

- Adds a service that can be replaced in place of ```$alert``` to show subsequent alerts only when the previous one is closed.
- Modifies relevant references of ```$alert``` to ```myAlertOnValium``` .

alertOnValium: Fix/ui thwart mad alerts clicking

---

cdap-ui/Gulpfile.js
cdap-ui/app/features/apps/controllers/tabs/status-ctrl.js
cdap-ui/pom.xml

- Fixes maven UI build process, where the maven build would take forever to RAT check UI because the 'dist' folder generated as part of the build process still stays and we are not ignoring it.
- Fixes a UI es6ify issue (ng-sanitize for app status controller)

Fixes maven UI build to ignore dist and other un-necessary folders + fixes UI issues

---

cdap-ui/app/styles/themes/cdap/theme.less

*  Disables resizing in modal textreas. Modal textareas will scroll vertically when there is more text than rows initially displayed

disabled resizing in modal textareas

---

cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-output-schema.html

Fixes empty output schema to have appropriate message instead of showing both the table and the message

---

cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-config-form.html
cdap-ui/app/features/adapters/templates/create/popovers/plugin-edit-output-schema.html

Same PR (https://github.com/caskdata/cdap/pull/4381) but for 3.2.1

Fixes the condition to show appropriate message when no output schema present on a plugin

---

cdap-ui/app/directives/navbar-hydrator/navbar.less
cdap-ui/app/features/admin/templates/namespace/streamscreate.html
cdap-ui/app/features/explore/explore.less
cdap-ui/app/features/hydrator/leftpanel.less
cdap-ui/app/features/streams/templates/streamscreate.html
cdap-ui/app/index.html

*  Changes overall styling of Hydrator header and navbar to fix styling issues affecting Ubuntu OS. Screenshots below showing the UI running with the fix in each browser
*  Fixes some minor styling bugs including: 1) Hydrator leftpanel - new width properties to prevent longer plugin names from breaking the plugin container, 2) Streams create modal - removing unnecessary form-group class around label and input, which was causing a horizontal scrollbar to display, 3) Explore screen: decreasing right margin of tab headers by 1 px to prevent overflowing on larger devices.
Chrome:
Chromium:
Firefox:

fixes header issues affecting ubuntu OS

---

cdap-distributions/src/hdinsight/install.sh

(CDAP-4089) Temporary workaround by removing offending jar

---

cdap-distributions/src/packer/files/cdap-sdk-with-uri.json.template

This will be used by the upcoming build pipeline to take build artifacts from previous builds and using them, versus only using released artifacts. This is done by replacing the URI with a location on the local disk, skipping the need for a cdap cookbook update to test new SDK versions in Docker/VM.

Template for CI-based Docker builds

---

cdap-distributions/bin/build_yum_repo.sh
cdap-distributions/bin/rpmsign.expect

Create a YUM repository tarball artifact.
Includes:
- shell script to create a YUM repository after building the `rpm` profile (and its dependencies)
- expect script used for GPG signing packages

Repository build script for YUM

---

cdap-ui/app/styles/themes/cdap/theme.less

*  Adds default padding (padding: 6px 12px) to modal footer buttons
*  Removes 30px left margin from between 2 footer buttons (spacing was excessive)

fixes button padding issue for consistent styling

---

cdap-ui/app/features/adapters/controllers/tabs/log-ctrl.js

The UI should not refresh the logs view repeatedly unless there is a change in the latest run.

Fixes polling repeatedly for logs (avoids refreshing logs view every 10 seconds)

---

cdap-distributions/bin/build_apt_repo.sh
cdap-distributions/bin/build_yum_repo.sh
cdap-distributions/bin/rpmsign.expect
cdap-distributions/src/packer/files/cdap-sdk-with-uri.json.template

These files and scripts are backports from the develop branch, for use with the new [build pipeline](http://builds.cask.co/browse/CDAP-BUT)
Build: http://builds.cask.co/browse/CDAP-BUT812-1

Backport APT/YUM repository scripts from develop

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Tables.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTableTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTableAdmin.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetSpecificationUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
cdap-master/src/test/java/co/cask/cdap/data/tools/DatasetSpecificationUpgradeTest.java

use seconds in Dataset Specification, conversion to milliseconds only happens in HBaseTableAdmin implementation, all REST API's and  dataset specs uses seconds.
UpgradeTool has been updated to update DatasetSpecification Entries (from milli-seconds to seconds) in Dataset Instance MDS Table.
JIRA: https://issues.cask.co/browse/CDAP-3345

CDAP-3345, dataset TTL inconsistency fix.

---

cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java
cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/app/BaseBatchCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/app/RestartProgramsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/app/StartProgramsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/app/StatusProgramsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/app/StopProgramsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ApplicationCommands.java
cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java

Adding commands that stop, start, restart, and get status of all
programs in an application. By default, stop, start, and restart
work on long running programs, which means all flows, services,
and workers. Status will work on all programs.
Also fixing a small bug in ApplicationClient when listing programs
for a non-existent app. Will now correctly throw a
NotFoundException instead of some json parsing exception.

CDAP-4023 CLI program lifecycle commands for application programs

---

cdap-client-tests/src/test/java/co/cask/cdap/client/ApplicationClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/common/ClientTestBase.java
cdap-client/src/main/java/co/cask/cdap/client/config/ClientConfig.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java

The test fails on slow machines because artifact deployment takes
longer than the client read timeout. Fixing the test so that the
deployment exception shows up in the logs instead of the cleanup
exception. Also increasing the read timeout and fixing a bug in
the ClientConfig builder where read and connect timeouts were
getting swapped.

CDAP-4147 make app update test more robust.

---

cdap-docs/_common/_source/index.rst
cdap-docs/_common/_source/table-of-contents.rst

Adjusts the copy in the introduction and adds a missing hiding of the table of contents in the sidebar.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB31-1)
- [Overview](http://builds.cask.co/artifact/CDAP-DOB31/shared/build-1/Docs-HTML/3.2.1/en/index.html)
- [Table of Contents](http://builds.cask.co/artifact/CDAP-DOB31/shared/build-1/Docs-HTML/3.2.1/en/table-of-contents.html) ...compared with [current Table of Contents](http://docs.cask.co/cdap/current/en/table-of-contents.html) which has three table of contents; two is enough!

Two small doc fixes.

---

cdap-common/src/main/java/co/cask/cdap/common/internal/guava/ClassPath.java
cdap-common/src/main/java/co/cask/cdap/common/lang/ProgramResources.java
cdap-common/src/test/java/co/cask/cdap/common/lang/FilterClassLoaderTest.java

- The ScriptEngineFactory service resource is no longer available in Java 8
- Use a standard class file to test resource loading.

(CDAP-4140) Fix test in Java8

---

cdap-docs/included-applications/build.sh

As none of the recent changes to the guarded files affected included or copied content, the only change required to fix the build was to update the MD5 hashes.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB33-1).

Fix MD5 hashes.

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AppFabricServiceManager.java
cdap-proto/src/main/java/co/cask/cdap/proto/Containers.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/run/InMemoryAppFabricServiceManager.java

JIRA: https://issues.cask.co/browse/CDAP-4133
live-info for the app fabric now returns the following information instead of empty object:
```java
{
"containers": [
{
"container": "N/A", 
"host": "x.y.z", 
"instance": 0, 
"memory": 0, 
"name": "appfabric", 
"type": "system_service", 
"virtualCores": 0
}
]
}
```
This allows us to locate the leader in HA setup.

CDAP-4133 Ability to get the hostname of a appfabric service as a part of live-info.

---

cdap-ui/app/features/apps/applications.less
cdap-ui/app/features/apps/templates/list.html

*  Removes myEllipsis from app description
*  Keeps description column with at 45% to prevent longer descriptions from reducing the width of the other table columns

removes myEllipsis from app description

---

cdap-ui/app/directives/dag/my-dag-ctrl.js
cdap-ui/app/features/hydrator/controllers/create/partials/nodeconfig-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail-ctrl.js
cdap-ui/app/features/hydrator/services/canvas-factory.js
cdap-ui/app/services/app/my-app-dag-service.js

Fixing schema propagation inconsistencies, where the output schema is not the same as what the user set during creation.
Solution is to save the output schema to the backend.
Build - http://builds.cask.co/browse/CDAP-DRC2876/

[CDAP-4049] Feature/ui schema propagation inconsistencies

---

cdap-app-templates/cdap-data-quality/pom.xml

- cdap-etl-api shouldn’t be in provided scope.

(CDAP-4177) The packaging of data quality app is wrong

---

cdap-docs/developers-manual/source/building-blocks/schedules.rst
cdap-docs/developers-manual/source/building-blocks/workflows.rst
cdap-docs/reference-manual/source/http-restful-api/lifecycle.rst

Adding documentation for the new stop and start multiple programs
restful apis. As part of this, restructuring the docs a little bit
to have individual sections for each action rather than clumping
stop, start, and status into the same section. Also fixing some
descriptions to include the worker program type.

CDAP-4072 fix up lifecycle docs and add sections for multi stop/start

---

cdap-ui/app/features/hydrator/templates/list.html

While editing a draft (be it etl-batch or etl-realtime) we were not passing in the type of the pipeline. So the UI was defaulting to etl-batch. Fixed it by passing in the type while editing a pipeline.

Fixes editing a draft - passing in the pipeline type instead of defaulting to etl-batch

---

cdap-ui/app/features/hydrator/controllers/create/create-studio-ctrl.js
cdap-ui/app/features/hydrator/controllers/create/toppanel-ctrl.js
cdap-ui/app/features/hydrator/services/create/actions/config-actions.js
cdap-ui/app/features/hydrator/services/create/stores/config-store.js
cdap-ui/app/features/hydrator/templates/create/toppanel.html

- Adds top panel
- Right now none of the buttons work (related to communication)
- Right the artifact name alone is bound to the top panel. 
- Modifies ```ConfigStore``` to register event ```onArtifactSave``` as that gets set when the user enters create studio view.

Adds top panel + placeholder buttons + attaches artifact name in top panel

---

cdap-distributions/bin/build_apt_repo.sh
cdap-distributions/bin/build_yum_repo.sh

Allow setting GPG key name and passphrase as arguments, versus only via the environment. This will allow us to mask these values in Bamboo.

Accept GPG key name/passphrase as arguments

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json

currently, the default attributes in the ``idea`` cookbook no longer work.  It appears Jetbrains may have removed previous version downloads.  So setting this attr to get around it for now.

specify idea download version to get around broken default

---

cdap-examples/StreamConversion/pom.xml
cdap-examples/WikipediaPipeline/pom.xml
cdap-examples/deploy_pom.xml
cdap-examples/pom.xml

Exclude asm from the common-http dependency. Without this,
an old version of asm (4.0) gets pulled in instead of the version
the unit-test module requires, causing unit tests to break.
This was causing PurchaseHistory and Wikipedia example tests
to fail. The test failures are only seen when using the sdk.
In the cdap project, the correct version of asm is used.
Also excluding netty and jetty dependencies from StreamConversion
example to fix test failures.

CDAP-3694 fix examples poms

---

cdap-docs/developers-manual/build.sh
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/purchase.rst
cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseHistoryBuilder.java

Running on HDP 2.3, the PurchaseHistoryWorkflow kept restarting because it went over its memory limits. Increasing the MR driver resources to 1024 (default is 512) works around the issue.
Related PR which made this possible: https://github.com/caskdata/cdap/pull/4488
http://builds.cask.co/browse/CDAP-DUT3106-2

Give PurchaseHistoryBuilder (driver of the MR job) more memory.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/RealtimeCubeSinkTest.java
cdap-common/src/main/java/co/cask/cdap/common/utils/Tasks.java
cdap-examples/WikipediaPipeline/src/test/java/co/cask/cdap/examples/wikipedia/WikipediaPipelineAppTest.java
cdap-notifications/src/test/java/co/cask/cdap/notifications/NotificationTest.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppUsingGetServiceURL.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

The issue is that a program could stop 'RUNNING' (go into 'STOPPING') state, but the run record for it being stopped hasn't been written yet.
So, retry for up to 5 seconds for the stopped run record.
Also had a Tasks#waitFor with a default retry interval of 50 milliseconds, since it is a commonly used value.
https://issues.cask.co/browse/CDAP-4210
http://builds.cask.co/browse/CDAP-DUT3110-2

Fix flaky testTrameworkTest#runTestAppWithPlugin

---

pom.xml

Trying to build CDAP on a machine without 0.6.3-SNAPSHOT already in maven cache will have this issue:
`[ERROR] Failed to execute goal on project cdap-api: Could not resolve dependencies for project co.cask.cdap:cdap-api:jar:3.3.0-SNAPSHOT: Could not find artifact co.cask.tephra:tephra-api:jar:0.6.3-SNAPSHOT in sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]`
since 0.6.3 was recently released.
http://builds.cask.co/browse/CDAP-DUT3115-1

Bump tephra version from '0.6.3-SNAPSHOT' to '0.6.3'

---

cdap-docs/developers-manual/source/building-blocks/services.rst
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/fileset-example.rst
cdap-docs/included-applications/build.sh
cdap-examples/FileSetExample/src/main/java/co/cask/cdap/examples/fileset/FileSetService.java

- also fixes a bunch of other doc includes (broken MD5 hashes)
- also adds logging a warning in the FileSetService if the dataset can't be instantiated

Updates FileSetExample to use CLI and to explain HttpContentConsumer

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/ObjectMappedTable.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/ObjectStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/ObjectMappedTableDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/ObjectMappedTableDatasetTest.java

Adds the version of getSplits that takes a number of splits and
start and end keys to ObjectStore and ObjectMappedTable.
ObjectStoreDataset already implements it, just didn't have it in
the interface.

CDAP-4209 add getSplits method to ObjectStore and ObjectMappedTable

---

cdap-app-templates/cdap-data-quality/src/main/java/co/cask/cdap/dq/DataQualityApp.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchSourceContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLBatchApplication.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLWorkflow.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/BatchCubeSinkTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/BatchETLDBTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLBatchTestSuite.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLSnapshotTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLStreamConversionTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduceTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceRuntimeContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceSinkContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceSourceContext.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/S3AvroBatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/S3BatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/S3ParquetBatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/SinkOutputFormatProvider.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/DBSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/FileBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/SnapshotFileBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/SourceInputFormatProvider.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/TimePartitionedFileSetDatasetAvroSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/TimePartitionedFileSetDatasetParquetSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/TimePartitionedFileSetSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/common/db/ETLDBInputFormat.java

- Remove usage of BatchContext.getHadoopJob
- Also move MapReduce classes under "mapreduce" package

Added BatchSourceContext.setInput(InputFormatProvider)

---

cdap-api/src/main/java/co/cask/cdap/api/app/AbstractApplication.java
cdap-api/src/main/java/co/cask/cdap/api/schedule/Schedule.java
cdap-api/src/main/java/co/cask/cdap/api/schedule/Schedules.java
cdap-api/src/main/java/co/cask/cdap/internal/schedule/TimeSchedule.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithMultipleScheduledWorkflows.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithSchedule.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithStreamSizeSchedule.java
cdap-app-fabric/src/test/java/co/cask/cdap/ConcurrentWorkflowApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/ScheduleAppWithMissingWorkflow.java
cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowSchedulesWithSameNameApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/ScheduleSpecificationCodecTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-app-templates/cdap-data-quality/src/main/java/co/cask/cdap/dq/DataQualityApp.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLBatchApplication.java
cdap-client-tests/src/main/java/co/cask/cdap/client/app/FakeApp.java
cdap-docs/developers-manual/source/building-blocks/schedules.rst
cdap-docs/developers-manual/source/building-blocks/workflows.rst
cdap-docs/examples-manual/build.sh
cdap-examples/StreamConversion/src/main/java/co/cask/cdap/examples/streamconversion/StreamConversionApp.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/ScheduleSpecificationCodec.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithSchedule.java

removing the static creation methods in Schedules in favor of the
builder that was recently added. Also removing usage of those
methods in the codebase.
Also removing schedule methods that have been deprecated since 2.8.0.

CDAP-4217 deprecate static schedule creation methods

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionFilter.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionedFileSet.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionConsumer.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetTest.java

PartititionedFileSet#consumePartitions should support a limit and partition filter.
In order to support a limit and filter, the scanner on the partitions table has to be scanned during the consumePartitions call, in order for the appropriate PartitionConsumerState to be returned.
Previously, an iterator was returned that lazily did the scanning.
Note:
This PR contains the changes to PartitionedFileSetDataset as well as test cases to test it.
Exposing this functionality to the user (via a PartitionConsumer class to be used from a worker or mapreduce) is not in this PR.
https://issues.cask.co/browse/CDAP-3102
https://issues.cask.co/browse/CDAP-3103
http://builds.cask.co/browse/CDAP-DUT3109-2

PartititionedFileSet#consumePartitions should support a limit and partition filter

---

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/CacheConfig.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/LookupTableConfig.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/transform/CachingLookup.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/transform/ScriptLookup.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/transform/ScriptLookupProvider.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/etl/transform/CachingLookupTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/etl/transform/ScriptTransformTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
cdap-docs/included-applications/source/etl/plugins/transforms/script.rst
cdap-docs/included-applications/source/etl/plugins/transforms/scriptfilter.rst

https://issues.cask.co/browse/CDAP-4180
* Add 'cache' property to LookupTableConfig
* If 'cache' property is present, caching is enabled, and ScriptLookup wraps its Lookup delegate in a CachingLookup instance
* CachingLookup uses Guava's LoadingCache/CacheBuilder to provide caching mechanisms. It uses expireAfterWrite and maximumSize. Both are configurable using the 'cache' property.

CDAP-4180: Caching for lookup

---

cdap-docs/admin-manual/source/installation/installation.rst
cdap-docs/admin-manual/source/installation/quick-start.rst

Fixes two very minor typos, one of which is causing an included paragraph of text to not be included correctly.

Fix typos.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetInputFormat.java

This is because the sdk does not include hbase, so we need to
use cdap's Bytes class, which is functionally the same.

CDAP-4245 use cdap's Bytes instead of hbase's Bytes

---

cdap-api/src/main/java/co/cask/cdap/api/artifact/ArtifactVersion.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/api/artifact/ArtifactVersionTest.java

Fixing a bug in version parsing where the version for a string
like test1-1.0-SNAPSHOT gets parsed as 1-1.0-SNAPSHOT instead of
1.0-SNAPSHOT.

CDAP-4240 fix version parse bug when name ends with a number

---

cdap-ui/app/features/hydrator/controllers/detail/tabs/metrics-ctrl.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-runs-store.js

- Fixes batch metrics to use mapreduce run id instead of workflow runid.
Bamboo Build: http://builds.cask.co/browse/CDAP-DRC2941-1

Fixes batch metrics to take up mapreduce runid instead of workflow

---

cdap-ui/app/directives/tooltip-toggle/tooltip-toggle.js
cdap-ui/app/features/dashboard/style.less
cdap-ui/app/features/dashboard/templates/dashboard.html
cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-input-schema.html

*  Adds tooltip-ellipsis directive to watch for when dashboard title length exceeds parent element length
*  Fixes issue where long dashboard titles would cause tab's dropdown caret not to display

fixes dashboard tab styling issues

---

cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/tutorials/wise.rst

Running at [Quick Build](http://builds.cask.co/browse/CDAP-DOB44-2).
Fixes MD5 hashes and adjusts the inclusion of the WiseApp files based on the changes recently made.

Fix inclusion of WiseApp.

---

cdap-data-fabric-tests/pom.xml
cdap-data-fabric/pom.xml
cdap-hbase-compat-0.94/pom.xml
cdap-hbase-compat-0.96/pom.xml
cdap-hbase-compat-0.98/pom.xml
cdap-security/pom.xml
pom.xml

Background:
* Repository.continuuity.com hosts hbase-94.6.1 compiled against hadoop-2 which is needed to support versions 2.8.x - 3.0.x
* We wanted to remove the dependency on repository.continuuity.com 
Solution:
* Moved the hbase-0.94.6.1 jars to maven central under co.cask.hbase and updated the version to 0.94.6.1.cask (from 0.94.6.1.continuuity)
* Updated the pom with required changes
Tests:
* Build passes: https://builds.cask.co/browse/CDAP-RB3010-4
* Also able to create a cluster with hbase-0.94.6.1 from the feature branch.

Remove dependency on repository.continuuity.com

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java

Since the tags actually will be stored as comma delimited strings, when searching
for one of the tags doing both prefix and keyword match will not work well
if an entity has more than one tags.
Assume a program has tags: tag1,tag2,tag3 then search on tags:tag2 will not yield
any result nor search on tags:tag2*.
Need to add special handling for searching tags for key:value format.

Fix the metadata search on tags.

---

cdap-docs/developers-manual/source/building-blocks/artifacts.rst
cdap-docs/developers-manual/source/building-blocks/plugins.rst
cdap-docs/included-applications/source/etl/custom.rst

Fix for issue https://issues.cask.co/browse/CDAP-4292
Documentation should clearly specify the difference between system and user artifacts for Hydrator plugins.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB49-2)
- [Developers' Manual: Building Blocks… Plugins](http://builds.cask.co/artifact/CDAP-DOB49/shared/build-2/Docs-HTML/3.2.1/en/developers-manual/building-blocks/plugins.html#plugin-deployment)
- [Developers' Manual: Building Blocks… Artifacts](http://builds.cask.co/artifact/CDAP-DOB49/shared/build-2/Docs-HTML/3.2.1/en/developers-manual/building-blocks/artifacts.html)
- [Included Applications: Creating Custom ETL Plugins…](http://builds.cask.co/artifact/CDAP-DOB49/shared/build-2/Docs-HTML/3.2.1/en/included-applications/etl/custom.html#plugin-packaging-and-deployment)

CDAP-4292 Documentation to clearly specify the difference between system and user artifacts

---

cdap-docs/build.sh

Fixes a problem where any messages that occurred in the Sphinx build of the outer-most layer of the docs don't get surfaced to the end of the log and to Bamboo.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB45-1).

Add consolidation of outer-level messages.

---

cdap-ui/app/features/hydrator/controllers/create/toppanel-ctrl.js
cdap-ui/app/features/hydrator/services/canvas-factory.js
cdap-ui/app/features/hydrator/services/create/stores/config-store.js

- Fixes the way we generate config to be saved to backend.
- Right now generates the nodes (config) in the order of their connection. This is to ensure that artifact version 3.2 will be usable in 3.3 UI.

Fixes config generated to be saved with backend:

---

cdap-distributions/src/packer/scripts/lxde.sh

There's an xterm in the startup, designed to show the user the `welcome.txt` file. It was never intended on being used as a terminal. It doesn't support copy and paste in a way that Windows/Mac users understand. This gets rid of it from starting up.

Remove xterm from VM session, caused confusion

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduceTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ETLStage.java

https://github.com/caskdata/cdap/pull/4573 - kept the old constructors as we had to keep few old fields for backward compatibility, since they can be inferred during deserialization without constructor, removing them as they are not needed.

removing unwanted constructor as the fields can be inferred during deserialization

---

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/EntityValidator.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java
cdap-common/src/main/java/co/cask/cdap/common/ViewNotFoundException.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/KeyHelper.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsValueKey.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/BusinessMetadataDatasetTest.java
cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/NamespacedIdCodec.java
cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchTargetType.java

- Adds support for metadata to stream view
- Adds createOrUpdateView in AppFabricTestBase since currently a view cannot be created in an app spec and can only be created through StreamAdmin or HTTP calls. 
- Fixes an issue in metadata for artifact to make search work and adds a test for it.
Build: http://builds.cask.co/browse/CDAP-DUT3190-1

CDAP 4263: Add metadata support to stream view

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactMeta.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/GetArtifactPropertiesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/LoadArtifactCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/SetArtifactPropertiesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ArtifactCommands.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ArtifactClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java
cdap-common/src/main/java/co/cask/cdap/common/conf/ArtifactConfig.java
cdap-common/src/main/java/co/cask/cdap/common/conf/ArtifactConfigReader.java
cdap-common/src/test/java/co/cask/cdap/common/conf/ArtifactConfigReaderTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactInfo.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java

Added properties to an artifact. Properties are stored along with
other data about an artifact. Properties can be added to or deleted
from using the RESTful API. Also adding corresponding methods
to the ArtifactClient and CLI.
https://issues.cask.co/browse/CDAP-4289

CDAP-4289 adding ability to set properties on an artifact

---

cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

- Fix TestFrameworkTestRun#testServiceManager() by waiting for running run record to get written
- Also checked that there are no assertions made in this class program status without waiting/retrying on it.
Caused failure of this build: http://builds.cask.co/browse/CDAP-DUT3190-2
Issue: https://issues.cask.co/browse/CDAP-4306
Build running (Should wait for 3 consecutive build pass for this case before merge): http://builds.cask.co/browse/CDAP-DUT3200-2

CDAP-4306 fix TestFrameworkTestRun#testServiceManager() flaky test

---

BUILD.rst
cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/resources/cdap-etl-lib-batch-source.json
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/resources/cdap-etl-lib-batch.json
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/resources/cdap-etl-lib-realtime.json
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/resources/cdap-etl-lib.json
cdap-master/pom.xml
cdap-standalone/pom.xml

Adding a property that will allow the build to copy additional
artifacts into the artifacts directory. This can be used to
include artifacts from other projects that we want to be included
as system artifacts. For example, we plan on including various
hydrator plugins that may come from different repositories.
Also simplifying etl lib build to only create a single jar, since
the three it was creating before were exactly the same except for
their manifests.

CDAP-4226 enhance build to optionally copy additional artifacts

---

BUILD.rst
cdap-docs/_common/common-build.sh

Fix broken Doc Build.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB56-1)

Correct formatting of Build.rst and adjusts MD5 hash.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java

Plan is to - 
1. Disable the test case on the develop.
2. Refactor to use larger frequency (15-30 seconds) of the schedule instead of 1 second.
3. Have at least 10 successful builds on the branch.
4. Merge it to the develop again.

CDAP-3696 Ignore the flaky test case.

---

cdap-docs/developers-manual/source/building-blocks/plugins.rst
cdap-docs/reference-manual/source/http-restful-api/artifact.rst

Add "Artifact-Versions" header. Corrected spelling in both files.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB57-1)
Page Of Interest: [Developers' Manual: Building Block: Plugins](http://builds.cask.co/artifact/CDAP-DOB57/shared/build-1/Docs-HTML/3.3.0-SNAPSHOT/en/developers-manual/building-blocks/plugins.html#third-party-plugins)
Fix for https://issues.cask.co/browse/CDAP-4124

CDAP-4124 Document passing in the artifact version in the header for adding artifacts

---

cdap-docs/admin-manual/source/operations/tx-maintenance.rst

Adds documentation of the Queue Debugger Tool to the Transaction Maintenance page.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB55-3. [Updated to Build 3]
Page Of Interest:
- [Operations: Transactions Maintenance](http://builds.cask.co/artifact/CDAP-DOB55/shared/build-3/Docs-HTML/3.3.0-SNAPSHOT/en/admin-manual/operations/tx-maintenance.html)

CDAP-3611 Documenting Queue Debugger Tool

---

cdap-docs/admin-manual/source/index.rst

[Passes Quick Build](http://builds.cask.co/browse/CDAP-DOB62-2)
Fixes a link that was pointing to "Installation" when it should have been to "Operations," and adds a missing link.

Fix incorrect link.

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java
cdap-client-tests/src/test/java/co/cask/cdap/client/MetaClientAvailableTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/MetaClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/MetaClient.java

https://issues.cask.co/browse/CDAP-4316
http://builds.cask.co/browse/CDAP-DUT3212
New CLI behavior:
```
cdap-cli.sh
Successfully connected to CDAP instance at http://hostname:10000/default
cdap (http://hostname:10000/namespace:default)>
cdap-cli.sh -u localhost:9999
CDAP instance at 'http://localhost:9999/default' could not be reached: Unexpected response body.
```

CDAP-4316: CDAP CLI should not connect successfully if given a wrong IP and port

---

cdap-common/src/main/java/co/cask/cdap/common/namespace/DefaultNamespacedLocationFactory.java
cdap-common/src/main/java/co/cask/cdap/common/namespace/InMemoryNamespaceClient.java
cdap-common/src/main/java/co/cask/cdap/common/namespace/NamespacedLocationFactory.java
cdap-common/src/test/java/co/cask/cdap/common/namespace/DefaultNamespacedLocationFactoryTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSStreamFileJanitorTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/LocalStreamFileJanitorTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamFileJanitorTestBase.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/DFSStreamHeartbeatsTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamFileJanitor.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamFileJanitorService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamServiceRuntimeModule.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/StreamHandlerRunnable.java

The approach is to use namespace client to list namespaces, and only scan directories for existing namespaces (instead of all directories under the `../data/namespaces/` directory).
Note that this changes the Stream Janitor to now have a dependency on app-fabric (namespace service).
https://issues.cask.co/browse/CDAP-4247
http://builds.cask.co/browse/CDAP-DUT3143-5

CDAP-4247 .DS_Store files should be ignored

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DFSStreamFileJanitorTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/InMemoryNamespaceStore.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/LocalStreamFileJanitorTest.java

Example of failing test case: http://builds.cask.co/browse/CDAP-DUT3185-7
https://issues.cask.co/browse/CDAP-4346
http://builds.cask.co/browse/CDAP-DUT3262-2

Use in-memory NamespaceStore implementation for test cases.

---

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ArtifactSelector.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ArtifactSelectorConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelineRegisterer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/Plugin.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/ArtifactSelectorConfigTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/ArtifactSelectorTest.java

Adding configuration settings to the etl apps that will select
a plugin's artifact using scope, name, and/or version settings
provided by the user. The app will choose the first artifact
that matches all of the given artifact settings. If scope,
name, or version is not given, the app will not try to match
that field. If no match is found, an exception is thrown and the
app is not created.

CDAP-4228 add ability to select plugin artifact in etl apps

---

cdap-ui/app/directives/metadata-tags/metadata-tags.html
cdap-ui/app/directives/metadata-tags/metadata-tags.js
cdap-ui/app/directives/metadata-tags/metadata-tags.less
cdap-ui/app/features/apps/templates/detail.html
cdap-ui/app/features/datasets/templates/detail.html
cdap-ui/app/features/flows/templates/detail.html
cdap-ui/app/features/mapreduce/templates/detail.html
cdap-ui/app/features/services/templates/detail.html
cdap-ui/app/features/spark/templates/detail.html
cdap-ui/app/features/streams/templates/detail.html
cdap-ui/app/features/workers/templates/detail.html
cdap-ui/app/features/workflows/templates/detail.html

*  Adds show more/show less functionality to metadata tags (5 displayed by default, show more displays all tags and show less limits display to 5)
*  Adds ng-blur event to add metadata input (input is now removed from display on blur)
*  Adds link to filtered results view

adds show more/less functionality to metadata tags

---

cdap-ui/app/features/apps/applications.less
cdap-ui/app/features/apps/templates/detail.html
cdap-ui/app/features/datasets/datasets.less
cdap-ui/app/features/datasets/templates/detail.html
cdap-ui/app/features/flows/flows.less
cdap-ui/app/features/flows/templates/detail.html
cdap-ui/app/features/mapreduce/mapreduce.less
cdap-ui/app/features/mapreduce/templates/detail.html
cdap-ui/app/features/services/services.less
cdap-ui/app/features/services/templates/detail.html
cdap-ui/app/features/spark/spark.less
cdap-ui/app/features/spark/templates/detail.html
cdap-ui/app/features/streams/streams.less
cdap-ui/app/features/streams/templates/detail.html
cdap-ui/app/features/workers/templates/detail.html
cdap-ui/app/features/workers/workers.less
cdap-ui/app/features/workflows/templates/detail.html
cdap-ui/app/features/workflows/workflow.less
cdap-ui/app/styles/common.less
cdap-ui/app/styles/themes/cdap.less

*  Moves "Type: X" to icon tooltip
*  Consolidates styling of elements inside class="type-block"
data views:
app views:

cleans up data/apps detail overview heading

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetWithCustomActionApp.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

check for tx-aware in workflow driver; 
modify test case to use non-tx-aware

[CDAP-4278] fix cast exception in custom action if dataset is not tx-aware

---

cdap-ui/app/features/hydrator/controllers/detail/top-panel-ctrl.js
cdap-ui/app/features/hydrator/services/detail/actions/pipeline-detail-actions.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-runs-store.js
cdap-ui/app/services/hydrator/my-pipeline-detailed-common-api.js

- Fixes last run duration & last run time
- Fixes next runtime from REQUEST to POLL to update as soon as new value comes in.
Right now there is a latency in updating the last run's time and duration but this is because /runs end point in the backend doesn't update the status immediately. Ideally this should only be few seconds.

Fixes hydrator detailed (batch) - Poll for next run time + fixes lastrun duration

---

cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetWithCustomActionApp.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

- the fix was already implemented in the dynamic dataset feature
- this makes the test use a file set instead of another table, to test non-tx-aware dataset injection

[CDAP-4385] port test case from 3.2 to develop

---

cdap-docs/_common/common_conf.py
cdap-docs/admin-manual/build.sh
cdap-docs/build.sh
cdap-docs/included-applications/build.sh

Fixes the Doc build in develop: passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB64-1)
Adds support for processing Markdown files if ``recommonmark`` has been installed.

Fix doc build; add md support to Sphinx build

---

cdap-app-templates/cdap-etl/cdap-etl-common/src/main/java/co/cask/cdap/etl/common/HiveSchemaConverter.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/SnapshotFileBatchParquetSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/sink/TimePartitionedFileSetDatasetParquetSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/SnapshotFileBatchParquetSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/etl/batch/source/TimePartitionedFileSetDatasetParquetSource.java

Also renamed.
Build : http://builds.cask.co/browse/CDAP-DUT3270-1

Move SchemaConverter from etl-lib to etl-common

---

cdap-common/bin/common.sh

This causes the script to fail on a Hive error, informing the user of the failed command.
https://issues.cask.co/browse/CDAP-4006

CDAP-4006 Fail gracefully on Hive error

---

cdap-data-fabric-tests/pom.xml
cdap-data-fabric/pom.xml
cdap-hbase-compat-0.94/pom.xml
cdap-hbase-compat-0.96/pom.xml
cdap-hbase-compat-0.98/pom.xml
cdap-security/pom.xml
pom.xml

Cherry-picking a commit that was merged against release/3.0:
https://github.com/caskdata/cdap/pull/4559
https://issues.cask.co/browse/CDAP-4368
http://builds.cask.co/browse/CDAP-RBTKEY281-1

Update pom for hbase-0.94 dependency

---

cdap-master/pom.xml
cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseTableExporter.java

JIRA: https://issues.cask.co/browse/CDAP-3701
`HBaseTableExporter` utility allows user to dump the content of the HBase table into HFiles. The HFiles generated can be later bulk loaded into the existing table with the same schema.
```java
Usage: /opt/cdap/master/bin/svc-master run co.cask.cdap.data.tools.HBaseTableExporter <tablename>
Args:
tablename    Name of the table to copy
```
Migration process using the `HBaseTableExporter` utility:
1. Run the tool with the name of the table which need to be migrated.
`/opt/cdap/master/bin/svc-master run co.cask.cdap.data.tools.HBaseTableExporter ns1.mytable`
2. Tool will output the HDFS location where HFiles will be located.
`Export operation complete. HFiles are stored at location hdfs://<cluster-name>/user/root/hbasetableexporter/4017075518899339 …

CDAP-3701 Version1 of the tool that allows exporting data in the HBase to HFiles which later can be used for bulk upload.

---

cdap-api/src/main/java/co/cask/cdap/api/Resources.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/config/ETLBatchConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/Connection.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ETLConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ETLStage.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/Plugin.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/realtime/config/ETLRealtimeConfig.java
cdap-app-templates/cdap-etl/cdap-etl-tools/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/UpgradeTool.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/config/OldETLBatchConfig.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/config/OldETLConfig.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/config/OldETLRealtimeConfig.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/config/OldETLStage.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/resources/etl.properties
cdap-app-templates/cdap-etl/cdap-etl-tools/src/test/java/co/cask/cdap/etl/tool/config/OldETLBatchConfigTest.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/test/java/co/cask/cdap/etl/tool/config/OldETLRealtimeConfigTest.java
cdap-app-templates/cdap-etl/pom.xml
cdap-docs/cdap-apps/source/hydrator/overview.rst
cdap-master/pom.xml
pom.xml

The 3.3.x versions of the etl applications are backwards
incompatible with the 3.2.x versions. The upgrade tool offers
a way to upgrade all pipelines, all pipelines in a namespace,
or a specific pipeline. Also offers a way to take a request that
could have been used to create a 3.2.x pipeline and convert it
into a request to create a 3.3.x pipeline.

CDAP-4225 added an upgrade tool for Hydrator

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/DefaultEmitter.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TransformDetail.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TransformExecutor.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TransformResponse.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/TransformExecutorTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java

based on the comments on this PR : https://github.com/caskdata/cdap/pull/4613
we decided to address the TransformDetail refactoring in TransformExecutor in a separate PR
build : http://builds.cask.co/browse/CDAP-DUT3291-1

CDAP-4232 minor refactor for TransformExecutor

---

cdap-app-templates/cdap-data-quality/src/main/java/co/cask/cdap/dq/MapReducePipelineConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/StageConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/DefaultPipelineConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/DefaultStageConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelineRegisterer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/PipelineRegistererTest.java

configuring pipeline with a sorted order and configuring the pipeline with appropriate input schemas for validating schema during configuring a pipeline. 
JIRA : https://issues.cask.co/browse/CDAP-4229
Build : http://builds.cask.co/browse/CDAP-DUT3287-1

CDAP-4229 output schema propagation

---

cdap-api/src/main/java/co/cask/cdap/api/data/DatasetContext.java
cdap-api/src/main/java/co/cask/cdap/api/data/DatasetProvider.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ClientSparkContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionSparkContext.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetCache.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/MultiThreadDatasetCache.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/SingleThreadDatasetCache.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/cache/DynamicDatasetCacheTest.java
cdap-docs/developers-manual/source/building-blocks/datasets/index.rst
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/fileset-example.rst
cdap-examples/FileSetExample/src/main/java/co/cask/cdap/examples/fileset/FileSetService.java

Please read https://issues.cask.co/browse/CDAP-4338 before review (note: branch name incorrectly has 4388). 
- removes the weak values configuration from the dataset cache, along with all the code to support that
- adds a new API DatasetProvider. It will replace DatasetContext in the future and has additional methods to explicitly release/dismiss a dataset that is no longer used
- all program contexts now implement DatasetProvider
- modified one example (FileSetExample) that uses dynamic datasets, to dismiss its service's datasets after use, and extended the test case to make repeated calls to the service.
- still pending: documentation changes to document the new behavior and API method. I will do that in its own commit so that it can be reviewed on its own
Docs Build: …

[CDAP 4338] Do not expire datasets based on GC's weak references; introduce a new API dismissDataset()

---

cdap-docs/_common/common-build.sh
cdap-docs/examples-manual/build.sh
cdap-docs/reference-manual/source/release-notes.rst

- Ports a change from 3.3.0 to help with determination of the correct branch when building the docs.
- Fixes documentation build (update MD5 hash after checking file).
- Adds release notes for 3.2.2.
Passes [Quick Build #2](http://builds.cask.co/browse/CDAP-DOB68-2). 
[Release Notes](http://builds.cask.co/artifact/CDAP-DOB68/shared/build-2/Docs-HTML/3.2.2/en/reference-manual/release-notes.html#release-3-2-2)

Release 3.2.2 Documentation changes

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json

Otherwise, we run out of memory attempting to fill the Maven cache. This is for the old VM build, which uses artifacts from Maven Central, exclusively.

Increase VM memory earlier

---

cdap-docs/examples-manual/source/examples/wikipedia-data-pipeline.rst

Fix for https://issues.cask.co/browse/CDAP-4402
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB70-2)
[Wikipedia Data Pipeline Example](http://builds.cask.co/artifact/CDAP-DOB70/shared/build-2/Docs-HTML/3.3.0-SNAPSHOT/en/examples-manual/examples/wikipedia-data-pipeline.html#deploying-the-example): compare with [current](http://docs.cask.co/cdap/3.3.0-SNAPSHOT/en/examples-manual/examples/wikipedia-data-pipeline.html#deploying-the-example) page

CDAP-4402 Remove hard-coded versions in an example

---

cdap-ui/app/features/admin/admin.less
cdap-ui/app/features/admin/templates/system/configuration.html

*  Removes unnecessary .div-responsive class from around table
*  Adds a fixed table layout and word-breaking to prevent table columns from becoming unevenly distributed
*  Tested in Safari, Chrome, and Firefox

fixes table layout issue affecting bg-color in safari

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java

- refactoring DatasetInstanceHandler to throw BadRequestException if the JSON is invalid, or if an ID is invalid, etc. 
- removed duplicate logging
- moved logging to after validation has happened
- added test case for all kinds of bad requests.

[CDAP-2360] fix internal errors in DatasetInstanceHandler for bad requests

---

cdap-ui/app/directives/navbar-hydrator/namespace.html
cdap-ui/app/directives/navbar-hydrator/navbar.html
cdap-ui/app/directives/navbar-hydrator/navbar.js
cdap-ui/app/directives/navbar-hydrator/navbar.less

*  Adds more consistent styling to the dropdown toggle (open vs. closed)
*  Changes display limit to 32 character in dropdown menu and 12 characters for displayed namespace
*  Limits number of displayed namespaces to 10, after which a vertical scroll is used

fixes namespace dropdown styling

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/SingleThreadDatasetCache.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/cache/DynamicDatasetCacheTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/cache/MultiThreadDatasetCacheTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/cache/TestDataset.java

Root cause of the problem was that the test uses system properties to implement some checks. Concurrent threads sometimes clashed on setting the same property. 
Secondary issue was that these threads might fail but that does not fail the test case. That failure would have made the actual issue a lot clearer. Added additional checks to make sure the test fails early in that case.

[CDAP-4423] fix the flaky MultiThreadDatasetCacheTest.java

---

cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
cdap-proto/src/test/java/co/cask/cdap/proto/IdTest.java

https://issues.cask.co/browse/CDAP-4277
http://builds.cask.co/browse/CDAP-RBT528

CDAP-4277: Id should not serialize toString and hashCode fields

---

cdap-data-fabric/src/test/java/co/cask/cdap/data/hbase/HBaseTestBase.java

Summary: configure port 0 for all the HBase ports instead of using Networks.getRandomPort(). I have tested this on my laptop, and I have run the test case 4 times concurrently. It works. I am not sure why we did not use port 0 before as that is the standard way to obtain a random free port. Perhaps older HBase versions did not work that way.

Bugfix: [CDAP-3824] flaky HBaseTableTest

---

cdap-distributions/bin/build_parcel.sh

Updates the parcel build script to use ``PARCEL_VERSION`` environment variable if set.  It still checks that all included CDAP components are of the same version, and still defaults to that detected version if ``PARCEL_VERSION`` is not set.  This allows for custom release-candidate versions, etc.

add ability to override parcel version

---

cdap-ui/app/features/admin/controllers/namespace/templates-ctrl.js
cdap-ui/app/features/hydrator/controllers/create/partials/nodeconfig-ctrl.js
cdap-ui/app/features/hydrator/services/plugin-config-factory.js

- Modifies the way we generate the key while fetching a config for a plugin. (pluginname-plugintype) (eg: ```http://127.0.0.1:10000/v3/namespaces/default/artifacts/mongodb-plugins/versions/1.2.0-SNAPSHOT/properties?scope=system&keys=widgets.MongoDB-batchsink```)
- Handles the case where ```output``` array has a schema property but that property is not from backend. If thats the case we don't show the output schema for a sink and default the input schema to output schema for source and transform.
This PR is dependent on this one - https://github.com/caskdata/hydrator-plugins/pull/75. We should merge this once that is merged.

Modifies the key (json file name) that needs to be generated to fetch the config json for a plugin

---

cdap-common/bin/common.sh

Fixes syntax error from https://github.com/caskdata/cdap/pull/4750.
```
Alis-MacBook-Pro-2:cdap alianwar$ bash cdap-common/bin/common.sh
cdap-common/bin/common.sh: line 48: syntax error near unexpected token `;;'
cdap-common/bin/common.sh: line 48: `    die "Cannot locate xmllint, are XML tools installed?" ;;'
```
Relevant: http://stackoverflow.com/questions/16905183/dash-double-semicolon-syntax

CDAP-4444 Make xmllint dependency optional

---

cdap-ui/app/directives/error/error-popover.html
cdap-ui/app/directives/error/error-template.html
cdap-ui/app/directives/error/error.less

*  Notification icon (fa-bolt) now displays regardless of errors
*  Changes badge color from green to red
*  Adds default message if there are no errors
*  Hides Clear All button if there are no errors

adds correct badge color + no errors message

---

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/log/LogStageAppender.java

Without this, the original root appenders will never be stopped,
and the program will hang on shutdown. This is because we will
have a KafkaAppender from Twill that will not shutdown its
scheduler or zk and kafka services.

CDAP-4429 override appender stop to stop delegates as well

---

cdap-ui/app/features/search/routes.js

*  Breadcrumbs label for search now always displayed as "Search Results"

adds correct search results breadcrumb label

---

cdap-docs/cdap-apps/source/hydrator/plugins/third-party.rst

Corrects four errors in the "Using Third-Party JARs" example; the contents of the *type* and *name* fields were all incorrectly shown; they must be lowercase, and with no spaces as they are specific identifiers.
Changed the order of the fields to match the other examples in the documentation.

Fix third-party example

---

cdap-ui/app/directives/search/search-ctrl.js
cdap-ui/app/directives/search/search.html
cdap-ui/app/directives/search/search.less

*  Keeps search bar open if user has entered text and then mouses away
*  Search bar now opens from the search icon and closes toward it

fixes search style transitions on hover/active

---

cdap-ui/app/directives/dag/my-dag-ctrl.js
cdap-ui/app/directives/my-popover/my-popover.js
cdap-ui/app/features/apps/controllers/tabs/status-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail/canvas-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail/tabs/pipeline-config-tab-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail/tabs/status-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail/top-panel-ctrl.js
cdap-ui/app/features/hydrator/controllers/list-ctrl.js
cdap-ui/app/features/hydrator/routes.js
cdap-ui/app/features/hydrator/services/create/actions/config-actions.js
cdap-ui/app/features/hydrator/services/create/stores/config-store.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-nonruns-store.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-runs-store.js
cdap-ui/app/features/hydrator/templates/detail/tabs/configuration.html
cdap-ui/app/main.js

- Fixes pipeline drafts to be namespace'd
- Adds ```engine``` attribute to the configuration for batch pipeline
- Fixes clone behavior in hydrator detailed view
- Minor cleanup with modals & popovers while leaving state.

Feature/ui fix hydrator clone+spark mapreduce engines

---

cdap-ui/app/directives/dag/my-dag.less

*  Fixes border issue on selected nodes when canvas is zoomed
Chrome:
Safari:
Firefox:

fixes node border issue on canvas zoom

---

cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh

Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB77-1)

Fix Broken Doc Build: Correct case and text of descriptions; updated MD5 hash.

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/SecurityAuthenticationHttpHandler.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/MockAccessTokenTransfomer.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/MockTokenValidator.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/NettyRouterPipelineAuthTest.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/NettyRouterPipelineTest.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterResource.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/ServerResource.java

- introduces a new router configuration, specifying a regex. If the the regex matches the path of a request, then the router will skip authentication
- refactors the existing netty pipeline test
- adds a new test case to test auth and the new bypass option
- Jira: https://issues.cask.co/browse/CDAP-4323
- Build: http://builds.cask.co/browse/CDAP-RBT545

[CDAP-4323] Allow a configuration to bypass access token validation for certain paths

---

cdap-ui/app/features/hydrator/bottompanel.less

*  Fixes helper class name so that .config-table can calculate viewport height
Chrome:
Safari:
Firefox:

adds correct helper class for table height calculation

---

cdap-ui/app/directives/dag/my-dag-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail/tabs/metrics-ctrl.js
cdap-ui/app/features/hydrator/services/detail/actions/pipeline-detail-actions.js
cdap-ui/app/features/hydrator/services/detail/actions/pipeline-detail-metrics-actions.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-metrics-store.js

Root cause: We are polling for the available metrics, and then inside the callback, we start polling for the values again, but only retaining 1 poll-id for the values. So when the stop-poll happen, it only stop the latest values poll, not the previous polls.

[CDAP-4475] Fix Hydrator Metrics Issue

---

cdap-common/bin/common.sh
cdap-common/bin/service

Fixing init scripts so that only the master service tries to set
the explore classpath, instead of all cdap services.
Also tweaking the set hive classpath function to print the
contents of stderr for the hive command when it fails so that the
user has some idea of what went wrong.

CDAP-4539 only set hive classpath for master service

---

cdap-docs/examples-manual/source/examples/wikipedia-data-pipeline.rst
cdap-examples/WikipediaPipeline/src/main/java/co/cask/cdap/examples/wikipedia/WikipediaPipelineWorkflow.java

Fixes the Wikipedia Pipeline example (https://issues.cask.co/browse/CDAP-4472):
- corrects the instructions that had incorrect paths
- clarifies accompanying text
- highlights important concepts
Passes [Quick Build #2](http://builds.cask.co/browse/CDAP-DOB76-2)
Running [CDAP Build](http://builds.cask.co/browse/CDAP-DUT3365-1)

CDAP-4472 Fix Wikipedia Pipeline example.

---

cdap-api/src/main/java/co/cask/cdap/api/flow/FlowletDefinition.java
cdap-api/src/main/java/co/cask/cdap/internal/flow/DefaultFlowletConfigurer.java

We grab the PropertyFields in ``FlowletDefinition`` class. So we don't have to do it twice for Flowlets.
JIRA : https://issues.cask.co/browse/CDAP-4508
Build : http://builds.cask.co/browse/CDAP-RBT547

CDAP-4508 Extract Property fields only once in Flowlet

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh

Removed yarn.user from cdap-default.xml and from Constants.java
since it is unused in the code. Also tried setting it in the conf
to verify that it doesn't do anything.
Other than that, all other constants are unused in the code and
not in cdap-default.xml.

removing unused constants

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ProgramClientTestRun.java

The issue is that a program could stop 'RUNNING' (go into 'STOPPING') state, but the run record for it being stopped hasn't been written yet.
So, retry for up to 5 seconds for the stopped run record.
Note - the fix is similar to as in https://github.com/caskdata/cdap/pull/4506.
One failing test case is: http://builds.cask.co/browse/CDAP-RBT-JOB1-999/test/case/31581011
Other failing test case is: http://builds.cask.co/browse/CDAP-RBT-JOB1-974/test/case/990418
Build for this PR: http://builds.cask.co/browse/CDAP-RBT558-2

Fix WorkflowHttpHandlerTest#testWorkflowToken - flaky test case.

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/ElementType.java

http://builds.cask.co/browse/CDAP-RBT555-1
Workflow logs retrieval wasn't supported in CDAP CLI previously. It now looks like this:

support workflow log retrieval in CDAP CLI

---

cdap-integration-test/README.rst
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java

I tried to run the integration tests cases against a cluster running SSL, but wasn't able to because IntegrationTestBase always had `verifySSL` as true.
http://builds.cask.co/browse/CDAP-DUT3336-2

Allow disabling verification of SSL certs in integration tests.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java

The issue is that a program could go into 'RUNNING' state, but the run record for it being stopped hasn't been updated yet.
So, retry for up to 5 seconds for the expected run record.
Note - the fix is similar to as in https://github.com/caskdata/cdap/pull/4506.
Failing test case which this should fix: http://builds.cask.co/browse/CDAP-RBT548-JOB1-4/test/case/37752036
Build for this PR: http://builds.cask.co/browse/CDAP-RBT560-1

Fix WorkflowHttpHandlerTest#testWorkflowForkApp

---

cdap-common/src/main/java/co/cask/cdap/common/twill/LocalLocation.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/MultiLiveStreamFileReaderTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/file/LiveFileReader.java

- Instead of returning zero events when reading an empty partition
(which is a valid behavior of LiveFileReader, as it requires caller
to keep calling the read() method),
it will try to advance to the next event file and try reading
events from it.

(CDAP-4545) Improve LiveFileReader to read more efficiently

---

cdap-ui/app/services/data/my-cdap-datasource.js
cdap-ui/app/services/settings.js

- Fixes fetching data from user store (adds API token to the header).
- Fixes MyCDAPDatasource's (request, poll & config) calls to use success and errorCallback if available (callback vs promise versions)
This PR is related to this PR (https://github.com/caskdata/ng-capsules/pull/39) Please don't merge before ng-capsules PR is merged.

Fixes mySettings factory to have API token when authentication is enabled

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json
cdap-distributions/src/packer/cdap-sdk-ubuntu12.json

Use latest IntelliJ as VM builds are failing with:
```
06-Jan-2016 01:25:05	    cdap-sdk-vm: [2016-01-06T01:31:15+00:00] ERROR: remote_file[/var/chef/cache/ideaIC-14.1.4.tar.gz] (idea::default line 37) had an error: Net::HTTPServerException: 403 "Forbidden"
```
Files are on S3, so cannot browse directory.

Use IntelliJ 15.0.2

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ScheduleClientTestRun.java

Summary: Check if the trigger is paused and if not return the next scheduled fire time for that trigger.
JIRA : https://issues.cask.co/browse/CDAP-4397
Build : http://builds.cask.co/browse/CDAP-RBT563

CDAP-4397 NextRunTime endpoint should not return any time if the triggers are paused

---

cdap-ui/package.json

Note: This is cherrypicked from https://github.com/caskdata/cdap/pull/4837.
Because of a change in package `main-bower-files` that was released yesterday, the cdap-ui build no longer works. Issue is described in detail in the JIRA linked below.
http://builds.cask.co/browse/CDAP-RBT566-1
https://issues.cask.co/browse/CDAP-4559

Fix main-bower-files version to 2.11.0

---

cdap-common/bin/common.sh
cdap-ui/bin/config-tool

The `config-tool` script in the CDAP UI uses a function from `common.sh` which was missed in #4712

Fix config-tool after changes from #4712

---

cdap-common/bin/common.sh
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/java/co/cask/cdap/common/startup/Check.java
cdap-common/src/main/java/co/cask/cdap/common/startup/CheckRunner.java
cdap-common/src/main/java/co/cask/cdap/common/startup/ConfigurationLogger.java
cdap-common/src/main/resources/cdap-default.xml
cdap-common/src/test/java/co/cask/cdap/common/startup/CheckRunnerTest.java
cdap-common/src/test/java/co/cask/cdap/common/startup/check/NoOpCheck.java
cdap-common/src/test/java/co/cask/cdap/common/startup/check/fail/AlwaysFailCheck.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DatasetTypeManager.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterTwillApplication.java
cdap-master/src/main/java/co/cask/cdap/master/startup/AbstractMasterCheck.java
cdap-master/src/main/java/co/cask/cdap/master/startup/ConfigurationCheck.java
cdap-master/src/main/java/co/cask/cdap/master/startup/FileSystemCheck.java
cdap-master/src/main/java/co/cask/cdap/master/startup/HBaseCheck.java
cdap-master/src/main/java/co/cask/cdap/master/startup/ServiceResourceKeys.java
cdap-master/src/main/java/co/cask/cdap/master/startup/YarnCheck.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/kafka/KafkaNotificationService.java
cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java

adding some sanity checks on master startup to make sure hdfs,
yarn, and hbase are available before starting up the master.
If any are not, master will shut down. Also adding a config
setting to turn off these checks in case there is any faulty
logic, or in case this behavior is not desired and we want to
start up anyway and just wait for those systems to come up.

CDAP-4536 check infrastructure on master startup

---

cdap-common/bin/service

changed the status command to always print the status instead of
only printing if the service is running

CDAP-4526 always print service status

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/java/co/cask/cdap/common/service/UnloggedExceptionIdleService.java
cdap-common/src/main/resources/cdap-default.xml
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricDistributedModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricInMemoryModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricLevelDBModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/LocalDatasetOpExecutor.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/RemoteDatasetOpExecutor.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/YarnDatasetOpExecutor.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/MDSDatasetsRegistry.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DatasetTypeManager.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/tx/TransactionalDatasetRegistry.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/DelegatingTransactionSystemClientService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/DistributedTransactionSystemClientService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/TransactionSystemClientService.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/AbstractNotificationService.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/inmemory/InMemoryNotificationService.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/kafka/KafkaNotificationService.java

changes to services to wait for the transaction service or
dataset op serivces to be up while they are starting.
This is to improve the user experience so that they dont see
a flurry of errors in the log when the master first starts up.

CDAP-4522 wait for tx service to be available on startup

---

cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst
cdap-docs/examples-manual/source/examples/data-cleansing.rst

Updating the existing documentation, regarding how to use `PartitionBatchInput` in place of `BatchPartitionConsumer` (the latter did not support concurrent runs of the MR job).
https://issues.cask.co/browse/CDAP-4319

CDAP-4319 Update docs for partition consumer changes.

---

cdap-common/bin/service
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
cdap-master/src/main/java/co/cask/cdap/master/startup/MasterStartupTool.java

Moving startup checks from MasterServiceMain to its own class so
that they are run in a separate command. This is so we can call
it separately in the init script. This will make it so that a
startup failure will cause the init scripts to exit with a failure,
rather than having the scripts exist with a success, then have the
master fail soon after.

CDAP-4566 separate startup checks and run by init scripts

---

cdap-app-fabric/pom.xml
cdap-app-fabric/src/main/java/co/cask/cdap/hive/ExploreUtils.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/security/TokenSecureStoreUpdater.java
cdap-app-fabric/src/main/java/co/cask/cdap/security/hive/HiveTokenUtils.java
cdap-app-fabric/src/main/java/co/cask/cdap/security/hive/JobHistoryServerTokenUtils.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java

- Move HiveTokenUtils and JobHistoryServerTokenUtils and some helper method to app-fabric
- Make Hive tokens available to all program runners
Build: http://builds.cask.co/browse/CDAP-DUT3315-1
Issue: https://issues.cask.co/browse/CDAP-4421

[CDAP-4421] Provide Hive tokens to twill containers

---

cdap-common/bin/service
cdap-common/src/main/java/co/cask/cdap/common/startup/CheckRunner.java

fixing a problem with the startup check runner when the classpath
contains empty entries and the tool is run from the root directory.
In those cases, the working directory, which is the root directory,
gets added as a uri for the url classloader, which will cause
ClassPath to scan the entire filesystem.

CDAP-4581 protect against root directory in url classloader

---

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java

JIRA: https://issues.cask.co/browse/CDAP-3964
During initialization of the `StandAloneMain` or the `MasterServiceMain`, we first attempt to clear the tmp directory. If the directory is not present we see the following exception in the log file - 
```java
2015-10-09 01:05:29,127 - DEBUG [main:c.c.c.d.r.m.MasterServiceMain@429] - Failed to cleanup temp directory /var/tmp/cdap/data/tmp
java.io.IOException: Not a directory: /var/tmp/cdap/data/tmp
at co.cask.cdap.common.utils.DirUtils.deleteDirectoryContents(DirUtils.java:61) ~[co.cask.cdap.cdap-common-3.2.0.jar:na]
at co.cask.cdap.data.runtime.main.MasterServiceMain.cleanupTempDir(MasterServiceMain.java:426) [co.cask.cdap.cdap-master-3.2.0.jar:na]
at co.cask.cdap.data.runtime.main.MasterServiceMain.init(MasterServiceMain.java:172) …
```

CDAP-3964 Check if the tmp directory is present before attempting to delete it.

---

cdap-ui/app/directives/dag/my-dag.html
cdap-ui/app/directives/dag/my-dag.less
cdap-ui/app/directives/group-side-panel/group-side-panel.less
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js
cdap-ui/app/features/hydrator/bottompanel.less
cdap-ui/app/features/hydrator/controllers/create/canvas-ctrl.js
cdap-ui/app/features/hydrator/controllers/create/leftpanel-ctrl.js
cdap-ui/app/features/hydrator/controllers/create/partials/nodeconfig-ctrl.js
cdap-ui/app/features/hydrator/services/create/actions/config-actions.js
cdap-ui/app/features/hydrator/services/create/stores/config-store.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-nodeconfig-store.js
cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-nonruns-store.js
cdap-ui/app/features/hydrator/services/hydrator-service.js
cdap-ui/app/features/hydrator/services/plugin-config-factory.js
cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-form.html
cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-input-schema.html
cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-output-schema.html

- ~~Right now the schema propagation doesn't work for implicit schemas. The reason being, the first node have to be opened up to fetch the ui config from node proxy to get the implicit schema. And this happens only when we connect all the nodes and just click on schema icons on the edges without opening any node (I am assuming that if people have already used a plugin, say Twitter, and they know that it has an implicit schema and expect that to propagate automatically without even opening the node).~~
- We fetch the properties and node config for a node as soon as its added to the canvas. So now we have this information and whenever we encounter an implicit schema down the line we stop the propagation there for that particular path.
- We need to re-word the confirmation message we show …

Fixes schema propagation while creating a hydrator pipeline

---

cdap-docs/admin-manual/source/security.rst

Title says it all. Tested the provided example in a secure cluster. 
Jira: https://issues.cask.co/browse/CDAP-4534
Build (docs only, no code change): http://builds.cask.co/browse/CDAP-DOB82

[CDAP-4534] document router auth exemptions

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/java/co/cask/cdap/common/guice/TwillModule.java
cdap-common/src/main/resources/cdap-default.xml
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java

turn off streaming app logs to the master log by default. It can
still be turned back on through configuration, but the default
behavior should not be to include app logs.

CDAP-4548 remove app logs from the master log

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java

https://issues.cask.co/browse/CDAP-3816
http://builds.cask.co/browse/CDAP-RBT588-2
When not specifying the status, it individually applies the limit and adds the run records together.
Instead, the limit value passed in should be an upper limit over all the run records.

CDAP-3816 Correctly apply limit on run record retrieval.

---

cdap-ui/app/features/hydrator/services/hydrator-service.js

Fixes the case where when the user adds the same node twice, the icon of the second (or subsequent nodes) gets defaulted to ```fa-plugin``` icon instead of appropriate node's icon.

Fixes node icons when we add same node multiple times

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultPluginConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/Specifications.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryConfigurator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/mapreduce/DefaultMapReduceConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/DefaultHttpServiceHandlerConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/DefaultServiceConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/spark/DefaultSparkConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/worker/DefaultWorkerConfigurer.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/ScheduleSpecificationCodecTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/ConfiguratorTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java

Fix a bug where users in one namespace could see plugins from
another namespace when using a system application artifact.
To fix this, when deploying an app, we need to pass down the
namespace the app will be in to filter out plugin artifacts from
other namespaces. Most of the changes revolve around passing
namespace to the configurers that require it.

CDAP-4294 namespace isolation for system artifact plugins

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java

this is to try and stupid proof against users who set an
InputFormatProvider or OutputFormatProvider that has the format
class set to one thing, but then sets
"mapreduce.job.outputformat.class" or "mapreduce.job.inputformat.class"
to something else in its configuration settings.

CDAP-4619 set inputformat and outputformat class after config settings

---

cdap-api-common/src/main/java/co/cask/cdap/api/data/format/FormatSpecification.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationManager.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/AllProgramsApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/runtime/OpenCloseDataSetTest.java
cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/view/ViewAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AppSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ArtifactSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ProgramSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/StreamSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ViewSystemMetadataWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchTargetType.java

(CDAP-4264) Add system metadata for all CDAP entities. 
(CDAP-4269) Added REST REST APIs to query system metadata by setting the 'scope' query parameter to 'system'.
(CDAP-4265) (CDAP-4266) (CDAP-4267) (CDAP-4268) Added the ability to add/update/delete system metadata for artifacts, apps, programs, datasets, streams and views.
Build: http://builds.cask.co/browse/CDAP-RBT592
Jiras:
[CDAP-4264](https://issues.cask.co/browse/CDAP-4264)
[CDAP-4265](https://issues.cask.co/browse/CDAP-4265)
[CDAP-4266](https://issues.cask.co/browse/CDAP-4266)
[CDAP-4267](https://issues.cask.co/browse/CDAP-4267)
[CDAP-4268](https://issues.cask.co/browse/CDAP-4268)
[CDAP-4269](https://issues.cask.co/browse/CDAP-4269)
This PR is based off of #4884, which has already been reviewed. Please only review the second …

(CDAP-4264) Added system metadata for all CDAP entities

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLEmailActionTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLMapReduceTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLSparkTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/config/ETLBatchConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ETLConfig.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ETLStage.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/realtime/config/ETLRealtimeConfig.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java

Adds a configuration setting for the resources for the
mapreduce or spark driver for etl batch pipelines. Since this
requires adding yet another constructor, took this opportunity to
add builders for the configs.

CDAP-4629 add setting for driver resources to etl batch

---

cdap-formats/src/main/java/co/cask/cdap/format/RecordPutTransformer.java
cdap-formats/src/test/java/co/cask/cdap/format/RecordPutTransformerTest.java

RecordPutTransformer class needs to support nullable schema because plugins such as TableSink support null schema and they use RecordPutTransformer.
http://builds.cask.co/browse/CDAP-RBT599-1

Update RecordPutTransformer to work with a null schema.

---

cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh

Re-ordered properties alphabetically, removed extra capital letters, updated MD5 hash.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB86-1).

Fix cdap-defaults.xml

---

cdap-ui/app/directives/error/error-popover.html
cdap-ui/app/directives/error/error.less
cdap-ui/app/directives/schedules-view/schedules-view.html
cdap-ui/app/directives/schedules-view/schedules-view.js
cdap-ui/app/directives/schedules-view/schedules-view.less
cdap-ui/app/directives/start-stop-button/start-stop-button.js
cdap-ui/app/features/hydrator/adapters.less
cdap-ui/app/features/hydrator/controllers/create-ctrl.js
cdap-ui/app/features/hydrator/controllers/detail/top-panel-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/schedule-ctrl.js
cdap-ui/app/features/workflows/templates/tabs/schedules.html
cdap-ui/app/index.html
cdap-ui/app/main.js
cdap-ui/app/services/app-uploader.js
cdap-ui/app/styles/common.less
cdap-ui/app/styles/themes/cdap/theme.less
cdap-ui/app/styles/variables.less

*  Removes 3 sec duration for program operation errors (alert message now persists until user dismisses it by clicking "X")
*  Adds new styling and positioning of these alerts (including workflow schedules modal)
*  Adjusts styling of "x" in the alert notification center to be consistent with the new alert styles
TO DO:
-  [x] Add new error ribbon styling to import pipeline 
-  [x] Add new error ribbon styling to custom app uploaded (currently, errors are sent to global notification popover)
Custom app upload error:
import pipeline error:
error in CDAP:
error within modal:

updates styling and duration of error alert banners

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTest.java
cdap-app-fabric/src/test/resources/cdap-site.xml
cdap-client-tests/src/test/java/co/cask/cdap/client/QueryClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/common/ClientTestBase.java
cdap-data-fabric-tests/src/test/resources/cdap-site.xml
cdap-data-fabric/src/test/resources/cdap-site.xml
cdap-standalone/pom.xml
cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java

The build time was significantly increased by this PR: https://github.com/caskdata/cdap/pull/4859
Disable explore in cdap-app-fabric, cdap-data-fabric, cdap-data-fabric-tests to reduce build time.
http://builds.cask.co/browse/CDAP-RBT605-4

Reduce build time by disabling explore

---

cdap-distributions/bin/build_parcel_repo.sh

This is similar to `build_apt_repo.sh` or `build_yum_repo.sh` and creates a `manifest.json` which can be used in our builds to create a Parcel repository. This prefers use of our new Ruby port of `make_manifest.py` and checks for its presence. If missing, it assumes it can run `make_manifest.py` from the PATH.

Script to build Parcel repo from artifacts/existing repo

---

cdap-data-fabric/src/main/java/co/cask/cdap/hbase/wd/RowKeyDistributorByHashPrefix.java
cdap-data-fabric/src/test/java/co/cask/cdap/hbase/wd/RowKeyDistributorTestBase.java

Tests get speed up from 300 seconds to 25 seconds.

Speed up unit-tests by using local MR instead of forking new processes

---

cdap-docs/developers-manual/source/getting-started/standalone/docker.rst

Docker link to install is incorrect in documentation. (It may have been accurate in the past).

Fix docker download link

---

cdap-standalone/bin/cdap.bat

The current bat script had a bug which did not allow node versions 0.10.x, though the error message says it is allowed.
Related: https://github.com/caskdata/cdap/pull/4492

Allow node versions 0.10.x

---

cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.js

hide delimiters on keyvalue and also use the new pattern for dropdown

fix widget-keyvalue properties

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java

Revert a change made in this PR : https://github.com/caskdata/cdap/pull/4762
Specifically, this line : https://github.com/caskdata/cdap/pull/4762/files#diff-f25334a1ec822e775c2aaf25f10ed04cR479
This change is causing failure in the integration tests since the streamId#getId returns just the streamName while streamId#toString returns stream:ns.streamname. This change was not made in other places where ``ResourceRequirement.Partition`` is created. Also ``DistributedStreamService#StreamsLeaderHandler`` is expecting PartitionReplica to be of the format : stream:ns.streamname.
Build : http://builds.cask.co/browse/CDAP-RBT610-2

Fix ITN failure

---

cdap-ui/app/features/hydrator/leftpanel.less
cdap-ui/app/polyfill.js

*  Adjusts widths of .plugin-item and child `<span>` containing label name to ensure proper 2 column width across all builds
SDK:
VM:

fixes plugin item widths to ensure 2 column layout

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java

[Andreas] The upgrade tool is too confusing. It is completely unclear why after creating the MetadataDataset instance with the oldColumnsToIndex properties in the in-memory dsFramework, we have to provide those same properties again when we call getOrCreateDataset(). It should already exist at that time and the properties should be ignored. Can't explain this. 
Other than that LGTM. If you test this and you can validate it is correct, all good. And we have to simplify the UpgradeTool in the next release. [end Andreas]

Delete rows from index table when deleting MetadataDataset entries

---

cdap-ui/app/directives/app-level-loading-icon/loading.js
cdap-ui/app/services/service-status-factory.js
cdap-ui/app/services/status-factory.js

Steps to reproduce the original issue,
- Stop cdap-master
- Stop cdap-router
The UI always shows 'Service(s) are offline' message and would never update the UI even when the services back online.
The current fix checks for services and show appropriate messages when master or router services go down & constantly polls for the status of services & when back updates the UI appropriately.
Tested in both secure & un-secure. Works the same.

Fixes the use-case to show two different messages when cdap-master & cdap-router services goes down

---

cdap-ui/app/features/hydrator/bottompanel.less

*  Vertical aligns Node Config tab columns to the top to prevent bottom panel alignment of schema columns
Before:
After:

fixes issue where column content was bottom-aligned

---

cdap-distributions/bin/build_parcel_repo.sh

Previously, we were putting them under ${TARGET_DIR} rather than our temporary repository directory.

Put symlinks in correct location for repository

---

BUILD.rst

Running ``mvn package`` multiple times without a clean results in a failure in the CDAP parcel build. Adding it to other commands in the ``BUILD.rst`` as well.

Add clean to mvn package where it was missing in the build instructions

---

cdap-docs/cdap-apps/source/hydrator/index.rst
cdap-docs/cdap-apps/source/hydrator/overview.rst
cdap-docs/cdap-apps/source/hydrator/upgrade.rst

This will let us link directly to it from the CDAP upgrade docs
instead of linking to part of an overview page.

CDAP-4710 pulling hydrator upgrade out to its own section

---

cdap-master/pom.xml

Copying of additional artifacts needs to be in a phase that occurs
before the copy-deb-staging execution in deb-prepare. Otherwise
those additional artifacts will not be in the staging directory
when the copy occurs, and they will be missing in the debian.

CDAP-4709 copy artifacts should be an earlier phase

---

cdap-docs/cdap-apps/source/hydrator/custom.rst
cdap-docs/cdap-apps/source/hydrator/index.rst

The name of the branch can be ignored; this is to update the documentation on plugin configuration.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB92-1)
[Custom Page: Plugin Configuration JSON](http://builds.cask.co/artifact/CDAP-DOB92/shared/build-1/Docs-HTML/3.3.0/en/cdap-apps/hydrator/custom.html#plugin-configuration-json)

Updates for plugin configuration JSON documentation

---

cdap-common/src/main/java/co/cask/cdap/common/internal/guava/ClassPath.java
cdap-common/src/main/java/co/cask/cdap/common/lang/ProgramResources.java

- Loading the every resources from the class loader takes a lot of time
We don’t actually need to load it since during the discovery of
those resources, we already know the URLs

Speed up unit-test app deployment

---

cdap-examples/resources/weblog-analytics-config.json
cdap-examples/resources/weblog-analytics.txt
cdap-examples/resources/weblog-service.txt
cdap-ui/app/features/hydrator/controllers/create-ctrl.js
cdap-ui/package.json
cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json
cdap-ui/templates/apps/predefined/KafkaToHBase.json
cdap-ui/templates/apps/predefined/KafkaToOLAPCube.json
cdap-ui/templates/apps/predefined/KafkaToStream.json
cdap-ui/templates/apps/predefined/StreamToHBase.json
cdap-ui/templates/apps/predefined/TwitterToHBase.json
cdap-ui/templates/apps/predefined/TwitterToStream.json

Merging release into develop made '3.3.0' appear in some places.
This addresses that and bumps the version also, as appropriate.

Bump cdap and plugin versions

---

cdap-distributions/bin/build_apt_repo.sh
cdap-distributions/bin/build_parcel_repo.sh
cdap-distributions/bin/build_yum_repo.sh

This allows this script to be used with non-CDAP packages. The only requirement is that all versions match between all packages being processed.

Allow non-CDAP packages to use repo scripts

---

cdap-distributions/bin/build_yum_repo.sh

Fixes:
```
22-Jan-2016 21:48:56	ls: cannot access *.rpm: No such file or directory
22-Jan-2016 21:48:56	rpm: no arguments given for query
22-Jan-2016 21:48:56	Usage: grep [OPTION]... PATTERN [FILE]...
22-Jan-2016 21:48:56	Try `grep --help' for more information.
22-Jan-2016 21:48:56	ERROR: [Errno 32] Broken pipe
```

Check for RPM files in target directory

---

cdap-docs/admin-manual/source/operations/index.rst
cdap-docs/build.sh
cdap-docs/developers-manual/source/building-blocks/workflows.rst
cdap-docs/examples-manual/source/apps-packs.rst
cdap-docs/integrations/source/index.rst
cdap-docs/integrations/source/partners/cloudera/index.rst
cdap-docs/integrations/source/partners/cloudera/ingesting.rst

Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB94-2)
Fixes a number of broken links.
Removes an un-used line in the main build script that was generating an error message. We don't have any Markdown files in the main documentation build that we are copying (only in the cdap-apps manual), and attempting to copy any that weren't present causes an error...

Release 3.3.1: Fix broken links.

---

cdap-examples/pom.xml
cdap-unit-test/pom.xml

This change is so that other Spark programs can be run from unit test cases.
This change replaces the following two PRs (and so I closed them):
https://github.com/cdap-guides/cdap-spark-guide/pull/49
https://github.com/caskdata/cdap-apps/pull/103
http://builds.cask.co/browse/CDAP-RBT616-1

Move jersey dependency to unit test, for use by user spark programs.

---

cdap-docs/admin-manual/source/operations/index.rst
cdap-docs/build.sh
cdap-docs/developers-manual/source/building-blocks/workflows.rst
cdap-docs/examples-manual/source/apps-packs.rst
cdap-docs/integrations/source/index.rst
cdap-docs/integrations/source/partners/cloudera/index.rst
cdap-docs/integrations/source/partners/cloudera/ingesting.rst
cdap-ui/app/features/hydrator/services/plugin-config-factory.js
cdap-ui/app/features/hydrator/templates/create/popovers/plugin-edit-form.html
cdap-ui/app/services/constants.js

Merging release/3.3 into develop.
There were conflicts due to the version being bumped to 3.3.1 in release branch. I chose 'develop' (HEAD) for all of the following conflicts:
[conflicts.txt](https://github.com/caskdata/cdap/files/105495/conflicts.txt)

Merge release 3.3 into develop

---

cdap-ui/app/features/hydrator/services/detail/stores/pipeline-detail-nonruns-store.js

- Removes the assumption of output schema for stream plugin. This could be useful if the user creates the JSON from scratch and deploy it through backend and use the UI to view the pipeline.

Removes the assumption of an output schema for the stream plugin all the time

---

cdap-common/bin/common.sh

This is to ensure that cdap jars come earlier in the classpath
than twill jars, so that the patched ApplicationMasterMain from
cdap is used instead of the one from twill.

CDAP-4768 sort jars in master lib

---

cdap-docs/_common/highlevel_conf.py
cdap-docs/build.sh
cdap-docs/vars

Added a "docs-outer" target that builds only the outer docs. Speeds up debugging.
Fixed the cleanup of the Master index to correctly remove a file.
Add a function which defines the files to be removed, and included the "404" file in the list
of files to be removed from the index.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB96-1)
Compare:
- [Existing search for "release"](http://docs.cask.co/cdap/current/en/search.html?q=release&check_keywords=yes&area=default): second hit is the "404" page
- [New search for "release"](http://builds.cask.co/artifact/CDAP-DOB96/shared/build-1/Docs-HTML/3.3.1-SNAPSHOT/en/search.html?q=release&check_keywords=yes&area=default): "404" page is not in the results

Fix CDAP-4729: Remove "404" page from the index and returned results.

---

cdap-docs/admin-manual/source/hadoop-compatibility.rst

Added Spark dependency, re-organized the table alphabetically, and added additional notes.
Updated for Build 2:
- Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB97-2)
- Revised [Hadoop Compatibility page](http://builds.cask.co/artifact/CDAP-DOB97/shared/build-2/Docs-HTML/3.3.1-SNAPSHOT/en/admin-manual/hadoop-compatibility.html)
Fix for https://issues.cask.co/browse/CDAP-4257

CDAP-4257 Add supported versions of Spark

---

cdap-docs/examples-manual/source/examples/spark-page-rank.rst

Corrects the lines included from the example Java file showing the memory requirements and how to set them. It should be these two lines:
```
setDriverResources(new Resources(1024));
setExecutorResources(new Resources(1024));
```
Instead, by error, it was this one line:
```
ivate static final Gson GSON = new Gson();
```
Fixes https://issues.cask.co/browse/CDAP-4786
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB99-1)
Updated example page: [Spark Page Rank Example](http://builds.cask.co/artifact/CDAP-DOB99/shared/build-1/Docs-HTML/3.3.1-SNAPSHOT/en/examples-manual/examples/spark-page-rank.html#memory-requirements)
- [3.2.1 Version (correct)](http://docs.cask.co/cdap/3.2.1/en/examples-manual/examples/spark-page-rank.html#memory-requirements)
- [3.3.0 Version (with …

CDAP-4786 Correct inclusion in the Spark Page Rank Example

---

cdap-ui/app/directives/dag/my-dag.less

*  Modifies node transition property to fix flicking issue where node icons would go away for a fraction of time when clicking another node
Before:
After:
Decreased alert height:

changes transition property for nodes

---

cdap-common/src/main/java/co/cask/cdap/common/io/FileContextLocation.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/StorageProviderNamespaceAdmin.java

minor bug in if-else logic, as we were logging warning as namespace doesn't exists while namespace exists and deletion was successful. 
JIRA : https://issues.cask.co/browse/CDAP-4780

CDAP-4780 improve logging for namespace deletion

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java

https://issues.cask.co/browse/CDAP-4784
The issue is that `Table#get(row, columns)` returns all columns in HBase if the second parameter is an empty list. This is due to some discrepancy in the Table APIs (https://issues.cask.co/browse/CDAP-4790), which is a larger (more impactful) change to fix/clean up.
For now, avoid deleting the all the index columns if `colsToIndex` is empty.
**Note:** This can be a temporary fix (and can be reverted), depending on the resolution to CDAP-4790.
Build: http://builds.cask.co/browse/CDAP-RBT622-2

CDAP-4784 IndexedTable#put to avoid Table#get if colsToIndex is empty.

---

cdap-master/pom.xml

Copying of additional artifacts needs to be in a phase that occurs
before the copy-deb-staging execution in deb-prepare. Otherwise
those additional artifacts will not be in the staging directory
when the copy occurs, and they will be missing in the debian.
Note: This is the same PR as https://github.com/caskdata/cdap/pull/4986, but for some reason, the change was lost on develop.

CDAP-4709 copy artifacts should be an earlier phase.

---

cdap-docs/cdap-apps/build.sh

Change of case in hydrator repo breaking inclusion of a file.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB101-1)

Fix broken build.

---

cdap-docs/developers-manual/source/_includes/building-apps.txt
cdap-docs/developers-manual/source/_includes/windows-note.txt
cdap-docs/developers-manual/source/getting-started/building-apps.rst
cdap-docs/developers-manual/source/getting-started/standalone/docker.rst
cdap-docs/developers-manual/source/getting-started/standalone/index.rst
cdap-docs/developers-manual/source/getting-started/standalone/virtual-machine.rst
cdap-docs/developers-manual/source/getting-started/standalone/zip.rst
cdap-docs/developers-manual/source/getting-started/start-stop-cdap.rst

Adds a warning about not using a Windows JAVA_HOME with spaces in it.
Fix for https://issues.cask.co/browse/CDAP-3262
Passes [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB102-2)
Pages of Interest:
- [Getting Started: CDAP SDK](http://builds.cask.co/artifact/CDAP-DOB102/shared/build-2/Docs-HTML/3.3.1-SNAPSHOT/en/developers-manual/getting-started/standalone/index.html)
- [Getting Started: Starting and Stopping Standalone CDAP](http://builds.cask.co/artifact/CDAP-DOB102/shared/build-2/Docs-HTML/3.3.1-SNAPSHOT/en/developers-manual/getting-started/start-stop-cdap.html)
- [Getting Started: Building and Running CDAP Applications](http://builds.cask.co/artifact/CDAP-DOB102/shared/build-2/Docs-HTML/3.3.1-SNAPSHOT/en/developers-manual/getting-started/building-apps.html)
You can confirm that …

CDAP-3262 Adding a Windows warning message.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRangeTest.java
cdap-common/src/main/java/co/cask/cdap/common/conf/ArtifactConfigReader.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactRange.java

Error when a version range has a lower version that is equal to
the upper version, but the lower version is inclusive and the
upper is exclusive. Also fixing a unit test that was trying to
test for this scenario, but calling the wrong method.
Also a small change to the artifact config parser so that the
right error message is used in the above scenario.

CDAP-4800 handle edge case for version range

---

cdap-docs/cdap-apps/source/hydrator/creating.rst

Fixes two connection strings that were buried in literal text yet being formatted as links.
[Passes Quick Build](http://builds.cask.co/browse/CDAP-DOB104-1)
Original page: [CDAP Hydrator](http://docs.cask.co/cdap/current/en/cdap-apps/hydrator/creating.html)
Revised page: [CDAP Hydrator](http://builds.cask.co/artifact/CDAP-DOB104/shared/build-1/Docs-HTML/3.3.1-SNAPSHOT/en/cdap-apps/hydrator/creating.html#sample-application-configurations)

Mark connection strings so they don't format as links in HTML.

---

cdap-ui/app/features/hydrator/services/create/stores/config-store.js

Issue:
1. Create any pipeline
2. Add initial nodes and give it a name
3. Save it as a draft.
4. Don't leave the state and make more changes.
5. Rename the pipeline and save it as draft again.
During the 5th step UI creates another draft with the new name (different from the one created in step 3). We should not create 2 drafts at step 5. It should all go to the same one created in step 3.
Fix:
- Save draftId in config(state) during step 3 and make sure the user edits the same draft (no matter what changes).
- Update the URL with the draftId if it is newly generated.

Fixes saving draft in hydrator studio view

---

cdap-app-fabric/pom.xml
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/partitioned/DynamicPartitioningOutputFormat.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithMapReduceUsingAvroDynamicPartitioner.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/DynamicPartitionerWithAvroTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRunnerTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceWithPartitionedTest.java

DynamicPartitioner did not work with avro output formats. See the JIRA for more details.
The fix is a few-line change in DynamicPartitioningOutputFormat.java, and the remainder of the PR is test code.
The second commit is refactoring of test cases to not have code duplication.
https://issues.cask.co/browse/CDAP-4806
http://builds.cask.co/browse/CDAP-RBT627-3

DynamicPartitioner with Avro OutputFormat

---

cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/README.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/docs/Sink-batchsink.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/widgets/Sink-batchsink.json
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/README.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/docs/Source-batchsource.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/widgets/Source-batchsource.json
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/README.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/docs/Sink-realtimesink.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/widgets/Sink-realtimesink.json
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/README.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/docs/Source-realtimesource.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/widgets/Source-realtimesource.json
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/README.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/docs/MyTransform-transform.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/src/main/java/TransformPlugin.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/widgets/MyTransform-transform.json
cdap-app-templates/cdap-etl/cdap-etl-archetypes/pom.xml

add the build script used to create the deployment json for etl
plugins. This change will create the json file in the target
directory instead of forcing users to create it themselves. It
also introduces the docs and widgets directories that integrate
with the Hydrator UI to format plugin fields and provide reference
documentation.

CDAP-4723 add build improvements to plugin archetypes

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java

There's an invalid log message being printed - the literal `{}` is being printed, since the second parameter is a Throwable, instead of an object that is to be interpolated into the string.
Here's what it looked like:

Log the exception's message, instead of the entire thing.

---

cdap-common/src/main/resources/cdap-default.xml
cdap-distributions/src/etc/cdap/conf.dist/cdap-site.xml.example
cdap-docs/admin-manual/build.sh
cdap-docs/tools/cdap-default-exclusions.txt
cdap-docs/tools/cdap-xml-files.txt
cdap-docs/tools/doc-cdap-default.py
cdap-examples/Purchase/src/test/resources/cdap-site.xml
cdap-standalone/src/main/resources/cdap-site.xml

Addresses https://issues.cask.co/browse/CDAP-4803 (update description for app.artifact.dir)
Passes [Quick Build 6](http://builds.cask.co/browse/CDAP-DOB103-6)
Updates 
- cdap-common/src/main/resources/cdap-default.xml
- cdap-distributions/src/etc/cdap/conf.dist/cdap-site.xml.example
- cdap-examples/Purchase/src/test/resources/cdap-site.xml
- cdap-standalone/src/main/resources/cdap-site.xml
The Documentation Tool (cdap-docs/tools/doc-cdap-default.py) has a new option, "-a", that compares all the files or URLs listed in the file ``cdap-docs/tools/cdap-xml-files.txt`` against the default (cdap-default.xml) and publishes to standard out a report detailing any differences in the descriptions that it finds. It identified a number of properties that are only in the other sources, plus …

Fixes to cdap-defaults.xml

---

cdap-common/bin/common.sh
cdap-standalone/bin/cdap.sh

The `*` was making it so that the paths were being iterated over by bash, and by default, space character is a delimiter which splits it, so any path with a space in it was being interpreted as two separate paths.
Using the `find` command and then joining the paths by `:` works better for this.
Tested:

Fix CDAP SDK, when there are space(s) in the path.

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Previously DataSpec upgrade was called during upgrade_hbase step as well. 
JIRA: https://issues.cask.co/browse/CDAP-4889
Build: http://builds.cask.co/browse/CDAP-RBT630-1

CDAP-4889 DatasetSpecUpgrade should only be called during upgrade 

---

cdap-ui/app/directives/error/error.less

*  Adds black background color to alert badges in alert popover
*  Adds white text to success alerts in alert popover

changes my-error badge padding + background-color

---

cdap-distributions/bin/build_apt_repo.sh
cdap-distributions/bin/build_yum_repo.sh

fixes or relates to https://issues.cask.co/browse/CDAP-4805
We host repo definition files at the root of our Yum/Apt repos, ie http://repository.cask.co/centos/6/x86_64/cdap/3.3/cask.repo
This PR adds their creation to our build scripts.  It will need to be backported to all release branches

create yum/apt repo definition file for new repos

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

JIRA - https://issues.cask.co/browse/CDAP-4906
Build - http://builds.cask.co/browse/CDAP-RBT636-3
Note: Upgrade Tool logging needs to be fixed. Filed JIRA https://issues.cask.co/browse/CDAP-4912 for it.

CDAP-4906 Exiting with code 1 in Upgrade Tool on exception

---

cdap-common/bin/common.sh

This restores functionality to some internal tools that utilize symlinked ``lib`` directories.

follow symlinks when constructing CDAP classpath

---

cdap-ui/app/directives/navbar-hydrator/namespace.html
cdap-ui/app/directives/navbar-hydrator/navbar.html
cdap-ui/app/directives/navbar-hydrator/navbar.js
cdap-ui/app/directives/navbar-hydrator/navbar.less

Right now we show "No other namespaces" in Hydrator & just default namespace in the other. 
Related JIRA: https://issues.cask.co/browse/CDAP-4669

Fixes namespace dropdown to show only namespace

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTableTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java

Jira: https://issues.cask.co/browse/CDAP-4894
Tested on a secure cluster.

[CDAP-4894] make coprocessor jar locations path-only instead of full URIs

---

cdap-distributions/bin/build_parcel_repo.sh

backporting https://github.com/caskdata/cdap/pull/5075 to release/3.3, so that any future 3.3.x patch releases will include a centos7 parcel.

create an el7 parcel

---

cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreConnection.java

Changing set calls to only error when setting to invalid values.
For example, if we only support auto commit = true, setting auto
commit to true should not be an error. Similarly, calling commit
should not be an error. It doesn't do anything, so it should be
a no-op.

CDAP-4927 dont error when there is no error

---

cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/UpgradeTool.java

Fix a bug when the upgrade tool is told to only upgrade pipelines
but still tries to upgrade ui data.
The tool assumes that the ui data is in the 3.2.x format. This may
not be true, as the console store is not cleaned up or upgraded
in between cdap versions. This change moves ui data upgrade to the
end so that it does not interfere with upgrading pipelines, which
is more important. It also does not assume application names are
cdap-etl-batch or cdap-etl-realtime, since that is not the case
with really old ui data.
In general... that console store needs to be removed.

CDAP-4944 make hydrator upgrade more robust

---

cdap-docs/build.sh
cdap-docs/reference-manual/source/cli-api.rst

Updates the CDAP CLI documentation for the latest changes, in particular, metadata and lineage.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB112-1)
[CDAP CLI Documentation](http://builds.cask.co/artifact/CDAP-DOB112/shared/build-1/Docs-HTML/3.3.1-SNAPSHOT/en/reference-manual/cli-api.html)
Changes:
- The main segments of the command table are organized in alphabetical order
- minor edits have been to the text on that page, to be consistent with other CDAP docs
- a target (``docs-cli``) has been added to the ``build.sh`` script to build the documentation and write the output to a temp file. This is a first-step in the eventual automation of this.

Update CDAP CLI documentation

---

cdap-client/src/main/java/co/cask/cdap/client/config/ClientConfig.java

- Change upload timeouts in ClientConfig to 0 (unlimited)

CDAP-4951: Read timeout error when uploading large file to stream using CLI

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/RowColumns.java

In https://github.com/caskdata/cdap/pull/5108, a no-parameter `add` method was introduced for backwards compatibility. However, this is not needed, since users can not actually call any of the `add` methods without parameters. I had intended to remove it from that PR. I even mentioned that I removed it (https://github.com/caskdata/cdap/pull/5108#issuecomment-181659208), but didn't actually remove it. 
So, removing it now.
Revert "Add a deprecated, no-parameter add method for backwards compatability."
This reverts commit a97d9431c1b2e42109cd0adf332f1439be4351d8.
http://builds.cask.co/browse/CDAP-RBT633-12

Revert unintended new API.

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json

We had missed this when bumping versions most recently.

Update CDAP version in packer file.

---

cdap-docs/admin-manual/build.sh
cdap-docs/developers-manual/source/building-blocks/metadata-lineage.rst

Fix MD5 hash. Breaks an overly-long line.
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB116-1).

Documentation Fixes

---

cdap-api-common/src/main/java/co/cask/cdap/internal/io/SchemaTypeAdapter.java
cdap-common/src/test/java/co/cask/cdap/io/SchemaTest.java

The bug occurs when a record has a field of type record X,
and another field that uses record X as an inner field.
In such cases, the inner X is just a reference to the record name
instead of a full schema, which causes problems when trying to
create the schema for that field. The fix is to keep a global map
of all known record types instead of a map per record.

CDAP-4967 fix a schema parsing bug due to repeat inner records

---

cdap-common/src/main/java/co/cask/cdap/common/security/YarnTokenUtils.java
cdap-common/src/main/java/org/apache/twill/internal/yarn/Hadoop21YarnAppClient.java

- In YarnTokenUtils, cast the null parameter to resolve an ambiguous overloaded method
- An overloaded method ConverterUtils.convertFromYarn is added in Hadoop 2.4
- The YarnAppClient interface has changed in Twill 0.7.0, modify the copied Hadoop21YarnAppClient class accordingly

Resolve compilation error after merging release/3.3

---

cdap-docs/admin-manual/source/installation/cloudera.rst
cdap-docs/reference-manual/source/release-notes.rst

When was merged, it altered the existing text incorrectly. It moved text that applied to all the points of the Hadoop Configuration to apply to just the last point of the three points.
- Corrects text, indentation, and formatting of the Cloudera instructions.
- Corrects formatting of release notes.
Part of https://issues.cask.co/browse/CDAP-4547
Passes [Quick Build](http://builds.cask.co/browse/CDAP-DOB120-1).
Pages:
- [Cloudera Hadoop Configuration](http://builds.cask.co/artifact/CDAP-DOB120/shared/build-1/Docs-HTML/3.3.1/en/admin-manual/installation/cloudera.html#hadoop-configuration)
- [Release Notes 3.3.1](http://builds.cask.co/artifact/CDAP-DOB120/shared/build-1/Docs-HTML/3.3.1/en/reference-manual/release-notes.html#release-3-3-1)

CDAP-4547: Correct modified documentation.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunnerTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriterTestBase.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

- Longer timeout for SparkProgramRunnerTest and DFSConcurrentStreamWriterTest
- Attempt to eliminate race condition in deploy workflow test in TestFrameworkTestRun

Fix 3 flaky tests

---

cdap-distributions/src/hdinsight/cdap-conf.json

Configure ntp on the edgenode to use the same servers as ntp on the hdinsight cluster nodes.

update ntp configuration to point to same ntp servers as hdinsight

---

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java

- Making it not too verbose when Spark is not available in the cluster
**Not a critical fix and it doesn't affect any functionality at all.**

Catch IllegalStateException instead of IllegalArgumentException

---

cdap-docs/_common/_themes/cdap/layout.html
cdap-docs/_common/common-build.sh
cdap-docs/_common/common_conf.py
cdap-docs/build.sh

Add new Google Tag Manager code support, and remove old Google Analytics.
Removes some blank lines in the layout template that were making the header extra long.
Corrected formatting of the Amazon SQS comment tags.
Fix for https://issues.cask.co/browse/CDAP-5048.
Passes [Quick Build 4](http://builds.cask.co/browse/CDAP-DOB127-4).
You can see the results by looking at the source of [any of the pages](http://builds.cask.co/artifact/CDAP-DOB127/shared/build-4/Docs-HTML/3.3.2-SNAPSHOT/en/index.html).

CDAP-5048 Add doc support for Google Tag Manager

---

cdap-docs/admin-manual/source/_includes/installation/installation.txt
cdap-docs/admin-manual/source/cdap-components.rst
cdap-docs/reference-manual/source/cli-api.rst
cdap-docs/reference-manual/source/glossary.rst

Adds [CDAP CLI as an optional component for installation](http://builds.cask.co/artifact/CDAP-DOB126/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/admin-manual/cdap-components.html).
Added [installation instructions](http://builds.cask.co/artifact/CDAP-DOB126/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/admin-manual/installation/packages.html#installing-cdap-services).
Added [startup instructions to the CLI docs](http://builds.cask.co/artifact/CDAP-DOB126/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/cli-api.html).
Added [CLI glossary entries](http://builds.cask.co/artifact/CDAP-DOB126/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/glossary.html#term-command-line-interface).
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB126-1).
Fix for …

CDAP-4988: Documenting CDAP CLI in Distributed CDAP

---

cdap-ui/app/directives/explore/explore.js

Check for '.' in column name before splitting on it, because when specific columns are queried, the schema's column names are not prefixed by the dataset name.
The cause of the issue is described in more detail in the comments in the JIRA.
https://issues.cask.co/browse/CDAP-5036
Select *:
Select particular columns:

Explore preview - column names fix

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/app/UpdateAppCommand.java
cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java

Fix the update app command to use the same format for its input
file as the create app command. This will also let somebody use
the contents of a pipeline export directly rather than modifying
it first.

CDAP-5076 fix update app command

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/AbstractPartitionConsumer.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/ConcurrentPartitionConsumer.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/PartitionConsumer.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/TransactionalPartitionConsumer.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionConsumerTest.java

Expose an API to specify PartitionKeys (instead of Partition) when calling onFinish of a PartitionConsumer.
https://issues.cask.co/browse/CDAP-4977
http://builds.cask.co/browse/CDAP-DUT3605-2

Expose an API to specify PartitionKeys (instead of list of Partitions)

---

cdap-common/bin/common.sh

JIRA: https://issues.cask.co/browse/CDAP-5063

CDAP-5063 Updated command for setting the EXPLORE_CONF_FILES to ignore the conf.server directory.

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTestRun.java

Fixed a bug where the explore schema was not being used unless
the explore format was also being set. The explore schema should
always be used. It just happened to be the case that avro filesets
work with Hive without an explore schema because the schema can
be set through the avro.schema.literal table property.

CDAP-5094 always use explore schema if it exists

---

cdap-docs/developers-manual/source/building-blocks/workflows.rst

Passed [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB133-2).
Fix for https://issues.cask.co/browse/CDAP-4450.
[Revised Workflows page](http://builds.cask.co/artifact/CDAP-DOB133/shared/build-2/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/building-blocks/workflows.html#concurrent-workflows)

CDAP-4450 Update default to concurrent workflows

---

cdap-common/bin/common.sh
cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersionSpecificFactory.java

There aren't any HBase incompatibilities between CDH 5.5 and CDH 5.6, but our version-detection needs updating.
https://issues.cask.co/browse/CDAP-5134
http://builds.cask.co/browse/CDAP-RBT648-1

Support CDH 5.6, using the CDH 5.5 compat modules.

---

cdap-unit-test/pom.xml

Opening https://github.com/caskdata/cdap/pull/5223 against 3.3 release branch. See https://github.com/caskdata/cdap/pull/5223 for discussion.
Build - http://builds.cask.co/browse/CDAP-RBT649-1

Exclude asm from jersey-servlet

---

cdap-docs/integrations/source/jdbc.rst
cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreConnection.java
cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreConnectionParams.java
cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreDriver.java
cdap-explore-jdbc/src/main/java/co/cask/cdap/explore/jdbc/ExploreStatement.java
cdap-explore-jdbc/src/test/java/co/cask/cdap/explore/jdbc/ExploreConnectionParamsTest.java
cdap-explore-jdbc/src/test/java/co/cask/cdap/explore/jdbc/ExploreDriverTest.java

Added a 'fetch.size' connection setting that controls how big the
fetch size should be. Also increasing the default fetch size from
50 to 1000 to make the default value more performant.

CDAP-5062 make explore jdbc fetch size configurable

---

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
cdap-integration-test/src/test/java/co/cask/cdap/test/IntegrationTestBaseTest.java
cdap-integration-test/src/test/java/co/cask/cdap/test/TestApplication.java
cdap-integration-test/src/test/java/co/cask/cdap/test/TestFlow.java
cdap-integration-test/src/test/java/co/cask/cdap/test/TestFlowlet.java
cdap-test/src/main/java/co/cask/cdap/test/TestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/ApplicationManagerFactory.java

Changes made in TestManager to get ApplicationManager. This change is required for long running tests. Cherry-picked changes from #5200 .
release build: http://builds.cask.co/browse/CDAP-RBT650-1

Adding getApplicationManager() method to IntegrationTestBase

---

cdap-docs/admin-manual/source/cdap-components.rst
cdap-docs/developers-manual/source/advanced/application-logback.rst
cdap-docs/developers-manual/source/advanced/index.rst

- Fixes a broken link.
- Rewrites the "Application Logback" section to include useful links.
- Re-orders an index that did not match other content.
- Adds logging info to the CDAP components page.
Building [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB135-2).
- [Advanced Topics](http://builds.cask.co/artifact/CDAP-DOB135/shared/build-2/Docs-HTML/3.3.2-SNAPSHOT/en/developers-manual/advanced/index.html)
- [Application Logback](http://builds.cask.co/artifact/CDAP-DOB135/shared/build-2/Docs-HTML/3.3.2-SNAPSHOT/en/developers-manual/advanced/application-logback.html)
- [CDAP Components](http://builds.cask.co/artifact/CDAP-DOB135/shared/build-2/Docs-HTML/3.3.2-SNAPSHOT/en/admin-manual/cdap-components.html#admin-manual-cdap-components)

Fix broken links.

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/AbstractWorkflow.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
cdap-app-fabric/src/test/java/co/cask/cdap/GoodWorkflowApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/verification/WorkflowVerificationTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowSpecificationCodec.java

JIRA: https://issues.cask.co/browse/CDAP-5117
Following changes are done as a part of this PR:
1. Added `createLocalDataset` methods in the `WorkflowConfigurer` interface.
2. The local datasets are stored as a part of `WorkflowSpecification`.

CDAP-5117 Ability to create the local datasets inside the Workflow configure method.

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/DatasetSpecification.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/GetDatasetInstancePropertiesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DatasetCommands.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetType.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/file/FileSetDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceServiceTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
cdap-docs/admin-manual/build.sh
cdap-docs/reference-manual/source/cli-api.rst
cdap-docs/reference-manual/source/http-restful-api/dataset.rst

- stores the original properties in the dataset spec
- adds an endpoint and CLI command to retrieve them
- compatibility mode for datasets that were created pre-3.4
- unit tests
- documentation
Description: https://issues.cask.co/browse/CDAP-5182
Build: http://builds.cask.co/browse/CDAP-DUT3646
Docs Build: http://builds.cask.co/browse/CDAP-DOB140
Docs build failed initially due to a wrong MD5 hash that was not caused by this PR.

[cdap 5182] add a way to retrieve the original properties used to create/update a dataset

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/ProgramWorkflowRunnerFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDatasetFramework.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunnerFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/ForwardingDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/ForwardingProgramContextAwareDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowAppWithLocalDatasets.java

Following changes are implemented in this PR: 
1. Added implementation for creating and deleting the local datasets in the Workflow driver.
2. Using `ForwardingDatasetFramework` in the `WorkflowDriver` now which delegates the calls to the underlying dataset framework. It also maintains the mapping of the local dataset to the name assigned to them for the particular run of the Workflow which is of the form `datasetName.<workflow_run_id>`.
3. Passing the dataset name mapping to the `MapperWrapper` as well through the job configuration.
Spark related changes and deletion of the local datasets based on the the runtime argument will be done in separate PR.

CDAP-5117 Implementation for creating the local dataset instances and using them for MapReduce programs in the Workflow.

---

cdap-docs/_common/common_conf.py
cdap-docs/admin-manual/source/upgrading/cloudera.rst
cdap-docs/admin-manual/source/upgrading/packages.rst

Add version examples, and make current examples independent of the version.
Adds reST "replacements" for the "short version", "previous short version", and bold and literal versions of each.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB142-1).
Pages of Interest:
- [Upgrading CDAP with CM](http://builds.cask.co/artifact/CDAP-DOB142/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/admin-manual/upgrading/cloudera.html#admin-upgrading-cloudera)
- [Upgrading CDAP using Packages](http://builds.cask.co/artifact/CDAP-DOB142/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/admin-manual/upgrading/packages.html)

Improvement to Admin Documentation of upgrades: show examples of CDAP version

---

cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowAppWithLocalDatasets.java

JIRA: https://issues.cask.co/browse/CDAP-5117
The test case works as follows.
1. `WorkflowWithLocalDatasets` has two local datasets one is of type `FileSet` and another is `KeyValueTable`.
2. `LocalDatasetWriter` custom action in the Workflow writes a comma separated file to the local `FileSet` dataset.
3. Next runs the Spark program `JavaSparkCSVToSpaceConverter` which reads from the comma separated file and writes the file replacing comma by space.
4. This local fileset containing space separated file is read by the `WordCount` MapReduce program and counts the unique words, which is written to the local `KeyValueTable` dataset.
5. Finally custom action `LocalDatasetReader` runs which simply counts the unique words and write it to another non-local `KeyValueTable` dataset.

CDAP-5117 Added Spark stage in the test case for the Workflow local datasets.

---

cdap-api-spark/src/main/java/co/cask/cdap/api/spark/JavaSparkExecutionContext.java
cdap-api-spark/src/main/scala/co/cask/cdap/api/spark/SparkExecutionContext.scala
cdap-spark-core/src/test/java/co/cask/cdap/app/runtime/spark/SparkTransactionServiceTest.java

- Direct dataset access inside closure doesn’t fit well in Spark execution model
- Spark is meant to be functional, hence doing side-effect writes is not well defined
- We want to provide read-only access to dataset, but that requires enhancement to the underlying DatasetFramework, which will be in future work.
- Also added a unit-test for SparkTransactionService to test transaction failure

(CDAP-5085) Removed the getDataset method from SparkExecutionContext

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowAppWithLocalDatasets.java

JIRA: https://issues.cask.co/browse/CDAP-5117
`WorkflowDriver` before deleting the local dataset checks the `dataset.<dataset_name>.keep.local` runtime argument.

CDAP-5117 Implementation to keep the local datasets based in the input runtime arguments.

---

cdap-ui/app/styles/themes/cdap/theme.less

*  Changes positioning of alert close button to ensure it's always fully displayed in the alert ribbon
Local build:
VM Build (3.3.1 snapshot):

fixes alert close button positioning/visibility

---

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/Dag.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpec.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpecGenerator.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/StageConnections.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/TrackedPluginSelector.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/MockPluginConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/DagTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/spec/PipelineSpecGeneratorTest.java

Extracts some of the logic in the
PipelineRegisterer into a Dag class which can be used to check
for cycles, linearize, etc. This class will be enhanced next to
include methods to help with pipeline planning.
Also uses the Dag class to validate the user provided ETLConfig and
generate a PipelineSpec.  The spec contains all information needed
to plan the pipeline execution.

CDAP-5186 add dag class to prepare for hydrator planner

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/CompositeFinisher.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/Finisher.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/TransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/SinkOutput.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSparkProgram.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/Constants.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelineRegisterer.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java

ETLMapReduce is in dire need of cleanup so that we can more easily
modify it in the future. This takes a pass
at removing unneccessary logic, consolidating common logic,
removing warnings, and other general cleanup.
Consolidated onRunFinish logic that was happening in both spark
and mapreduce, which now both use the CompositeFinisher to avoid
special logic for sources and special logic for sinks and for
maintaining state about source, sinks, and their contexts.
Consolidated logic for creating a TransformExecutor into the
TransformExecutorFactory class, which should also help a good
deal when we need to create an executor in both the mapper and the
reducer.

CDAP-5146 refactoring and cleanup to prepare for new plugin types

---

cdap-ui/app/directives/dag/my-dag.html
cdap-ui/app/features/hydrator/services/non-store-pipeline-error-factory.js

*  Removes node ID from DAG display in scenarios when node label is empty
*  Increases error count if node label is left blank
*  Adds condition to check for multiple empty node labels (as they shouldn't be treated as duplicates)

removes nodeId / increases errorCount when node label is empty

---

BUILD.rst
cdap-authorization-dataset-plugin/pom.xml
cdap-common/src/main/resources/cdap-default.xml
cdap-docs/_common/common-build.sh
cdap-docs/admin-manual/build.sh
cdap-docs/build.sh
cdap-docs/developers-manual/build.sh
cdap-docs/reference-manual/build.sh
cdap-docs/vars
pom.xml

- Adds a target to BUILD.rst for the complete build (all-module) of the Javadocs that works.
- Re-formats BUILD.rst to not have excessively long lines.
- Adds a stylesheet to the pom.xml that is used by the complete (all-module) Javadoc build.
- Adds a name to the cdap-authorization-plugin so that the mvn build doesn't look like it's missing something.
- Moves two doc build parameters to the vars file so they are easier to find.
- Updates the SDK build target of the docs build.sh script to include the building of the hydrator plugins, if they are available.
- Corrected paths in the build.sh script that were incorrect (they had a trailing "/")
- Updated cdap-default.xml: moved "Audit Configuration" to correct alphabetical location and updated descriptions to be consistent with others.
- …

Documentation Changes

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/audit/AuditPublishTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/SystemMetadataKafkaPublishTest.java
cdap-docs/reference-manual/source/http-restful-api/lifecycle.rst
cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayFastTestsSuite.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/apps/HighPassFilterApp.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/RuntimeArgumentTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/run/StreamWriterTestRun.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

When we first introduced artifacts, we overloaded the
PUT /apps/<app-id> api to have different behavior based on the
Content-Type header. This was to keep the endpoint backwards
compatible.
The old behavior, which expected the request body to be the jar
contents, has been deprecated for several releases so we are
removing it.

CDAP-4772 remove deprecated app create restful api

---

cdap-docs/integrations/source/partners/cloudera/ingesting.rst
cdap-docs/introduction/source/index.rst

Fixes errors in filenames in the Application configuration for an ETL example.
Fixes formatting and content error in an Impala example.
Fixes https://issues.cask.co/browse/CDAP-5248.
Passes [Quick Build 3](http://builds.cask.co/browse/CDAP-DOB147-3)
- [Revised ETL example](http://builds.cask.co/artifact/CDAP-DOB147/shared/build-3/Docs-HTML/3.4.0-SNAPSHOT/en/introduction/index.html#transforming-your-data)
- [Revised Impala example](http://builds.cask.co/artifact/CDAP-DOB147/shared/build-3/Docs-HTML/3.4.0-SNAPSHOT/en/integrations/partners/cloudera/ingesting.html#ingesting-and-exploring-data-with-impala)

CDAP-5248 Application configuration for ETL example

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/ConversionHelpers.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/TestModule1.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/TestModule2.java

Listing dataset instances should return the properties that the dataset was created with. See the comment in CDAP-5182 (https://issues.cask.co/browse/CDAP-5182?focusedCommentId=21209&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21209).
Build: http://builds.cask.co/browse/CDAP-DUT3702

[CDAP-5182] return original properties when listing datasets

---

cdap-docs/cdap-apps/source/data-quality/index.rst
cdap-docs/developers-manual/source/building-blocks/views.rst
cdap-docs/developers-manual/source/data-exploration/streams.rst
cdap-docs/reference-manual/source/licenses/index.rst

Revises the details on setting formats and schema on streams.
Passes [Quick Build 5](http://builds.cask.co/browse/CDAP-DOB131-5).
Fix for issue https://issues.cask.co/browse/CDAP-2696.
[Stream Exploration page](http://builds.cask.co/artifact/CDAP-DOB131/shared/build-5/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/data-exploration/streams.html)

CDAP-2696 Document stream formats

---

cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java
cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceTaskContext.java
cdap-spark-core/pom.xml

Removes the cdap-spark-core from the Javadoc build and adds a TO-DO to fix when the Javadocs are complete for the new module.
Adds a missing link to the MapReduce Javadocs.
Corrects spelling and grammar in MapReduceTaskContext.
Passes a [Docs Develop Build](http://builds.cask.co/browse/CDAP-DDB34-1)
[New Javadocs](http://builds.cask.co/artifact/CDAP-DDB34/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/javadocs/index.html)

Fix Javadocs

---

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/ConnectorDag.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/ControlDag.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/Dag.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/PipelinePlan.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/PipelinePlanner.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpecGenerator.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/ConnectorDagTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/ControlDagTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/DagTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/PipelinePlannerTest.java

Also adds a ConnectorDag class that helps with splitting a dag into
multiple dags based on special knowledge about certain types of
nodes. The ConnectorDag takes a normal dag as input as well as a
set of reduce nodes. Reduce nodes basically map to plugins in the
pipeline that would require a reduce step in the mapreduce program.
The ConnectorDag uses this information to mark certain nodes in the
dag as connector nodes, which is a node that the dag can be split
on to create multiple sub-dags. Each connector node will translate
into a local dataset source and sink that will be used as temporary
storage linking mapreduce programs. This is used by the PipelinePlanner
to create one or more phases to be executed in the workflow.
Also adds a ControlDag class that is used to transform an …

CDAP-5186 add planner dags

---

cdap-api/src/main/java/co/cask/cdap/api/plugin/EndpointPluginContext.java
cdap-api/src/main/java/co/cask/cdap/api/plugin/PluginClass.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultPluginConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/DefaultEndpointPluginContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/FindPluginHelper.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/PluginEndpoint.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/PluginInstantiator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/PluginService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/endpointtest/MockEndpointPluginContext.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/endpointtest/PluginEndpointContextTestPlugin.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/endpointtest/TestEndpointPluginContext.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/invalid/InvalidPlugin.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/invalid2/InvalidPluginMethodParams.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/invalid3/InvalidPluginMethodParamType.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/p3/CallablePlugin.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/p4/CallingPlugin.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/p5/PluginWithPojo.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/p5/TestData.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
cdap-common/src/main/java/co/cask/cdap/common/conf/PluginClassDeserializer.java

Implementation of app-fabric endpoint to hit plugin endpoint methods. 
Next steps:
1) Implementation of plugin methods listTables and getSchema for DBSource in Hydrator plugins repo.
JIRA : https://issues.cask.co/browse/CDAP-5152
Build : http://builds.cask.co/browse/CDAP-DUT3648-2

CDAP-5152 Invoke Plugin endpoint method from Artifact handler

---

cdap-common/src/main/java/co/cask/cdap/common/UnauthenticatedException.java

External repositories will have compile error with the existing implementation of UnauthenticatedException (see below for an example).
In order to make it backwards compatible, this change is needed (it was undone in https://github.com/caskdata/cdap/pull/5312).
http://builds.cask.co/browse/CDAP-DUT3705-5

Make UnauthenticatedException once again extend UnauthorizedException

---

cdap-docs/developers-manual/build.sh
cdap-docs/developers-manual/source/building-blocks/mapreduce-programs.rst
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/fileset-example.rst
cdap-docs/examples-manual/source/examples/purchase.rst

Passes [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB150-2)
This fixes the MD5 hashes, and adjusts the documentation for changes in the included files.

Fix broken doc build, and updates the MD5 hashes.

---

cdap-ui/app/features/admin/templates/namespace/templates.html

- Adds an asterisk to "Template name" property in plugin template create view.
- Disables saving plugin templates without name.

[CDAP-5123] - Adds asterik to template name field and disables plugin template if there is no name

---

cdap-ui/app/directives/widget-container/widget-factory.js
cdap-ui/app/features/hydrator/bottompanel.less

Associated PR: https://github.com/caskdata/hydrator-plugins/pull/171 not necessarily dependent (as an unknown widget will be defaulted to textbox in UI) but would be better if its merged before merging this PR.

Adds textarea as widget to hydrator plugins

---

cdap-ui/app/features/hydrator/controllers/create/leftpanel-ctrl.js
cdap-ui/app/features/hydrator/services/create/actions/plugin-actions.js
cdap-ui/app/features/hydrator/services/create/stores/left-panel-store.js

- Prevents ETL-Batch templates to appear in Realtime & vice versa
- Resets left panel every time the user leaves the studio (prevent momentarily showing batch plugins in realtime and then replacing it with realtime plugins)

[CDAP-5116] Reset left panel store on changing etl template type (prevents batch templates appear in realtime)

---

cdap-docs/developers-manual/source/data-exploration/index.rst
cdap-docs/reference-manual/source/http-restful-api/query.rst
cdap-docs/tools/doc-cdap-default.py

Passes [Quick Build 3](http://builds.cask.co/browse/CDAP-DOB149-3).
Fix for https://issues.cask.co/browse/CDAP-4783.
- [Query RESTful API, "Enable and Disable Querying"](http://builds.cask.co/artifact/CDAP-DOB149/shared/build-3/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/query.html#enabling-and-disabling-querying)
- [Data Exploration](http://builds.cask.co/artifact/CDAP-DOB149/shared/build-3/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/data-exploration/index.html)

CDAP-4783 Documentation of Explore enable/disable endpoints

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/BatchPhaseSpec.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLBatchApplication.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/PipelinePluginInstantiator.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/TransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/connector/ConnectorSink.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/connector/ConnectorSource.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSparkProgram.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/Constants.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelinePhase.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelineRegisterer.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TransformExecutor.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/PipelinePlanner.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/StageInfo.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpec.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/TransformExecutorTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/PipelinePlannerTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java

Adds a source and sink for connector nodes. Also introduces a
PipelinePluginInstantiator that will instantiate these sources
and sinks directly instead of the through the plugin context, and
will instantiate all other plugins through the plugin context.
This is because we dont want to expose these classes as actual
sources and sinks that people can use.
As part of this work, refactoring PipelinePhase so that it tracks
plugin types instead of having specific knowledge about what a
source or transform or aggregator is.

CDAP-5186 add connector implementations

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AuthorizationHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AuthorizationHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/InMemoryAuthorizer.java
cdap-authorization-dataset-plugin/src/main/java/co/cask/cdap/security/authorization/ACLDataset.java
cdap-authorization-dataset-plugin/src/main/java/co/cask/cdap/security/authorization/DatasetBasedAuthorizer.java
cdap-authorization-dataset-plugin/src/test/java/co/cask/cdap/security/authorization/ACLDatasetTest.java
cdap-authorization-dataset-plugin/src/test/java/co/cask/cdap/security/authorization/DatasetBasedAuthorizerTest.java
cdap-client/src/main/java/co/cask/cdap/client/AuthorizationClient.java
cdap-proto/src/main/java/co/cask/cdap/proto/security/Principal.java
cdap-proto/src/main/java/co/cask/cdap/proto/security/Privilege.java
cdap-proto/src/main/java/co/cask/cdap/proto/security/Role.java
cdap-security-spi/src/main/java/co/cask/cdap/security/spi/authorization/Authorizer.java
cdap-security-spi/src/main/java/co/cask/cdap/security/spi/authorization/NoOpAuthorizer.java
cdap-security-spi/src/main/java/co/cask/cdap/security/spi/authorization/RoleAlreadyExistsException.java
cdap-security-spi/src/main/java/co/cask/cdap/security/spi/authorization/RoleNotFoundException.java
cdap-security-spi/src/test/java/co/cask/cdap/security/spi/authorization/AuthorizerTest.java
cdap-security/src/test/java/co/cask/cdap/security/authorization/AuthorizerInstantiatorServiceTest.java

- This introduces the concepts of roles in CDAP Authorization: This is needed to support RBAC such as apache sentry.
- Added role based API to AuthorizerHandler as discussed here: https://wiki.cask.co/display/CE/Authorization+API
- Added support for RBAC in InMemoryAuthorizer
- Added unit tests to test RBAC
- Note: This PR does not include associated CLI commands. That will be in a separate PR.
- Issue: https://issues.cask.co/browse/CDAP-5155
- Build: http://builds.cask.co/browse/CDAP-DUT3716-1

CDAP-5155: Role Management in Authorization

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramRunners.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceTaskContextProvider.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextConfig.java

- Unify logic for getting logical start time 
- Remove unnecessary configs for MR and Spark for logical start time.

Refactor context logic for logical start time

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/AbstractWorkflow.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/Workflow.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-client-tests/src/main/java/co/cask/cdap/client/app/FakeWorkflow.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/WorkflowAppWithLocalDatasets.java

JIRA: https://issues.cask.co/browse/CDAP-4075
This PR adds `initialize` and `destroy` methods to the Workflow. 
Next PR will contain following changes - 
1. Ability to get the map of node ids to the `WorkflowNodeState` from `WorkflowContext`. The dependent PR is already opened here #5326 
2. Ability to get the status of the Workflow through `WorkflowContext`.

CDAP-4075 Added lifecycle methods for the Workflow.

---

cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/co/cask/cdap/etl/proto/v2/ETLConfig.java

We need to check that transforms are not null before iterating
over them. The field can be null because the object is created
through deserialization.

fix backwards compatibility upgrade for etl configs

---

cdap-master/pom.xml
cdap-standalone/pom.xml

Due to change in the hydrator-plugins build process source and javadoc artifacts are being created which are then included into the CDAP SDK and Distributed builds. This change is to not include javadoc and sources during the build process.

CDAP-5333 Fixing issue with inclusion of javadoc and sources as additional artifacts

---

cdap-cli/bin/cdap-cli.sh

The issue was that we were not checking the JDK version and that was causing the issue running on CDH cluster. The default JDK configured in JDK cluster is 1.6. We need to figure out how we can change that, but for now the script makes sure that it has the right environment before running.

CDAP-5126 Checking incompatible version of java before running CLI

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSparkProgram.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/PipelinePlan.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpecGenerator.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/BranchProgramAdder.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/DataPipelineApp.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/SmartWorkflow.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/TrunkProgramAdder.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/WorkflowProgramAdder.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/DataPipelineTest.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/mock/IdentityTransform.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/mock/MockSink.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/mock/MockSource.java
cdap-app-templates/cdap-etl/pom.xml

Add the application for data pipeline. The app will use the
pipeline planner to break up a logical pipeline into physical
phases. Each phase is a program with its own source(s), transforms,
and sink(s). Phases are connected through local datasets.

CDAP-5186 add data pipeline application

---

cdap-ui/npm-shrinkwrap.json

This is reverted as shrinkwrap maintains everything as "dependencies" instead of differentiating between dev & production dependencies. So ```npm install --production``` causes dev dependencies to be installed in production environment. 
This [npm#10073 - PR](https://github.com/npm/npm/pull/10073) seems to fix this issue. However if we need to take this release we need to upgrade node & npm versions which we are not right now doing. Hence resorting to this change.
Checkstyle build - http://builds.cask.co/browse/CDAP-DRC3492-1

Removes devDependencies from shrinkwrap to install production dependencies alone

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/WorkflowTokenProvider.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/AbstractProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowToken.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/MapReduceProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/ProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/SparkProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java

- Remove unnecessary method from the ProgramWorkflowRunner
- Introduce a new WorkflowTokenProvider interface
- Unify the way how a ProgramController return a WorkflowToken
back to WorkflowDriver to merge
- Move logic of setting MapReduce counters into BasicWorkflowToken
- Make BasicWorkflowToken.merge work against WorkflowToken to reduce the need of casting.

Refactor ProgramWorkflowRunner

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/verification/AbstractVerifier.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/MultipleOutputs.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/input/MultipleInputs.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/partitioned/DynamicPartitioningOutputCommitter.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithMapReduceUsingAvroDynamicPartitioner.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/DynamicPartitionerWithAvroTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/dataset/MultipleOutputsTest.java
cdap-common/src/main/java/co/cask/cdap/common/conf/ConfigurationUtil.java
cdap-common/src/test/java/co/cask/cdap/common/conf/ConfigurationUtilTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/data-cleansing.rst
cdap-examples/DataCleansing/src/main/java/co/cask/cdap/examples/datacleansing/DataCleansingMapReduce.java
cdap-examples/DataCleansing/src/test/java/co/cask/cdap/examples/datacleansing/DataCleansingMapReduceTest.java

User should be able to define partition metadata, when using DynamicPartitioner.
https://issues.cask.co/browse/CDAP-4071
http://builds.cask.co/browse/CDAP-DUT3701-3

User should be able to define partition metadata, when using DynamicPartitioner

---

cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataTestBase.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/SearchMetadataCommand.java
cdap-client/src/main/java/co/cask/cdap/client/MetadataClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
cdap-docs/reference-manual/source/cli-api.rst
cdap-docs/reference-manual/source/http-restful-api/metadata.rst

Build - http://builds.cask.co/browse/CDAP-DUT3762-5
Passes [Doc Quick Build 4](http://builds.cask.co/browse/CDAP-DOB154-4)
Revised documentation: 
- [Metadata Searching](http://builds.cask.co/artifact/CDAP-DOB154/shared/build-4/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/metadata.html#http-restful-api-metadata-searching)
- [CLI Documentation](http://builds.cask.co/artifact/CDAP-DOB154/shared/build-4/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/cli-api.html#available-commands) (fixes an error in the existing CLI documentation, and updates it to the latest version)

CDAP-4997 Allow filtering metadata search on mulitple target types

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json
cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/cookbook-setup.sh

The previous download gives a 403 forbidden error when attempting to fetch.

Update to latest IntelliJ version, previous version unavailable

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetsUtil.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/DatasetsUtilTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java

- fixes the concurrent modification in fixProperties()
- fixes the unit that also had a bug (always instantiated fileSet)
- renames and moves the unit test to the same package

[CDAP-5367] fix fixDatasetProperties() and its unit test

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionSparkContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/NameMappedDatasetFramework.java
cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java
cdap-app-fabric/src/test/java/co/cask/cdap/AllProgramsApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataHttpHandlerTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/dataset/SystemDatasetInstantiator.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetCache.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/ForwardingDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/SingleThreadDatasetCache.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/cache/DynamicDatasetCacheTest.java

For MapReduce and Spark, we know the dataset access types (when setting as input or output of the MR/Spark program), so we can specify that particular accessType, instead of `AccessType.Unknown`.
This updates DynamicDatasetCache, SystemDatasetInstantiator, and DatasetFramework to have a `getDataset` method that takes in an `AccessType`.
One thing to note is that `RemoteDatasetFramework` and `InMemoryDatasetFramework` have implementation of this method that totally ignore this parameter, because it is only needed up until the `lineageWriterDatasetFramework`.
https://issues.cask.co/browse/CDAP-5216
http://builds.cask.co/browse/CDAP-DUT3767-5

CDAP-5216 Improve determining dataset access type for MapReduce and Spark

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/DescribeArtifactCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/DescribeArtifactPluginCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/GetArtifactPropertiesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/ListArtifactPluginTypesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/ListArtifactPluginsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/artifact/ListArtifactVersionsCommand.java
cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java

Currently when you describe artifact, the artifact is searched only in USER namespace. This creates confusion and forces one to know the SCOPE before describing. With this change when no scope is provided it would search in both SCOPE in the order SYSTEM and the USER. 
Following are all the commands that have been fixed.

CDAP-4987 Fix Describe Artifact to search in both scope

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/AuthorizationCLITest.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLITestBase.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/security/GrantActionCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RemoveRoleFromPrincipalCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeActionCommand.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
cdap-proto/src/main/java/co/cask/cdap/proto/element/EntityType.java
cdap-proto/src/main/java/co/cask/cdap/proto/id/InstanceId.java
cdap-proto/src/main/java/co/cask/cdap/proto/security/Principal.java
cdap-proto/src/test/java/co/cask/cdap/proto/id/EntityIdTest.java
cdap-security/src/main/java/co/cask/cdap/security/authorization/AuthorizerInstantiatorService.java
cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java
cdap-test/src/main/java/co/cask/cdap/test/TestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
cdap-unit-test/src/test/java/co/cask/cdap/security/AuthorizationTest.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

- Added a new ``EntityId`` - ``InstanceId`` to represent a CDAP instance
- Namespace create needs *ADMIN* privilege on the CDAP instance
- Namespace delete needs *ADMIN* privilege on the namespace being deleted
- Also added initial support for authorization in ``TestBase``. Currently only supports granting and revoking privileges
- Added support for listing and retrieving namespaces as well as retrieving ``CConfiguration`` in ``TestBase``
- Refactored ``CLIMainTest`` to pull out Authorization CLI Tests into a separate class which can enable authorization
Overall, the PR looks large, but mostly involves adding functionality to ``TestBase`` and refactoring some tests. The core logic of enforcement is contained in ``DefaultNamespaceAdmin``, while test is in ``AuthorizationTest``
Jira: …

(CDAP-4253) Added authorization enforcement in Namespace HTTP APIs

---

cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java
cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceTaskContext.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowInfo.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowToken.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/NameMappedDatasetFramework.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramInfo.java
cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowTokenTestPutApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java

- adds an interface WorkflowInfo and changes internal class WorkflowProgramInfo to implement that
- adds methods getWorkflowInfo() to MapReduceContext and MapReduceTaskContext
- adds validation to existing unit test and the app used by that test
- refactors same unit test and app to run faster, by starting the workflow only once instead of six times.

[CDAP-5376] add a way for programs to retrieve the enclosing workflow and run id if they are part of a workflow

---

cdap-distributions/src/packer/scripts/cookbook-setup.sh

Remove `--force` from knife, as it's not supported on all versions. Also, use `die()` function over directly calling `exit 1` to prevent erroneous failures.
Build: http://builds.cask.co/browse/CDAP-BUT821-5

Fix VM/Docker compiles

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowAction.java
cdap-api/src/main/java/co/cask/cdap/internal/workflow/ProgramWorkflowAction.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/CustomActionExecutor.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java

Moved execution of the custom action to separate class.
This is done because custom action lifecycle methods - `initialize`, `run`, and `destroy` runs in transaction and they are executed on the Workflow driver side. While program lifecycle methods are handled by respective program runners such as `MapReduceProgramRunner` and `SparkProgramRunner`. We wrap the program under `ProgramWorkflowAction`, however `run` method of it does not really need to be executed in transaction.

Refactored the WorkflowDriver code to move execution of the Custom actions in separate class.

---

cdap-docs/reference-manual/source/http-restful-api/query.rst

Retrieving the status of a query isn't namespaced.
Building as [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB155-2)
Pages of Interest:
- [Query API, status of a query](http://builds.cask.co/artifact/CDAP-DOB155/shared/build-2/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/query.html#status-of-a-query)
- [Query API, current documentation, status of a query](http://docs.cask.co/cdap/3.3.2/en/reference-manual/http-restful-api/query.html#status-of-a-query)

CDAP-5280 Documentation of Query API

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkConfUtils.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramWrapper.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkUtils.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/java/co/cask/cdap/internal/asm/Methods.java
cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh

- No longer requires the __spark_conf__.zip file generated externally
- Can optionally turn off the rewrite

Modify the Spark Yarn Client rewrite logic

---

cdap-docs/admin-manual/source/upgrading/ambari.rst
cdap-docs/admin-manual/source/upgrading/cloudera.rst
cdap-docs/admin-manual/source/upgrading/mapr.rst
cdap-docs/admin-manual/source/upgrading/packages.rst

- Adjusted text for upgrade to always run the upgrade tool with any update.
- Corrected links that were jumping when resolved.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB148-1)
- [Upgrading CDAP using Cloudera Manager]()
- [Upgrading CDAP using Packages]()
Fix for https://issues.cask.co/browse/CDAP-5232

CDAP-5232 Upgrade Instructions

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLBatchApplication.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/ConnectorDag.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/Dag.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/planner/PipelinePlanner.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/ConnectorDagTest.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/planner/PipelinePlannerTest.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/DataPipelineApp.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java

An isolation node is one that should be bracketed on both sides
by connectors. This is to support the spark transform plugin type,
which will read from a source, perform some rdd operation, then
write to a sink.  If inserted into the middle of a pipeline, we
will need to write to a local dataset, then use that local dataset
as input into the spark transform.

add planner logic for isolation nodes

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRunnerTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTableService.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTableServiceTest.java

- Use Transaction.isVisible instead of just the read point to filter versions

Fix a bug in InMemoryTable implementation that it cannot read it’s own writes after flushing.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultPluginConfigurer.java
cdap-app-templates/cdap-etl/cdap-etl-api-spark/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/co/cask/cdap/etl/api/batch/SparkPluginContext.java
cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/co/cask/cdap/etl/api/batch/SparkSink.java
cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/co/cask/cdap/etl/api/batch/package-info.java
cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/ETLBatchApplication.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/TransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/BasicSparkPluginContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSparkProgram.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLBatchTestBase.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TransformExecutor.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpecGenerator.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/spec/PipelineSpecGeneratorTest.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/DataPipelineApp.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/SmartWorkflow.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/DataPipelineTest.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/mock/SpamMessage.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/mock/SpamOrHam.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java
cdap-app-templates/cdap-etl/pom.xml
cdap-master/pom.xml
cdap-standalone/pom.xml

Users can write plugins that get the data from previous stages of an ETL pipeline and can run arbitrary spark code (for instance, MLLib functions) against it.
The Spark MLLib plugin is not a `BatchSink`, but it is treated as the final node of a pipeline.
Other stages can not come after it.
https://issues.cask.co/browse/CDAP-5362
http://builds.cask.co/browse/CDAP-DUT3792

CDAP-5362 Spark MLLib Plugin Type

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/StructuredRecordWritable.java

Without these, the same record could be sent to different reducers.

CDAP-5429 forgot to implement hash code and equals

---

cdap-ui/app/directives/widget-container/widget-factory.js
cdap-ui/app/directives/widget-container/widget-function-dropdown-with-alias/widget-function-dropdown-with-alias.html
cdap-ui/app/directives/widget-container/widget-function-dropdown-with-alias/widget-function-dropdown-with-alias.js
cdap-ui/app/directives/widget-container/widget-function-dropdown-with-alias/widget-function-dropdown-with-alias.less
cdap-ui/app/features/hydrator/templates/list.html
cdap-ui/app/features/hydratorplusplus/controllers/create/create-studio-ctrl.js
cdap-ui/app/features/hydratorplusplus/services/detail/stores/pipeline-detail-nodeconfig-store.js

Right now we have explicit layout for source,transform & sink plugins. We are adding batchaggregator as a type of plugin and we are treating it as a transform plugin. This fix allows a user to view/edit batchaggregator type plugin configuration as a transform plugin. 
TL;DR - View batchaggregator type plugins as a transform type plugin.

Fix to show node config for tranfrom-type plugins

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/FindPluginHelper.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/PluginService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/security/RevokeActionCommand.java
cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteArtifactManager.java
cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java
cdap-test/src/main/java/co/cask/cdap/test/ArtifactManager.java
cdap-test/src/main/java/co/cask/cdap/test/TestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/ArtifactManagerFactory.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultArtifactManager.java
cdap-unit-test/src/test/java/co/cask/cdap/security/AuthorizationTest.java

- Added authorization checks in ArtifactRepository
- To deploy an artifact, a user needs WRITE permission on the namespace
- Once deployment is successful, the user gets ALL privileges on the artifact
- To write/remove properties of an artifact, or to delete an artifact a user needs ADMIN privileges on the artifact
- Replaced usages of Id.Namespace with NamespaceId where easily possible
(CDAP-4925) Improved support for artifacts in TestBase using an ArtifactManager. Deprecated old methods.
Jira: 
[CDAP-5382](https://issues.cask.co/browse/CDAP-5382)
[CDAP-4925](https://issues.cask.co/browse/CDAP-4925)
Build: http://builds.cask.co/browse/CDAP-DUT3796

(CDAP-5382) Added authorization enforcement for artifacts

---

cdap-api-common/src/main/java/co/cask/cdap/api/data/format/StructuredRecord.java
cdap-api-common/src/main/java/co/cask/cdap/api/data/schema/Schema.java
cdap-api-common/src/main/java/co/cask/cdap/api/data/schema/SchemaHash.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryConfigurator.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchAggregator.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSparkProgram.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkAggregatorContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/AbstractAggregatorContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/AbstractBatchContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceAggregatorContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/DataPipelineApp.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/main/java/co/cask/cdap/etl/datapipeline/SmartWorkflow.java
cdap-app-templates/cdap-etl/cdap-etl-data-pipeline/src/test/java/co/cask/cdap/etl/datapipeline/DataPipelineTest.java

Added an implementation for aggregators in spark. Implementation
is not ideal for a few reasons. The first is that we can't run
multiple spark programs at the same time in a workflow, so we
are forced to squash a parallel jobs into sequential jobs.
The second is that we should be able to compute the entire pipeline
in a single spark job rather than splitting it across multiple.
As part of this change, had to make StructuredRecord an Schema
implement the Serializable interface in order for them to be
usable in Spark.
Also made a small fix so that enums in application configs dont
have to be given as all caps.

CDAP-5146 implement aggregators in spark program

---

cdap-proto/src/main/java/co/cask/cdap/proto/DatasetInstanceConfiguration.java

The incompatibility was introduced in #5374 causing build failures in external repos.

Make DatasetInstanceConfiguration backward-compatible again

---

cdap-cli/bin/cdap-cli.bat
cdap-data-fabric/bin/tx-debugger.bat
cdap-standalone/bin/cdap.bat
cdap-standalone/bin/cdap.sh

This PR:
- Changes (in all our `.bat` files) the copyright to remove the © symbol, so that the file encoding on Windows won't cause a problem if the files are edited in an editor such as `Notepad`.
- Adds to the Windows SDK start-script the same JVM options as our shell script (`-Xmx2048m -XX:MaxPermSize=128m`). This fixes running the Purchase app under Windows. Tested on two different Windows installations.
- Removes two lines from of *NIX start script that were printing the `Node.js` version unnecessarily.
Fixes https://issues.cask.co/browse/CDAP-5417.
Running a Develop RAT and Checkstyle at: http://builds.cask.co/browse/CDAP-DRC3558-1

CDAP-5417 Purchase Example fails under Windows

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationManager.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ProgramGenerationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/ProgramGenerationStageTest.java
cdap-unit-test/src/test/java/co/cask/cdap/security/AuthorizationTest.java

- When an app is successfully deployed, the user gets ALL privileges on all programs in the app.
- To start/stop a program, a user needs EXECUTE privileges on the program.
- When an app is deleted, all privileges on all programs are revoked
Jira: [CDAP-5382](https://issues.cask.co/browse/CDAP-5382)
Build: http://builds.cask.co/browse/CDAP-DUT3807
Discovered a couple of issues in the authorization implementation during this PR: 
[CDAP-5427](https://issues.cask.co/browse/CDAP-5427) and [CDAP-5428](https://issues.cask.co/browse/CDAP-5428), which will be implemented in subsequent PRs and will remove some of the hacks in this PR.

(CDAP-5382) Enforced authorization for program lifecycle

---

cdap-api-spark/src/main/java/co/cask/cdap/api/spark/JavaSparkExecutionContext.java
cdap-api-spark/src/main/scala/co/cask/cdap/api/spark/SparkExecutionContext.scala
cdap-api-spark/src/main/scala/co/cask/cdap/api/spark/SparkMain.scala
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/Transactions.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkClassLoader.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkExecutionContextFactory.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkPluginContext.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContext.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextConfig.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkServiceDiscoverer.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkTaskLocalizationContext.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkTransactionClient.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkTransactionService.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkTransactional.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkUserMetrics.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/TransactionInfo.java
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/BatchReadablePartition.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/BatchReadableRDD.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DatasetCompute.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DatasetRDD.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultJavaSparkExecutionContext.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkContextCache.scala
cdap-spark-core/src/test/java/co/cask/cdap/app/runtime/spark/SparkTransactionServiceTest.java
cdap-spark-core/src/test/resources/logback-test.xml

- Mainly contains new classes and implementation of cdap-api-spark objects
- It doesn't hooked up with app-fabric runtime system yet
- Many of the test cases are actually running Spark program, which requires hooking up with app-fabric runtime system, hence will come in future PR.

(CDAP-5085) Added implementation of the new Spark Runtime Core (Part 1)

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/NodeStatus.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowContext.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowNodeState.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ApplicationSpecificationAdapter.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/AbstractProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/MapReduceProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/ProgramWorkflowRunnerFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/SparkProgramWorkflowRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowAppWithScopedParameters.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/DefaultThrowable.java
cdap-proto/src/main/java/co/cask/cdap/proto/ProgramRunStatus.java
cdap-proto/src/main/java/co/cask/cdap/proto/WorkflowNodeStateDetail.java
cdap-proto/src/main/java/co/cask/cdap/proto/WorkflowNodeThrowable.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/DefaultThrowableCodec.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowNodeThrowableCodec.java

JIRA: https://issues.cask.co/browse/CDAP-4075
JIRA: https://issues.cask.co/browse/CDAP-5181
Following changes are done as a part of the PR:
1. In memory `Map<String, WorkflowNodeState>` is maintained in the `WorkflowDriver`.
2. `WorkflowContext` api has method `getNodeStates` which returns the above map.
3. `WorkflowNodeState` class now contains the failureCause of type `Throwable` instead of `String`, so as to give the programmatic access to the developer.
4. Added `WorkflowNodeStateDetail` class in the `cdap-proto` which has failureCause of type `DefaultThrowable` for storing it in MDS and serving through REST endpoint.
5. REST endpoint implementation for getting node states. The endpoint has path: `/apps/{app-id}/workflows/{workflow-id}/runs/{run-id}/nodestates`

Implementation of returning node states from WorkflowContext and through REST endpoint.

---

cdap-docs/_common/_themes/cdap/static/cdap.css_t
cdap-docs/examples-manual/source/examples/hello-world.rst
cdap-docs/examples-manual/source/examples/log-analysis.rst
cdap-docs/examples-manual/source/examples/purchase.rst
cdap-docs/examples-manual/source/examples/spark-k-means.rst
cdap-docs/examples-manual/source/examples/spark-page-rank.rst
cdap-docs/examples-manual/source/examples/user-profiles.rst
cdap-docs/faqs/source/cdap.rst

This is a simple CSS change that adds a ``background box with a border`` to the documentation's literals, similar to ``this text`` in GitHub. The style is a little stronger, as it has a border in addition to the background coloring.
It does not do it when the text is in a table, as that doesn't work very well.
Some editing might be required, as text such ``"sample"`` no longer requires the quotes to distinguish it, and can instead just be ``sample``. As can be seen in the [Hello World example](http://builds.cask.co/artifact/CDAP-DOB152/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/examples-manual/examples/hello-world.html), some of the titles have literals in them; the literals can either be removed or suppressed.
Passes [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB152-2)
*Build 2 …

Add background formatting to literals, but not when they are in a table.

---

cdap-docs/cdap-apps/build.sh

Remove references to removed documents at the Hydrator repo.
Passes [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB159-2)

Fix Broken CDAP Doc Build

---

cdap-api/src/main/java/co/cask/cdap/api/annotation/Batch.java
cdap-api/src/main/java/co/cask/cdap/api/annotation/ProcessInput.java

Passed [Docs Develop Build 2](http://builds.cask.co/browse/CDAP-DDB35-2) which builds the Javadocs...

Fix broken links in Javadocs.

---

cdap-ui/app/features/hydratorplusplus/services/detail/stores/pipeline-detail-metrics-store.js

Previously we used to check for just `in` & `out` in metric names. It is possible that the UI gets more than one metric with the node name. Changing it to make it explict (`'user.' + <node-name> + '.records.in/out'`)

Fixes the logic to match metric with a node name in hydrator++

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AuthorizationHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AuthorizationHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/InMemoryAuthorizer.java
cdap-authorization-dataset-plugin/src/main/java/co/cask/cdap/security/authorization/DatasetBasedAuthorizer.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/AuthorizationCLITest.java

- To grant/revoke privileges on an entity, a user must have ``ADMIN`` privileges on that entity.
- Added support for superusers in ``InMemoryAuthorizer`` and ``DatasetBasedAuthorizer``.
Jira: [CDAP-4329](https://issues.cask.co/browse/CDAP-4329)
Build: http://builds.cask.co/browse/CDAP-DUT3859

(CDAP-4329) Enforced authorization in grant/revoke APIs.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRunnerTestBase.java

Set a low tx timeout value for only one of the test classes, instead of everything that extends MapReduceRunnerTestBase.
The `MapReduceWithMultipleInputsTest` test runs a MapReduce job with more mappers than usual, so it makes more simultaneous calls to the dataset service. Because of this, the reads that the dataset service does may take more than the 1 second tx timeout and then time out the transaction.
https://issues.cask.co/browse/CDAP-5439
http://builds.cask.co/browse/CDAP-DUT3854-3

Fix flaky test case

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/BatchPhaseSpec.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSpark.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/BatchPhaseSpecTest.java

The description was being built using plugins of type `BatchSink`, but this is inaccurate now, since plugins of Type `Connector` might also be the terminating nodes of the nodes that the program is handling.
This also gives ETLSpark's description more information than it previously had.
http://builds.cask.co/browse/CDAP-DUT3850-2

Program descriptions for ETLSpark and ETLMapReduce weren't accurate.

---

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ClientVersions.java
cdap-master/src/main/java/co/cask/cdap/master/startup/MasterStartupTool.java

We log the version of several other components, so also logging hbase version.
http://builds.cask.co/browse/CDAP-DUT3867-1

Log HBase version upon Master startup.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AbstractInMemoryProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/FlowTwillProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/ServiceTwillProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkerTwillProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java

make in-memory service/worker controller behave like distributed mode: 
- expect runnable, oldInstances, newInstances 
- fix lifecycle service to pass that in correctly
- throw exceptions if setInstances fails 
- stop in-memory flow if setInstances fails
This is the same as https://github.com/caskdata/cdap/pull/5442, reopened against release/3.4

[CDAP-5463] fix setInstances for workers and services

---

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java

Fix IntegrationTestBase to check if default namespace exists instead of checking default is the only namespace that exists.
Build: http://builds.cask.co/browse/CDAP-DUT3881-2

Fix IntegrationTestBase to check if default namespace exists instead of checking default is the only namespace that exists

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/AbstractWorkflow.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultPluginConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
cdap-unit-test/src/test/java/co/cask/cdap/test/artifacts/AppWithPlugin.java

Add plugin support in workflows. This amounts to extending the
WorkflowContext interface so that it also implements PluginContext,
and extending WorkflowConfigurer so that it also implements
PluginConfigurer, and extending AbstractWorkflow so that it extends
AbstractPluginConfigurable.
The rest is just re-using the plugin work already done for the
other program types to pass a PluginInstantiator into
BasicWorkflowContext.

CDAP-5512 plugin support in workflows

---

cdap-docs/admin-manual/source/installation/cloudera.rst

Fix for https://issues.cask.co/browse/CDAP-5482.
Passed [Quick Build 4](http://builds.cask.co/browse/CDAP-DOB162-4
[Enabling Kerberos](http://builds.cask.co/artifact/CDAP-DOB162/shared/build-4/Docs-HTML/3.4.0-SNAPSHOT/en/admin-manual/installation/cloudera.html#advanced-topics)

CDAP-5482 Add Kerberos note to Cloudera installation

---

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java

Cherry picked changes from [this PR](https://github.com/caskdata/cdap/pull/5469)
Fix IntegrationTestBase to check if default namespace exists instead of checking default is the only namespace that exists.
Build: http://builds.cask.co/browse/CDAP-DUT3880-5

Reverting overwritten changes for IntegrationTestBase

---

cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLBatchTestBase.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/MockSink.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/MockSource.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/aggregator/FieldCountAggregator.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/aggregator/IdentityAggregator.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/realtime/LookupSource.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/realtime/MockSink.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/realtime/MockSource.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/test/HydratorTestBase.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/transform/DoubleTransform.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/transform/ErrorTransform.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/transform/IdentityTransform.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/transform/IntValueFilterTransform.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/transform/StringValueFilterTransform.java

This is to workaround the fact that when a project adds
hydrator-test as a dependency, the jar that gets created adds
hydrator-test as a lib jar, which does not get inspected for
plugins.

CDAP-4842 explicitly list all mock plugins

---

cdap-examples/deploy_pom.xml

The scala version should be in deploy pom. This was causing failure in VM builds. 
scala was added in example pom here: https://github.com/caskdata/cdap/pull/5501

add scala version in deploy-pom.xml

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoader.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkContextCache.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkMainWrapper.scala
pom.xml

- Spark is not designed for running multiple times inside the same VM, hence it's not doing proper cleanup.
Extra cleanup steps are added
- Shutdown the jetty server that Spark uses as file server (SPARK-14513)
- Stop the QueuedThreadPool(s) used by the jetty server that Spark uses as file server and WebUI (SPARK-14513)
- Remove the shutdown hook from ShutdownHookManager
- Invalid the LoadingCache of class constructor in BeanIntrospector
- Patch the akka.remote.Remoting code for fixing akka thread leak bug https://github.com/akka/akka/issues/17729
- Done through simple bytecode replacement
- Also there are CDAP spark-core fixes related to ClassLoader leakage
- Clear the SparkListener list when Spark job finished
- Don't use guice Injector to instantiate SparkProgramRunner directly, as …

(CDAP-5530) (CDAP-5547) Fix Spark ClassLoader and memory leakage

---

cdap-ui/app/features/hydratorplusplus/services/create/stores/config-store.js
cdap-ui/app/features/hydratorplusplus/services/non-store-pipeline-error-factory.js
cdap-ui/app/services/constants.js

Until now UI check if the DAG has exactly one source. This PR removes the validation rule while validating/publishing pipeline from UI.

Remove the rule of having only source while creating DAG from UI

---

cdap-common/bin/common.sh

Removes error output from find.
```
find: failed to restore initial working directory: Permission denied
```

Redirect find errors to /dev/null

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DefaultProgramRunnerFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnerModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/program/Programs.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/ProgramRuntimeProvider.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramRuntimeProviderLoader.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/DummyProgramRunnerFactory.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/ConfiguratorTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
cdap-common/src/main/java/co/cask/cdap/common/lang/ProgramClassLoaderProvider.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRunner.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoader.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtils.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java

- Use the ProgramClassLoader that can load Spark classes
as the ClassLoader for running Application.configure()
- This is the old behavior before the switching to the new spark-core
This one includes changes in #5515 . Please review #5515 first.

Fix a bug for artifact deployment with Spark

---

cdap-common/src/main/java/co/cask/cdap/common/lang/FilterClassLoader.java
cdap-common/src/test/java/co/cask/cdap/common/lang/FilterClassLoaderTest.java

This fix makes the FilterClassLoader delegate first to the
ExtClassLoader instead of the bootstrap classloader. This is so
that programs can load extension classes, such as the Nashorn
classes included in Java 8.

CDAP-4735 expose java ExtClassLoader to programs

---

cdap-common/bin/common.sh
cdap-common/bin/service

This uses `spark-shell` to determine `SPARK_HOME` in the start script. This way the user does not have to configure it in their environment. However, any configuration pointing to a valid directory will override detection.

CDAP-5086 Automatically determine SPARK_HOME

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DeletedDatasetMetadataRemover.java
cdap-master/src/main/java/co/cask/cdap/data/tools/ExistingEntitySystemMetadataWriter.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
cdap-master/src/test/java/co/cask/cdap/data/tools/DeletedDatasetMetadataRemoverTest.java

(CDAP-4696) Removed code for upgrading metadata storage format as well as updating the dataset specification since it is not required for an upgrade from 3.3 to 3.4
(CDAP-5402) Added an upgrade step to delete metadata for deleted datasets
Jiras:
[CDAP-4696](https://issues.cask.co/browse/CDAP-4696)
[CDAP-5402](https://issues.cask.co/browse/CDAP-5402)
Build: http://builds.cask.co/browse/CDAP-DUT3944
Tested a 3.3 -> 3.4 upgrade on a cluster

Metadata upgrade code updates

---

cdap-app-fabric/src/main/java/co/cask/cdap/security/TokenSecureStoreUpdater.java

For encrypted file systems, FileContext does not acquire the KMS delegation token.
Since we know we are in Yarn, it is safe to get the FileSystem directly, bypassing LocationFactory.

[CDAP-5350] Workaround to obtain KMS delegation token in encryption-enabled clusters

---

cdap-app-fabric/src/test/java/co/cask/cdap/runtime/FlowTest.java

JIRA : https://issues.cask.co/browse/CDAP-4357
Take-2 at fixing this flaky test. Missed the case where the pending events metrics will be 8. This was observed in this build failure : https://builds.cask.co/download/CDAP-BUT842-JOB1/build_logs/CDAP-BUT842-JOB1-37.log
Build : http://builds.cask.co/browse/CDAP-DUT3934

CDAP-4357 Missed the case where the pending events metric for source flowlet to fwd-one flowet can be 8

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/ConcurrentPartitionConsumer.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/PartitionAcceptor.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionConsumerTest.java

Improve javadocs and write test cases for `PartitionAcceptor`.
Also fix a bug with Return.STOP, discovered while writing the test case.
https://issues.cask.co/browse/CDAP-5534
http://builds.cask.co/browse/CDAP-DUT3941

Documentation and test cases for custom PartitionAcceptor

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/ConditionCodec.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionFilter.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionedFileSetArguments.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/ComparableCodec.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/PartitionKeyCodec.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetArgumentsTest.java
cdap-proto/src/test/java/co/cask/cdap/proto/codec/ConditionCodecTest.java

Fixes using PartitionFilter.ALWAYS_MATCH as the partition filter.
Now, using a custom GSON and custom serializer/deserializer to serialize the PartitionFilter into just one key of the runtime arguments map.
https://issues.cask.co/browse/CDAP-5267
http://builds.cask.co/browse/CDAP-DUT3937

Update how PartitionFilter gets serialized in the runtime arguments.

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12-with-uri.json

Upstream removes old versions from availability, which breaks the VM build.

Use latest IntelliJ version (backport from 3.4)

---

cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java

Enabling LogSaverTests which were [disabled](https://github.com/caskdata/cdap/pull/5383).
Issue: https://issues.cask.co/browse/CDAP-4070
Build: http://builds.cask.co/browse/CDAP-DUT3960-1

Enable LogSaverTest

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/PluginService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/StandaloneAppFabricServer.java

JIRA: https://issues.cask.co/browse/CDAP-5277

CDAP-5277 added caching of plugin instantiators

---

cdap-docs/reference-manual/source/release-notes.rst

Release notes for 3.3.3.
Copies improvements made under 3.4.0 to the older release notes.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB171-1)
[Release Note(s)](http://builds.cask.co/artifact/CDAP-DOB171/shared/build-1/Docs-HTML/3.3.3/en/reference-manual/release-notes.html#release-3-3-3)

Release Notes for release 3.3.3

---

cdap-ui/app/services/alert-on-valium/alert-on-valium.js

Ways to repeat the error,
- Try editing stream properties.
- Have an error while saving it.
- Fix the error and re-save it without closing the error message.
- The success message will also be shown as error.
We are right now only updating the message instead we should update both message and the style.

[CDAP-5490] Fix showing success messages after a failure from backend 

---

cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
cdap-ui/app/directives/plugin-templates/plugin-templates.html
cdap-ui/app/features/hydratorplusplus/controllers/create/leftpanel-ctrl.js
cdap-ui/app/features/hydratorplusplus/controllers/create/toppanel-ctrl.js
cdap-ui/app/features/hydratorplusplus/leftpanel.less
cdap-ui/app/features/hydratorplusplus/routes.js
cdap-ui/app/features/hydratorplusplus/services/create/stores/config-store.js
cdap-ui/app/features/hydratorplusplus/templates/create/popovers/canvas-overwrite-confirmation.html

- Fixes the message to be `Do you wish to save your work before navigating away?` when the user has un-saved changes in the dag and is trying to do one of the following,
- Change artifact
- Import a pipeline
- Choose a plugin template
- Saves the draft if the user wises to save it before navigating away
- Shows appropriate message in console if the pipeline does not have a name to be saved as draft.
- Fixes updating default state on config store once a draft has been saved.

[CDAP-5568, CDAP-5587, CDAP-5354] Fix unsaved changes behavior hydrator++

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowToken.java
cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ApplicationVerificationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorkflow.java
cdap-client-tests/src/test/java/co/cask/cdap/client/WorkflowClientTestRun.java

JIRA: https://issues.cask.co/browse/CDAP-5580
Added ability to get and put in the token through `AbstractWorkflow.initialize` and `AbstractWorkflow.destroy` methods. While storing the data in the token through these methods, name of the Workflow is used as node name.

CDAP-5580 Ability to get/put in the Workflow token through initialize and destroy methods.

---

cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoader.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkTransactional.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultJavaSparkExecutionContext.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkRuntimeEnv.scala
cdap-unit-test/src/test/java/co/cask/cdap/spark/SparkTestRun.java
cdap-unit-test/src/test/scala/co/cask/cdap/spark/app/ForkSpark.scala
cdap-unit-test/src/test/scala/co/cask/cdap/spark/app/TestSparkApp.scala

We already have the Spark runtime ClassLoader isolation, however,
SparkSubmit uses System properties as the mean to transfer configurations
to SparkConf, hence making parallel Spark execution affecting each other.
The fix for that is to have SparkConf and SparkSubmit rewritten so that
instead of using the System properties, they use a per ClassLoader class,
SparkRuntimeEnv for those configurations
- Rename SparkContextCache to SparkRuntimeEnv
- Rewrite usage of System.setProperty to SparkRuntimeEnv.setProperty in the SparkSubmit class
- Rewrite the SparkConf constructor to pickup configurations from SparkRuntimeEnv
- Added new unit-test

(CDAP-349) Make parallel Spark job possible in Standalone

---

cdap-docs/reference-manual/source/http-restful-api/stream.rst

Fixes formatting.
Moves "Default Value" column to the middle, as that will be easier to read and understand.
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB174-1)

Fix Reference Manual Documentation Build

---

cdap-docs/cdap-apps/build.sh
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/batchsinks/index.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/batchsources/index.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/index.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/realtimesinks/index.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/realtimesources/index.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/shared-plugins/core.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/shared-plugins/index.rst
cdap-docs/cdap-apps/source/_includes/hydrator-plugins/transforms/index.rst
cdap-docs/cdap-apps/source/conf.py

Fix for https://issues.cask.co/browse/CDAP-5020
Passes [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB169-1)
Adds the hydrator version to the documentation in:
- [index page](http://builds.cask.co/artifact/CDAP-DOB169/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/cdap-apps/hydrator/hydrator-plugins/index.html)
- [section pages](http://builds.cask.co/artifact/CDAP-DOB169/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/cdap-apps/hydrator/hydrator-plugins/batchsources/index.html)
- [bottom of each plugin page](http://builds.cask.co/artifact/CDAP-DOB169/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/cdap-apps/hydrator/hydrator-plugins/batchsources/azureblobstore.html)

CDAP-5020 Add Hydrator version to documentation

---

cdap-ui/app/directives/my-global-navbar/my-global-navbar.html
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.less
cdap-ui/app/features/hydratorplusplus/bottompanel.less
cdap-ui/app/features/hydratorplusplus/controllers/create/create-studio-ctrl.js
cdap-ui/app/features/hydratorplusplus/controllers/create/leftpanel-ctrl.js
cdap-ui/app/features/hydratorplusplus/controllers/create/popovers/pre-configured-ctrl.js
cdap-ui/app/features/hydratorplusplus/routes.js
cdap-ui/app/features/hydratorplusplus/services/hydrator-service.js
cdap-ui/app/features/hydratorplusplus/templates/create/popovers/plugin-edit-form.html

- CDAP-5619, CDAP-5557: Show appropriate message in bottom panel when imported config json doesn't have artifact information or has invalid artifact information.
- CDAP-5297: Handling pipelines created using old hydrator. Show warning message for pipelines created using old hydrator and prevents showing detailed view requesting user to upgrade their pipeline.
- CDAP-4692: Prevents user from accidentally navigating away from the studio view. Shows browser native alert message before proceeding with the navigation.
- Fixes the trash icon in the node config panel not overflow its container.

Hydrator++ UI bug fix

---

cdap-client-tests/src/test/java/co/cask/cdap/client/NamespaceClientTestRun.java
cdap-common/src/main/java/co/cask/cdap/common/namespace/AbstractNamespaceClient.java
cdap-common/src/main/java/co/cask/cdap/common/namespace/InMemoryNamespaceClient.java

Fix NamespaceClient.exists() to catch NotFound exception instead of throwing it. 
Issue: https://issues.cask.co/browse/CDAP-5655
Build: http://builds.cask.co/browse/CDAP-DUT3988-5

Fix NamespaceClient.exists() to return boolean value instead of NotFound exception

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java

with hbase 1.1 and higher
The FuzzyRowFilter implementation has changed: https://issues.apache.org/jira/browse/HBASE-13761
and it has bug where it matches everything if the mask consists of all zero. I have opened a bug in HBase: https://issues.apache.org/jira/browse/HBASE-15676 (Please see this for more details about the issue)
This fix workaround this bug and is tested on HDP 2.3 and CDH 5.7 cluster.

CDAP-5369 Fix FuzzyRowFilter for metadata search

---

cdap-docs/developers-manual/build.sh
cdap-docs/developers-manual/source/building-blocks/datasets/index.rst
cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/examples/fileset-example.rst
cdap-examples/FileSetExample/src/main/java/co/cask/cdap/examples/fileset/FileSetService.java
cdap-examples/FileSetExample/src/main/java/co/cask/cdap/examples/fileset/WordCount.java

- added dataset admin endpoints to FileSetExample
- added documentation for dataset admin in developer guide
Passes [Quick Build 5](http://builds.cask.co/browse/CDAP-DOB176-4)
- [Developers’ Guide: Dataset Admin](http://builds.cask.co/artifact/CDAP-DOB176/shared/build-5/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/building-blocks/datasets/index.html)
- [Examples: FileSet](http://builds.cask.co/artifact/CDAP-DOB176/shared/build-5/Docs-HTML/3.4.0-SNAPSHOT/en/examples-manual/examples/fileset-example.html)

[CDAP-3051] Add documentation and an example for dataset management in programs

---

cdap-distributions/pom.xml
cdap-ui/LICENSE-node
cdap-ui/conf/ui-env.sh
cdap-ui/pom.xml
pom.xml

This bundles Node.js with the CDAP UI when creating RPM, DEB, or Parcel packages as these are meant to only be used on a single platform. This does *NOT* affect the SDK, as the single ZIP artifact is used on multiple platforms.

Bundle Node.js with CDAP UI packages

---

cdap-docs/admin-manual/source/_includes/installation/installation.txt
cdap-docs/admin-manual/source/installation/ambari.rst
cdap-docs/admin-manual/source/installation/cloudera.rst
cdap-docs/admin-manual/source/installation/mapr.rst
cdap-docs/admin-manual/source/installation/packages.rst
cdap-docs/admin-manual/source/system-requirements.rst
cdap-docs/developers-manual/source/getting-started/standalone/index.rst

Move all references to requiring Node.js to the SDK instructions, as that is the only place they will be required.
Building as [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB181-1).

CDAP-5658 Remove instructions for Node.js installation from distributed CDAP

---

cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowStatsSLAHttpHandlerTest.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowStatsSLAHttpHandler.java
cdap-docs/reference-manual/source/http-restful-api/workflow.rst

JIRA: https://issues.cask.co/browse/CDAP-5550
For the statistics endpoint, added default values for interval = 10s and limit = 10.
JIRA: https://issues.cask.co/browse/CDAP-5551
Added checks in the statistics endpoint so that if interval <= 0 or limit <= 0 throw `BadRequestException`

CDAP-5550 Added default values for interval and limit for the statistics endpoint of the WorkflowStatsSLAHttpHandler.

---

cdap-data-fabric/bin/tx-debugger.bat
cdap-standalone/bin/cdap.bat

Fix Windows startup issues by caching the original path (and then restoring it when finished), adding `%CDAP_HOME%\lib\native` to the path, and renaming a variable that is use to cache the original directory by a more appropriate name.
Similarly for `tx-debugger.bat`.
Fixes for https://issues.cask.co/browse/CDAP-4213 and https://issues.cask.co/browse/CDAP-5657.

CDAP-4213, CDAP-5657 Windows startup scripts

---

cdap-docs/admin-manual/source/hadoop-compatibility.rst

And consolidate the change into one place, while we are at it.
Passes [Quick Build 2](http://builds.cask.co/browse/CDAP-DOB179-2)
[Hadoop Compatibility](http://builds.cask.co/artifact/CDAP-DOB179/shared/build-2/Docs-HTML/3.4.0-SNAPSHOT/en/admin-manual/hadoop-compatibility.html)

Update the CDH version 5.7.0. 

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java

Since `WorfklowDriver.run` method already has same message, its not required in `startUp`

Removed extra message.

---

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchSinkContext.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/batch/BatchSourceContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/AbstractSparkBatchContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkBatchSinkContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkBatchSinkFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkBatchSourceContext.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkBatchSourceFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/etl/batch/ETLWorkflowTestRun.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceSinkContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceSourceContext.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ExternalDatasets.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/MockExternalSink.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/MockExternalSource.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/test/HydratorTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/external/ExternalDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/external/ExternalDatasetAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/external/ExternalDatasetDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/external/ExternalDatasetModule.java

JIRA - https://issues.cask.co/browse/CDAP-5424
TODO:
Build - http://builds.cask.co/browse/CDAP-DUT3961-15
Depends on https://github.com/caskdata/cdap/pull/5586

CDAP-5424 Record lineage for external sources/sinks

---

cdap-kafka/pom.xml

This bug causes rpm/deb to not have lib directory for kafka. Bug introduced by PR #5503

Should not override the 'copy-dependencies' id. Using a different id

---

cdap-kafka/pom.xml

Fix another bug introduced by #5503 
So that cdap-kafka JAR is packaged under /opt/cdap/kafka/lib

Fix dist build for cdap-kafka JAR

---

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
cdap-integration-test/src/test/java/co/cask/cdap/test/IntegrationTestBaseTest.java
cdap-test/src/main/java/co/cask/cdap/test/TestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java

Changing IntegrationTestBase to use ApplicationId instead of Id.Application
Issue: https://issues.cask.co/browse/CDAP-5690
Build: http://builds.cask.co/browse/CDAP-DUT4010-6

Changing IntegrationTestBase to use ApplicationId instead of Id.Application

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunnerTest.java
cdap-unit-test/src/test/java/co/cask/cdap/spark/SparkTestRun.java

- The max resolution table should be used to query for aggregates.
Otherwise there are chances that they are recorded on
separated cell on lower resolution table.

(CDAP-4358) (CDAP-5594) (CDAP-5621) Fix flaky tests

---

cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java

Issue: https://issues.cask.co/browse/CDAP-5751
Verified on cluster for the SparkPageRankAppTest integration test to pass

CDAP-5751: Give more perm gen space to SparkPageRankApp driver

---

cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/TransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/ETLSparkProgram.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/spark/SparkTransformExecutorFactory.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TrackedEmitter.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TrackedTransform.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/TransformDetail.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/common/TransformExecutorTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/etl/realtime/ETLWorker.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/etl/realtime/ETLWorkerTest.java
cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/realtime/LookupSource.java

Fixed a bug where the metrics for records in and out of an
aggregator were incorrect because they were counting intermediate
group metrics.
Includes some refactoring so that metrics are all handled in
TrackedTransform instead of partly in TrackedTransform and partly
in DefaultEmitter. Also making the tracking classes a little more
generic so that the metric emitted can be set. This allows us to
introduce a new 'aggregator.groups' metric to count the number of
groups in an aggregator.

CDAP-5605 fix incorrect aggregator metrics

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/PartitionAcceptor.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/partitioned/PartitionConsumer.java
cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst

Describing how to use PartitionConsume in conjunction with PartitionAcceptor.
Including a code sample in the develop docs, after describing it.
Marking the relevant classes as Beta (PartitionedFileSet itself is Beta).
https://issues.cask.co/browse/CDAP-5534
Building [Quick Build 3](http://builds.cask.co/browse/CDAP-DOB186-3)

Developer docs for PartitionConsumer and PartitionAcceptor

---

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/ExternalDatasets.java

Add a check to prevent external datasets from having the same name as an existing CDAP dataset instance
JIRA - https://issues.cask.co/browse/CDAP-5728
Build - http://builds.cask.co/browse/CDAP-DUT4031-3

CDAP-5728 External dataset type check

---

pom.xml

Without this parameter, Junit trims the stack trace.
We effectively miss out on the root cause of the exception.
For instance: https://builds.cask.co/browse/CDAP-BUT-JOB1-276/test/case/34145108
We don't see the actual assertion exception message, because it gets wrapped within a transaction exception.

Avoid trimming stacktrace, to see root cause of failure.

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/EntityVerifierModule.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/entity/EntityExistenceTest.java
cdap-common/src/main/java/co/cask/cdap/common/entity/InstanceExistenceVerifier.java
cdap-data-fabric/src/main/java/co/cask/cdap/store/DefaultNamespaceStore.java

- Also fixed a bug in ``DefaultNamespaceStore`` which was resulting in the ``MultiThreadDatasetCache`` not caching the ``Dataset (Table)`` objects and instead returning a new one every single time.
Jira: [CDAP-5756](https://issues.cask.co/browse/CDAP-5756)
Build: http://builds.cask.co/browse/CDAP-DUT4039

(CDAP-5756) Added a missing EntityExistenceVerifier for InstanceId.

---

cdap-docs/admin-manual/source/upgrading/cloudera.rst
cdap-docs/admin-manual/source/upgrading/packages.rst
cdap-docs/cdap-apps/source/hydrator/upgrade.rst

Reverse last two steps of upgrade process.
Fix for https://issues.cask.co/browse/CDAP-5784
Passes [Quick Build 3](http://builds.cask.co/browse/CDAP-DOB189-3).

CDAP-5784 Upgrade steps have hydrator upgrade as the wrong step

---

cdap-ui/app/directives/group-side-panel/group-side-panel.html
cdap-ui/app/features/hydratorplusplus/leftpanel.less
cdap-ui/app/features/hydratorplusplus/services/create/stores/left-panel-store.js

[CDAP-5788](https://issues.cask.co/browse/CDAP-5788) - Remove braces `(` & `)` around the plugin counts in hydrator++'s left panel.
[CDAP-5775](https://issues.cask.co/browse/CDAP-5775) - Alphabetically sorts plugins in left panel in hydrator++

UI Hydrator++ Bug fixes 

---

cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/co/cask/cdap/etl/proto/v1/ETLConfig.java
cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/co/cask/cdap/etl/proto/v1/ETLRealtimeConfig.java
cdap-app-templates/cdap-etl/cdap-etl-tools/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/UpgradeTool.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/config/BatchClientBasedUpgradeContext.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/co/cask/cdap/etl/tool/config/RealtimeClientBasedUpgradeContext.java
cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/resources/logback.xml
cdap-docs/cdap-apps/source/hydrator/upgrade.rst

Fixed a bug in the upgrade logic that would fail if certain optional
settings -- like instances -- were not set.
Also making general improvements to the upgrade tool.
Logging was not set up correctly, so configuring error and warn
messages to write to stderr and everything else to stdout. Also
adding an option to write configs that failed to upgrade to an
error directory for manual investigation. Pipelines can fail to
upgrade if they use plugins that are not backwards compatible.

CDAP-5786 fix hydrator etl-realtime upgrade

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/audit/AuditPublishersTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/AuditPublishers.java

This is to prevent multiple access messages to the same entity with the same AccessType from the same accessor. 
JIRA : https://issues.cask.co/browse/CDAP-5746
Build :  http://builds.cask.co/browse/CDAP-DUT4044

CDAP-5746 Adding Cache to AuditPublishers

---

cdap-ui/conf/ui-env.sh

This hides the error output from the `node --version` test on our embedded `node` binary and gives a better output on failure to locate `node` in the system's PATH.

Redirect errors on node check and give friendly error message

---

cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java

this PR https://github.com/caskdata/cdap/pull/5650 broke the build, as standalone tester creates standalone main instance.
disabling audit log in standalone tester config.
build running: http://builds.cask.co/browse/CDAP-DUT4059-1

disable audit logging in standalone tester

---

cdap-docs/cdap-apps/source/hydrator/custom.rst

Adding documentation in the creating custom plugins section about
creating aggregators, spark compute plugins, and spark sinks.
Also added information about the hydrator-test module and
restructured it a little bit to avoid repetition.
Running as [Quick Build 1](http://builds.cask.co/browse/CDAP-DOB194-1)
[Page of Interest](http://builds.cask.co/artifact/CDAP-DOB194/shared/build-1/Docs-HTML/3.4.0-SNAPSHOT/en/cdap-apps/hydrator/custom.html)

CDAP-5718 documenting new data pipeline plugin types

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoader.java
cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java
cdap-spark-core/src/main/scala/co/cask/cdap/app/runtime/spark/SparkRuntimeEnv.scala
cdap-spark-core/src/test/java/co/cask/cdap/app/runtime/spark/SparkRunnerClassLoaderTest.java

- Use getResource() instead of getResourceAsStream()
Also fixed a Spark compatibility issue on older Spark version
- Not to call the isStopped and getState method from SparkContext and StreamingContext because they are added in 1.6 and 1.5 respectively
- The side effect is there would be a warning being logged when the spark job finished

(CDAP-5822) Workaround the URLClassLoader getResourceAsStream bug

---

cdap-app-fabric/src/main/java/org/apache/hadoop/fs/sftp/SFTPConnectionPool.java
cdap-app-fabric/src/main/java/org/apache/hadoop/fs/sftp/SFTPFileSystem.java
cdap-app-fabric/src/main/java/org/apache/hadoop/fs/sftp/SFTPInputStream.java
cdap-app-fabric/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem

The current implementation of FTPBatchSource in hydrator-plugins will work with SFTP source once we merge this PR. 
Distributed mode verification done
Classes copied from : https://github.com/apache/hadoop/tree/branch-2.8/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/sftp
Only modification is in the seek method of SFTPInputStream to skip if the position to seek to is as same as the current position.
Build : http://builds.cask.co/browse/CDAP-DUT4062-1

Copying SFTP Hadoop FileSystem implementation to support SFTP batch source

---

cdap-docs/reference-manual/source/http-restful-api/metadata.rst

Jira: [CDAP-5457](https://issues.cask.co/browse/CDAP-5457)
Quick Build: http://builds.cask.co/browse/CDAP-DOB196
Passes [Quick Build 7](http://builds.cask.co/browse/CDAP-DOB196-7)
Relevant Doc Pages:
[Lineage RESTful API](http://builds.cask.co/artifact/CDAP-DOB196/shared/build-7/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/metadata.html#http-restful-api-metadata-lineage)
[Collapsing Lineage Output Section](http://builds.cask.co/artifact/CDAP-DOB196/shared/build-7/Docs-HTML/3.4.0-SNAPSHOT/en/reference-manual/http-restful-api/metadata.html#lineage-collapse)

(CDAP-5457) Added documentation for collapsing lineage output.

---

cdap-ui/app/features/tracker/routes.js

- While switching namespaces we check if tracker is enabled in a particular namespace if not we go to `enable-tracker` state. This state inherits from `ns` which has a namespace in its url. 
When we use `$state.go('enable-tracker')` we are missing out on the namespace information while the namespace switch happens. Passing the `$stateParams` fixes this.

[CDAP-5832] - Fixes switching between namespaces in tracker

---

cdap-ui/app/features/overview/controllers/apps-section-ctrl.js

Hides datasets and streams created by the tracker app `_kafkaOffset` & `_AuditLog` from the home page in CDAP.

Hides datasets & streams that starts with '_' in home page

---

cdap-docs/reference-manual/source/licenses/index.rst

Re-organizes the licenses so that they are alphabetical. Added a new one (JSch), added by https://github.com/caskdata/cdap/pull/5692.
Building as http://builds.cask.co/browse/CDAP-DOB201-2

Revisions to licenses.

---

cdap-app-fabric/pom.xml
pom.xml

Fix build broken by #5672. Spark example app failed since it was using FileSystem and JSchException class was not found. 
Additional dependencies brought in : com.jcraft:jsch, com.jcraft:jzlib
Tested in both SDK, Distributed, CM modes
Build : http://builds.cask.co/browse/CDAP-DUT4074-1

Add jcraft.jsch dependency

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java

Do not use HIVE_SERVER2_SPNEGO_KEYTAB constants since its not present in earlier version of hive .

Do not use HIVE_SERVER2_SPNEGO_KEYTAB constants

---

cdap-common/src/main/resources/cdap-default.xml
cdap-docs/admin-manual/build.sh
cdap-docs/developers-manual/source/building-blocks/audit-logging.rst
cdap-docs/developers-manual/source/building-blocks/index.rst
cdap-docs/developers-manual/source/building-blocks/metadata-lineage.rst
cdap-docs/integrations/source/partners/cloudera/navigator-integration.rst

(CDAP-5247) Deprecated Metadata updates notification feed.
Issues:
* [CDAP-5242](https://issues.cask.co/browse/CDAP-5242)
* [CDAP-5247](https://issues.cask.co/browse/CDAP-5247)
[Quick Build 8](http://builds.cask.co/browse/CDAP-DOB198-8)
Relevant doc pages:
* [Audit Logging](http://builds.cask.co/artifact/CDAP-DOB198/shared/build-8/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/building-blocks/audit-logging.html)
* [Metadata Feed Deprecation](http://builds.cask.co/artifact/CDAP-DOB198/shared/build-8/Docs-HTML/3.4.0-SNAPSHOT/en/developers-manual/building-blocks/metadata-lineage.html#metadata-update-notifications)

(CDAP-5242) Added documentation for audit publishing.

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java

Explore should use updated credentials when launching Hive jobs.
Without this fix, hive jobs started by explore service will fail after the container_tokens file goes out of date.
Note: This is somewhat of a workaround for https://issues.apache.org/jira/browse/TWILL-170.
https://issues.cask.co/browse/CDAP-5793
http://builds.cask.co/browse/CDAP-DUT4066-4

Explore should use updated credentials when launching Hive jobs.

---

cdap-ui/app/features/admin/controllers/namespace/datasets-ctrl.js
cdap-ui/app/features/data/list-ctrl.js
cdap-ui/app/features/overview/controllers/apps-section-ctrl.js

- Hides external datasets from being surfaced in UI
There is one caveat still. We could see the external dataset & local dataset in datasets tab under a MR program. This should be a backend fix and we will address this in 3.5

[CDAP-5850] - Filters out externalDataset from being surfaced in UI

---

cdap-spark-core/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java

in non local mode
Issue: https://issues.cask.co/browse/CDAP-5854
Tested on windows
Tested on cluster

CDAP-5854 Add extraclasspath to spark executor and driver only 

---

cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/Purchase.java

Instead of defaulting catalogId to "", which causes a warning and then gets stored as null, we just default it to null in the first place.

[CDAP-5833] fix purchase example empty writes

---

cdap-api-common/src/main/java/co/cask/cdap/api/data/schema/Schema.java
cdap-common/src/test/java/co/cask/cdap/io/DatumCodecTest.java

- The ordering of the enum symbols are important.
We cannot use HashMap to store symbol to ordinal.
Need to use LinkedHashMap.

(CDAP-5862) The enum Schema representation was wrong.

---

cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java

State is set to COMPLETE in the ProgramController before the runtimeInfo is removed in AbstractProgramRuntimeService. Hence wait until the list becomes empty.
JIRA : https://issues.cask.co/browse/CDAP-5565
Build : http://builds.cask.co/browse/CDAP-DUT4087

CDAP-5565 Fix flaky AbstractProgramRuntimeServiceTest testDeadlock

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AbstractInMemoryProgramRunner.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithExceptionThrowingWorker.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

This affects only InMemory run of Worker/Service Handler. Capture the cause when a component ends with an error and set the state of the ProgramController to ERROR. Added a unit test case.
JIRA : https://issues.cask.co/browse/CDAP-5573
Build : http://builds.cask.co/browse/CDAP-DUT4089

CDAP-5573 Set the state of ProgramController to ERROR when a component ends with an error
