caskdata/cdap

cdap-docs/admin-manual/source/operations/scaling-instances.rst, cdap-docs/reference-manual/source/cli-api.rst, cdap-docs/reference-manual/source/http-restful-api/lifecycle.rst
The documentation was there, just hard to find. Fixes [CDAP-1097](https://issues.cask.co/browse/CDAP-1097).
Added documentation on the scaling of services. 
Added links and references to the three different ways that components can be scaled.
Staged at:
http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.0-SNAPSHOT-r2.6.0_fix_services/en/index.html
In particular, look at:
- [Scaling Instances, first section](http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.0-SNAPSHOT-r2.6.0_fix_services/en/admin-manual/operations/scaling-instances.html)
- [Scaling Instances, Scaling Services section](http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.0-SNAPSHOT-r2.6.0_fix_services/en/admin-manual/operations/scaling-instances.html#scaling-services)
=> Fix for CDAP-1097 (Missing Services Scaling Documentation)

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/MultiLiveStreamFileReader.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileReader.java
This remove the need for waiting on an extra cycle unnecessarily.
E.g. Timeout = 0, unit = SECONDS
stopwatch.elapsedTime(SECONDS) > 0 will be false until 1 second is passed
=> Fix the condition of timeout checking from > to >= to timeout earlier

cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithSchedule.java
I don't think the dummyAction needs to be added twice.
=> Remove redundant addition of action in workflow

cdap-docs/admin-manual/source/installation/security.rst
Corrects the formatting of the security documentation tables. The main change is making most items in the tables literals and thus in code font.
Additionally, added text about paths being either absolute or relative to the CDAP SDK for these properties:
- cdap.master.kerberos.keytab
- security.auth.server.ssl.keystore.path
- router.ssl.keystore.path
- dashboard.ssl.cert
- dashboard.ssl.key
- security.authentication.basic.realmfile
Added a sentence at the end of the first section describing relative and absolute paths.
Staged at:
http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.0-SNAPSHOT-r2.6.0_fix_security_docs/en/admin-manual/installation/security.html
=> Fix security docs formatting

cdap-docs/reference-manual/source/release-notes.rst
Adds a Known Issue to the release notes for all versions of CDAP for [TWILL-110](https://issues.apache.org/jira/browse/TWILL-110).
Staged at: [2.6.0 Release Notes](http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.0-SNAPSHOT-r2.6.0_twill_issue/en/reference-manual/release-notes.html#known-issues)
Last item of the *2.6.0 Known Issues*; references added to the other versions. Will be added to 2.5.2 docs once approved.
=> TWILL-110 Known Issue of CDAP

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/DeleteMetricsHandler.java
deleting timeseries metrics is incredibly inefficient and causes app deletion timeout at the moment.
=> delete only aggregated metrics on delete app

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamDataFileTestBase.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/TimePartitionedStreamTestBase.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/file/FileWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/file/PartitionedFileWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/InMemoryStreamFileWriterFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileWriter.java
- The batch write support also guarantees events from the same batch that have the same timestamp are written in the same data block. This is an essential part to support file upload for stream.
=> (CDAP-1153) Added support of batch write to Stream file writer

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamInputFormatTest.java
=> ts was taken out of record because it was redundant, but was not

cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/increment/hbase94/IncrementHandler.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementHandlerTest.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementSummingScannerTest.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementHandler.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementHandlerTest.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScannerTest.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementHandler.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementHandlerTest.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScannerTest.java
We need that for tables that are non-transactional, but want to use readless increments. E.g. metrics table.
=> allow configure unlim compaction bound for table with readless incs

cdap-api/src/main/java/co/cask/cdap/api/data/stream/StreamBatchReadable.java, cdap-api/src/main/java/co/cask/cdap/api/stream/GenericStreamEventData.java, cdap-api/src/main/java/co/cask/cdap/api/stream/StreamEventData.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamInputFormatTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamInputFormat.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/decoder/FormatStreamEventDecoder.java, cdap-unit-test/src/test/java/co/cask/cdap/mapreduce/AppWithMapReduceUsingStream.java
that read the stream body as something other than a
StructuredRecord.
=> clean up the mapreduce api around stream format to allow formats

cdap-data-fabric/src/main/java/co/cask/cdap/data/file/FileWriters.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamInputSplitFinder.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamFetchHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/AbstractStreamFileConsumerFactory.java, cdap-data-fabric/src/test/java/co/cask/cdap/data/stream/StreamUtilsTest.java
This is a preparation step to support file upload REST endpoint. When the REST endpoint is added, there will be temp directory created under the stream directory, which could affect logic that scans the stream directory for set of partitions.
Also, piggy-back an addition of `FileWriters` util class, which is a pretty straightforward class right now.
=> (CDAP-960) Added method to filter valid stream partition directory (Stream upload Part 1)

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/InMemoryStreamFileWriterFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/LocationStreamFileWriterFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/TimePartitionedStreamFileWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/TimestampCloseable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/MutableStreamEvent.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/MutableStreamEventData.java
1. Expose the stream file prefix from the StreamFileWriterFactory
2. Introduce interface TimestampCloseable interface and have StreamDataFileWriter implements it to expose close timestamp
3. Add new classes MutableStreamEventData and MutableStreamEvent
4. Refactor TimePartitionStreamFileWriter
=> (CDAP-960) Collections of small stream changes

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/OperationException.java
OperationException existed in legacy code. We don't need it anymore, the implementation doesn't throw OperationException. 
Removing it now so that the new code that is added doesn't need to follow the same.
=> Remove OperationException from MDS

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamDataFileTestBase.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileReader.java
In the old logic, the position is not always update to date,
causing re-reading the same data-block again.
=> Update the reader position correctly.

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriterTestBase.java
- It seems like it sometime takes longer than 5 seconds to finish on slow machine.
=> Increase the test timeout for DFS concurrent writer test

cdap-docs/developers-manual/source/getting-started/standalone/docker.rst
- Remove `boot2docker` docs... Docker has documented its usage well enough
- Use `http://localhost:9999` to match our published ports (otherwise, why publish them)
- Replace VM with Container
- Remove Dev Environment includes
=> Clean up docker docs

cdap-web-app/client/core/controllers/workflow-status.js, cdap-web-app/client/core/models/mapreduce.js, cdap-web-app/client/index.html
Fixes the workflow UI based on changes in the backend API.
Existing API returned everything (schedules, mapreduces etc.,) in the same API call (apps/PurchaseHistory/workflows/PurchaseHistoryWorkflow)
Right now this has been split up into separate calls for schedules and mapreduce. 
The structure of actions in a workflow and structure of schedules object are the ones changed. The UI changes are related to changing the property names to appropriate changes in the API.
=> Fixes workflow ui with changes in backend API

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGenerator.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTest.java
Along with a 500 response code, send back a response message saying a transaction failure occurred.
https://builds.cask.co/browse/CDAP-DUT560-1/
=> (CDAP-616) Send error string in response upon transaction failure

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsQueryTestRun.java, cdap-security/src/main/java/co/cask/cdap/security/server/GrantAccessToken.java, cdap-security/src/test/java/co/cask/cdap/security/server/ExternalAuthenticationServerTestBase.java
Even when given an explicit header value, `netty-http` overrides the `Content-Type` header value to `octet-stream` when using the `sendByteArray` or `sendBytes` methods (which is probably the right thing to do). Instead I've replaced the calls with `sendJson`, which also cleans up the implementation. 
Some minor unrelated cleanups as well.
Build: https://builds.cask.co/browse/CDAP-DUT553-2/
=> (CDAP-1098) Use sendJson instead of explicitly setting header type

cdap-web-app/bin/config-tool
fixes https://issues.cask.co/browse/CDAP-998
This appears to be only used in distributed mode packaged along with the init framework, hence the sourcing of common.sh
=> find java executable via sourced common.sh

cdap-client-tests/src/test/java/co/cask/cdap/client/StreamClientTestRun.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamFetchHandler.java
- Also increase the CHUNK_SIZE from 20 to 8K. Chunk size that is too small will only brings overhead to the output without any benefits.
=> (CDAP-1234) Copy the buffer for chunk output since the buffer will get reused

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/AbstractMapReduceContextBuilder.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextProvider.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceMetricsWriter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetRecordReader.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AggregateMetricsByTag.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithMapReduce.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsDiscoveryQueryTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsQueryTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionService.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/MapReduceCounterCollectionService.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricRecordsWrapper.java
https://issues.cask.co/browse/CDAP-1238
Couple notes:
* all mapreduce metrics emitted as gauges, as this is how mr counters work that we use
* for that to work properly, we need to emit from tasks with task id in the context, so that for aggregate values all are summed (as expected)
* metrics collector's context in tasks now has only task type and id - since metrics reported by mr program runner, all other tags present in its context (like app id, etc.)
* added emitting custom metrics in mr tests which cought couple isuues by itself, no asserting results well - without refactoring that is coming later it is really hard
=> fix metrics collection in mapreduce

cdap-app-fabric/src/main/java/co/cask/cdap/test/RuntimeStats.java, cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteApplicationManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultApplicationManager.java
Instead of sleeping based on the provided timeout unit, which could easily sleep for a minute without checking, bound the sleep time by 1 second.
This should improve the responsively of quick a number of test cases that wait for completion by polling.
=> Bound sleep time

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
Summary:
1. Fixed an NPE in ``NamespaceHttpHandler``
2. Combined two tests into one.
Build: https://builds.cask.co/browse/CDAP-RBT73-1/
=> [CDAP-1115] Fixed NPE in NamespaceHttpHandler

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
* Mostly contains refactor of ``AppLifecycleHttpHandlerTest``, ``ProgramLifecycleHttpHandlerTest`` and ``PreferencesHttpHandlerTest`` to move common members/methods to base class ``AppFabricTestBase``.
* Enabled verification for the following v3 APIs:
* Delete app while flow is running
* Change flowlet stream connection
* Merged two almost similar slow tests ``testRunnableStatus`` and ``testProgramStartStop`` into one. Achieves a tiny speedup of ~15 seconds
=> [CDAP-1041] [CDAP-1201] Refactor App Fabric Http V3 tests

cdap-client-tests/src/test/java/co/cask/cdap/client/StreamClientTestRun.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java
It used to record the content type of the original batch request
=> Added content.type header to stream event

cdap-examples/FileSetExample/src/main/java/co/cask/cdap/examples/fileset/WordCount.java
MR fails due to unavailability of heap space otherwise. Defaults were not enough. 
Bamboo : https://builds.cask.co/browse/CDAP-RBT93
=> Set memory resources for Mapper, Reducer tasks

pom.xml
Updating ``netty-http`` version to pull in fix for [CDAP-744](https://issues.cask.co/browse/CDAP-744).
Build: https://builds.cask.co/browse/CDAP-RBT98-1
=> [CDAP-744] Updating netty-http version to pull in fix for CDAP-744.

cdap-standalone/pom.xml
a stream that has been bulk-uploaded.
=> CDAP-1272 fix ClassNotFoundException in cdap-sdk when querying

cdap-common/bin/service
This allows the user to update settings for CDAP by editing `CDAP_CONF/cdap-env.sh` or `/etc/cdap/conf/cdap-env.sh` in most installations. Otherwise, users are required to edit files in CDAP_HOME, which will get replaced on package upgrades.
=> CDAP-1268 Allow user-defined variables outside CDAP_HOME

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricClient.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppFabricHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java, cdap-docs/reference-manual/source/http-restful-api/lifecycle.rst, cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteApplicationManager.java, cdap-test/src/main/java/co/cask/cdap/test/ScheduleManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultApplicationManager.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
1. Updated following schedule endpoints:
a) Moved apps/{app-id}/workflows/{workflow-id}/schedules/{schedule-name}/status to apps/{app-id}/schedules/{schedule-name}/status
b) Moved apps/{app-id}/workflows/{workflow-id}/schedules/{schedule-name}/suspend to apps/{app-id}/schedules/{schedule-name}/suspend
c) Moved apps/{app-id}/workflows/{workflow-id}/schedules/{schedule-name}/resume to apps/{app-id}/schedules/{schedule-name}/resume 
2. Updated unit test cases to reflect the new end-points.
3. Added unit test case for accessing the schedules in another namespace which should give 404. 
Note that schedule status endpoint is handled by /apps/{app-id}/{runnable-type}/{runnable-id}/status and schedule suspend/resume endpoint is handled by /apps/{app-id}/{runnable-type}/{runnable-id}/{action}. …
=> Updated schedule endpoints.

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseOrderedTableTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/increment/hbase/IncrementHandlerState.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/increment/hbase/SettableTimestampOracle.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/increment/hbase/TimestampOracle.java, cdap-data-fabric/src/test/java/co/cask/cdap/data/hbase/HBaseTestBase.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/increment/hbase/AbstractIncrementHandlerTest.java, cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/increment/hbase94/IncrementHandler.java, cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/increment/hbase94/IncrementSummingScanner.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data/hbase/HBase94Test.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementHandlerTest.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementSummingScannerTest.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementHandler.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScanner.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data/hbase/HBase96Test.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementHandlerTest.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScannerTest.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementHandler.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScanner.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data/hbase/HBase98Test.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementHandlerTest.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScannerTest.java
This change makes readless increments safe to use in a non-transactional context by assigning a region-unique timestamp to all writes, similar to how the Tephra TransactionManager assigns timestamp based transaction IDs.
The change breaks down into a few parts:
* IncrementHandlerState factored out to reduce code duplication between IncrementHandler implementations
* IncrementHandler implementations updated to assign timestamps in non-transactional case
* AbstractIncrementHandler pulled out to provide a single set of test cases for IncrementHandlerTest implementations.  Also added test cases for mixed increment, put, delete and TTL handling.
* HBaseTestBase, HBaseTest94, HBaseTest96 HBaseTest98 refactored to reduce code duplication (supports shared test cases in …
=> CDAP-1185 Assign unique timestamps for non-transactional readless increments

cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/ExecuteQueryCommand.java
Temporary Fix for https://issues.cask.co/browse/CDAP-1281
We need to have a better fix - returning a QueryHandle and a separate command to fetch results using that QueryHandle.
Bamboo : https://builds.cask.co/browse/CDAP-RBT106-1
=> Increasing timeout to 1hour from 30secs

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
because it was translating a RowSet to a TRowSet (thrift object),
and then getting the rows from that. But different versions of
the protocol get the rows differently, with older versions using
a RowBasedSet and newer versions using a ColumnBasedSet that
behave differently. Instead, we should just be using the RowSet
directly.
=> CDAP-1255 the explore service was not returning any results

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/BasicStreamWriterSizeCollector.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamServiceRuntimeModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/heartbeat/HeartbeatPublisher.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/heartbeat/NotificationHeartbeatPublisher.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/service/AbstractNotificationService.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/service/kafka/KafkaMessage.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/service/kafka/KafkaNotificationService.java
- It was assumed that only one partition would be created for each notification feed in Kafka, but ``kafka.num.partitions`` are actually created. For now, the subscriber to a feed will subscribe to all the partitions for the topic in which the notifications for the feed will be stored.
- Leader election was not started in the ``DistributedStreamService``
- The counting logic was wrong in the aggregation of heartbeats in the ``DistributedStreamService``
- Truncating the stream meant creating an aggregator based on the initial threshold of the stream, and not the updated one, if it had been updated.
Build: https://builds.cask.co/browse/CDAP-RBT102
=> Fix a few bugs for Notifications in Streams to work

cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricRecordsWrapper.java
Corrects ``contains`` logic.
Fixes 9/25 failing audi tests. 
Build: https://builds.cask.co/browse/CDAP-RBT113-1
=> [CDAP-1284] Fixed contains logic in metrics aggregation

cdap-docs/_common/_source/404.rst, cdap-docs/_common/_themes/cdap/search.html
After some more testing and discussion, it has been decided to remove Google Search from the Search page and the 404 page, as it is not ready for release. Certain terms were not finding any results, even when they should or could.
See CDAP-1039 (https://issues.cask.co/browse/CDAP-1039)
Staged at:
- [Search](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_404_search_pages/en/search.html)
- [404](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_404_search_pages/en/404.html)
=> Revised 404 and Search documentation pages

cdap-docs/examples-manual/source/examples/count-random.rst, cdap-docs/examples-manual/source/examples/fileset.rst, cdap-docs/examples-manual/source/examples/hello-world.rst, cdap-docs/examples-manual/source/examples/purchase.rst, cdap-docs/examples-manual/source/examples/spark-k-means.rst, cdap-docs/examples-manual/source/examples/spark-page-rank.rst, cdap-docs/examples-manual/source/examples/web-analytics.rst, cdap-docs/examples-manual/source/examples/word-count.rst
Fixes a broken link in the source files for examples, such a file to be included wasn't included.
Bad link: http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT/en/examples-manual/examples/hello-world.html#running-cdap-applications ("Running CDAP Examples" is empty)
Fixed link: http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_examples_fix/en/examples-manual/examples/hello-world.html#running-cdap-applications ("Running CDAP Examples" is included and versioned: see first bullet under "Deploying an Application")
=> Fixes broken link.

cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricRecordsWrapper.java
Moved ``instanceId`` outside Aggregation Rules and used it if available.
Fixes audi tests for services metrics.
Build: https://builds.cask.co/browse/CDAP-RBT123-1
=> [CDAP-1284] Move instanceId outside rules

cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricClient.java
This is necessary in case a flowlet or other program wishes to use hbase classes (which are not exposed by cdap).
For instance, the test cases in cdap-etl-pack fail due to ClassNotFoundException, because it tries to use hbase classes.
Build is GREEN:
https://builds.cask.co/browse/CDAP-RBT120-2
=> Avoid excluding hbase classes from bundled jar in unit tests.

cdap-client-tests/src/test/java/co/cask/cdap/client/PreferencesClientTestRun.java
Fixing a timing issue where we try to query the service before it is started. So wait until the service status turns to running.
Bamboo : https://builds.cask.co/browse/CDAP-RBT124
=> Wait for Service to start/stop

cdap-docs/developers-manual/source/advanced/index.rst, cdap-docs/developers-manual/source/data-exploration/custom-datasets.rst, cdap-docs/developers-manual/source/data-exploration/filesets.rst, cdap-docs/developers-manual/source/data-exploration/index.rst, cdap-docs/developers-manual/source/data-exploration/integration.rst, cdap-docs/developers-manual/source/data-exploration/streams.rst, cdap-docs/developers-manual/source/index.rst, cdap-docs/developers-manual/source/table-of-contents.rst, cdap-docs/reference-manual/source/http-restful-api/stream.rst, cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseApp.java
filesets. Moved data exploration out of the advanced section and
into its own section. This is because there is is now much more
content about exploration, and because we want exploration to be
one of the starting points for people and not advanced usage.
=> CDAP-1156 adding documentation for exploration of streams and

cdap-docs/developers-manual/source/building-blocks/datasets/system-custom.rst, cdap-docs/developers-manual/source/building-blocks/datasets/table.rst, cdap-docs/developers-manual/source/building-blocks/transaction-system.rst, cdap-docs/reference-manual/source/http-restful-api/dataset.rst
Adds an example to the custom datasets documentation of using a DatasetSpecification to pre-split a table.
Fix for [CDAP-1112](https://issues.cask.co/browse/CDAP-1112).
=> Fix for CDAP-1112: No documentation for pre-splitting in table datasets

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/installation/quick-start.rst
Fix for [CDAP-1390](https://issues.cask.co/browse/CDAP-1390)
Staged at:
[Installation](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_zookeeper_docs/en/admin-manual/installation/installation.html) Second "Note" of "Hadoop/HBase Environment"
[Quick-start](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_zookeeper_docs/en/admin-manual/installation/quick-start.html) Last line under "Preparing the Cluster"
=> Zookeeper Configuration documentation

cdap-docs/admin-manual/source/installation/security.rst
Preliminary Fix for [CDAP-1289](https://issues.cask.co/browse/CDAP-1289): adding descriptions to security options for cdap-site.xml
The security page tables have been adjusted, and I have added to them as I saw fit, but there are gaps missing that need fixing. CDAP-1289 is about adding descriptions for all the settings for security; however, it's not clear what they are for, and so require assistance in completing. **Please check and confirm that all descriptions are accurate!**
Staged Page: [Security Page](http://stg-web101.sw.joyent.continuuity.net/cdap/2.7.0-SNAPSHOT-r2.7.0_security/en/admin-manual/installation/security.html)
=> Descriptions for Security options for cdap-site.xml

cdap-watchdog/src/main/java/co/cask/cdap/metrics/data/EntityTable.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/Fact.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactCodec.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactScan.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactScanResult.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactScanner.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/MeasureType.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/TagValue.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/TimeValue.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/package-info.java, cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactCodecTest.java, cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactTableTest.java
Fact table will be used by changed metric storage layer.
Sub-task https://issues.cask.co/browse/CDAP-1321 of https://issues.cask.co/browse/CDAP-1243, which is part of this epic: https://issues.cask.co/browse/CDAP-1138. A step towards design reviewed in https://issues.cask.co/browse/CDAP-760.
=> initial FactTable commit

Dockerfile
When modules are added to CDAP, they need to be added to the Docker build context.
=> Update Dockerfile to match new modules in CDAP

cdap-cli/bin/cdap-cli.sh
fixes the case when cdap-cli.sh invoked via an alternatives link and does not resolve its location properly, resulting in an empty classpath
this would be needed in order to include the cli into the CDAP parcel.
=> cdap-cli doesnt resolve its location correctly

cdap-docs/_common/common_conf.py
Remove "new" icon badge from the Integrations manual, and add docs about using icons.
=> Remove "New" badge from current (develop) docs build

cdap-docs/examples-manual/source/examples/stream-conversion.rst, cdap-docs/integrations/source/partners/cloudera/configuring.txt, cdap-docs/reference-manual/source/release-notes.rst
Replaces references to "2.7.0" with either references to non-versioned links or to 2.7.1
=> Replace references to 2.7.0.

cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsClientRuntimeModule.java
NOTE: merges into metric-store-integrated branch (as per #1251)
=> fix metric standalone binding for unit-tests

cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/TableId.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/util/hbase/AbstractHBaseTableUtilTest.java, cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/util/hbase/HBase94TableUtil.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/util/hbase/HBase96TableUtil.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/util/hbase/HBase98TableUtil.java
Adds preliminary APIs in ``HBaseTableUtil`` to use HBase namespaces. Updated unit test to use APIs.
Currently tested on a .98 cluster to ensure that the *configuration* table gets created in the *cdap_system* HBase namespace. (Those changes are not included in this PR, this PR only contains new APIs in compat modules).
These APIs will evolve till we complete the namespaces work in datasets. To summarize, the APIs manage HBase namespaces, as well as help construct ``HTableDescriptor`` and ``HTable`` objects using ``TableName`` objects if they are available in specific HBase versions. Otherwise, the ``HTableDescriptor`` and ``HTable`` objects are created using String prefixes.
```
boolean namespacesSupported()
HTableDescriptor getHTableDescriptor(TableId tableId)
HTable …
```
=> [CDAP-1376] Introduced HBase namespaces in compat modules

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java, cdap-common/src/main/java/co/cask/cdap/common/http/RESTMigrationUtils.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetServiceModules.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerV2.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetTypeHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetTypeHandlerV2.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandlerV2.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandlerV2.java
Adds mock v3 APIs for dataset admin op handler.
v2 APIs deletegate to v3 handler.
Actual namespace usage will come in a later PR.
Build: http://builds.cask.co/browse/CDAP-DUT759
=> v3 dataset admin handler

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HTableDatasetAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java, cdap-master/src/main/java/co/cask/cdap/data/tools/Main.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/MetricsConstants.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/MetricDatasetFactory.java
Follow up on #1251 , addresses:
* remove + .v2 in dataset names
* upgrade metric datasets (part, see CDAP-1458 for rest)
=> metric store table rename and prepare for upgrade

cdap-cli/src/main/java/co/cask/cdap/cli/command/DescribeStreamCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetStreamFormatCommand.java, cdap-client-tests/src/test/java/co/cask/cdap/client/StreamClientTestRun.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamCoordinatorTestBase.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/AbstractStreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/CoordinatorStreamProperties.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamAdmin.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceStreamTest.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTestRun.java, cdap-proto/src/main/java/co/cask/cdap/proto/StreamProperties.java
The field `name` is unnecessary in StreamProperties, because its used as an interchange between client/server. Anytime the StreamProperties is exchanged, the surrounding system is already operating on a particular stream.
For instance, when user does a PUT of StreamProperties via REST call, they anyways pass streamName in the path of the endpoint (so no need to have two sources for the same piece of information). Same for retrieval of StreamProperties.
Build: http://builds.cask.co/browse/CDAP-DUT765-4
=> Remove name field from StreamProperties

cdap-examples/StreamConversion/src/test/java/co/cask/cdap/examples/streamconversion/StreamConversionTest.java
use partition time instead of start time to validate
=> [CDAP-1462] Stream adapter test sometimes fails

cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionDatumReader.java, cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionDatumWriter.java, cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionPutWriter.java, cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionReader.java, cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionRowReader.java, cdap-common/src/main/java/co/cask/cdap/internal/io/ReflectionWriter.java, cdap-data-fabric/src/test/java/co/cask/cdap/api/dataset/lib/ReflectionTableTest.java
can be re-used for formats other than our avro-like binary
encoding. Also adding classes that encode objects as Put objects
to be written to a Table, and decode objects from Row objects
fetched from a Table.
=> CDAP-1411 refactor reflection writer/reader classes so that they

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/CommandCategory.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateAdapterCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateStreamConversionAdapterCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteAdapterCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/ListAdaptersCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/UseNamespaceCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DefaultCommands.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/NamespaceCommands.java, cdap-client-tests/src/test/java/co/cask/cdap/client/AdapterClientTest.java, cdap-client/src/main/java/co/cask/cdap/client/AdapterClient.java, cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java, cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java, cdap-client/src/main/java/co/cask/cdap/client/ServiceClient.java
I needed this change to make it easier to demo namespaces of streams.
Dataset-related clients are not being namespaced in this PR, as the entities are not namespaced in CDAP.
Build: http://builds.cask.co/browse/CDAP-DUT801-5
=> namespace clients

cdap-cli/src/main/java/co/cask/cdap/cli/command/GetStreamStatsCommand.java
* Fixed bug in determining length of the longest bucket prefix (e.g. "  [200, 299]: ")
* Changed rendering style to be as shown below:
```
[8800, 8899]: 12       |+
[8900, 8999]: 22       |+++
[9000, 9099]: 16       |+
[9100, 9199]: 9        |
```
=> Fixed histogram rendering in GetStreamStatsCommand

cdap-cli/src/main/java/co/cask/cdap/cli/docs/GenerateCLIDocsTableCommand.java
```
**General**
``connect <cdap-instance-uri>``,"Connects to a CDAP instance."
``exit``,"Exits the CLI"
``help [<command-category>]``,"Prints this helper text. Optionally provide <command-category> to get help with a specific category"
``quit``,"Exits the CLI"
``search commands <query>``,"Searches available commands using regex"
``version``,"Prints the version"
**Namespace**
``create namespace <namespace-id> [<namespace-display-name>] [<namespace-description>]``,"Creates a namespace in CDAP."
``delete namespace <namespace-id>``,"Deletes a Namespace."
``describe namespace <namespace-id>``,"Describes a Namespace."
``list namespaces``,"Lists all Namespaces."
``use namespace <namespace-id>``,"Changes the current Namespace"
**Lifecycle**
``create adapter <adapter-name> type <adapter-type> …
```
=> Use same category order in GenerateCLIDocsTableCommand and HelpCommand

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/NamespacedDatasetFramework.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java
Main functional changes:
1. ``DatasetServiceClient`` is namespace-local.
2. ``RemoteDatasetFramework`` has a cache of ``Id.Namespace`` -> ``DatasetServiceClient``
3. ``DatasetFramework``'s ``deleteAllModules()`` method is now ``deleteAllModules(Id.Namespace)``
=> Namespace-local DatasetServiceClient.

cdap-api/src/main/java/co/cask/cdap/api/app/AbstractApplication.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/CounterTimeseriesTable.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimeseriesTable.java, cdap-docs/_common/common-build.sh, cdap-docs/build.sh
Fixes broken Javadoc build. 
Fixes two long-standing Javadoc warnings (bugs) that resulted from using "..." where "[]" was required.
Added code to documentation build scripts to allow for building just the Javadocs.
Produces a clean Javadoc build. First in a very long time...
=> Fixes Javadoc and SDK build

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
Fixes an issue mentioned in JIRA for stream create:
https://issues.cask.co/browse/CDAP-1469
The issue in the JIRA is actually a much larger issue, dealing with all sorts of other program/data types and their handlers as well.
Build: http://builds.cask.co/browse/CDAP-DUT821-4
=> streamCreate returns 400 instead of 500, if given invalid stream name

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/AbstractSchedulerService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DistributedSchedulerService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/LocalSchedulerService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/ScheduleStoreTableUtil.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java, cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricTestHelper.java, cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/guice/AppFabricTestModule.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/scheduler/SchedulerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java, cdap-master/src/main/java/co/cask/cdap/data/tools/Main.java
- Create a shell of a StreamSizeScheduler. It integrates in the ``AbstractSchedulerService``. 
- The ``TimeScheduler`` is moved, from inside the ``AbstractSchedulerService`` class to its own class.
- The ``AbstractSchedulerService`` uses the metastore to check the type of a schedule, to route the operations to the right scheduler (either TimeScheduler or StreamSizeScheduler).
- The ``SchedulerServiceTest`` is modified so that the schedules that are... scheduled, do appear in the metastore.
Build: http://builds.cask.co/browse/CDAP-DUT819
=> Create a new StreamSizeScheduler

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
The past fix was half the fix.
Also, correct a bug introduced when streams were first namespaced.
Build: http://builds.cask.co/browse/CDAP-DUT814-6
=> [CDAP-1444] Retry logic when trying to create the heartbeats feed

cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/DistributedMetricsClientModule.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsClientRuntimeModule.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsHandlerModule.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/runtime/MetricsProcessorTwillRunnable.java
MetricStore interface is an API that will be used by different components for querying metrics data. We want to expose it.
=> expose MetricStore in metric client guice module

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java
- adds an upgrade method. It needs to be called repeatedly until all records are migrated
- that is to prevent transaction timeout. 
- adds a unit test for the upgrade
=> upgrade method for time partitioned file sets

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
Applications among namespaces were leaked in system namespace. this fixes the issue.
=> fix app leak across namespace in system

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ProcedureClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java, cdap-client/src/main/java/co/cask/cdap/client/ProcedureClient.java, cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java, cdap-client/src/main/java/co/cask/cdap/client/util/VersionMigrationUtils.java
V3 procedure APIs will be removed.
In order to facilitate that, moving procedure operations from CLI + Client to hit the V2 endpoints.
These effective changes can be removed once procedures are completely removed from CDAP.
Now, from the CLI, procedure operations will only function if the user is in the default namespace. Otherwise, they will receive an error message:
```Error: Procedure operations are only supported in the default namespace.```
Build: http://builds.cask.co/browse/CDAP-DUT856-4
=>  Procedure operations to use v2 APIs

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/UnderlyingSystemNamespaceAdmin.java
The soft delete would not work if you deleted multiple times. 
We can implement soft delete separately in a better way (with a janitor) as a separate PR. 
Until then, using delete because this will cause build failures the next time develop builds.
Build: https://builds.cask.co/browse/CDAP-DUT872
=> Removed soft delete until we come up with a good way of managing trash

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/KeyValueTable.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/AbstractTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTable.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableTest.java, cdap-docs/developers-manual/source/building-blocks/datasets/table.rst, cdap-examples/WordCount/src/main/java/co/cask/cdap/examples/wordcount/RetrieveCountsHandler.java
Adds a multi-get operation to Table, IndexedTable and KeyValueTable.  This also adds sample usage of the multi-get operation to the WordCount example app, and some minor documentation to the datasets guide.
=> CDAP-73 Add multi-get operation to Table

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NotificationFeedHttpHandler.java
It removes exceptions shown in the master logs when starting CDAP.
=> Catch exceptions thrown in the notification feed handler

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java, cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricDataQuery.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/CubeQuery.java
due to ImmutableMap, we were returning 500 when there were null in tag-value.
build running : http://builds.cask.co/browse/CDAP-DUT896-1
=> bugfix : Allow query metrics with wildcard

cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/coprocessor/ConsumerConfigCache.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/QueueTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java, cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase94/HBaseQueueRegionObserver.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase96/HBaseQueueRegionObserver.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase98/HBaseQueueRegionObserver.java
- Since we have one config table per namespace, the cache update thread should stop if the table doesn’t exists.
=> Stop queue config table cache update thread when the table is gone.

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/FileContentWriter.java
Using the toString of Id.Stream object in file path is not good. Also, streamId is not necessary in the path in this case as the directory it is passed is already namespaced for the stream it is writing to.
Alternative: namespace (for a particular stream) the eventFile/indexFile in this class (instead of namespacing the directory and then passing it in - from FileContentWriterFactory).
Resolves: https://issues.cask.co/browse/CDAP-1619
Build: http://builds.cask.co/browse/CDAP-RBT133-1
=> Fix CDAP-1619

cdap-api/src/main/java/co/cask/cdap/api/service/ServiceWorkerContext.java, cdap-api/src/main/java/co/cask/cdap/api/service/TxRunnable.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/BasicServiceWorkerContext.java, cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithServices.java
Users should have to modify as little code as possible when they upgrade CDAP versions (marking it as deprecated first so they have plenty of time to modify the code to new APIs).
Brought back a copy of TxRunnable in cdap.api.service package, and changed AppWithServices to use it to test it. Simply delegates execution to the TxRunnable in cdap.api package.
Also removed the checked Exception from TestBase#clear method (it has been deprecated for 2.8, so we should support it as is in previous version, until we remove it).
Unsure how to handler RuntimeStats#clearStats(String). Perhaps we can't do anything but remove that method and require the user to modify their code.
http://builds.cask.co/browse/CDAP-DUT904-5
=> Source backwards compatability

cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceTestRun.java
Two small changes:
1. No-op the creation of the "default" namespace in Hive. This prevents an additional log warning.
2. Database creation and usage is now "cdap_<namespace-id>".
=> (CDAP-1627) No-op default database creation in Hive

cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTest.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTestV2.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTestV3.java
PR contains the following changes
* Removed v3/namespaces/{id}/streams/{id}/info endpoint
* Added v3/namespaces/{id}/streams/{id} endpoint
* Removed v3/namespaces/{id}/streams/{id}/config endpoint
* Added v3/namespaces/{id}/streams/{id}/properties endpoint
* Corresponding Stream Client changes for CLI
Related JIRA: https://issues.cask.co/browse/CDAP-1641
Build: http://builds.cask.co/browse/CDAP-DUT936-2
=> Streams V3 API changes

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueConsumer.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTableTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableTest.java
Two issues fixed:
* in level db case, in non-tx, we should not write empty byte array delete tombstone
* in hbase case, in non-txt, when deleting a column, Delete.deleteColumnS method must be called to delete all versions
Just in case also added unit-test for transactional table.
=> fix non-tx delete increments (metrics tables)

cdap-docs/_common/_source/index.rst, cdap-docs/_common/common_conf.py, cdap-docs/admin-manual/source/index.rst, cdap-docs/developers-manual/source/building-blocks/transaction-system.rst, cdap-docs/developers-manual/source/index.rst, cdap-docs/developers-manual/source/overview/abstractions.rst, cdap-docs/reference-manual/source/glossary.rst, cdap-docs/reference-manual/source/index.rst, cdap-docs/reference-manual/source/licenses/index.rst, cdap-docs/reference-manual/source/release-notes.rst, cdap-docs/reference-manual/source/table-of-contents.rst
Adds info on Trademarks, adds trademark symbols, moves the trademark symbol replace directives to the common file, so they are available in all files.
Corrects some usages of trademarks. Makes the copyright string available as a replace directive, and uses it on the License page.
Staged at: [2.8.0-SNAPSHOT-2.8.0_trademarks](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-2.8.0_trademarks/en/index.html)
=> Update usage of Trademarks

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgraderMain.java
The stopping message can be confusing in ideal case when upgrade runs well as its basically completing and not stopping. Just getting rid of it.
=> remove confusing info log

cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteNamespaceCommand.java
https://issues.cask.co/browse/CDAP-1629
This is what happens when you delete the current namespace now:
```
cdap (http://127.0.0.1:10000/default)> create namespace sdf
Namespace 'sdf' created successfully.
cdap (http://127.0.0.1:10000/default)> use namespace sdf
Now using namespace 'sdf'
cdap (http://127.0.0.1:10000/sdf)> delete namespace sdf
Namespace 'sdf' deleted successfully.
Now using namespace 'default'
cdap (http://127.0.0.1:10000/default)> 
```
=> CDAP-1629: Use default namespace when current namespace is deleted in CLI

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/DefaultCube.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactCodec.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java, cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactTableTest.java
* context search no longer returns "*"
* you can now search for context and metrics with tag values defined in any order
* tag value = "*" now means any non-null value, when searching
=> Improve metrics & context search

cdap-common/src/main/java/co/cask/cdap/common/conf/CConfigurationUtil.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/java/co/cask/cdap/common/guice/ConfigModule.java, cdap-common/src/test/java/co/cask/cdap/common/conf/CConfigurationUtilTest.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java, cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
StandaloneMain and MasterServiceMain do not start if the 'root.prefix' configured in CConfiguration is not strictly alphanumeric.
This is not a comprehensive list of all the checks we need to perform against the cConf, but it is a start - one that is necessary due to limitations on the characters that can be in hbase namespace, and assumptions we make about what values can be in the hbase namespace for cdap tables.
Note that our allowed values (strictly alphanumeric) are stricter than hbase's.
Build: http://builds.cask.co/browse/CDAP-DUT961-3
[Here is what happens in sdk when invalid root.prefix is given.](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/ZJstMN1Qken9iDD/Screen%20Shot%202015-03-03%20at%203.03.57%20PM.png)
Things to consider:
I am not restricting the zookeeper …
=> Restrict 'root.prefix' values.

cdap-app-fabric/src/main/java/co/cask/cdap/config/DefaultConfigStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/ScheduleStoreTableUtil.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetMetaTableUtil.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HTableNameConverter.java, cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/util/hbase/HTable94NameConverter.java, cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/util/hbase/HTable96NameConverter.java, cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/util/hbase/HTable98NameConverter.java, cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaverTableUtil.java
Fixes the CDAP-1715 and enables the upgrade tool to read the old meta data tables again 
Build : http://builds.cask.co/browse/CDAP-DUT1019-1
=> CDAP-1715: Upgrade tool now reads the old metatable again

cdap-data-fabric/src/test/java/co/cask/cdap/data2/increment/hbase/AbstractIncrementHandlerTest.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementHandlerTest.java, cdap-hbase-compat-0.94/src/test/java/co/cask/cdap/data2/increment/hbase94/IncrementSummingScannerTest.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementHandlerTest.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/increment/hbase96/IncrementSummingScannerTest.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementHandlerTest.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/increment/hbase98/IncrementSummingScannerTest.java
Need for this change arises due to the fact that the IncrementHandler coprocessor needs to read from the ConfigurationTable.
In order to do so, it needs to construct the configuration table name based off of the table the coprocessor instance is operating on, and so it needs the table prefix (which is 'cdap' by default).
In 2.7, this test case was fine, because of the following logic:
[release/2.7.0](https://github.com/caskdata/cdap/blob/release/2.7.0/cdap-data-fabric/src/main/java/co/cask/cdap/data2/increment/hbase/IncrementHandlerState.java#L78-L82)
So if it couldn't parse the root prefix, it improperly constructed the configuration table name, and so failed to talk to the ConfigurationTable.
Instead, the test cases should use a table name from which a root prefix can be computed (which …
=> Use TableId for IncrementHandlerTest / IncrementSummingScannerTest

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
Addresses: https://issues.cask.co/browse/CDAP-1648
Steps 2 and 3 of the JIRA have already been done during the separation of workers and services by @gokulavasan. The only problem was that the old endpoints also got transferred to v3.
=> (CDAP-1648) Remove deprecated instances endpoint for services

cdap-ui/app/features/admin/controllers/NamespaceCreateController.js
angular initialize $scope.model.name with empty string and it's causing the backend to process name to empty string.
=> CDAP-1722 Fix/namespace name

cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/ProgramRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/NamespaceAdmin.java, cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java, cdap-client-tests/src/test/java/co/cask/cdap/client/NamespaceClientTestRun.java, cdap-client-tests/src/test/java/co/cask/cdap/client/StreamClientTestRun.java, cdap-common/src/main/java/co/cask/cdap/common/namespace/AbstractNamespaceClient.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgraderMain.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultApplicationManager.java
Summary
Issues Addressed:
* [CDAP-870](https://issues.cask.co/browse/CDAP-870)
* [CDAP-1501](https://issues.cask.co/browse/CDAP-1501)
Build:
* http://builds.cask.co/browse/CDAP-DUT1027-JOB1-1/
=> [CDAP-870] Namespace Delete

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java, cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml, cdap-explore/src/main/java/co/cask/cdap/explore/service/HiveStreamRedirector.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive13ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/HiveCDH4ExploreService.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/HiveCDH5ExploreService.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveStreamRedirectorTest.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterMain.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
=> (CDAP-1395) Log rotation of containers

cdap-client-tests/src/test/java/co/cask/cdap/client/NamespaceClientTestRun.java
Ignoring NamespaceClientTestRun until its fixed correctly. Currently state from other tests seems to be impacting it.
=> Ignore NamespaceClientTestRun till its fixed

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/FileSetProperties.java, cdap-api/src/main/java/co/cask/cdap/api/flow/FlowSpecification.java
Two small changes: to fix the broken Javadoc build, and fix a few spelling mistakes I stumbled on upon the way.
=> Fix broken Javadoc build.

cdap-common/src/main/java/co/cask/cdap/common/queue/QueueName.java, cdap-master/src/main/java/co/cask/cdap/data/tools/QueueConfigUpgrader.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Adds the 2.8 ``QueueName`` to '``cdap.system.queue.config`` table.
Requires more rigorous testing. However, seeking feedback on the approach.
Note: This has to delete old rows since we share the same table in 2.8.
=> [CDAP-1515] Added queue config upgrade

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MonitorHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ServiceHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppFabricHttpHandlerTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceClientTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseOrderedTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/DequeueScanAttributes.java, pom.xml
https://issues.cask.co/browse/CDAP-1540
Porting from https://github.com/caskdata/cdap/pull/1571
=> CDAP-1540 Port to 2.6 - Exposing transaction manager APIs to truncate invalid list through Router

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDSUpgrader.java
We read the new meta table to get the filesets which is written with new key format. So read it in that way.
I had this fixed during the review process but looks like it got lost some where :/
=> fix upgrade tool filset key prefix

cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowApp.java, cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowAppWithScopedParameters.java
We collect spark program success status through the listener which list to job completion in spark. So we have to have a job in dummy programs. 
Opened a jira to find out if the improvement is possible: https://issues.cask.co/browse/CDAP-1806
=> add job in spark programs which runs in test

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramControllerServiceAdapter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramController.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/MapReduceTwillRunnable.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillRunnable.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramController.java
Jira: https://issues.cask.co/browse/CDAP-1744
Failure of a program was incorrectly attempting to mark them as COMPLETED. It should be marked KILLED.
=> Failure of the program should move it to KILLED instead of COMPLETED.

cdap-docs/_common/common-build.sh, cdap-docs/examples-manual/build.sh
Fix the Build to use curl to download example documentation and set the version based on the release.
It doesn't depend on the example documentation to be locally available; instead, it downloads it from GitHub.
=> Fix documentation build.

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/GetStreamStatsCommand.java
Jira: [CDAP-1837](https://issues.cask.co/browse/CDAP-1837)
Build: http://builds.cask.co/browse/CDAP-RBT168-2
=> [CADP-1837] Fix stream table name in get stream-stats command

Dockerfile
These two directories no longer exist. Tested on a `docker-base` single node spun up via Coopr in GCE.
=> CDAP-1841 Dockerfile fixes

pom.xml
Sometimes error appear in `LogAppenderInitializer` since there are multiple logging jars in the classpath. This explicitly excludes `slf4j-log4j12`.
I also built the rpms and ran: `find . -name "*.rpm" | xargs -I '{}' rpm -qlp '{}' | grep slf4j-log4j12`. This gave no output.
=> Exclude slf4j-log4j from hadoop-mapreduce-client-jobclient & hbase-testing-util

cdap-docs/reference-manual/source/characters.rst, cdap-docs/reference-manual/source/index.rst, cdap-docs/reference-manual/source/table-of-contents.rst
Fix for https://issues.cask.co/browse/CDAP-1565
Staged at: [Supported Characters](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_suported_characters/en/reference-manual/characters.html)
=> Document Supported Characters

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/installation/quick-start.rst, cdap-docs/reference-manual/source/faq.rst
Fix for https://issues.cask.co/browse/CDAP-837
Staged at: 
- [FAQ](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_java_version/en/reference-manual/faq.html#platforms-and-language)
- [Quick Start](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_java_version/en/admin-manual/installation/quick-start.html#software-prerequisites)
- [Installation](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_java_version/en/admin-manual/installation/installation.html#system-requirements)
For the last link, look at the "Java Runtime" section.
=> Add a recommendation for Oracle JDKs on installation instructions

cdap-master/src/main/java/co/cask/cdap/data/tools/MDSUpgrader.java
The start time is just a part of the key in runRecordCompleted so get it from there 
Issue: https://issues.cask.co/browse/CDAP-1843
Build: http://builds.cask.co/browse/CDAP-RBT172-1
=> CDAP-1843 fix NaN issue on start time after upgrade

cdap-distributions/src/debian/init.d/cdap-service, cdap-distributions/src/etc/default/cdap-master, cdap-distributions/src/rpm/init.d/cdap-service, cdap-docs/admin-manual/source/installation/installation.rst
This is a semi-reversal of #996 for CDAP-1171 which allows Explore to run on secure clusters by detecting the Hive CLASSPATH properly.
=> CDAP-1817 Run kinit on secure clusters so "hive -e" works

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/BasicServiceWorkerContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/worker/BasicWorkerContext.java
This is a temporary fix till we can handle cache timeouts more elegantly in the future.
=> Increase worker dataset cache timeout to 2 hours

cdap-common/src/main/resources/cdap-default.xml, cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaTopic.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/write/FileMetaDataManager.java
- Bump the version of kafka topic for new schema with namespace
- Increase the number of partitions
Issues: https://issues.cask.co/browse/CDAP-1861
Build: http://builds.cask.co/browse/CDAP-RBT189-1
=> CDAP-1861 bump the kafka topic version and parition  of logging for ns

cdap-client-tests/src/test/java/co/cask/cdap/client/common/ClientTestBase.java, cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamFileJanitorTestBase.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/StreamFileSizeFetcherTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/StreamAdminTest.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/hbase/HBaseFileStreamAdminTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/AbstractStreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/InMemoryStreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamFileJanitor.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamAdmin.java, cdap-unit-test/src/test/java/co/cask/cdap/batch/stream/BatchStreamIntegrationTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/DummyBaseCloneTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/DummyBaseTestRun.java
- We should disable the stream table in Hive when dropping a stream
- Also fixed a annoying exception when StreamClient is used to fetch events.
=> Fix dropping namespace issue

cdap-cli/src/main/java/co/cask/cdap/cli/command/system/RenderAsCommand.java, cdap-docs/reference-manual/source/cli-api.rst
Fixes a typo in the CLI help for the "RenderAsCommand", rewords it to have the options in both alphabetical and order of default.
Adds documentation for this feature to the CLI docs. Fixes a couple of other CLI doc formatting errors.
Running build locally on machine to check the Java code change.
=> Fixes for help command and documents the CLI rendering of tables

cdap-docs/admin-manual/source/operations/cdap-console.rst
Provides documentation on starting the new UI.
Staged at: [CDAP Console](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_new_gui/en/admin-manual/operations/cdap-console.html) or http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_new_gui/en/admin-manual/operations/cdap-console.html
=> Document new UI

cdap-docs/developers-manual/source/building-blocks/datasets/index.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/dataset.rst
Fix for https://issues.cask.co/browse/CDAP-406
Staged at:
- [Datasets](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_ttl_config/en/developers-manual/building-blocks/datasets/index.html) (see "Dataset Time-To-Live (TTL)")
- [RESTful API: Creating a Dataset](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_ttl_config/en/reference-manual/http-restful-api/http-restful-api-v3/dataset.html#creating-a-dataset) (see Example Body and Description)
- [RESTful API: Updating a Dataset](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_ttl_config/en/reference-manual/http-restful-api/http-restful-api-v3/dataset.html#updating-an-existing-dataset) (see Example Body and Description)
The latter two links were updated as to the example …
=> Add TTL configuring for Datasets.

cdap-master/src/main/java/co/cask/cdap/data/tools/MDSUpgrader.java
This will make the UI not list the apps making it explicit for the user that they need to redeploy apps. 
Note: We still upgrade runRecords so once the app is deployed history will be available. 
Issue: https://issues.cask.co/browse/CDAP-1881
Build: http://builds.cask.co/browse/CDAP-RBT197-1
I have tested this and the app.meta does not have application meta's anymore. But since the schedule store bug does not let cdap starts I was not able verify it in the UI: https://issues.cask.co/browse/CDAP-1882
=> CDAP-1881 do not upgrade application meta

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java
=> CDAP-1902 enabling explore on a dataset that is not explorable

cdap-master/src/main/java/co/cask/cdap/data/tools/MetricsKafkaUpgrader.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/upgrade/MetricsDataMigrator.java
if table does not exist, we just return, previously we would throw exception which is not in contract with UpgradeTool.
=> check table exists before upgrade/delete kafka metrics table

cdap-docs/admin-manual/source/installation/installation.rst
on a single distribution version and known to be broken on many
others.
=> revert notes about secure explore since it is only well tested

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/developers-manual/source/advanced/adapters.rst, cdap-docs/developers-manual/source/data-exploration/custom-datasets.rst, cdap-docs/developers-manual/source/data-exploration/filesets.rst, cdap-docs/developers-manual/source/data-exploration/object-mapped-tables.rst, cdap-docs/developers-manual/source/data-exploration/streams.rst, cdap-docs/developers-manual/source/getting-started/quick-start.rst, cdap-docs/examples-manual/source/examples/stream-conversion.rst, cdap-docs/examples-manual/source/examples/web-analytics.rst, cdap-docs/integrations/source/jdbc.rst, cdap-docs/integrations/source/partners/cloudera/ingesting.rst, cdap-docs/reference-manual/source/characters.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v2/query.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/query.rst, cdap-docs/reference-manual/source/java-client-api.rst
This isn't quite finished, but there are some things that can be checked already...
This PR covers:
- the upgrade docs (and the metrics migration tool)
- the "Update table names in explore docs" (https://issues.cask.co/browse/CDAP-1671)
The last item involves updating the table name references: 
- "cdap_user_[ds-name] -> dataset_[ds-name]" and 
- "cdap_stream_[stream-name] -> stream_[stream-name]"
...everywhere...so please look and see if that looks correct.
Staged at: http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_upgrade_docs/
=> Upgrade docs

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java, cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java, cdap-cli/src/main/java/co/cask/cdap/cli/LaunchOptions.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateNamespaceCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteNamespaceCommand.java, cdap-client/src/main/java/co/cask/cdap/client/config/ConnectionConfig.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/NettyRouter.java, cdap-standalone/src/main/java/co/cask/cdap/StandaloneContainer.java, cdap-standalone/src/main/resources/cdap-site.xml, cdap-unit-test-standalone/src/main/java/co/cask/cdap/test/standalone/StandaloneTestBase.java
https://issues.cask.co/browse/CDAP-1896
http://builds.cask.co/browse/CDAP-RBT202
Also includes a fix for handling default connection which ideally would be a separate PR, but seemed easier to include in here.
```
cdap (http://Alvins-MacBook-Pro-2.local:10000/default)> create namespace ok
Namespace 'ok' created successfully.
cdap (http://Alvins-MacBook-Pro-2.local:10000/default)> delete namespace default
WARNING: Deleting namespace is an unrecoverable operation
Are you sure you want to delete contents of namespace 'default' [y/N]? y
Contents of namespace 'default' were deleted successfully
cdap (http://Alvins-MacBook-Pro-2.local:10000/default)> delete namespace default
WARNING: Deleting namespace is an unrecoverable operation
Are you sure you want to delete contents of namespace 'default' …
```
=> CDAP-1896: Deleting default namespace in CLI should tell user what actually happens

README.md, cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/operations/cdap-console.rst, cdap-docs/admin-manual/source/operations/resource-guarantees.rst, cdap-docs/developers-manual/source/building-blocks/namespaces.rst, cdap-docs/developers-manual/source/getting-started/standalone/index.rst, cdap-docs/integrations/source/partners/cloudera/configuring.rst, cdap-docs/reference-manual/source/faq.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/metrics.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/namespace.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/stream.rst, cdap-docs/reference-manual/source/release-notes.rst
Staged at:
- [Installation: Upgrade](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/admin-manual/installation/installation.html#upgrading-an-existing-version)
- [Release Notes](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/reference-manual/release-notes.html#new-features)
- [Stream Properties](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/reference-manual/http-restful-api/http-restful-api-v3/stream.html#setting-stream-properties)
- [Namespace Components](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_upgrade_limitation/en/developers-manual/building-blocks/namespaces.html#namespace-components)
- [Namespace …
=> Add notes about limitations on upgrade tools.

Dockerfile
It needs to be added to the Dockerfile...
```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project co.cask.cdap:cdap:2.8.0 (/Build/pom.xml) has 1 error
[ERROR]     Child module /Build/cdap-ui of /Build/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
INFO[0552] The command [/bin/sh -c cd Build &&     MAVEN_OPTS="-Xmx512m" mvn clean package -DskipTests -P examples -pl cdap-examples -am -amd &&     mvn package -pl …
```
=> The cdap-ui child module was added

Dockerfile
Also, moved apt packages to a single line, except openjdk and maven, which depends on it.
Fixes this:
```
[INFO] bower angular#1.3.14                      ENOGIT git is not installed or not in the PATH
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Cask Data Application Platform (CDAP) ............. SUCCESS [25.042s]
[INFO] CDAP Build Common ................................. SUCCESS [4.643s]
[INFO] CDAP API .......................................... SUCCESS [12.859s]
[INFO] CDAP Protocol ..................................... SUCCESS [5.155s]
[INFO] CDAP Common ....................................... SUCCESS [11.788s]
[INFO] CDAP Watchdog API ................................. SUCCESS [4.000s]
[INFO] CDAP Notifications …
```
=> The cdap-ui module uses bower to get angular via git

Dockerfile
Prevents:
```
Setting up openjdk-6-jre-headless (6b34-1.13.6-1ubuntu0.12.04.1) ...
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode.
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode.
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode.
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode.
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode.
update-alternatives: using …
```
=> Put maven before openjdk so alternatives point to openjdk 7, rather than 6

cdap-docs/examples-manual/build.sh
Fix build for branches off of develop: "feature" branches use develop for their CDAP Guide READMEs.
=> Doc Build Fix

cdap-ui/app/features/dashboard/widget.js, cdap-ui/app/features/dashboard/widgets/line.html
- Backend send metrics only when it is emitted.
So even if I ask for a particular metric for the last 1 min it will give me a series with some data only if that particular metric was emitted by something in the backend. Otherwise the UI gets an empty array.
- We are interpolating the rest of the values with 0s if we don't get any.
Get ```events.in``` metric for a flow in an app for the last 1 min:
Scenario1:
Three events happend in the last one min. So we get exactly three values with three timestamps. Even though we are requesting metrics for 60 timestamps since the metric was not emitted at other time periods we will have only 3 values for corresponding 3 time stamps.
Scenario2:
No events are in the last one min. So we get no time series data from the backend.
In both the cases we have …
=> Fixes data interpolation with 0s for operations dashboard.

cdap-docs/_common/_themes/cdap/static/cdap.css_t, cdap-docs/_common/common_conf.py
and add a "https" replacement; re-order replacements in the conf.py
-[current style](http://docs.cask.co/cdap/2.6.2/en/admin-manual/installation/security.html)
-[new version](http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.2-r2.6.0_fix_mouseovers/en/admin-manual/installation/security.html)
Merged in 2.8.0 already.
Fix for https://issues.cask.co/browse/CDAP-1944
=> Port the 2.8.0 fix for mouseover bolding

cdap-docs/_common/common_conf.py, cdap-docs/examples-manual/source/examples/sport-results.rst, cdap-docs/examples-manual/source/examples/stream-conversion.rst
Sets the minimum required version of Sphinx needed to 1.3.1.
Corrected text in "Sport Results" that was overly-indented, and added dedents to code samples.
Added dedents and corrected an include sample in "Stream Conversion".
Staged at:
- [Sport Results](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_fix_pfs_output_commiter/en/examples-manual/examples/sport-results.html)
- [Stream Conversion](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_fix_pfs_output_commiter/en/examples-manual/examples/stream-conversion.html)
=> Fixes documentation for "Sport Results" and "Stream Conversion"

cdap-docs/admin-manual/source/installation/installation.rst
Ports a change in the installation instructions from 2.6.2 to 2.8.0. and fixes command examples (makes all command start with a "$") and cleans up a description and minor formatting issues.
Staged at http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_update_installation/en/admin-manual/installation/installation.html#preparing-package-managers
=> Update installation instructions

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java
http://builds.cask.co/browse/CDAP-DUT1302
=> Use provided namespace when namespace isn't provided in IntegrationTestBase.deployApplication

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/AbstractMapReduceContextBuilder.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetWithMRApp.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Bamboo : http://builds.cask.co/browse/CDAP-DUT1305
This fix includes input/output dataset names in the dataset collection used in the creation of the MapReduceContext. For example, this will enable the use case illustrated in the test added in this PR - accessing datasets without adding the names during compile time.
=> Fix datasets collection used during the creation of MapReduce Context

cdap-ui/pom.xml
JIRA: https://issues.cask.co/browse/CDAP-1919
Update the frontend-maven-plugin version to pass build using maven 3.3.1.
This is due to conflict with slf4j and the plugin using particular maven [1].
See JIRA ticket for details of error stack.
[1] https://github.com/eirslett/frontend-maven-plugin/issues/183
=> [CDAP-1919] cdap-ui fails to build in some environments.

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java, cdap-cli/src/main/java/co/cask/cdap/cli/CLIMainArgs.java, cdap-cli/src/test/java/co/cask/cdap/cli/CLIMainArgsTest.java
http://builds.cask.co/browse/CDAP-DUT1330
The command below wasn't working because Apache commons-cli was parsing the `-0400` as a command line option. `CLIMain` needs to use the convention of having command line options first in the main() args, then the command to execute after.
```
cdap-cli.sh send stream logEventStream '255.255.255.185 - - [23/Sep/2014:11:45:38 -0400] "GET /cdap.html HTTP/1.0" 401 2969 " " "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)"'
```
=> Treat options and command as two separate sections of args from main()

cdap-cli/src/main/java/co/cask/cdap/cli/util/table/AltStyleTableRenderer.java, cdap-cli/src/test/java/co/cask/cdap/cli/util/table/TableRendererTest.java
http://builds.cask.co/browse/CDAP-DUT1301
Now CLI table rendering will no longer use up the entire terminal when it doesn't need to.
```
cdap (http://Alvins-MacBook-Pro-2.local:10000/default)> list apps
+==================+
| id | description |
+==================+
+==================+
cdap (http://Alvins-MacBook-Pro-2.local:10000/default)> deploy app /opt/cdap/sdk/cdap-sdk-2.8.0-SNAPSHOT/examples/Purchase/target/Purchase-2.8.0-SNAPSHOT.jar
Successfully deployed application
cdap (http://Alvins-MacBook-Pro-2.local:10000/default)> list apps
+=================================================+
| id              | description                   |
+=================================================+
| PurchaseHistory | Purchase history application. | …
```
=> Use less whitespace in AltStyleTableRenderer

cdap-docs/_common/common_conf.py, cdap-docs/developers-manual/source/getting-started/quick-start.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/metrics.rst
Both of these had errors in them.
Staged at: 
- [Quick Start](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_quick_start/en/developers-manual/getting-started/quick-start.html)
- [Metrics](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_quick_start/en/reference-manual/http-restful-api/http-restful-api-v3/metrics.html)
A change has been made to develop that fixes this issue in develop without changing the CLI API. This PR then fixes the documentation (to remove its errors.) The CLI fix is needed in 2.8 so that the Quick Start and CLI will work there.
=> Feature/r2.8 fixes to RESTful API "Metrics" and Developers' Manual "Quick Start"

cdap-docs/developers-manual/source/testing/debugging.rst, cdap-docs/developers-manual/source/testing/index.rst
Staged at: http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_2001_Debugging_Docs_Update/en/developers-manual/testing/debugging.html
Removes references to Procedures and adds v3 references. Though v3 doesn't actually work right now (https://issues.cask.co/browse/CDAP-2017)...
See: [Debugging page](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_2001_Debugging_Docs_Update/en/developers-manual/testing/debugging.html)
Fixes: https://issues.cask.co/browse/CDAP-2001
=> Update debugging docs

BUILD.md, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-client/src/main/java/co/cask/cdap/client/config/ClientConfig.java, cdap-common/src/main/java/co/cask/cdap/common/stream/StreamEventTypeAdapter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/decoder/FormatStreamEventDecoder.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamFetchHandler.java
This is a few minor Javadoc fixes. It was found by running Javadocs on the entire CDAP repo, using increased memory for Javadocs. This is what I found worked reliably:
```
MAVEN_OPTS="-Xmx512m" mvn clean site -Dmaxmemory=1024m -DskipTests
```
Running a grep over the source tree identifies a 162 potential errors that need correcting, in addition to the approximately 500 existing broken links (seen in the output the above command) that exist in the full set Javadocs:
```
grep -rnw --include=*.java . -e "^ *\*.*[<>]" | grep --ignore-case -v -e "</*[bip]/*>" -e "</*pre/*>" -e "</*[ou]l/*>" -e "</*li/*>" -e "</*h.*>" -e "</*br/*>" -e "</*code/*>" -e "</*strong/*>" -e "</*table/*.*>" -e "</*t[dhrt]/*>" -e "</*a/*.*>" -e "{@literal <}" -e "<[A-Z]>"
```
=> Javadoc Cleanup

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/logging.rst, cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/service.rst
Removes Procedures from Javadocs, fixes errors in downloading logging and obtaining list of of System Services.
Staged at: http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_logging/en/index.html
-[v3 Service RESTful API](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_logging/en/reference-manual/http-restful-api/http-restful-api-v3/service.html)
-[v3 Logging RESTful API](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_logging/en/reference-manual/http-restful-api/http-restful-api-v3/logging.html#downloading-system-logs)
=> Removing Procedures, Fixing Errors in downloading logs

cdap-client-tests/src/test/java/co/cask/cdap/client/AdapterClientTest.java
https://issues.cask.co/browse/CDAP-2034
http://builds.cask.co/browse/CDAP-DUT1365
=> CDAP-2034: Removed unnecessary actions in AdapterClientTest, as StandaloneTestBase takes care of cleanup already

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsQueryTestRun.java
this test was failing on one of the builds , reported by @rohitsinha54  - this is a fix. 
we had gauge and increments in the same timestamp and their ordering affects the result, now we gauge after the increments separated by a timestamp and also fixed the assertion.
build running : http://builds.cask.co/browse/CDAP-DUT1380-1
=> fix flaky metrics query test

cdap-api/src/main/java/co/cask/cdap/api/data/format/StructuredRecord.java, cdap-api/src/main/java/co/cask/cdap/api/data/schema/Schema.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/format/AvroRecordFormat.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/format/StructuredRecordDatumReader.java, cdap-data-fabric/src/test/java/co/cask/cdap/data/format/AvroRecordFormatTest.java, cdap-explore/src/main/java/co/cask/cdap/hive/serde/ObjectDeserializer.java, cdap-unit-test/src/test/java/co/cask/cdap/mapreduce/AppWithMapReduceUsingStream.java
We never expose `GenericRecord` class through Program ClassLoader, hence having the record format emit `GenericRecord` would make it unusable from the user program (there will be class cast exception if avro jar is bundled with user program jar).
=> (CDAP-2043) Make AvroRecordFormat decodes Avro binary data into StructuredRecord

cdap-docs/examples-manual/source/examples/purchase.rst
Corrects error in example of using the CDAP CLI.
Fix for https://issues.cask.co/browse/CDAP-2033.
=> Fix for Purchase App Example Documentation

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/AbstractProgramWorkflowRunner.java
In distributed mode the RunId is passed to the programs from AbstractProgramTwillRunnable. So the RunId key is always present in the options. If we use ImmutableMap.Builder to recreate the options in the ProgramRunner, in distributed mode it fails with "duplicate key" exception. There is a bigger refactoring needs to be done around how RunId should be propagated as a part of jira https://issues.cask.co/browse/CDAP-2039.
=> Updated code to use HashMap instead of ImmutableMap.Builder

cdap-docs/_common/highlevel_conf.py
Removes an extra space character that is causing issues on CentOS and building the documentation.
=> Fix build on bamboo.

cdap-docs/_common/highlevel_conf.py
Apparently, under CentOS, having even a single extra space at the end of a python file causes grief.
This change deletes that last line with that single character in it.
=> Fix doc build on bamboo by removing an extra space character.

cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionService.java, cdap-watchdog/src/test/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionServiceTest.java
Ignore zero values only for COUNTER Metric Type. Gauge of a zero value should NOT be ignored.
https://issues.cask.co/browse/CDAP-2055
http://builds.cask.co/browse/CDAP-DUT1399-1
=> Ignore zero values only for COUNTER Metric Type.

cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
worker metrics didn't have aggregation group defined, so we weren't collecting metrics emitted from worker. this is the fix.
=> surface worker metrics

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java
- An AbstractScheduledService.runOneIteration shouldn’t throw exception, otherwise it will kill the service.
=> (CDAP-2036) Fix the LocalStreamService failure

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java
Jira: https://issues.cask.co/browse/CDAP-1943
Updated the misfire instruction for the time scheduler to the `MISFIRE_INSTRUCTION_DO_NOTHING `. This will discard the misfired execution and the scheduler will simply waits for next scheduled time.
=> CDAP-1943 Added policy to do nothing on the trigger misfire.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/main/java/co/cask/cdap/templates/AdapterSpecification.java, cdap-app-fabric/src/main/java/co/cask/cdap/templates/DefaultAdapterConfigurer.java
Removing WorkerSpec from AdapterSpec since it can be retrieved from the ApplicationSpec from Store. The only information that is required to be passed on from the Template's configureAdpater method is instances and runtime args (in case of Realtime Adapter) and ScheduleSpecification (in case of Batch Adapter) since we don't allow schedules to be part of Application Template.
More changes need to be done to AdapterSpec but they will be addressed in subsequent PRs so that PR #1962 can make use of these changes.
Bamboo : http://builds.cask.co/browse/CDAP-DUT1405-3
=> Remove workerSpec from AdapterSpec

cdap-docs/_common/_themes/cdap/globaltoc.html, cdap-docs/_common/_themes/cdap/layout.html, cdap-docs/_common/_themes/cdap/relations.html, cdap-docs/_common/common_conf.py, cdap-docs/admin-manual/source/conf.py, cdap-docs/examples-manual/build.sh
These changes modify the build scripts so that they will successfully run under Python 2.6 on CentOS 6.
The script runs successfully; the documentation built is [staged](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_convert_build_to_python_2.6/en/index.html).
These changes would need to be ported to 3.0 in order for it to build there.
=> Convert documentation build to run under python 2.6

cdap-docs/_common/_themes/cdap/casksites.html, cdap-docs/_common/common_conf.py
This PR adds a short list of links to the bottom of the left sidebar of each page of the documentation, back to the other documentation pages. Up on the highest-level CDAP page is the new timeline (http://docs.cask.co/cdap/index.html).
It updates the version information used to generate the timeline in the common_conf.py.
This is staged at: http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_add_doc_timeline/en/index.html
See the lower-left portion of the left sidebar for the new "Documentation" section that lists all documentation directories.
Issue: https://issues.cask.co/browse/CDAP-1985
=> Adding Access to Documentation Timeline...and other Cask Data Sites

cdap-common/src/main/java/co/cask/cdap/common/logging/ApplicationLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/FlowletLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/GenericLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/MapReduceLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/ProcedureLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/SparkLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/UserServiceLoggingContext.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/WorkerLoggingContext.java, cdap-watchdog/src/test/java/co/cask/cdap/common/logging/logback/TestLoggingContext.java
Using setter for adapter id eliminates the need to have Nullable constructor parameters.
JIRA - https://issues.cask.co/browse/CDAP-2052
=> CDAP-2052 Restructuring adapter id in logging context

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
When a mapreduce is run through an adapter, you should be able to query its metrics using tags: *namespace* and *adapter* as well as *namespace*, *app*, *mapreduce*
Jira: https://issues.cask.co/browse/CDAP-1787
Build: https://builds.cask.co/browse/CDAP-DUT1389
=> [CDAP-1787] Added 'adapter' tag to mapreduce metrics when run through adapters

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/jms/JmsProvider.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/JmsMessageToStringSourceTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/MockJmsProvider.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/resources/jndi.properties
This is the first drop to support JMS realtime source for ETL Template.
The PR consists of:
-) Add new JmsSource class in the etl/realtime/sources package
-) Add new JmsProvider interface that Adapter need to implement or get from configuration to provide JMS ConnectionFactory in the etl/realtime/jms package
-) Added MockJmsProvider and unit test JmsMessageToStringSourceTest to test getting JMSMessage to String emitter.
-) Currently just use Session.AUTO_ACKNOWLEDGE for message acknowledgement [1]
-) To test just run the JmsMessageToStringSourceTest and if successful you should see this message in console:
Sending Message to Topic:CDAP.TOPIC destination with text: Hello World to destination: org.apache.activemq.command.ActiveMQTopic
Getting JMS Message in emitter with value: Hello World …
=> [CDAP-1879]  Add JMS realtime source for ETL Template

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/StreamDecoderDetectionTest.java
This is needed as for BatchSources in ETL which does not have access to internal classes. 
Conversation here: https://github.com/caskdata/cdap/pull/1921/files#r28036460
Build running here: http://builds.cask.co/browse/CDAP-DUT1408-1
=> CDAP-2056 Change to MapReduceRuntimeService inferDecoderClass

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/LoadStreamCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SendStreamEventCommand.java
Corrects the tense: "send" -> "sent". Adjusted in both output and in the test that depends on the output.
=> Correct the grammar of Command Line Interface messages and its test.

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java
using empty list/map when groupBy, tags or time-range is not provided
Jira link : https://issues.cask.co/browse/CDAP-1955
=> use current time as endTime for aggregate queries and 

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogLine.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandlerV2.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LoggingTester.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java
JIRA https://issues.cask.co/browse/CDAP-2051
Adding log endpoints to fetch logs by run-id -
* `/namespaces/{namespace-id}/apps/{app-id}/{program-type}/{program-id}/runs/{run-id}/logs`
* `/namespaces/{namespace-id}/apps/{app-id}/{program-type}/{program-id}/runs/{run-id}/logs/next`
* `/namespaces/{namespace-id}/apps/{app-id}/{program-type}/{program-id}/runs/{run-id}/logs/prev`
* `/namespaces/{namespace-id}/adapters/{adapter-id}/runs/{run-id}/logs`
Also refactored test cases.
=> Adding endpoint to fetch logs by runid

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLMapReduceTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/IdentityTransform.java
Check for two cases - if types are Parameterized check only the rawType, if types are classes then check assignable, else pass validation.
If TypeToken's isAssignableFrom is directly used on Parametrized types, it checks for the assignability of Type Arguments as well, and this fails validation of Pipeline used in #1921.
Fix required to unblock #1921 
Bamboo : http://builds.cask.co/browse/CDAP-DT13
=> Relax ETL Batch Adapter Validation

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/AbstractCubeHttpHandler.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/CubeQuery.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithCube.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestAppWithCube.java
NOTE: Currently, we can only provide an abstract http handler which subclass has to implement method that returns Cube dataset. Because there's no support of instantiating dataset dynamically based on name in a program.
=> CDAP-1965: Provide AbstractCubeHttpHandler out of the box to query a Cube dataset

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLMapReduceTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/BatchWritableSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/TableSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToPutTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToPutTransformTest.java
this, also adding a BatchWritableSink that will work for any
CDAP BatchWritable, but which requires users to supply the dataset
type and any properties that type requires. TableSink and
KVTableSink then extend the BatchWritableSink.
=> CDAP-2087 adding a table sink for the etl template. As part of

cdap-docs/_common/common-build.sh
Under "OS X" ("Darwin"), always build javadocs under 1.7. This will match what we are intending to do with Bamboo.
Fixes https://issues.cask.co/browse/CDAP-523
=> Fix Building of Javadocs under OS X

cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst, cdap-docs/developers-manual/source/building-blocks/datasets/index.rst, cdap-docs/reference-manual/source/glossary.rst
Add entries to glossary for TimePartitioned and TimeSeries Datasets, added links to examples to Building Blocks Datasets, added description to Filesets commentary.
Staged at: http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_1827_Dataset_Building_Block/en/index.html
Pages of note:
- [Datasets, page bottom](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_1827_Dataset_Building_Block/en/developers-manual/building-blocks/datasets/index.html)
- [Glossary](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT-3.0_1827_Dataset_Building_Block/en/reference-manual/glossary.html#term-timepartitioned-dataset)
Fix for https://issues.cask.co/browse/CDAP-1827 and https://issues.cask.co/browse/CDAP-1972
=> Adding Dataset example links and glossary entries

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetadataStoreDataset.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/MetadataStoreDatasetTest.java
MetadataStoreDataset's list was applying limit on records fetched rather than on records returned.
=> Fix MetadataStoreDataset list to handle limit correctly

cdap-api/src/main/java/co/cask/cdap/api/data/stream/StreamBatchReadable.java, cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSourceContext.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/MapReduceSourceContext.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/StreamBatchSource.java
StreamBatchReadable as the input to match the static methods
available in StreamBatchReadable and to match what is in the
javadoc for the class. Also updating the ETL template to use the
new method instead of converting StreamBatchReadable to its uri.
=> CDAP-2143 adding a method to MapReduceContext to set a

cdap-docs/build.sh
The shell bamboo drops into during scripts needs a relative path for handling files in the current directory (based on our testing). It cannot find the file otherwise.
The script runs like this, essentially:
./build.sh <options>
The first line in build.sh (source vars) is failing, because it cannot find vars in the current directory (even though it is there).
This works: 
source ./vars
=> prepend relative path (dot slash) to sourced file

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/RunRecord.java
Resolves: https://issues.cask.co/browse/CDAP-2144
RunRecord of a RUNNING program throws NPE upon getStopTime().
This was happening because the return type of `getStopTs` is `long`, even though its possible for `stopTs` to be null.
Build: http://builds.cask.co/browse/CDAP-DUT1472-2
=> CDAP-2144 getStopTs returns Long instead of long.

cdap-api/src/main/java/co/cask/cdap/api/Resources.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/InMemoryWorkerRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/templates/AdapterSpecification.java, cdap-app-fabric/src/main/java/co/cask/cdap/templates/DefaultAdapterConfigurer.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
Use ProgramOptions (system arguments) to pass instances, resources. Unfortunately this has to be replicated thrice in different places. Need to fix this cleanly in the future.
Bamboo: http://builds.cask.co/browse/CDAP-DUT1476-2
=> Set Adpater Worker resources before starting the program

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java
The first drop for JMS realtime source for template uses internal Queue to support asynchronous push messages from
JMS consumer so when the CDAP template transformer call the JmsSource#poll it already should have message available.
However, this could consume some extra heap allocation given that poll is the mechanism we used to get the
realtime data from CDAP source.
The Queue could get large such that we need to cap it or start dropping older messages if CDAP template transformer
does not poll fast enough.
Need to change the async mode to get messages from JMS provider to sync mode by calling JMS MessageConsumer#receive explicitly.
=> CDAP-2137 Get JMS messages from JMS Consumer from async to sync to reduce heap usage

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/CubeFact.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToCubeFactTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToCubeFactTransformTest.java
Second part will be the Cube dataset sink.
In the end, these two will likely to merge into one, as the new idea is for sink to accept StructuredRecord to ease its usage. For now, it is separate transform to be consistent with other similar sink cases.
=> CDAP-1966: first part: transformation from StructuredRecord to CubeFact

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterServiceTests.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-common/src/main/resources/cdap-default.xml, cdap-standalone/src/main/resources/cdap-site.xml
- Also fixed a bug in the template upgrade logic
- It uses file name when update the internal file->template info map, but uses full file path when looking up
- Fix a unit test that relies on the bug mentioned above.
=> (CDAP-2148) Make adapter service thread-safe

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/webapp/ServePathGenerator.java, cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricClient.java, cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/webapp/ServePathGeneratorTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/DFSStreamHeartbeatsTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/TransactionManagerDebuggerMain.java, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayFastTestsSuite.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/RuntimeArgumentTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTest.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTestV2.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTestV3.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/hooks/MetricsReporterHookTestRun.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/run/StreamWriterTestRun.java
- also adds a few tests for v3/ routing that were not there previously. 
- also fixes a handful of bugs found while doing this
=> [CDAP-2150] convert all usages of v2/ APIs in test to v3/ - unless they test a v2 API

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamCoordinatorTestBase.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/AbstractStreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamCoordinatorClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamPropertyListener.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
- Instead of incrementing the generation, a stream deleted event should be sent.
=> (CDAP-2160) Fix the stream coordination when deleting stream

cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/MRJobClient.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/MapReduceMetricsInfo.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/app/mapreduce/MapReduceMetricsInfoTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/MRJobInfo.java, cdap-ui/app/features/mapreduce/templates/tabs/runs/run-detail.html
1) Use RunRecords for job-level state, start/end time.
2) Add a field to the return object which returns if the return object is complete or not.
Change no. 1 helps to provide that information in standalone as well as when the JobHistory server is missing.
Build: http://builds.cask.co/browse/CDAP-DUT1324-20
=> Use RunRecords for job-level state, start/end time.

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BatchETLDBAdapterTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/DBSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/DBRecord.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/ETLDBOutputFormat.java, cdap-app-templates/cdap-etl/pom.xml
Adds a ``DBSink`` that:
1. Reads a ``StructuredRecord``
2. Makes a JDBC call to the destination table to figure out the schema of the destination table as ``ResultSetMetadata``. This is needed because Database Drivers do not reliably return the schema from a ``PreparedStatement``.
3. Constructs a ``DBRecord`` using the ``StructuredRecord`` and ``ResultSetMetadata`` from 1 and 2 above.
4. Sends the ``DBRecord`` a custom ``ETLDBOutputFormat``, which is needed to load the driver class properly, just like we do in ``ETLDBInputFormat``.
Jira: [CDAP-2066](https://issues.cask.co/browse/CDAP-2066)
Build: https://builds.cask.co/browse/CDAP-DT26
=> [CDAP-2066] Added DB Batch Sink

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java, cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/standalone/StandaloneLogAppender.java
It needs to override the lifecycle methods and the append method to correctly delegate calls from logback into underlying log appender.
=> (CDAP-2177) Fix standalone log appender

cdap-ui/app/main.js
Currently, issues related to NodeJS not being able to communicate with CDAP are being propagated to user. This information is useless as if the NodeJS is not able to connect to CDAP, then we block the screen and show a pop-up. But, adding alerts for every time we try connecting with CDAP makes no sense. This PR includes the fix for the same.
It makes sure, that it will not push the response only if it's not a connect call failure.
=> Making sure that we don't propogate connection errors into alerts

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterServiceTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/NettyRouterPipelineTest.java
and make sure api version and namespace are always specified in
AppFabricTestBase when deploying an app.
=> name tests correctly so they actually get run by maven,

cdap-api/src/main/java/co/cask/cdap/api/templates/ApplicationTemplate.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalAdapterManager.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationManager.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationTemplateManager.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/adapter/ConfigureAdapterStage.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/main/java/co/cask/cdap/pipeline/Pipeline.java, cdap-app-fabric/src/test/java/co/cask/cdap/DummyBatchTemplate.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTests.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/EndPointStage.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/templates/etl/common/ETLTemplate.java
when configuring an adapter will tell the framework that the
config was invalid. This will make the rest api return a 400
instead of a 500. Also making sure the exception is not lost
wrapped in layers of ExecutionExceptions.
=> CDAP-2184 document that throwing an IllegalArgumentException

cdap-ui/app/features/dashboard/templates/userdashboard.html
Widget footer that shows the metrics in graph is removed, but will be added in the edit window.
=> Removed the widget footer

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AdapterHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTest.java
optional 'template' query param that will filter the adapters
returned by those that match the template given.
=> CDAP-2185 extend the get all rest api for adapters to support an

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWebappProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/FlowTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/MapReduceTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/ServiceTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WebappTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkerTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillApplication.java
- Removed bunch of duplicated code by introducing an AbstractProgramTwillApplication
- Generalize file localize rather than a hard coded three files (program JAR, hConf and cConf)
- Prepare the path for adding plugin files localization.
=> (CDAP-1917) Refactor program TwillApplication and distributed ProgramRunner

cdap-api/src/main/java/co/cask/cdap/api/annotation/Description.java, cdap-api/src/main/java/co/cask/cdap/api/annotation/Name.java, cdap-api/src/main/java/co/cask/cdap/api/annotation/Plugin.java, cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginClass.java, cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginConfig.java, cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginInfo.java, cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginProperties.java, cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginPropertyField.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/program/ManifestFields.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginClassLoader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginFile.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginInstantiator.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java, cdap-app-fabric/src/test/java/co/cask/cdap/PluginTestAppTemplate.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/plugins/test/TestPlugin.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/plugins/test/TestPlugin2.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/plugins/test/package-info.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/EmptyClass.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/PluginTest.java, cdap-common/src/main/java/co/cask/cdap/common/utils/DirUtils.java
It is the ground work for the whole plugin system for application template.
This PR includes works on the following pieces:
- New annotations defined for annotating plugin class and plugin config properties
- New data structure classes for recording plugin information and plugin class information.
- A `PluginClassLoader` for defining the class loading behavior of plugin classes
- A `PluginRepository` for inspecting and caching plugin information
- A `PluginInstantiator` for creating new instances of plugin classes
Template plugins are deployed as JAR files under the template plugin directory (i.e. under "data/plugins/[template_name]").
There are two ways of defining plugin classes in a plugin jar.
1. Annotate class with the `@Plugin` annotation, and make the package name of the class …
=> (CDAP-1917) Added plugin repository and plugin instantiate support.

cdap-common/src/main/java/co/cask/cdap/gateway/handlers/PingHandler.java, cdap-gateway/src/test/resources/logback-test.xml
ping endpoint is called frequently and was causing log.saver overflow. so removing the log message.
=> remove info logging in pingHandler 

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MDSKey.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageDatasets.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/keymaker/AdapterKeyMaker.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/keymaker/DatasetKeyMaker.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/keymaker/ProgramKeyMaker.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/keymaker/StreamKeyMaker.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/pair/KeyMaker.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/pair/OrderedPair.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/internal/pair/OrderedPairs.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/MDSKeyTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/registry/UsageDatasetTest.java
Implementation for Usage Dataset that stores what datasets/streams are used by what programs/adapters. It stores each usage as two mappings.
For example, if program P uses dataset D then P->D and D->P mappings are stored.
JIRA https://issues.cask.co/browse/CDAP-2095
=> Usage dataset

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/JmsMessageToStringSourceTest.java
The PR contains some changes to help buffer some bulk messages from JMS sync:
-) Fix the consumer timeout from 30s to 2s
-) Add small buffer for 50 messages or if no more messages within the receive call.
The default message could be set by "jms.messages.receive" runtime arg.
This will allow more buffering to emitted messages when adapter poll to the JMS source.
=> CDAP-2196 Add bounded message buffer to JMS poll to emit some messages instead of just one per poll from adapter

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/templates/etl/common/Constants.java
To enforce noninstantiability add private constuctors to Contants and its nested classes.
Throw AssertionError as reccomended in the Effective Java by Joshua Bloch.
This means that I am asserting that this constructor will never be called so if somehow it is called
then it violates the assumption.
=> Add private constructors to classes in the etl Constants class to enforce noninstantiability

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnerModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/InMemoryProgramRunnerModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamWriter.java, cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/StreamWriterFactory.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/MockResponder.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/Properties.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/StreamSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/TestSource.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLRealtimeTemplate.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/templates/etl/realtime/ETLWorkerTest.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/resources/logback-test.xml, cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java, cdap-test/src/main/java/co/cask/cdap/test/StreamManager.java, cdap-test/src/main/java/co/cask/cdap/test/TestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java, cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultStreamManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultStreamWriter.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/LocalStreamWriter.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/StreamManagerFactory.java
* Adds a real-time Stream sink
* PR looks large because of the two following changes in the CDAP platform:
1. ``BasicWorkerContext`` used to ``new DefaultStreamWriter()`` earlier. Which meant that it always depended on the Stream Service to be up and running, even in tests. In ``TestBase``, however, we do not start Stream Service, so all calls to write to streams failed because Stream Service could not be discovered. Fixed this by adding a Guice Factory for ``StreamWriter``, that accepts an ``@Assisted String namespaceId``. ``StreamWriterFactory`` is now injected into ``WorkerProgramRunner`` and made available to ``BasicWorkerContext`` to create a ``DefaultStreamWriter`` for the required namespace.
2. In ``TestBase``, there was no way to read from a stream. Introduced a ``StreamManager`` …
=> [CDAP-2062] Added real-time Stream Sink

cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-core/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-realtime/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-test/pom.xml
To make sure we got fresh version of dependencies, add ${project.version} to version to
make sure -am works as intended for inter modules dependencies.
=> Add version to cdap-uni-test dependencies in the app-templates module to force rebuild

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/jms/JndiBasedJmsProvider.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/JmsMessageToStringSourceTest.java
This PR add default JmsProvider that tries to get ConnectionFactory and Destination from JNDI lookup.
The JniBasedJmsProvider will create ConnectionFactory and Destination from JNDI context.
The JmsSource need to be passed several runtime properties for the JNDI JmsProvider:
-) java.naming.factory.initial
-) java.naming.provider.url
-) jms.destination.name
Also update the JmsSource#configure to add more information about config that could be
passed to the JmsSource#initialize.
=> Add default JmsProvider implementation that tries to get ConnectionFactory and Destination via JNDI

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
The system namespace must be created before we setup DSFramework
=> create namespace before initializing DSFramework

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
schedule could succeed but the stopping of active runs could fail.
In that scenario, the stop fails and every subsequent stop will
fail because the schedule isn't found when we try to delete it.
Also fixing a bug in DistributedProgramRuntimeService where it
could not look up runtime info of programs that were not already
in memory.
=> CDAP-2198 fix a bug in stop adapter where the deletion of the

cdap-ui/app/directives/c3/charts.js, cdap-ui/app/features/dashboard/controllers/widget.js, cdap-ui/app/features/dashboard/templates/widgets/c3-bar.html, cdap-ui/app/features/dashboard/templates/widgets/c3-donut.html, cdap-ui/app/features/dashboard/templates/widgets/c3-line.html, cdap-ui/app/features/dashboard/templates/widgets/c3-pie.html, cdap-ui/app/features/overview/controllers/overview-ctrl.js, cdap-ui/app/features/overview/overview.html, cdap-ui/app/features/overview/overview.less, cdap-ui/app/services/helpers.js
System and app errors on overview page, using c3.
Perhaps a single number should also be visible (either aggregated for past 5 minutes or past hour).
Note: Because it is based off of c3 charts, it depends on: https://github.com/caskdata/cdap/pull/2184
=> Errors Chart on overview page

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
Looks like there duplicates of hadoop-mapreduce-client-core in cdap-etl-lib module pom.xml.
This causes warning messages when compile:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.hadoop:hadoop-mapreduce-client-core:jar -> duplicate declaration of version (?) @ co.cask.cdap:cdap-etl-lib:[unknown-version], /Users/henrysaputra/open/cask/cdap/cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, line 134, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.hadoop:hadoop-mapreduce-client-core:jar -> duplicate declaration of version (?) @ co.cask.cdap:cdap-etl-lib:[unknown-version], /Users/henrysaputra/open/cask/cdap/cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, line 168, column 17
=> Remove duplicate dependency declaration on hadoop-mapreduce-client-core in cdap-etl-lib module

cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
https://github.com/caskdata/cdap/pull/1775/ added handler + method aggregation in DefaultMetricStore and my recent merge https://github.com/caskdata/cdap/pull/2185 added a duplicate for that. so removing the duplicate aggregation rule.
=> remove duplicate aggregation, we already have handler + method aggregation

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/DefaultKafkaConfigurer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/Kafka08SimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaBrokerConfigurer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaConfig.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaConfigurer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaConsumerConfigurer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaConsumerInfo.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaMessage.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaSimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSourceTest.java
The PR contains first drop supporting Kafka as realtime source:
-) The Kafka consumer are borrowed from cdap-kafka-pack/cdap-kafka-flow project leveraging Kafka Simple Consumer. The logic is modified and simplify to fit the scenario of realtime source which is less complicated that CDAP Flow and Flowlets.
-) The Kafka source only support latest Kafka version supported by CDAP which is 0.8.x (as long as Kafka does not have API change within minor releases). 
-) The Kafka realtime source also leverages library from Twill to start and stop ZK server and client and manage the Topic partition and offset.
-) Add unit test to test single partition with single broker list for send and receive Kafka messages. 
TODO: 
-) Will add more tests such as to use ZK as connection broker
=> CDAP-1878 Add Kafka realtime source

cdap-api/src/main/java/co/cask/cdap/api/data/stream/StreamBatchReadable.java, cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginSelector.java
Fixes these two warnings:
```
2 warnings
[WARNING] Javadoc Warnings
[WARNING] /Users/john/Source/cdap/cdap-api/src/main/java/co/cask/cdap/api/data/stream/StreamBatchReadable.java:63: warning - End Delimiter } missing for possible See Tag in comment string: "This class is for using a Stream as input for a MapReduce job. An instance of this class should be set in the
[WARNING] {@code MapReduceContext} of the {@code beforeSubmit} method to use the Stream as input.
[WARNING] <pre>
[WARNING] {@code
[WARNING] class MyMapReduce implements MapReduce {
[WARNING] public void beforeSubmit(MapReduceContext context) {
[WARNING] context.setInput(new StreamBatchReadable("mystream"));
[WARNING] }
[WARNING] }
[WARNING] </pre>"
[WARNING] /Users/john/Source/cdap/cdap-api/src/main/java/co/cask/cdap/api/templa …
```
=> Fixes two Javadoc warnings.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AbstractInMemoryProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/InMemoryServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/InMemoryWorkerRunner.java
We were passing only userArguments that were passed in through ProgramRunner and were skipped systemArguments. Need to pass in the sysArguments (figured this out while passing Adapter Name/Adapter Spec).
Builds : http://builds.cask.co/browse/CDAP-DUT1628
JIRA : https://issues.cask.co/browse/CDAP-2250
=> Pass ProgramOptions to Worker/Service in inmemory mode

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java
bugfix: https://issues.cask.co/browse/CDAP-2157
we send badRequest when there are no metric query param for the /query endpoint, but missed that for the /query endpoint with context query param (deprecated). this solves that issue. 
build running : http://builds.cask.co/browse/CDAP-RBT218-1
=> if no metrics are provided in metrics query, send bad request

cdap-docs/examples-manual/source/examples/count-random.rst, cdap-examples/CountRandom/src/main/java/co/cask/cdap/examples/countrandom/NumberCounter.java, cdap-examples/CountRandom/src/main/java/co/cask/cdap/examples/countrandom/NumberSplitter.java, cdap-examples/CountRandom/src/main/java/co/cask/cdap/examples/countrandom/RandomSource.java
There is no Jira for this. But I added these to CountRandom for my manual testing of CDAP-2259 and thought it might be useful to add that to the example in the release, because we have no examples yet that use runtime arguments or hash partitioning.
=> add runtime arguments and hash partitioning to CountRandom; update docs

cdap-api/src/main/java/co/cask/cdap/api/templates/ApplicationTemplate.java
We don't need the method in Application Templates since plugins are recognized and supported by the platform.
Build: http://builds.cask.co/browse/CDAP-RBT224-1
=> Removing service handler handler method

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/JmsMessageToStringSourceTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/JmsSourceTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/MockJmsProvider.java
The PR contains changes to move JMS realtime source to plugin mode.
Change the Emitter to emit StructuredRecord with message String inside.
Updated the tests to reflect this changes.
=> Convert the ETL Template adapter JMS source to plugin

pom.xml
title says it all. 
Build runs here: http://builds.cask.co/browse/CDAP-RBT226-1
=> [CDAP-2266] use version 1.2.0 of cdap-clients, which uses v3 APIs

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/Kafka08SimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaConfig.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaSimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSourceTest.java
This PR consists changes to make Apache Kafka realtime source to be plugin mode:
-) Emit StructuredRecord instead of ByteBuffer
-) Follow plugin mode by using PluginConfig to pass properties to Kafka source.
=> Change Kafka source emitter to use StructuredRecord. Convert to plugin.

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/Kafka08SimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/kafka/KafkaSimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSource.java
Kafka messages could have null keys, so we need to check before calling KafkaSimpleApiConsumer#decodeKey method when processing the messages.
Also removed some unused imports.
=> Check for null keys when pulling messages for Kafka topic.

cdap-app-templates/cdap-etl/cdap-etl-api/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-realtime/pom.xml, cdap-app-templates/cdap-etl/pom.xml
- For modules that build bundle jar, we should explicitly declare dependency on cdap-api and have it as provided scope.
- For inter-module dependency, shouldn’t use dependency management.
=> Fix the dependency on cdap-api for the ETL app.

cdap-app-templates/cdap-etl/cdap-etl-realtime/pom.xml
- Only plugin (etl-lib) uses avro classes.
=> The realtime module shouldn’t haven’t dependency on avro.

cdap-ui/app/features/apps/controllers/list-ctrl.js, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/data/list-ctrl.js, cdap-ui/app/features/overview/controllers/overview-ctrl.js, cdap-ui/app/features/overview/templates/data-apps.html, cdap-ui/app/services/my-orderings.js
Ordering the Data and Apps on Overview page by most recently clicked first.
This is useful especially because we limit the number of elements shown.
Whenever someone clicks on an app or data element on the overview page, 'All apps' page, or 'App Datasets' page, it gets marked as most recently used. This information is then used to order the limited-length lists on the Overview page.
Click the gif for a larger view.
=> Ordering the Data and Apps on Overview page

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSource.java
The StructuredRecord builder need to be created per instance of StructuredRecord because calling the build method does not reset the internal fields.
=> Fix creating new StructuredRecord builder per conversion.

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java
Need to remove DEFAULT_MESSAGE_RECEIVE static variable in JmsPluginConfig since it is showing up to UI via reflection.
=> Remove static variable for JmsPluginConfig class in JmsSource

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java
- When the plugin jar has jar inside, it’s possible that there is more than one URL that matches with the package resource. We should search for the one that is in local directory (vs in JAR) and pickup Plugin classes form there.
=> (CDAP-2369) Scan all package resources to find plugin classes

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/KafkaSource.java
Since key could be null, need to make the StructuredRecord's schema to be nullable for Kafka realtime source plugin.
=> Make the key to become optional for schema definition in Kafka source.

cdap-ui/app/features/dashboard/controllers/dashboard-ctrl.js, cdap-ui/app/features/dashboard/templates/userdashboard.html
Previously, you could not suspend the polling frequency except by navigating to a different page or applying a Time Range.
This allows you to stop the polling.
=> Allow polling on metrics dashboard to stop polling.

cdap-docs/build.sh
These changes improve the output of the logs for the building of documentation.
There is now a clear start and finish header, and all headers follow the same pattern: a string of "=" followed by a string of "-". That way you can search for either pattern, and "hop" from header to header.
Additional quote marks have been added to make it clear which targets are being built.
=> Fix log output for the auto build of docs

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
race conditions. There are better ways to do this, but doing
something simple in the short term.
=> CDAP-2297 make adapter operations synchronized to protect against

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data/stream/service/upload/StreamBodyConsumerTestBase.java, cdap-docs/developers-manual/source/building-blocks/namespaces.rst, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
Disallows hyphens in namespace names only for now. Retains current behavior for other ids. 
This is needed because hive complains if the database name has a hyphen in it.
Jira: [CDAP-2330](https://issues.cask.co/browse/CDAP-2330)
Build: http://builds.cask.co/browse/CDAP-RBT242
=> [CDAP-2330] Disallow hyphens in namespace names

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProcessDriver.java
... instead of the full queue name
=> [CDAP-2393] emit process.events.processed tagged with the simple queue name 

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/installation/quick-start.rst, cdap-docs/admin-manual/source/operations/troubleshooting.rst, cdap-docs/developers-manual/source/getting-started/standalone/index.rst, cdap-docs/reference-manual/source/faq.rst
Note that READMEs are being handled in another PR: https://github.com/caskdata/cdap/pull/2382
=> Update the requirement for Java to 1.7 for CDAP.

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSink.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSource.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLMapReduce.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/BatchCubeSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/DBSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/TableSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/TableSource.java
Batch Source and Batch Sink should have access to their Contexts in the initialize method instead of just PluginProperties. 
JIRA : https://issues.cask.co/browse/CDAP-2368
Build : http://builds.cask.co/browse/CDAP-RT18
=> Batch Source/Sink initialize method takes in Context

cdap-common/src/main/java/co/cask/cdap/common/collect/AllPairCollector.java, cdap-common/src/main/java/co/cask/cdap/common/collect/PairCollector.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/queue/ConsumerConfig.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/AbstractQueueConsumer.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueEntryRow.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseConsumerStateStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueClientFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/QueueBarrier.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/ShardedHBaseQueueStrategy.java, cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java
Also opened here: https://github.com/caskdata/cdap/pull/2268
After installing CDAP on a cluster, you can run the tool using the following java command from `/opt/cdap/master`:
```
java -cp `hbase classpath`:"lib/*:../hbase-compat-0.98/lib/*":/etc/cdap/conf/* co.cask.cdap.data2.transaction.queue.hbase.HBaseQueueDebugger queue:///default/PurchaseHistory/PurchaseFlow/reader/queue
```
=> CDAP-2105: Queue introspection

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextProvider.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java, cdap-app-fabric/src/main/java/org/apache/hadoop/mapred/LocalJobRunnerWithFix.java, cdap-common/src/main/java/co/cask/cdap/common/lang/Delegator.java, cdap-common/src/main/java/co/cask/cdap/common/lang/Delegators.java, cdap-common/src/main/java/co/cask/cdap/common/lang/WeakReferenceDelegatorClassLoader.java, cdap-common/src/test/java/co/cask/cdap/common/lang/ClassLoaderTest.java
- Introduce a WeakReferenceDelegatorClassLoader to hold a weak reference to the actual MapReduceClassLoader. The MR Framework will keep a reference to the WeakReferenceDelegatorClassLoader in a static variable, but it won’t prevent the GC of the actual MR ClassLoader
- Fix the MR ProgramRunner so that in local mode it won’t create new UGI for each run. It is needed to avoid the cache inside the Hadoop FileSystem object keep building up.
- Fix the LocalJobRunnerWithFix to not creating a new ClassLoader, but always use the one set in the Configuration object.
=> (CDP-2311) Fix MapReduce memory leak issue in local mode

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
Tested on cluster (throws ClassNotFoundException: Class org.apache.avro.mapreduce.AvroKeyOutputFormat without this fix).
Bamboo : http://builds.cask.co/browse/CDAP-RT22-1
=> Expose Avro class in ETL lib batch jar

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/jms/JndiBasedJmsProvider.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/JmsSourceTest.java
Add more required parameters for JMS JNDI naming via the JmsPluginConfig fields rather than
pass through from PluginConfig properties to help testing.
This PR makes testing easier because the parent PluginConfig's properties is a private memeber
and the method to get the properties is final so need to push some of the java naming
properties as top level fields in JmsPluginConfig class which extends the PluginConfig
=> Fix JMS realtime source to pass the right properties via the PluginConfig

cdap-ui/app/directives/flow-graph/flow.js, cdap-ui/app/features/admin/templates/overview.html, cdap-ui/app/features/flows/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/features/flows/templates/tabs/runs/run-detail.html, cdap-ui/app/features/flows/templates/tabs/runs/tabs/status.html, cdap-ui/app/features/overview/controllers/overview-ctrl.js, cdap-ui/app/features/spark/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/features/spark/templates/tabs/runs/run-detail.html, cdap-ui/app/features/spark/templates/tabs/runs/tabs/status.html, cdap-ui/app/index.html, cdap-ui/app/services/data/datasource.js, cdap-ui/app/services/my-orderings.js, cdap-ui/app/styles/themes/cdap.less, cdap-ui/app/styles/themes/cdap/header.less
1) debounce of 1000ms after clicking on a data/app before registering it in the ordering service.
2) hover on stream/flowlets on a flow page with out runs.
3) show stream metrics on a flow page with out runs (previously wasn't retrieving stream metrics on the flow page, if there are no runs).
4) remove BETA
5) Update Management page to look like [this](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/RdNQt0sMSBqb6xx/Screen%20Shot%202015-04-30%20at%206.39.00%20PM.png) regardless of enterprise or standalone.
6) remove 2014 from footers
7) Changed 'RUNNING' to 'DURATION' on flow/spark run-detail page.
8) 'controler' -> 'controller'
9) Make loading bar thicker (upon app deploy): [like so](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/PL7ctSTCJnY6Dmv/Screen%20Shot%202015- …
=> Miscellanous UI changes

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/CubeQuery.java
Fixes broken Javadocs by surrounding code sample in \<code> and \</code> in addition to \<pre> and \</pre>.
The problem can be seen in the currently staged javadocs: [CubeQuery](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-SNAPSHOT/en/reference-manual/javadocs/co/cask/cdap/api/dataset/lib/cube/CubeQuery.html)
=> Fix CubeQuery Javadoc.

cdap-ui/bin/config-tool
This replaces #2497 by only restoring the necessary code.
=> CDAP-2413 config-tool respect JAVA_HOME

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
Jira: https://issues.cask.co/browse/CDAP-2404
Shutting down the executor used to run the action, once the action completes. Tested on the distributed and verified that once the MapReduce job running under Workflow completes, Workflow container also gets completed.
=> CDAP-2404 Shutting down the executor once the action completes.

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/pom.xml
Bamboo : http://builds.cask.co/browse/CDAP-RT23-1
=> Setting snappy dependency to 1.1.1.7 since 1.0.5 causes problems with Kafka RealtimeSource

cdap-cli/src/main/java/co/cask/cdap/cli/command/ExecuteQueryCommand.java, cdap-client/src/main/java/co/cask/cdap/client/QueryClient.java, cdap-explore-client/src/main/java/co/cask/cdap/explore/client/AbstractExploreClient.java, cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreExecutionResult.java, cdap-explore-jdbc/src/test/java/co/cask/cdap/explore/jdbc/MockExploreClient.java
https://issues.cask.co/browse/CDAP-2162
http://builds.cask.co/browse/CDAP-RBT267
```
cdap (http://localhost:10000/default)> execute "select count(*) from stream_purchasestream"
Error: Query 'select count(*) from stream_purchasestream' execution did not finish successfully. Got final state - ERROR
```
=> CDAP-2162: CLI show error status when query finishes with non-FINISHED status

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/realtime/RealtimeSource.java, cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/realtime/SourceState.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLWorker.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/templates/etl/realtime/ETLWorkerTest.java
Mainly by reducing dataset access.
i) Fetch the source state only once in the beginning.
ii) Update that state only if there is a change in state.
iii) Invoke the sink's write method only if there is data to be persisted
iv) Start a Transaction only if there is sink data to be persisted or state has to be persisted
v) Accumulate all data from TransformExecutor before invoking sink's write
Other functional changes:
i) If there is an exception thrown when polling source, then continue without processing data
JIRA: https://issues.cask.co/browse/CDAP-2415
Build : http://builds.cask.co/browse/CDAP-RT27-1
=> CDAP-2415 improving etl worker performance 

cdap-common/src/main/java/co/cask/cdap/common/queue/QueueName.java, cdap-master/pom.xml, cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java, cdap-master/src/main/java/co/cask/cdap/data/tools/flow/FlowQueuePendingCorrector.java, cdap-master/src/test/java/co/cask/cdap/data/tools/flow/FlowQueuePendingCorrectorTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java, cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricDataQuery.java
http://builds.cask.co/browse/CDAP-RBT264
```
/opt/cdap/master/bin/svc-master run co.cask.cdap.data.tools.FlowQueuePendingCorrector -n default -a PurchaseHistory -f PurchaseFlow
```
Help message for the new tool:
```
usage: --namespace <namespace> --app <app> --flow <flow>
[--producer-flowlet <flowlet> --consumer-flowlet
<flowlet> [--queue <queue>]]
-a,--app <arg>                app
-c,--consumer-flowlet <arg>   consumer flowlet (optional, leave empty to
correct entire flow)
-f,--flow <arg>               flow
-n,--namespace <arg>          namespace
-p,--producer-flowlet <arg>   producer flowlet (optional, leave empty to
correct entire flow)
-q,--queue <arg>              flowlet queue (optional, defaults to
"queue")
```
* Tested UpgradeTool changes in a cluster
* Tested …
=> CDAP-2264: FlowQueuePendingCorrector tool for correcting the queue.pending metric

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java
Explore Service Status endpoint was not working properly (which I noticed while trying to run JDBC driver against CDAP). The issue was a failure in routing.
Simply pulled in the following code from 2.8, to get it working again:
https://github.com/caskdata/cdap/blob/release/2.8/cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java#L91-L92
http://builds.cask.co/browse/CDAP-RBT261-1
=> Fix routing for explore service status endpoints

cdap-client/src/main/java/co/cask/cdap/client/AdapterClient.java, cdap-common/src/main/java/co/cask/cdap/common/http/AuthenticationChannelHandler.java
Some http logging wasn't logging the exception, [like so](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/2CLgnrdnyuubUgp/Screen%20Shot%202015-05-01%20at%2011.20.00%20AM.png). Now it's [like this](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/72a05GKCmB0JPLB/Screen%20Shot%202015-05-01%20at%2011.56.20%20AM.png).
Also, adapter create error message was not informative, [like so](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/3NekgQzWEdzIsib/Screen%20Shot%202015-05-01%20at%2011.37.17%20AM.png). Now it's [like this](https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/gM1rGFOP0tG5kYe/Screen%20Shot%202015-05-01%20at%2011.38.01%20AM.png).
http://builds.cask.co/browse/CDAP-RBT254-1
=> Improved log messages.

cdap-api/src/main/java/co/cask/cdap/internal/lang/Reflections.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java
Without this, unit test "TestFrameworkTestRun.testGenerator()" fails.
=> (CDAP-2423) Skip synthetic methods when inspecting flowlet methods.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
Looks like typo from ProgramLifecycleService class name when adding startup and shutdown method for ApplicationLifecycleService class.
=> Simple fix copy paste error log for ApplicationLifecycleService log.

cdap-ui/app/features/adapters/templates/create/tabs/sinkPropertyEdit.html, cdap-ui/app/features/adapters/templates/create/tabs/sourcePropertyEdit.html, cdap-ui/app/features/adapters/templates/create/tabs/transformPropertyEdit.html
Fixes plugin property label in adapter create view provides a valid popover with default description if the backend doesn't provide one.
=> Fixes source/sink & tranforms edit properites to popover default descriptions if not provided by nodejs config

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ScriptFilterTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ScriptTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ScriptFilterTransformTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ScriptTransformTest.java
supply a shouldFilter function instead of placing you inside the
shouldFilter function. This allows users to define their own
helper functions, and makes it more explicit what is going on.
=> CDAP-2411 tweak the filter transform so that the property must

cdap-standalone/bin/cdap.bat, cdap-standalone/bin/cdap.sh, cdap-standalone/pom.xml, cdap-standalone/src/main/java/co/cask/cdap/UserInterfaceService.java, cdap-ui/conf/ui-env.sh, cdap-ui/pom.xml
=> Remove alpha from the directory structure for UI

cdap-ui/app/features/userprofile/controllers/profile-ctrl.js
-This was missed because when security is not enabled we don't show the login view and skip directly to the overview page.
- But when it is enabled and if the current user is not authenticated we show the login form.
- This login form is being reused(only the template) in the profile page which wanted the security to be enabled (which needed to be set in the current scope)
=> Fixes viewing access token in user profile page when security is on

cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/services/etl-create-factory.js, cdap-ui/app/features/adapters/templates/create.html
- Fixes overflow-x to show the dropdown menu of list of stored adapters.
- Fixes plugins count to show '0' when no plugins are there.
=> Fixes overflow-x in adapters to show list of drafts + plugins count fix in panel header

BUILD.rst, cdap-docs/_common/common-build.sh
Delete a zero-length file. 
Update the Docs SDK build command to the latest target. 
Update the BUILD.rst to 1024 for building SDK.
=> Update build instructions, doc build script, and a file cleanup.

cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/datasets/templates/detail.html, cdap-ui/app/styles/themes/cdap/theme.less
- Fixes add app in apps list view.
- Fixes Dataset detailed view of explorable datasets.
- Fixes global table header view (reverses the background color with text color)
=> Fixes tables default header color + datasets non-explorable view + add in apps list view

.gitignore
Change the .gitignore to add templates and remove plugins directory.
=> Fix .gitignore to ignore templates directory due to plugins dir restructure

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
Jira: https://issues.cask.co/browse/CDAP-2449
Spark programs if run through Workflows should have the properties field which includes the runid of the Workflow.
=> CDAP-2449 Update the Spark runrecord with the Workflow runId

cdap-ui/app/directives/c3/charts.js
=> Give bar charts tick culling, to avoid crowded timestamps.

cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/read/FileLogReader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/read/KafkaLogReader.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LoggingTester.java
Also, closing log callback in handler instead of log readers since now each call to fetch logs can span multiple readers.
=> CDAP-2463 Using right log offset to fetch logs from Kafka

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java
Seemed like omitting JMS dependency spec caused problem with ETLAdapter tests
=> Return back dependency on JMS for realtime lib bc it is breaking class logic

cdap-ui/app/features/adapters/controllers/create-ctrl.js
The alert on adapter draft page wouldn't work.
https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/qK4lb80tLRHY4MY/Screen%20Shot%202015-05-05%20at%202.02.36%20AM.png
This resolves that.
Now it properly shows this:
https://s3.amazonaws.com/uploads.hipchat.com/26476/1011205/O7OOhNhSnQDjyAk/Screen%20Shot%202015-05-05%20at%202.04.21%20AM.png
=> Fix error message when name is missing from adapter draft.

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/realtime/source/JmsSourceTest.java
Currently the name of the ConnectionFactory property for JMS source is called "ConnectionFactory".
Need to change it something to follow the rest of JMS source property names, for example: jms.destination.name
=> [CDAP-2474] Change the ConnectionFactory JNDI name to be consistent with other properties in JMS source.

cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteStreamCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/StreamCommands.java, cdap-client-tests/src/test/java/co/cask/cdap/client/StreamClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java, cdap-common/src/main/java/co/cask/cdap/common/io/Locations.java, cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriterTestBase.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamFileJanitor.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriter.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
- Added the DELETE /streams/{stream-id} endpoint
- Includes some code cleanup to unify StreamMetaStore usage
- For stream not found, throw the NotFoundException to simplify code.
- Implements delete by moving the stream directory into a special .deleted directory
- Stream file janitor is responsible to cleanup that .delete directory
- Adjusted code that do raw list of stream directories to one filterd out special directory
=> (CDAP-332) Added a REST endpoint for deleting a stream

cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/styles/variables.less
Don't know how this got removed. Anyways adding it back in develop (https://github.com/caskdata/cdap/blob/release/3.0/cdap-ui/app/features/adapters/etlapps.less#L70)
=> Fixes stylings in adapter create view

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterTwillApplication.java
Looks like the log class for MasterTwillApplication has it sets to use MasterServiceMain class.
=> Fix the log class name for MasterTwillApplication from MasterServiceMain to MasterTwillApplication.

cdap-ui/templates/etlRealtime/Jms.json
From JIRA:
After the fix for CDAP-2474 for ConnectionFactory in JMS source, we need to update name of the ConnectionFactory in the json file to reflect in UI
=> CDAP-2493 Change the name of parameters for JMS source from ConnectionFactory to jms.jndi.connectionfactory.name in JSON file for UI.

cdap-common/src/main/java/co/cask/cdap/common/lang/CombineClassLoader.java
Jira: https://issues.cask.co/browse/CDAP-2491
=> Use LinkedHashSet to preserve the ordering of the classloader resourses.

cdap-ui/app/directives/c3/charts.js
=> Decrease donut radius, so that text overflow is not an issue.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
In 3.0 we have a scheduler thread to check and update Run Record store for those with RUNNING state but does not have the real program running via check to RuntimeService.
However, for Run Records for Workflow child programs, the runtime service never return runtime info since those runs are run from Workflow driver. Which means that there is no Twill application for the internal child programs run records to check against.
The effect is that the UI will display children program runs for a workflow as FAILED even though it may be COMPLETED or still RUNNING.
This PR contains fix to update the RunRecord checker to account for this situation:
-) Refactor the code to reuse the logic to get the right Program id for run records with RUNNING state but not actually running.
-) Check the RunRecord …
=> CDAP-2490 Check if invalid Run Records for Spark and MapReduce part of run from Workflow child programs

cdap-api/src/main/java/co/cask/cdap/api/templates/ApplicationTemplate.java
Simple PR to reduce use of word "configure" in the JavaDoc for the ApplicationTemplate class.
=> Simplify the JavaDoc for ApplicationTemplate

cdap-examples/pom.xml
It was missing, and so the following command from `BUILD.rst` was not working (RAT check failures):
` MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128m" mvn package -DskipTests -pl cdap-examples -am -amd -P examples`
http://builds.cask.co/browse/CDAP-DUT1831-2
=> Add CubeService as a module to cdap-examples pom

cdap-ui/app/styles/themes/cdap/theme.less
Fixes modal's margin-top to be a constant instead of using translate css property. (Doesn't play well with both angular-strap's modal and angular-bootstrap modal)
=> Fixes margin top for all modal in cdap

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
This PR is for back porting the fix for Jira https://issues.cask.co/browse/CDAP-2489 to release 3.0.1
=> CDAP-2489 Fixed the invalid RunId comparison and simplified the condition. Cherry pick for release 3.0.1

cdap-common/src/main/java/co/cask/cdap/common/lang/CombineClassLoader.java
Jira: https://issues.cask.co/browse/CDAP-2491 Fixed in develop. This PR is to back port the fix for release 3.0.1
=> Use LinkedHashSet to preserve the ordering of the classloader resourses. Cherry-pick commit from develop.

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json, cdap-distributions/src/packer/scripts/fluxbox.sh, cdap-distributions/src/packer/scripts/motd.sh
These settings improve performance and properly display a help menu in the first xterm.
Same as #2654 for develop branch
=> Change name and add more vboxmanage settings (develop)

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/realtime/source/JmsSourceTest.java, cdap-ui/templates/etlRealtime/Jms.json
Add 2 new JMS source configuration properties to set the dependent 3rd party plugin for JMS Connection initial context factory.
This will allow different JMS Source plugin to have different JMS provider implementation plugin definition, eg: ActiveMQ or RabbitMQ, or ZeroQ
=> CDAP-2475 Make the JMS source to accept type and name of the JMS provider plugin.

cdap-ui/app/features/admin/controllers/ServiceDetailController.js, cdap-ui/bower.json
Update Angular and angular components to 1.3.15 (1.4 is not a stable release yet). There are some performance improvement especially in regards to memory leakage.
You need to remove bower_components and clean up bower cache (**bower cache clean**). Then do **bower install**
=> update angular and fix breakage in services within admin

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
The PR add new test for ProgramLifecycleService#validateAndCorrectRunningRunRecords to validate the RunRecords with RUNNING state but no actual program running when checking the ProgramRuntimeService.
Make the validateAndCorrectRunningRunRecords method to be packaged private for easy testing.
=> CDAP-2448 Add new test ProgramLifecycleServiceTest to test RunRecord instances with RUNNING state but no actual program running

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TwitterSource.java
Currently the TwitterSource create one instance of StructuredRecord.Builder and reuse it to convert Tweets to StructuredRecord instances.
This will cause problems because StructuredRecord.Builder#build reuse the same fields
member variable to create new StructuredRecord. All converted Tweets to StructuredRecords will have the same values when being written to Emitter.
=> Create new StructuredRecord.Builder instance per Tweet conversions in TwitterSource

cdap-ui/app/directives/program-preferences/program-preferences.js, cdap-ui/app/directives/runtime-args/runtime-args.js, cdap-ui/app/directives/start-stop-button/start-stop-button.js
- Provides the ability to store the preferences and run time arguments for the duration of the browser session.
- Modifies my-start-stop-button directive to use the preferences & runtime arguments services (pass in runtime args and preferences to be displayed in the modal)
=> Fixes runtime args and preferences on program level to be persistent for the duration of the browser session

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AdapterHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterAlreadyExistsException.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/InvalidAdapterOperationException.java, cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricClient.java, cdap-common/src/main/java/co/cask/cdap/common/exception/BadRequestException.java, cdap-common/src/main/java/co/cask/cdap/common/exception/CannotBeDeletedException.java
https://issues.cask.co/browse/CDAP-2422
http://builds.cask.co/browse/CDAP-DUT1812
Preview before making changes to the rest of the HTTP handlers.
=> CDAP-2422: Remove redundant catch blocks in AdapterHttpHandler

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/kafka/KafkaSimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/realtime/source/KafkaSourceTest.java
In Adapter realtime source plugin flow the SourceState is used as the source of offset for the topics and only passed when poll is called.
The initialization of Kafka Consumer infos for topics need to be suspended until first call to poll is called.
Updated the unit test to relfect this.
=> CDAP-2547 Kakfa Source - Doesn't use the persisted offset when the Adapter is restarted.

cdap-ui/app/directives/metric-picker/metric-picker.html
100 is a larger limit, while still being performant.
Helps with: https://issues.cask.co/browse/CDAP-2173
=> CDAP-2173 increase metric-picker limit

cdap-ui/app/features/datasets/controllers/tabs/status-ctrl.js
because of hoisting in JavaScript, datasetTags variable is undefined when pollMetric function is called.
=> fix hoisting issue with dataset status page

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
- There are unnecessary wait in a loop in adapter lifecycle tests
- Cleanup methods in AppFabricTestBase to use the same way for retrying.
=> Cutting ~6m from test run time

cdap-test/src/main/java/co/cask/cdap/test/WorkflowManager.java
WorkflowManager extend ProgramManager for common program functionalities.
This change was missed from the following PR: https://github.com/caskdata/cdap/pull/2705; putting it in now.
http://builds.cask.co/browse/CDAP-DUT1900-1
=> WorkflowManager extend ProgramManager for common program functionalities

cdap-cli/src/main/java/co/cask/cdap/cli/command/DescribeDatasetInstanceCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetDatasetInstancePropertiesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DatasetCommands.java, cdap-client-tests/src/test/java/co/cask/cdap/client/DatasetClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/DatasetClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java, cdap-docs/reference-manual/source/http-restful-api/dataset.rst
https://issues.cask.co/browse/CDAP-1868
http://builds.cask.co/browse/CDAP-DUT1879
* Also removes requirement for passing in dataset type to PUT /data/datasets/{name}/properties endpoint (not backwards-compatible)
=> CDAP-1868: Set dataset properties support for client and CLI

cdap-ui/app/directives/start-stop-button/start-stop-button.js
Fixing a problem where when a user is at /runs/:runid and they click start a new run button, it does not go to the most recent runs.
=> go to the most current runs when a program start is clicked

cdap-ui/bower.json
Updated SockJS Client to version 1.0.0 from 0.3.4. 
Have to remove bower_components, and do bower install.
This PR should be merged after #2749
=> update sockjs client to version 1.0.0

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java
https://issues.cask.co/browse/CDAP-2529
Now when you try to execute a command in the CLI but the provided connection cannot be used, you see the following:
```
CDAP instance at 'http://localhost:10000' could not be reached: Connection refused
```
instead of
```
```
=> CDAP-2529: CLI print error on failed autoconnect

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
This PR contains change to make the RunRecords corrector thread to 
-) Add logging to indicate start of run method of the cleaner.
-) Add try-catch to ignore exceptions for the schedule executors
-) Save the processed incorrect RunRecord IDs to detect workflow and children programs.
-) Remove the static modifier for the ProgramLifecycleService#retrieveProgramIdForRunRecord 
method, so we  do not need to pass the Store.
=> [CDAP-2571] Make the ProgramLifecycleService.RunRecordsCorrectorRunnable to be more resilient.

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
JIRA: https://issues.cask.co/browse/CDAP-2254
Build: http://builds.cask.co/browse/CDAP-DUT1918-1
Fix the following bug: when one tries to suspend or resume a stopped/completed/failed workflow, he will get incorrect message "Unable to retrieve runtime information for %s (Application: %s)"
How to fix:
For the two methods suspendWorkflowRun and resumeWorkflowRun in WorkflowHttpHandler.java, once I found the run-id is stopped/completed/failed, I sent an error message at once.
Since sendInvalidResponse method is not used any more, delete it.
Test case:
1. Tested fix manually on standalone as well as on distributed mode.
2. Added a unit test case to the corresponding test file, to test I get correct code when I try to suspend/resume after a workflow is completed.
=> CDAP-2254 Fixed the error message returned by handler

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
Cherry pick from develop:
-) Add logging to indicate start of run method ot the cleaner.
-) Add try-catch to ignore exceptions for the schedule executors
-) Save the processed incorrect RunRecord IDs to detect workflow and children programs.
-) Remove the static modifier for the ProgramLifecycleService#retrieveProgramIdForRunRecord
method, so we do not need to pass the Store.
-) Updated some log statements.
=> CDAP-2584 Make the ProgramLifecycleService.RunRecordsCorrectorRunnable to be more resilient.

cdap-ui/app/directives/error/error.less
=> [CDAP-2633] add max-height to error popover content

cdap-docs/_common/common-build.sh, cdap-docs/build.sh, cdap-docs/examples-manual/build.sh
- cleaned up exit codes on main case statements
- added a message handling facility that writes messages to a tmp file and then plays them back again, at both the end of building a manual, and at the end of the entire run.
- returns 1 if there are any warning messages to indicate a failed run.
- [Example of failed run](http://builds.cask.co/browse/CDAP-DDBD151-1/log)
- [Example of successful run, after fixing MD5 changes](http://builds.cask.co/browse/CDAP-DDBD151-8/log)
https://issues.cask.co/browse/CDAP-2552
Update: it now outputs the Sphinx warnings to a tmp file, and then appends them to the message tmp file. That way, all messages are now visible at the end of the log file...
=> Revisions to build scripts:

cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/AbstractGetPreferencesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/AbstractSetPreferencesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteNamespaceCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/DeletePreferencesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/GetServiceEndpointsCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/GetWorkflowCurrentRunCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/LoadPreferencesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetPreferencesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetStreamFormatCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetStreamNotificationThresholdCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetStreamPropertiesCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/SetStreamTTLCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/system/HelpCommand.java
- Standardizes the capitalization for the CLI help and messages
- Corrects grammer in  a couple of messages
- Adds an additional "warning" message when deleting a namespace or its contents
=> CLI capitalization

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json, cdap-distributions/src/packer/scripts/network-cleanup.sh
This removes the MAC address -> interface mapping from udev, so the first ethernet device will become `eth0` whether the MAC is reinitialized or not.
=> CDAP-2640 Remove persistent network rules on VM

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetServiceModules.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetService.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DistributedStorageProviderNamespaceAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/LocalStorageProviderNamespaceAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/StorageProviderNamespaceAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/UnderlyingSystemNamespaceHandler.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/UnderlyingSystemNamespaceHandlerTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java
1st commit deletes the namespace directory if it exists during namespace creation. It also switches the order of deletion during namespace delete - Removes from MDS first, then from the storage providers. This ordering will help us make this process more fool-proof in future.
2nd commit is a mere rename of all ``Underlying**`` classes to ``StorageProvider**``.
Jira: [CDAP-2587](https://issues.cask.co/browse/CDAP-2587)
Build: http://builds.cask.co/browse/CDAP-RBT301
=> CDAP-2587 During namespace create, delete the namespace directory on the filesystem if it already exists

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
Utilize the config in the json of the metadata upon namespace create.
Also, ignore the `name` field of the metadata upon namespace properties update.
https://issues.cask.co/browse/CDAP-2635
http://builds.cask.co/browse/CDAP-DUT1948-6
=> Utilize the config in the json of the metadata upon namespacece create

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json, cdap-distributions/src/packer/scripts/cookbook-setup.sh
Pull in the `hadoop` [cookbook](https://github.com/caskdata/hadoop_cookbook) from Chef Supermarket and install the `hadoop::flume_agent` recipe, from the default distribution.
=> CDAP-2612 Add Flume agent to VM

cdap-docs/_common/common-build.sh
The doc log was truncating the last line of any collected messages. This fixes that by adding an extra line at the end.
=> Fix the build log message.

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AdapterHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/InvalidPluginConfigException.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginInstantiator.java
Handle NumberFormatException (invalid Integer/Double values in the PluginConfiguration) which was previously propagated as RuntimeException and thus returned 500 instead of 400 Bad Request.
Build : http://builds.cask.co/browse/CDAP-RBT300
=> CDAP-2597 Catch invalid Plugin configuration and return 400 instead of 500

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TwitterSource.java
of the tweet instead of calculating difference in ingest time
versus tweet time.
=> CDAP-2656 fix the time field for tweets to just use the timestamp

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json, cdap-distributions/src/packer/scripts/fill-maven-cache.sh
This populates `/home/cdap/.m2/repository` with a bunch of dependency JARs for building CDAP examples.
=> CDAP-2613 Cache dependencies to build CDAP examples

cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/user-profiles.rst, cdap-docs/examples-manual/source/examples/web-analytics.rst
Fixes the doc build. The break was due to changes in Java files that are included in the examples and are incorporated as part of the build. As these files are referenced by line number, any changes to the files can potentially require a change in the code that includes fragments of the Java code. In this case, that was so, as lines had been deleted from the Java code, and so the offsets needed to be adjusted in the documentation to accommodate.
=> Fix broken doc build.

pom.xml
The dependency of doxia-core on xerces causes lots of error messages in the maven builds:
```
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Warning:  org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not …
```
=> Remove dependency on xerces of doxia

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java, cdap-docs/reference-manual/source/http-restful-api/metrics.rst, cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseHistoryBuilder.java
We removed quite a few v2 handlers just prior 3.0 release, but did not simplify the helper methods in AppFabric.
This cleans it up a bit:
`programList` no longer accepts an `applicationId`, since there are no usages that pass one.
Same for the `getAppRecords` method.
http://builds.cask.co/browse/CDAP-DUT1984-4
=> Simplify AbstractAppFabricHttpHandler.java

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
- The bug was introduced to 3.0.0 in CDAP-1917, PR https://github.com/caskdata/cdap/pull/2147
- The attempt was to have all temporary files created under a single temp directory to simplify cleanup process, but missed the usage of File.createTempFile.
=> (CDAP-2698) Cleanup Program jar properly

cdap-ui/app/features/admin/controllers/NamespaceDatasetMetadataController.js, cdap-ui/app/features/admin/controllers/NamespaceSettingsController.js, cdap-ui/app/features/admin/controllers/StreamPropertiesController.js
hiding loading icon when an error occurs during delete operation of dataset, stream, or namespace
=> hide loading icon when there is an error in delete function

cdap-ui/templates/common/Projection.json
backend describes the expected format of the values while the UI
hides that from users.
=> CDAP-2722 UI specific descriptions for projection, since the

cdap-cli/src/main/java/co/cask/cdap/cli/command/GetProgramLogsCommand.java
This means that you can provide a time range for retrieving logs from the CLI. Earlier, if start and end times were provided, an error would pop up saying that the end time should be greater than the start time provided. This was because the start and end times were being defaulted to 0. Also, "now" works if given as input to the start and end times in CLI. So the current time can be obtained easily.
=> CDAP-2617 start and end times for logging now working.

cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/template/etl/realtime/ETLWorkerTest.java, cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java, cdap-common/src/main/java/co/cask/cdap/common/utils/TimeMathParser.java, cdap-common/src/test/java/co/cask/cdap/common/utils/TimeMathParserTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamFetchHandler.java, cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteStreamManager.java, cdap-test/src/main/java/co/cask/cdap/test/StreamManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultStreamManager.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java, cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java
Build -http://builds.cask.co/browse/CDAP-DUT1934-2
JIRA - https://issues.cask.co/browse/CDAP-1926
Streams endpoint now accepts times formatted as "now-xs".
=> [CDAP-1926] streams endpoint accepts now-xs format

cdap-common/src/main/resources/cdap-default.xml
Adding perm gen size to twill runnables.
Tested on a cluster and the service spun up with MaxPermSize set
`/usr/lib/jvm/java/bin/java -Djava.io.tmpdir=tmp -Dyarn.container=container_1434045650548_0001_01_000006 -Dtwill.runnable=master.services.explore.service -cp launcher.jar:/etc/hadoop/conf -Xmx774m -XX:MaxPermSize=128M -verbose:gc -Xloggc:/data/logs/hadoop-yarn/userlogs/application_1434045650548_0001/container_1434045650548_0001_01_000006/gc.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M org.apache.twill.launcher.TwillLauncher container.jar org.apache.twill.internal.container.TwillContainerMain true`
=> Add PermGen size in app.program.jvm.opts

BUILD.rst, cdap-standalone/pom.xml, pom.xml
Removes the HTML Javadocs included in the SDK zip file, and cdap-api files no longer required as offline compilation is no longer supported.
Built and tested locally.
Fix for https://issues.cask.co/browse/CDAP-2730
=> Fix SDK build and javadocs

cdap-ui/app/services/data/datasource.js
- improving apparent performance by making the stopPoll operation an asynchronous operation.
- consolidate the $destroy callback to both delete the instance binding and stop poll.
=> consolidate $destroy callback to delete binding instances and stop poll

cdap-ui/app/features/spark/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/features/spark/spark.less, cdap-ui/app/features/spark/templates/tabs/runs/tabs/status.html
Increase polling frequency for metrics so that it will show up in the status page.
Spark program finished very quickly so the metric changed rapidly.
=> increase polling frequency

cdap-cli/src/main/java/co/cask/cdap/cli/command/StartDebugProgramCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/StartProgramCommand.java, cdap-cli/src/main/java/co/cask/cdap/cli/command/StartProgramCommandSet.java, cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java
The `StartDebugProgramCommand` seemed to be nearly identical to `StartProgramCommand`, with only minor differences, so refactored it.
Also, the `StartDebugProgramCommand` was not being added to the `StartProgramCommandSet`, which is fixed in this PR.
Build: http://builds.cask.co/browse/CDAP-DUT2028-1
=> Refactor and fix start-debug command of CDAP CLI.

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
- The “root” node can be namespace by the zk connect string, hence may not exist yet.
- E.g. host:2181/cdap
- By creating “/“ with the given connection string, it make sure the relative root exist.
=> (CDAP-2569) Always try to create the root ZK node on Master service startup

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/InMemoryServiceProgramRunner.java
Use co.cask.cdap.common.app.RunIds instead of org.apache.twill.internal.RunIds for InMemoryServiceProgramRunner.
This issue is found when the RunId cleaner try to filter the RUNNING run records with check to
the RunId hash code which is from UUID for CDAP common and String for Twill.
=> CDAP-2769 Use co.cask.cdap.common.app.RunIds for InMemoryServiceProgramRunner

cdap-ui/npm-shrinkwrap.json, cdap-ui/package.json
Right now there is no way to freeze on dependencies for node modules in node proxy. shrinkwrap allows us to lock onto the specific versions. So any subsequent npm install would install only those specific versions guaranteeing a stable version of node server based on current dependencies.
NOTE:
I have manually gone through all 1st level dependencies' package.json files to check what is the min node version that it needs to run stable. Based on that I have modified the min version of node engine to be 0.10.0. This ensures that if the user is using a node version that is less than that then npm install would fail, indicating that they need a newer version of node.
=> Flattens node module dependencies with shrinkwrap

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AbstractInMemoryProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/InMemoryServiceProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/InMemoryWorkerRunner.java
Moving common functionality to parent class. Removal of ServiceWorkers logic made this easier to accomplish.
Build: http://builds.cask.co/browse/CDAP-DUT2030
=> CDAP-1583 refactored inmemory program runners - worker, service

cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/spark-page-rank.rst
Staged at: http://docs-staging.cask.co/cdap/3.1.0-SNAPSHOT-feature-3.1_fix_doc_build/en/examples-manual/examples/spark-page-rank.html
=> Correct broken doc build.

cdap-ui/app/features/apps/controllers/list-ctrl.js, cdap-ui/app/features/apps/templates/list.html
Search input has been positioned to the right of the Actions dropdown since it requires more space overall. This will allow it to kick to a full row column on smaller devices.
=> adds search and pagination filtering to apps list

cdap-docs/_common/common_conf.py, cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/developers-manual/source/getting-started/standalone/index.rst, cdap-docs/integrations/source/partners/cloudera/configuring.rst, cdap-docs/reference-manual/source/faq.rst
- Add text " ; we recommend |recommended-node-js-version|" everywhere that Node.js is described.
- Set recommended version to "v0.12.0".
Staged at (and pages of interest):
- [Installation](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_update_nodejs_text/en/admin-manual/installation/installation.html#node-js-runtime)
- [Getting Started: Standalone](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_update_nodejs_text/en/developers-manual/getting-started/standalone/index.html#standalone-index)
- [FAQ](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_update_nodejs_text/en/reference-manual/faq.html#platforms-and-language)
- [Integrations: Configuring Cloudera](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_update_nodejs_text/en/integrations/partners/cloudera/configuring. …
=> Updating text about Node.js version

cdap-ui/app/features/adapters/controllers/create-ctrl.js, cdap-ui/app/features/adapters/controllers/create/default-tab-ctrl.js, cdap-ui/app/features/adapters/services/AdapterCreateModel.js
- Should be able to add the same source/sink any number of times the user want. The UI should still create only object (no overwrites should happen)
- When plugin's property is already being edited (opened in a new tab) and if the plugin is either deleted or overwritten then the tab should be removed to avoid any confusion.
- When publish button is clicked and when the UI does client side validations only one alert message should be opened at a time. No repeated multiple alert messages.
Secure Cluster: http://securecluster1762-1000.dev.continuuity.net
Non-Secure Cluster: http://nodeproxy1736-1000.dev.continuuity.net:9999/
=> Fixes repeated alerts and confusion about opened tabs in adapter create view

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/BaseETLBatchTest.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLStreamConversionTest.java
JIRA: https://issues.cask.co/browse/CDAP-2670
Builds: http://builds.cask.co/browse/CDAP-DUT2054-5
Added unit test to the parquet sink, 
In function readOutput(), the method new AvroParquetReader<GenericRecord> is a deprecated method but I cannot find an easy way about how to read Parquet file without using mapreduce on google.
=> CDAP-2670 add unit cases

cdap-docs/developers-manual/source/getting-started/standalone/index.rst, cdap-docs/developers-manual/source/getting-started/standalone/zip.rst
Add to the standalone/zip (which is linked on the Cask website as the "Installation Guide" for the SDK zip) instructions on the dependency requirements.
Staged at: http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_download_instructions/en/developers-manual/getting-started/standalone/zip.html
Current: http://docs.cask.co/cdap/3.0.0/en/developers-manual/getting-started/standalone/zip.html
=> Fix Installation Guide instructions for SDK zip

cdap-docs/_common/common_conf.py, cdap-docs/_common/highlevel_conf.py, cdap-docs/build.sh
These changes support modifications to the CDAP timeline, displayed at http://docs.cask.co/cdap/index.html. The changes modify the json-versions.js so that it results in a condensed timeline, and with improved formatting of the list of "Older" releases.
- Added targets to build and display the JSON file (json-versions.js) to the build script.
- Moved scripts that manipulate the JSON file from the common configuration to the high-level configuration file, so that the common conf.py is more just configuration rather than scripting.
=> Improvements to CDAP timeline

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java, cdap-docs/developers-manual/source/building-blocks/namespaces.rst, cdap-docs/reference-manual/source/http-restful-api/dataset.rst, cdap-docs/reference-manual/source/http-restful-api/namespace.rst
Staged at:
-[Deleting a Namespace](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_delete_namespaces/en/reference-manual/http-restful-api/namespace.html#deleting-a-namespace)
-[Deleting all Datasets](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_delete_namespaces/en/reference-manual/http-restful-api/dataset.html#deleting-all-datasets)
-[Namespaces: Using Namespaces](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_delete_namespaces/en/developers-manual/building-blocks/namespaces.html#using-namespaces)
=> Adding deletion of namespace to documentation.

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java
https://issues.cask.co/browse/CDAP-2802
http://builds.cask.co/browse/CDAP-DUT2067
=> CDAP-2802: Stop using HiveConf.ConfVars.defaultValue, to support Hive >0.13

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/TrackedTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/DBSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/DBSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/DBRecord.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/DBUtils.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/ETLDBInputFormat.java, cdap-standalone/src/main/java/org/apache/hadoop/util/ReflectionUtils.java
This thread maintains a reference to the classloader, thereby causing OOM as well as too many open files errors.
Also fixed a related issue where the BatchSource and BatchSink's destroy methods were not being called by making TrackedTransform a Destroyable.
Jira: 
[CDAP-2743](https://issues.cask.co/browse/CDAP-2743) 
[CDAP-2750](https://issues.cask.co/browse/CDAP-2750)
Build: http://builds.cask.co/browse/CDAP-RT38
=> [CDAP-2743] [CDAP-2750] Shutdown a dangling MySQL Abandoned Cleanup Thread in DBSource and DBSink's destroy method.

cdap-ui/app/index.html, cdap-ui/app/services/data/socket.js
- Removes live-reload script from index.html 
- Avoids logging-in request and response in debugger when in secure mode.
=> Removes live-reload + avoid logging request and response in secure mode

cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/sport-results.rst
Update MD5 hashes and update include of a file.
Documentation build was broken as of [build #205](https://builds.cask.co/browse/CDAP-DDBD-205/).
Clean Built at: 
- [CDAP Docs](http://docs-staging.cask.co/cdap/3.1.0-SNAPSHOT-feature-3.1_fix_examples_manual/en/index.html)
- [Log](http://builds.cask.co/browse/CDAP-DDBD385-1/log)
=> Fix broken documentation build

cdap-docs/_common/_themes/cdap/search.html, cdap-docs/_common/_themes/cdap/static/searchtools.js_t, cdap-docs/_common/common_conf.py
Brings (most) of https://github.com/caskdata/cdap/pull/2728 to Release 3.0.1. (It leaves the "New" icon on Application Templates.)
It brings the re-organized search results (divided into groups based on the manual, and then scored within the group) in the documentation to the next Release.
Staged at: [Search page](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_fix_search_results/en/search.html)
[Example Search of "Hadoop"](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_fix_search_results/en/search.html?q=Hadoop)
=> Port Improved Search Results to Release 3.0.1

cdap-distributions/src/packer/scripts/fill-maven-cache.sh
This uses the files from /opt/cdap/sdk/examples versus fetching develop from git.
=> Use SDK examples to fill Maven cache, not develop

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/DBSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/DBSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/DBUtils.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/ETLDBInputFormat.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/ETLDBOutputFormat.java, cdap-common/src/main/java/co/cask/cdap/common/io/URLConnections.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java, cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
Build: http://builds.cask.co/browse/CDAP-RT39
Jira: [CDAP-2750](https://issues.cask.co/browse/CDAP-2750)
Currently running a test with SDK on Ubuntu.
=> [CDAP-2750] Ported JDBC driver cleanup fixes to DBSink

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java, cdap-ui/templates/ETLBatch/FileBatchSource.json
JIRA -  https://issues.cask.co/browse/CDAP-2849
Build - http://builds.cask.co/browse/CDAP-DUT2093-1
FileBatchSource would read in twice if the mapreduce took longer than the duration of the workflow, since the last time read wouldn't be updated until onFinish(). Thus, we now update it in prepareRun() and revert it in onFinish() if the mapreduce failed.
=> [CDAP-2849] - FileBatchSource reads in twice

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetadataStoreDataset.java
The javadoc on the `Row get(byte[] row)` method of `Table` class says that it never returns `null`.
I have checked the two implementations of this method to verify that, and then make use of this fact to update the calls to the method.
http://builds.cask.co/browse/CDAP-DUT2082-2 (GREEN)
=> Table#get is guaranteed not to return null.

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java, cdap-common/src/main/java/co/cask/cdap/common/exception/CannotBeDeletedException.java, cdap-common/src/main/java/co/cask/cdap/common/namespace/AbstractNamespaceClient.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java, cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreHttpClient.java, cdap-notifications-api/src/main/java/co/cask/cdap/notifications/feeds/client/RemoteNotificationFeedManager.java, pom.xml
Fixed error messages in namespace delete operations.
Also fixed some cdap clients to reuse HttpResponse.toString instead of redefining the logic in private methods.
=> [CDAP-2767] Fix error messages in namespace delete

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactAlreadyExistsException.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInfo.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactMeta.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactNotExistsException.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/WriteConflictException.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
artifacts and their metadata. The store keeps the artifacts
on hdfs and metadata about the artifacts in a table. Artifact
metadata consists of information about the plugins contained
in the artifact. In the future, it will also contain info
about application classes in the artifact. The table also stores
a mapping from plugin to artifact to allow lookups by plugin
in addition to lookups by artifact id.
Not yet used anywhere, but the next step will be to use it as
the backing for plugins and plugin jars.
=> CDAP-2665 adding an ArtifactStore that can be used to persist

cdap-docs/integrations/source/partners/cloudera/configuring.rst
Documentation updates for https://issues.cask.co/browse/CDAP-2871
Staged here:  http://docs-staging.cask.co/cdap/3.1.0-SNAPSHOT-feature-csd-document-hbase-gateway/en/integrations/partners/cloudera/configuring.html
=> [CDAP-2871] document the client dependencies for CM cluster

cdap-distributions/src/packer/scripts/apt-cleanup.sh, cdap-distributions/src/packer/scripts/apt-setup.sh, cdap-distributions/src/packer/scripts/cookbook-dir.sh, cdap-distributions/src/packer/scripts/cookbook-setup.sh, cdap-distributions/src/packer/scripts/eclipse-cookbook.sh, cdap-distributions/src/packer/scripts/fill-maven-cache.sh, cdap-distributions/src/packer/scripts/lxde.sh, cdap-distributions/src/packer/scripts/motd.sh, cdap-distributions/src/packer/scripts/network-cleanup.sh, cdap-distributions/src/packer/scripts/random-root-password.sh, cdap-distributions/src/packer/scripts/remove-chef.sh, cdap-distributions/src/packer/scripts/sdk-cleanup.sh, cdap-distributions/src/packer/scripts/slim.sh, cdap-distributions/src/packer/scripts/vbox-guest-additions.sh, cdap-distributions/src/packer/scripts/xorg.sh, cdap-distributions/src/packer/scripts/zero-disk.sh
This error checks cases where we could potentially fail to produce the desired output. Specifically, this will fail the build if the Maven cache cannot be filled.
=> CDAP-2855 Fail on errors in scripts for Docker/VM

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/BatchFileFilter.java
JIRA- https://issues.cask.co/browse/CDAP-2739
BUILD - http://builds.cask.co/browse/CDAP-DUT2108-1
An arraylist of times that still need to be read are now stored in the table. If the file date falls within one of the ranges specified by this arraylist, then the file is accepted. If not, then the file is rejected.
=> Feature/cdap 2866 Ensure files are read in even after failure

cdap-ui/Gulpfile.js, cdap-ui/app/index.html
- Separates out dev build vs prod build (ui js build process)
Mainly addresses ```gulp watch``` when developing UI. ```gulp build``` should still work exactly the same.
=> Modifies Gulpfile to speed up build process for development

cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java, cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java
- Adds a MapReduce job in SparkPageRankProgram which calculates total number of pages for a given rank. 
- Adds a workflow which runs the Spark program followed by MapReduce.
- Updated the unit tests for the above additions.
- Doc updates will come in a separate PR. 
Build: http://builds.cask.co/browse/CDAP-DUT2105-2
=> Add a MapReduce job with Workflow in SparkPageRank example

cdap-ui/app/index.html
* Removes "All Rights Reserved" from UI copyright text in the footer
=> removes 'All Rights Reserved' from footer text

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactDetail.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInfo.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/PluginNotExistsException.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/WriteConflictException.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/filesystem/LocationCodec.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java, cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactVersion.java
Snapshot versions are mutable unlike other artifacts.
Also fixing up some bugs where the absence of a plugin or artifact
was not correctly throwing a not found exception.
Also changing ArtifactStore to return unmodifiable collections,
and to return location of the artifact when getting plugins.
=> CDAP-2846 support for snapshot versions to the artifact store

cdap-docs/admin-manual/source/installation/cdap-site.rst
updating cdap-site.xml appendix in release branch docs:
=> fix app.template.* to match cdap-default.xml

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceClassLoader.java, cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/BaseETLBatchTest.java, cdap-common/src/main/java/co/cask/cdap/common/lang/FilterClassLoader.java, cdap-common/src/main/java/co/cask/cdap/common/lang/ProgramClassLoader.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/dataset/SystemDatasetInstantiatorFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DirectoryClassLoaderProvider.java, cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/ExtensiveSchemaTableDefinition.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/KeyExtendedStructValueTableDefinition.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/KeyStructValueTableDefinition.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/KeyValueTableDefinition.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/WritableKeyStructValueTableDefinition.java
The first issue is that the FilterClassLoader does not filter
when getResource is called. When a dataset jar is built, this
can result in system jars getting leaked into the dataset jar.
The second issue is that in standalone mode, the classloader used
to instantiate DatasetType is a URLClassLoader, which means the
bundled lib jars are not visible. Finally, in explore, the
classloader a dataset is the same as the classloader for that
dataset's type, with the system classloader as a parent. This means
that system classes are leaked. Instead, the parent classloader
must be a FilterClassLoader. To support this, adding a couple
new ways to create a FilterClassLoader.
=> CDAP-2208 fixing dataset and explore classloading issues.

cdap-common/src/main/java/co/cask/cdap/common/exception/AlreadyExistsException.java
- Fixes DatasetInstanceHandlerTest.testBasics
http://builds.cask.co/browse/CDAP-DUT2152
=> Make AlreadyExistsException extend ConflictException

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/BatchFileFilter.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/LogParserTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/transform/LogParserTransformTest.java, cdap-ui/templates/common/LogParser.json
JIRA - https://issues.cask.co/browse/CDAP-2893
BUILD - http://builds.cask.co/browse/CDAP-DUT2134-2
Custom Transform that parses various log formats (currently only CLF and S3) and extracts information such as URI, IP, browser, device, and time. Part of the Caskalytics project.
=> [CDAP-2893] Log parser transform

cdap-distributions/src/emr/install.sh
This script does everything necessary to install CDAP on an Amazon EMR cluster.
- Setup YUM repository and install CDAP packages
- Install CDAP dependencies
- Create `kafka.log.dir` directory
- Configure CDAP
- Create `hdfs.namespace` HDFS directory
- Start CDAP services
=> CDAP-2913 EMR install script

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java, cdap-common/src/main/java/co/cask/cdap/common/twill/HadoopClassExcluder.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
After https://issues.apache.org/jira/browse/TWILL-117, we can include the classpath common for ApplicationMaster and all runnables and also a classAcceptor to filter the classes to include in the bundler jar for AM and runnables.
Since we can use the jars from the classpath specified by "yarn.application.classpath" for hadoop classes, we can exclude the hadoop classes while building the bundler jar.
=> with application classpath and classAcceptor to exclude hadoop classes

cdap-distributions/src/emr/install.sh
Otherwise, EMR installs fail. This was there to prevent a big, ugly exception from showing up in the logs, but doesn't affect overall functionality.
=> Remove mkdir as HDFS isn't available at bootstrap time

cdap-docs/admin-manual/source/installation/cdap-site.rst
same as https://github.com/caskdata/cdap/pull/3071 but for develop branch
updating cdap-site.xml appendix in docs to match cdap-default.xml:
=> docs fix app.template.* to match cdap-default.xml

cdap-common/src/main/java/co/cask/cdap/common/lang/FilterClassLoader.java, cdap-common/src/test/java/co/cask/cdap/common/lang/FilterClassLoaderTest.java
The FilterClassLoader should try and use its bootstrap classloader
before doing any filtering. This is so that java system classes
and resources are available. For example, the classloader must be
able to get the javax.script engines as resources.
=> CDAP-2941 fix filter classloader's get resource(s)

cdap-ui/app/styles/themes/cdap/tabs.less
* Removes pointer cursor when hovering over active tab
* Removes orange font color when hovering over active tab
=> refines active/hover state styling for slanted tabs

cdap-ui/Gulpfile.js
DagreD3 updated the version of lodash from 2.* to 3.* straight away.  (https://github.com/cpettitt/dagre-d3/commit/e746821ab29e0cab58dc8a9f12a12f475ff2f0bc)
Lodash changed its built files location from dist/lodash.js to just ./lodash.js  (https://github.com/lodash/lodash/wiki/Changelog#v300)
So when we took an update from DagreD3 we didn't update the path of lodash. That is the reason the UI was failing.
TODO: 
Remove epoch.js and protractor completely in a separate PR
=> Fixes bower component (lodash) path from dist/lodash.js to just lodash.js

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInfo.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactMeta.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRange.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
Doing some refactoring to reflect the fact that plugins extend
a set of parent artifacts and are not stand alone objects. Changes
the table schema to support finding the plugins that extend a
given parent artifact.
=> CDAP-2846 artifact plugins extend another artifact

cdap-ui/app/features/dashboard/services/query-helper.js, cdap-ui/app/features/dashboard/templates/dashboard.html
* Removes ui-sref-opts attribute, which was causing reload of the widget dropdown and preventing it from staying in focus
* Adds a FIXME note for addressing input of random strings (Metric) when creating a widget
=> fixes widget dropdown reloading/flickering

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive13ExploreService.java
- Hive13ExploreService.doFetchNextResults wasn't getting the
correct fetchResults method
=> CDAP-2955: NoSuchMethodException when trying to explore Datasets/Stream

cdap-api/src/main/java/co/cask/cdap/api/spark/AbstractSpark.java, cdap-api/src/main/java/co/cask/cdap/api/spark/SparkConfigurer.java, cdap-api/src/main/java/co/cask/cdap/api/spark/SparkContext.java, cdap-api/src/main/java/co/cask/cdap/api/spark/SparkSpecification.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/SparkTwillApplication.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextFactory.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/spark/DefaultSparkConfigurer.java, cdap-proto/src/main/java/co/cask/cdap/proto/codec/SparkSpecificationCodec.java
- Added methods in SparkConfigurer for setting driver and executor resources
- Added methods in SparkContext for overriding executor resources set through SparkConfigurer.
- Use the driver resources setting when launch the Twill container that serves as driver
- Use the executor resources setting when submitting the Spark job.
=> (CDAP-2936) Allow setting Spark driver and executor memory size

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionConsumerResult.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionConsumerState.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionMetadata.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionedFileSet.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionConsumer.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDefinition.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetModule.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDefinition.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetModule.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionConsumerStateTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java
Index partitions on transaction id, to allow consumption of partitions as they are created/committed, along with a simple consumer which holds its state in memory.
https://issues.cask.co/browse/CDAP-2747
http://builds.cask.co/browse/CDAP-DUT2124-21
This is based off the design here:
https://wiki.cask.co/display/CE/Periodically+consuming+partitions+of+a+PartitionedFileSetDataset
The design (API and implementation) for the client side to this functionality (likely a periodically-running workflow) has yet to be finalized.
=> CDAP-2747 - Use IndexedTable for PartitionedFileSet.

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/SqsSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/realtime/source/SqsSourceTest.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/template/etl/realtime/ETLWorkerTest.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/template/etl/realtime/RealtimeCubeSinkTest.java, cdap-ui/templates/ETLRealtime/Sqs.json
JIRA - https://issues.cask.co/browse/CDAP-2915
BUILD - http://builds.cask.co/browse/CDAP-DUT2187-2
Realtime SQS source for ETL. Used in Caskalytics. Tested and works on clusters (with etlrealtimesourcestate disabled).
=> [CDAP-2915] SQS realtime source

cdap-app-fabric/src/main/java/co/cask/cdap/config/DefaultConfigStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/ScheduleStoreTableUtil.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetMetaTableUtil.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java, cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaverTableUtil.java
* Upgrades all tables in system namespace
* Upgrades all user table across all namespace
* Avoids creating redundant empty tables after the upgrade
* Avoids upgrading non-cdap managed tables
JIRA: https://issues.cask.co/browse/CDAP-2962
Build: http://builds.cask.co/browse/CDAP-RBT308
=> Upgrade tool fixes

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerDriver.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceHttpServer.java
The particular bug that was observed was a getDataset() call that
eventually creates an HTable, which runs some static code
blocks that create HBaseConfiguration. HBaseConfiguration will try
and load hbase-default.xml by calling the context classloader's
getResource(), which is the ProgramClassLoader. Thus, the resource
is filtered out and the conf setting required by hbase is not
found and and exception is thrown.
This change will set the context classloader to a combined
classloader that uses the bootstrap as the parent, then uses
the program classloader, and finally the CDAP system classloader.
This means the program classes should always be loaded by the
program classloader instead of the system classloader, but also
serves as a catch all to load any classes that are needed by the …
=> CDAP-2972 use combined classloader to run program code

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunnerTest.java
One of the tests starts a Spark program with output to an existing location. This is a new test that validates that the dataset's inFailure() is called. This test also validates that the Spark program throws an exception. Apparently there is a race condition that sometimes the exception is not captured by the program runner. In that case the test case fails. because it expects that exception.
It always succeeds on my laptop, but sometime fails, or sometimes succeeds in Bamboo.
A quick fix is to remove the assertion of the exception from the test case, and only to assert that the onFailure was called.
=> do not validate success of runProgram()

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowClient.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorkflow.java, cdap-app-fabric/src/test/java/co/cask/cdap/ConditionalWorkflowApp.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/runtime/WorkflowTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/tx/Transactional.java, cdap-proto/src/main/java/co/cask/cdap/proto/RunRecord.java, cdap-proto/src/main/java/co/cask/cdap/proto/WorkflowTokenDetail.java, cdap-proto/src/main/java/co/cask/cdap/proto/WorkflowTokenNodeDetail.java, cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowTokenDetailCodec.java, cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowTokenNodeDetailCodec.java
Added ability to persist WorkflowToken to MDS after every node's execution completes.
The WorkflowToken is stored as a json in a Workflow's RunRecord's properties with the key 'workflowToken'.
Also adds two HTTP endpoints for querying workflow tokens.
Issues addressed:
[CDAP-2713](https://issues.cask.co/browse/CDAP-2713) 
[CDAP-2714](https://issues.cask.co/browse/CDAP-2714)
Build:
https://builds.cask.co/browse/CDAP-DUT2206/
Includes #3128. The changes in this PR are in the last commit.
=> Persist WorkflowToken to MDS

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProcessEntry.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/flow/FlowletProcessEntryTest.java
- Handle @Tick initialDelay by treating it as a delay instead of a
timestamp relative to `System.nanoTime()`
https://issues.cask.co/browse/CDAP-3002
http://builds.cask.co/browse/CDAP-DUT2232
=> CDAP-3002: Tick initialDelay does not work properly

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/SparkTwillRunnable.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillRunnable.java
- We no longer need those fields since we always ship the spark-assembly.jar to the spark containers, which contains everything spark needs.
=> Remove the unnecessary field

cdap-app-fabric/src/main/java/co/cask/cdap/config/DefaultConfigStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/ScheduleStoreTableUtil.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetMetaTableUtil.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java, cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaverTableUtil.java
Did a complete test on cluster: It works.
1. Deployed 3.0.0 cluster through coopr autobuild
2. Deployed Purchase app
3. Sent some events to the stream (which will create usage.registry table)
4. Verified through hbase shell that dataset.instance has the table type for above table as Table.
5. Stopped all services
6. Beamed the fix version branch from the PR. 
7. Ran the upgrade tool 
8. After upgrade verified that the type in dataset.instance is changed to UsageDataset
9. Started all services
10. Ran flow, services, workflow and queries for results.
=> CDAP-2548 : Upgrade usage.registry dataset type from Table to UsageDataset

cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java
- Made CLIConfig.tryConnect also set access token upon successful
connection
https://issues.cask.co/browse/CDAP-2992
http://builds.cask.co/browse/CDAP-DUT2236
=> CDAP-2992: CLI broken for secure CDAP

cdap-ui/app/styles/common.less
Fixes the margin top on all view . The current style prevented user from accessing any part of UI on top of the page.
=> Fixes margin top for the entire view to be consistent (for namespace dropdown)

cdap-api/src/main/java/co/cask/cdap/api/spark/SparkContext.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/NodeValue.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/Value.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ClientSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextConfig.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextFactory.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextProvider.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowToken.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/SparkProgramWorkflowRunner.java, cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowApp.java
Jira: [CDAP-2923](https://issues.cask.co/browse/CDAP-2923)
Build: http://builds.cask.co/browse/CDAP-DUT2240
Note: Currently, workflow token is available in ``beforeSubmit``, ``onFinish``, ``driver`` and ``executor``. However, you can only update it in ``beforeSubmit``, ``onFinish`` and ``driver``
=> [CDAP-2923] Added Support for Workflow Token in Spark programs run through workflows.

cdap-distributions/bin/build_artifact_upload.sh
Port over build_artifact_upload script changes to release 3.0.
This fixes the following issues:
* artifacts erroneously going to snapshot incoming directory on docs
* sync to remote should copy to blah/ not blah (risking creating a file, not adding to directory)
Note: this last thing should be ported back to 2.8 as well.
=> port changes to release_3_0

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/ServiceStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AbstractMonitorHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/DatasetServiceStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MonitorHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTest.java, cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractDistributedMasterServiceManager.java, cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractInMemoryMasterServiceManager.java, cdap-common/src/main/java/co/cask/cdap/common/twill/MasterServiceManager.java, cdap-proto/src/main/java/co/cask/cdap/proto/RestartServiceInstancesStatus.java
Add support for restart for CDAP system services instances. Need to be able to send restart commands to individual instances in System Services for CDAP Master.
Currently, to restart one of the CDAP master services (data-fabric, explore, metrics, etc.), you have to restart them all. It should be possible to just stop/start/restart a specific one.
=> (CDAP-2836) Add support for restart specific CDAP system services instances

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ApplicationClass.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactClasses.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactMeta.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/CloseableClassLoader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/InvalidArtifactException.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/PluginTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/app/InspectionApp.java
Enhance the ArtifactInspector to inspect the artifact for
Application Classes. For now, using the current application
requirement of having the application main class contained
in the artifact manifest.
=> CDAP-2967 inspect artifacts for application classes

cdap-data-fabric/src/test/java/co/cask/cdap/data/hbase/HBaseTestBase.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java, cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data/hbase/HBase96Test.java, cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data/hbase/HBase98Test.java, cdap-hbase-compat-1.0-cdh/src/test/java/co/cask/cdap/data/hbase/HBase10CDHTest.java, cdap-hbase-compat-1.0/src/test/java/co/cask/cdap/data/hbase/HBase10Test.java
- Tune down hconnection threads and regionserver handler count.
- Refactor HBaseTestBase code so that more configurations can be set before starting mini HBase cluster for testing.
=> (CDAP-3016) Tune down number of HBase threads

cdap-data-fabric/src/main/java/co/cask/cdap/data/dataset/SystemDatasetInstantiator.java, cdap-data-fabric/src/main/java/co/cask/cdap/data/dataset/SystemDatasetInstantiatorFactory.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/StaticDatasetFramework.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
Fixing a bug introduced by the fix to CDAP-2564. The previous
change changed DatasetFramework to just use the classloader it
is given instead of trying to unpack dataset jars to create
classloaders. Since the CDAP system does not have access to
user dataset jars in its classpath, it needs to pass a
DatasetClassLoaderProvider to DatasetFramework, which is
responsible for unpacking user dataset jars to create the
classloaders needed to instantiate a dataset.
That refactoring was done for dataset instantiation, but not for
dataset admin instantiation. This fix adds a corresponding
method for instantiating a DatasetAdmin, which must be used when
the CDAP system needs to instantiate a DatasetAdmin for a user
dataset.
=> CDAP-3001 fix classloading for getting user dataset admins

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/BatchFileFilter.java
JIRA - https://issues.cask.co/browse/CDAP-3021
BUILD - http://builds.cask.co/browse/CDAP-DUT2250
Cloudfront names files in a different format than S3 log files. Update BatchFileFilter to read cloudfront filenames.
=> [CDAP 3021] Accept cloudfront file naming convention

cdap-distributions/bin/build_artifact_upload.sh
This has been individually tested against both release/3.0 and release/2.8 CDAP repos & artifacts.
=> back port s3 sync script fixes to 2.8 release

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/BaseETLBatchTest.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/template/etl/realtime/ETLWorkerTest.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/template/etl/realtime/RealtimeCubeSinkTest.java, cdap-examples/FileSetExample/src/test/java/co/cask/cdap/examples/fileset/FileSetWordCountTest.java, cdap-examples/HelloWorld/src/test/java/co/cask/cdap/examples/helloworld/HelloWorldTest.java, cdap-examples/LogAnalysis/src/test/java/co/cask/cdap/examples/loganalysis/LogAnalysisAppTest.java, cdap-examples/Purchase/src/test/java/co/cask/cdap/examples/purchase/PurchaseAppTest.java, cdap-examples/SparkKMeans/src/test/java/co/cask/cdap/examples/sparkkmeans/SparkKMeansAppTest.java, cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java, cdap-examples/UserProfiles/src/test/java/co/cask/cdap/examples/profiles/UserProfilesTest.java, cdap-examples/WebAnalytics/src/test/java/co/cask/cdap/examples/webanalytics/WebAnalyticsTest.java, cdap-examples/WordCount/src/test/java/co/cask/cdap/examples/wordcount/WordCountTest.java, cdap-formats/pom.xml, cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java, cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java, cdap-unit-test/src/main/java/co/cask/cdap/test/TestConfiguration.java, cdap-unit-test/src/test/java/co/cask/cdap/partitioned/MapReducePartitionConsumingTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetUpgradeDisabledTest.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetUpgradeEnabledTest.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestAppWithCube.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/base/TestFrameworkTestSuite.java, cdap-unit-test/src/test/java/net/fake/test/app/TestBundleJarApp.java
It can be used by unit-test classes to alter CDAP configurations easily in unit-test.
- Deprecate the ConfigurableTestBase, since it’s harder to use
- Convert all existing unit-tests to use the TestConfiguration
- Disable explore for tests that doesn’t need explore capability.
- It cuts ~10-15 seconds from unit-tests that doesn't need explore service
=> Introduce a ClassRule, TestConfiguration, that unit-test can use to set CDAP configs

cdap-distributions/src/packer/scripts/cookbook-dir.sh, cdap-distributions/src/packer/scripts/cookbook-setup.sh, cdap-distributions/src/packer/scripts/eclipse-cookbook.sh, cdap-distributions/src/packer/scripts/lxde.sh, cdap-distributions/src/packer/scripts/vbox-guest-additions.sh, cdap-distributions/src/packer/scripts/zero-disk.sh
Bash evaluates && before || so wrap invocations in parentheses.
=> Fix error checking in VM build scripts

cdap-distributions/bin/build_parcel.sh
parcel buildscript needs updated to include the new hbase-compat modules, and drop the 0.94 module.
=> update hbase-compat modules, add 1.0, 1.0-cdh, remove 0.94

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AbstractMonitorHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTest.java, cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractDistributedMasterServiceManager.java
Add different HTTP status for service disabled/not ready and illegal instance id to be restarted.
=> (CDAP-3028) Improve the system service restart endpoints to handle invalid instance id and serbive not available/ready

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreServiceUtilsTest.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
1) editing yarn_application_classpath to include container working dir jars before job.jar for map-reduce job containers launched by explore queries. and changing appropriate parameters to use YARN_APP_CLASSPATH as classpath before job.jar
2) excluding hive-exec-*.jar from the container working directory
JIRA : https://issues.cask.co/browse/CDAP-2991
=> fixing explore classpath issues 

cdap-common/src/main/java/co/cask/cdap/common/namespace/DefaultNamespacedLocationFactory.java, cdap-common/src/test/java/co/cask/cdap/common/namespace/DefaultNamespacedLocationFactoryTest.java
The method to get a subdirectory of a namespace location was
returning the namespace location instead of the subdirectory.
This is really bad if somebody decides to delete that
'subdirectory', then ends up deleting the entire namespace.
=> CDAP-3058 NamespacedLocationFactory was not appending correctly

cdap-ui/app/features/flows/controllers/tabs/runs/tabs/status-ctrl.js, cdap-ui/app/features/flows/service/flow-graph-data.js
Use case: When there are 2 namespaces with identical programs, run a flow and it will generate metrics. When you switch to a different namespace and go to the identical flow, the metrics from the other namespace will show up. It disappears on refresh.
Solution: Adding a reset function on FlowDiagramData service which is called on $scope $destroy event of the status-ctrl.
=> reset flowlet metrics data on scope destroy

cdap-api/src/main/java/co/cask/cdap/api/spark/SparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ClientSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionSparkContext.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkAppUsingFileSet.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunnerTest.java, cdap-app-fabric/src/test/scala/co/cask/cdap/internal/app/runtime/spark/ScalaFileCountProgram.scala
- Add new API in SparkContext to take take arguments while reading and writing dataset.
- Unit test for the above
- Fix : Earlier testSparkWithTimePartitionedFileSet was calling testSparkWithPartitionedFileSet() rather than testSparkWithTimePartitionedFileSet()
Build: http://builds.cask.co/browse/CDAP-RBT319-1
=> CDAP-2986: spark takes dataset arguments when reading writing

cdap-ui/app/directives/fileselect/fileselect.less, cdap-ui/app/features/adapters/controllers/create-new-ctrl.js, cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js, cdap-ui/app/features/adapters/controllers/list-ctrl.js, cdap-ui/app/features/adapters/routes.js, cdap-ui/app/features/adapters/templates/list.html, cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/apps/controllers/list-ctrl.js, cdap-ui/app/features/apps/templates/list.html, cdap-ui/app/features/overview/controllers/apps-section-ctrl.js, cdap-ui/app/features/overview/templates/data-apps.html, cdap-ui/app/services/plumber/my-plumb-service.js, cdap-ui/app/styles/themes/cdap/buttons.less, cdap-ui/app/styles/themes/cdap/mixins.less
- Unifies Adapters with Apps
- Modifies "All Apps" to list All apps + All Published Adapters
- Modifies "Add App" to show dropdown to Add an app, Add ETL Batch app & Add ETL Realtime app.
- Adds a new white dropdown to be added to overview 
- Modifies overview listings to have both apps + adapters.
- Modifies apps list view to have both apps + adapters
- Passes adapter type or name during adapter creation view or draft edit view.
- Passes adapter type during new adapter creation
- Passes adapter name during adapter edit view.
=> Feature/ui adapter prototype integration 4.1

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/instance/DatasetInstanceManager.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java
- usage.registry table is created when something runs on a cluster and a usage record needs to be written. On a fresh cluster the usage.registry will not exists and will not be found. No upgrade is necessary in this case.
=> Don't try to upgrade usage.registy on fresh cluster

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AbstractMonitorHandler.java
Following basic HTTP status rule of thumb: 
5XX code is our fault, and 4XX code is caller fault.
=> Add new HTTP status for system service instances restart to separate between 503 Service unavailable and 403 Service is disabled.

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DatasetDefinitionLoader.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/EmbedsTableTwiceDataset.java
If a dataset embeds Table, and also embeds another dataset from a different module that itself embeds a Table, DatasetDefinitionLoader will try to register the Table's module twice (once directly for the embedded Table, once indirectly when adding the dependencies of the other dataset). The second time it will fail with a conflict because the type is already defined. This happens not only for table, but for any dataset that is embedded both directly and transitively through a different module (note this does not happen for IndexedTable, because it is in the same module as Table).
Fix is to ignore the TypeConflictException that happens in this case.
=> [CDAP-3037] handle type conflict for duplicate dependencies of a dataset type

cdap-docs/_common/_themes/cdap/static/doctools.js, cdap-docs/_common/common-build.sh, cdap-docs/build.sh
This attempts to fix the documentation build by improving the determination of the parent branch.
However, the real problem with the documentation build is that there is no 3.1-compatible branch in the CDAP-Apps repository.(This has been addressed directly in the CDAP-Apps repo.)
It moves an echo statement from a method into the place where the method is called, cleaning up the method.
This also fixes https://issues.cask.co/browse/CDAP-3072, a documentation Javascript error.
=> Fix documentation build

BUILD.rst, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/AbstractCloseableIterator.java, cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/CloseableIterator.java, cdap-docs/_common/common-build.sh
Fixes minor issues with two sets of Javadocs, and updates the build script and BUILD.rst with increased memory requirements for building the Javadocs.
=> CDAP-3043: Javadoc Building and Formatting

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceWithPartitionedTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/file/FileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/EmptyInputFormat.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java
This changes partitioned file sets to use an EmptyInputFormat if the input filter does not match anything. (the actual input format, which most likely extends FileInputFormat, would throw an exception if no input paths are configured). This does not change the behavior if no input filter was given - that will still throw an exception, unless the input was specified directly using FileSetArguments, bypassing the partition filter (not a common use case, but supported). 
Similar for TimePartitionedFileSet: If an input time range was specified, and it matches no partitions, use EmptyInputFormat. If no time range was given, fall back to PartitionedFileSet's method of input selection (using partition filters).
Also changes the behavior if not output path is given for a file set. It used to …
=> [CDAP 2945] PFS should not fail if the input partition filter matches no partitions

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/BufferingTable.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTable.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/BufferingTableTest.java, cdap-examples/UserProfiles/src/main/java/co/cask/cdap/examples/profiles/UserProfileService.java
Fixes a bug in BufferingTable where multiget calls for HBase were
only returning persisted data and could not see changes made in the
same transaction. In order to fix this, BufferingTable now has a
getPersisted(List<Get> gets) method for subclasses to override.
BufferingTable will then apply buffered changes on top of the
persisted changes.
Also adding a service endpoint to the UserProfiles example app to
demonstrate usage of multi-get on a Table.
=> CDAP-3042 fix bug where buffered operations weren't seen in multiget

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapperWrapper.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/ReducerWrapper.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetRecordReader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetRecordWriter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/inmemory/InMemoryMapReduceContextBuilder.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
- The sleep was there for waiting metrics be published. However, on
stopping the metrics collection service, metrics are being force pushed,
hence the sleep is unnecessary
=> Remove unnecessary sleep for 2 seconds in various places in MR.

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/BatchPartitionConsumer.java, cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst, cdap-unit-test/src/test/java/co/cask/cdap/partitioned/AppWithMapReduceConsumingPartitions.java
Documentation for incrementally consuming partitions of a partitioned file set.
Additionally, minor updates to existing PartitionedFileSet documentation.
http://builds.cask.co/browse/CDAP-RBT341-1
https://issues.cask.co/browse/CDAP-2993
Two comments from previous PR (accidentally opened against develop branch):
https://github.com/caskdata/cdap/pull/3212#discussion_r34857840
https://github.com/caskdata/cdap/pull/3212#discussion_r34857891
=> Documentation for incrementally consuming partitions of a partitioned file set.

cdap-ui/app/directives/plumb/my-plumb-ctrl.js, cdap-ui/app/services/plumber/my-plumb-service.js
Adds the ability to store nodes their location when dragged by user. So a refresh on the same page or a draft opened again will have nodes in the same place as it is left.
=> Stores the position of the nodes once they have been dragged

cdap-docs/admin-manual/source/installation/cdap-site.rst
Removed all trailing periods from descriptions to make them consistent.
=> Correct syntax for twill.jvm.gc.opts example. 

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/RemoteDatasetOpExecutor.java
Changing the dataset create endpoint to include the cause of any
IOException seen while creating the dataset. If there was some
exception instantiating the dataset admin, a generic message will
be included in the response, but the cause will not be shown since
that is a CDAP error and not an error in a dataset admin.
=> CDAP-3031 surface exception causes when datasets cant be created

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java, cdap-common/src/main/java/co/cask/cdap/internal/app/store/RunRecordMeta.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java, cdap-proto/src/main/java/co/cask/cdap/proto/RunRecord.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/AppMetadataStore.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/ProgramStore.java
Since twillrunid is internal to CDAP it should not be exposed to RunRecord proto which is wired to client:
-) Removed twillRunId field from proto RunRecord
-) Added RunRecordMeta class that extends RunRecord with twillRunId field to work with app meta store.
-) Updated handler and test classes to reflect the changes
=> CDAP-2454 Remove twillrunid from proto RunRecord so not send back to client

cdap-docs/developers-manual/source/data-exploration/custom-datasets.rst, cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java, cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreServiceTestsSuite.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreStructuredRecordTestRun.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/EmailTableDefinition.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/StructuredWritableDefinition.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/datasets/TableWrapperDefinition.java
There was a bug where Table and ObjectMappedTable are
explorable because they are ```RecordScannable<StructureRecord>```,
but custom datasets were not explorable in the same way. So
somebody could create a custom dataset that uses an explorable
table, but would not be able to use that to make their custom
dataset explorable.
This fix will create a Hive table for custom datasets that are
```RecordScannable<StructuredRecord>```, assuming the schema dataset
property is set. If the schema property is not set, enabling
exploration will fail with a message that the schema property
is required.
=> CDAP-2530 making RecordScannable<StructuredRecord> explorable

cdap-examples/LogAnalysis/pom.xml, cdap-examples/LogAnalysis/src/main/java/co/cask/cdap/examples/loganalysis/LogAnalysisApp.java, cdap-examples/LogAnalysis/src/main/scala/co/cask/cdap/examples/loganalysis/ResponseCounterProgram.scala, cdap-examples/LogAnalysis/src/test/java/co/cask/cdap/examples/loganalysis/LogAnalysisAppTest.java
- Spark program now writes the TPFS with partition key as the logicalStartTime by passing it as arguments while calling writeToDataset rather than requiring the user user to provide the partition time as a dataset argument. https://github.com/caskdata/cdap/pull/3215
- Exposes to handlers: One to get a list of all partitions and another to get contents of a partition as a string.
- Update the unit test for the same.
Build: http://builds.cask.co/browse/CDAP-RBT333-1
=> Add support to access tpfs through service in LogAnalysisApp

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
Since the ZK dependency in the cdap was turned into provided scope
Tested in standalone and cluster.
Build : http://builds.cask.co/browse/CDAP-RBT352-1
=> Adding ZK dependency as it is required by KafkaSource; 

cdap-ui/app/directives/plumb/my-plumb-ctrl.js
Fixes redrawing DAG when window resized.
=> [CDAP-3086] Fixes browser resize to re-draw DAG in adapter create view

cdap-common/bin/service
Quoting OPTS only allows a single Java property to be set. This is
fine with the default configuration of CDAP, but fails quite
spectacularly if the user specifies their own variables in the
cdap-env.sh file:
export OPTS="${OPTS} -Dhdp.version=2.2.4.2-2"
Our scripts interpret OPTS as a single parameter, and pass it to
the "java" binary as such, causing Java to not recognise this now
combined parameter. Removing the quotes allows them to be interpreted
correctly by Bash, and passed correctly to Java.
=> Do not quote OPTS

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/Properties.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/SqsSource.java, cdap-ui/templates/ETLBatch/FileBatchSource.json, cdap-ui/templates/ETLRealtime/AmazonSQS.json
JIRA - https://issues.cask.co/browse/CDAP-3092
BUILD - http://builds.cask.co/browse/CDAP-DUT2333-1
Allows each mapper in FileBatchSource to read in multiple files. Previous behavior would generate at least one mapper per file. This solves the many small files problem, in which a large number of mappers would cause slow runtime and eventually OOM issues.
=> [CDAP-3092] Mapper reads in multiple files

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AbstractInMemoryProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractProgramController.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/run/StreamWriterTestRun.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/NoOpWorkerApp.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
When the run method of the worker completes. This bug is relevant only for inmemory mode and thus no change is required for distributed mode logic
JIRA : https://issues.cask.co/browse/CDAP-3039
Build : http://builds.cask.co/browse/CDAP-RBT347-1
=> CDAP-3039 Fix to make Worker program stop

cdap-ui/app/directives/plumb/my-plumb-factory.js, cdap-ui/app/directives/plumb/my-plumb.html
- Fixes arrows to be attached to the tip of the endpoint in adapter DAG
- Hides the close button on a plugin once it is created
=> Fixes arrow placement attached to the end point

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/LogParserTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/transform/LogParserTransformTest.java
JIRA - https://issues.cask.co/browse/CDAP-3105
BUILD - http://builds.cask.co/browse/CDAP-DUT2353-2
LogParserTransform needs to emit HTTP status code for download information use in Caskalytics.
=> [CDAP 3105] Emit HTTP status code

cdap-ui/app/features/admin/templates/namespace/apps.html, cdap-ui/app/features/overview/overview.less, cdap-ui/app/features/overview/templates/data-apps.html
*  Adds correct dropdown menu text + icons to no apps template (dev start + admin)
*  Removes box shadow in dropdown menu open state
*  Adds consistent padding to buttons in data apps template (dev start)
=> updates dropdown options for no app template

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java, cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreTableTestRun.java
Fixes a bug where a request to enable exploration on a Table
without a schema would error. This is required because a call to
enable exploration is made on every single dataset when it is
created or when its properties change. All this dataset specific
logic in explore should be moved out, but that is outside the
scope of this fix and has its own open issue.
=> CDAP-3104 enabling explore on a Table without schema should no-op

cdap-common/src/main/resources/cdap-default.xml
The security warning removal is in the second commit. The first commit is white-space only.
=> CDAP-2765 Remove CLI security warning

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/DynamicMapReduceContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ClientSparkContext.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java, cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorker.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithMapReduceUsingRuntimeDatasets.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkAppUsingObjectStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunnerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunnerTest.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetContext.java, cdap-notifications/src/main/java/co/cask/cdap/notifications/service/BasicNotificationContext.java
This affects: workers, mapreduce, spark (driver side). 
- adds a metrics context to the DynamicDatasetContext
- changes to program contexts to pass in the metrics context
- additions to some test cases to validate that the metrics are emitted with correct context
- new test case WorkerProgramRunnerTest - we did not have a test case for workers before
=> [CDAP-2922] adds metrics to datasets obtained through DynamicDatasetContext

cdap-common/src/main/resources/cdap-default.xml
This is the same as #3353 but against `release/3.1`
=> CDAP-2765 Remove CLI security warnings

cdap-ui/app/directives/tooltip-toggle/tooltip-toggle.js, cdap-ui/app/features/adapters/etlapps.less, cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
add tooltip if input schema name is too long
modify modals columns for source, sink, transforms
=> [CDAP-3098] add tooltip to input schema

cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/read/DistributedLogReader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/read/FileLogReader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/read/KafkaLogReader.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointManager.java, cdap-watchdog/src/main/java/co/cask/cdap/logging/write/FileMetaDataManager.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestDistributedLogReader.java, cdap-watchdog/src/test/java/co/cask/cdap/logging/read/FileLogReaderTest.java
This contains the following fixes -
1. Simplify log file range calculation, also fixes a bug in rage calculation.
2. Handle a case where no logs were returned when logs in Kafka were expired for the latest run.
It would be easier to review commit by commit.
JIRA - https://issues.cask.co/browse/CDAP-2935
=> Misc log fixes

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueConstants.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueDatasetModule.java, cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
system.queue is a system dataset, but it exists in each namespace
once a flow has been started in the namespace. It should not be
visible via the get datasets rest call. This is a short term
fix, with the longer term fix to have support for system datasets
in namespaces other than the system namespace.
=> CDAP-2768 filter out system.queue from list of datasets

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TestSource.java
Logic should go to default mode if the type is not set to stream or table
Build : http://builds.cask.co/browse/CDAP-RBT376-1
JIRA : https://issues.cask.co/browse/CDAP-2498
=> CDAP-2498: Test Source has three modes - stream, table, default. 

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
title says it all.
Build: http://builds.cask.co/browse/CDAP-RBT380-1
=> [cdap 3132] fix race condition when test gets run record before (async) start/stop has completed

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MonitorHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTest.java
Follow up on endpoint for system service restart instances comments after demo.
Adding concept of "restart" resource to the /system/services/{service-name} endpoint.
The restart path represent a request to restart instances on the system services.
So to restart all instances of a system service need to send request to:
PUT /system/services/{service-name}/restart
and to restart particular instance id via:
PUT /system/services/{service-name}/restart/{instance-id}
Modify the GET endpoint for latest restart status by adding concept of latest-restart resource:
GET /system/services/{service-name}/latest-restart
=> Update the system services restart endpoints to be more RESTful

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
This fixes the VM build for release.
- Using a known-good version of HDP to get Flume Agent
- Set `sdk_version` default to `3.1.0`
- Set explicit list of Eclipse plugins to install
=> Explicitly set list of Eclipse plugins to install and set HDP 2.1

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/TimePartitionedFileSetDatasetAvroSource.java, cdap-docs/application-templates/source/etl/templates/sources/real-time/amazonsqs.rst, cdap-docs/application-templates/source/etl/templates/sources/real-time/index.rst, cdap-docs/developers-manual/source/building-blocks/workflows.rst, cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/data-cleansing.rst, cdap-docs/examples-manual/source/examples/index.rst, cdap-docs/examples-manual/source/examples/log-analysis.rst, cdap-docs/examples-manual/source/examples/wikipedia-data-pipeline.rst, cdap-docs/examples-manual/source/examples/word-count.rst
and fixes check style error in documentation strings.
Running Doc Build: http://builds.cask.co/browse/CDAP-DDBD540-1/log
Results staged at: [Examples](http://docs-staging.cask.co/cdap/3.1.0-SNAPSHOT-feature-r3.1-fix_broken_doc_build/en/examples-manual/examples/index.html)
Passes checkstyle (locally).
=> Fixes broken doc build 

cdap-ui/app/features/adapters/services/adapter-error-factory.js, cdap-ui/app/services/plumber/my-plumb-service.js
- When importing json in UI the user might construct the json by hand and they may add a property that is not in the backend. In that case the UI should not fail and should skip in sending that property to the backend.
- Minor js error to fix when we check if a property is required when it is not from the backend (in the malformed json being imported)
=> Fixes json error validation to skip properties that are added in imported json & not from backend

cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java, cdap-docs/developers-manual/source/building-blocks/datasets/index.rst, cdap-docs/developers-manual/source/building-blocks/datasets/system-custom.rst
Fix for https://issues.cask.co/browse/CDAP-3084
Corrects usage to show that TTL is (in these cases) specified in seconds, not milliseconds.
Related issue: https://issues.cask.co/browse/CDAP-2878
Passes local checkstyle.
=> Dataset TTL correction

cdap-docs/deploy.sh
This change allows us to remove 'cdap' from the bamboo global variable for staging and docs paths and make the paths generic (using $PROJECT which are already deriving from pom file in this script).
Note: This change will also be backported to release 3.1, 3.0 and 2.8
This CANNOT be merged until we disable all three docs build plans temporarily, backport and merge PRs for all four branches, and modify the two corresponding bamboo global variables.
=> make docs target paths project generic

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/resources/cdap-default.xml
Some of programs like Spark, MR, and workflow may die quickly due to memory error so we want
to make sure the runs status updated quickly.
=> CDAP-2341 Shorten the cleanup thread for invalid records to make sure store quickly updated.

cdap-docs/examples-manual/build.sh, cdap-docs/examples-manual/source/examples/spark-page-rank.rst, cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java
The SparkPageRankApp is being used in the workflow where the workflow driver need to share memory with Spark runner.
Need to add more resources to SparkPageRankSpecification to make sure it runs otherwise the container will randomly throw out of memory that restart the workflow app container.
=> Increase resources for Page Rank sample app to be successful in workflow

cdap-api/src/main/java/co/cask/cdap/api/flow/flowlet/AbstractFlowlet.java
JIRA : https://issues.cask.co/browse/CDAP-3175
Build : http://builds.cask.co/browse/CDAP-RBT397-1
=> Default AbstractFlowlet constructor should not be deprecated

cdap-ui/templates/common/Database.json
Also removing descriptions since the descriptions from the backend
should be used.
=> CDAP-2735 shouldn't have removed table name since the sink uses it

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java, cdap-examples/WikipediaPipeline/src/test/java/co/cask/cdap/examples/wikipedia/WikipediaPipelineAppTest.java
JIRA: https://issues.cask.co/browse/CDAP-3000
=> CDAP-3000 Persisting the WorkflowToken after the execution of the fork.

cdap-ui/app/directives/plumb/my-plumb-ctrl.js, cdap-ui/app/directives/plumb/my-plumb-factory.js, cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js, cdap-ui/app/services/plumber/my-plumb-service.js
- Add nodes in any random order.
- Form connections with/without source and sink.
- Re-order/change connections in anyway.
The above conditions should all be supported in UI and final config formed should be correct. There should be no restriction in the order in which we add nodes nor the order in which we make connections. The final connection should be the way we represent in UI.
=> Fixes DAG traversal to construct config based on connections in random order

cdap-docs/developers-manual/source/building-blocks/streams.rst, cdap-docs/reference-manual/source/http-restful-api/stream.rst
Fix for https://issues.cask.co/browse/CDAP-3084. Adds "seconds" to TTL references.
Other repos (cdap-ingest) have been updated separately and will automatically be included whenever the documentation is built.
=> Adding specifying in seconds to TTL references.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextProvider.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapperWrapper.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/ReducerWrapper.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetInputFormat.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetOutputFormat.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetRecordReader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/DataSetRecordWriter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceContextBuilder.java
For very short running MapReduce jobs, the logs were not collected. The issue was that the KakfaLogAppender was not getting closed and thus the messages were not getting flushed. PR makes sure that LogAppenderInititalizer is closed in MapperWrapper, ReducerWrapper and in DatasetInputFormat, DatasetOutputFormat (by closing MapReduceContextProvider). Also had to package logback.xml when building the MapReduce Job JAR so that messages are formatted in the expected format.
JIRA : https://issues.cask.co/browse/CDAP-2376
Build : http://builds.cask.co/browse/CDAP-RBT388-1
=> CDAP-2376: Make sure Mapper/Reducer Logs are flushed 

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/template/etl/batch/ETLMapReduce.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/ETLTemplate.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/PluginID.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/template/etl/common/StageMetrics.java, cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/template/etl/common/TransformExecutorTest.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/template/etl/realtime/ETLWorker.java, cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/template/etl/realtime/TrackedRealtimeSink.java
Adding the stage number to the metrics context so that two filters
in the same pipeline will emit different metrics.
=> CDAP-3187 metrics should be unique even if name is equal

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLMapReduceTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java, cdap-ui/templates/ETLBatch/FileBatchSource.json
this makes is consistent with all the other plugins. batch and
source are both redundant information.
=> CDAP-3223 filebatchsource should just be named file

cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamWriter.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/apps/AppWritingtoStream.java, cdap-gateway/src/test/java/co/cask/cdap/gateway/run/StreamWriterTestRun.java
prefix headers with the stream name so that they are interpreted
as stream headers instead of request headers.
=> CDAP-3232 fix stream writer to persist headers

cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java
For some reason, the url that StreamClient's async send event method hits was modified in this recent commit:
https://github.com/caskdata/cdap/commit/318bf1154511f4ba14d46bb090dad39e43312a42#diff-f61d08dd39129279edde2e03ec7f9dcfR444
There is a test case for this method, but it is difficult to assert that the async endpoint was hit, because even for stream events of size 1-2MB, it's nearly effectively synchronous.
http://builds.cask.co/browse/CDAP-RBT408-2
=> Fix the url for StreamClient#asyncSendEvent

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TableSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetAvroSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/TimePartitionedFileSetDatasetParquetSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/RecordPutTransformer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/StructuredToAvroTransformer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/sink/RealtimeTableSink.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/StructuredRecordToGenericRecordTransform.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/common/RecordPutTransformerTest.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/transform/StructuredtoAvroTest.java
Takes in an output schema and filters out fields that are not present in it.
This allows the sink to drop fields if the schema string that it gets has fields removed compared to the previous stage. Before this change, we were converting the structured record we get directly to Put or AvroRecord without taking into consideration the output schema that was provided (output schema was used only for explore). 
Build : http://builds.cask.co/browse/CDAP-RBT413-1
JIRA :
=> StructuredRecordToPutTransformer, StructuredRecordToAvro Transformer

cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/integrations/source/partners/cloudera/configuring.rst, cdap-docs/reference-manual/source/release-notes.rst
Added a link to the Javadocs in the release notes for 3.1.0 under "deprecated APIs".
Staged at: 
- [Cloudera: Configuring and Installing](http://docs-staging.cask.co/staging/cdap/3.1.0-feature-r3.1_CDH/en/integrations/partners/cloudera/configuring.html#upgrading-an-existing-version)
- [Upgrading An Existing Version](http://docs-staging.cask.co/staging/cdap/3.1.0-feature-r3.1_CDH/en/admin-manual/installation/installation.html#upgrading-an-existing-version)
Building...
=> CDH upgrade instructions

cdap-docs/reference-manual/source/faq.rst
Updates the supported versions to match the versions in the installation instructions.
"|version|" in the code is replaced with the CDAP version, "3.1.0".
Staged at: [FAQ: Hadoop](http://docs-staging.cask.co/staging/cdap/3.1.0-feature-r3.1_fix_faq/en/reference-manual/faq.html#hadoop) 
Built.
=> Correct supported versions in FAQ.

cdap-ui/app/features/flows/templates/tabs/runs/streams/detail.html, cdap-ui/app/features/streams/templates/tabs/explore.html, cdap-ui/app/services/streams/my-streams-service.js
- Ability to copy paste multiple lines (events) when sending events to a stream
- User can press shift + enter to go to a newline
=> ability to add multiple events when sending events to streams

cdap-docs/_common/common-build.sh, cdap-docs/build.sh, cdap-docs/developers-manual/build.sh
This fixes the current build, which is broken as two "guarded" files have triggered warnings and failure.
At the same time, fixes an error in the build script which was causing warning messages not to be repeated correctly.
It removes the JSON generation code (the "json-versions.js", as this has been moved out of the documentation build and over to the doc site building.)
Successful build: http://builds.cask.co/browse/CDAP-DDBD548-3/log
=> Fix broken build

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
Fix the flaky test case.
We give command to stop the Workflow and then call the current endpoint, which should return 404 when workflow is not running. However if the Workflow is not completely stopped, then the current endpoint may return 500. 
Added wait in the test case till the Workflow stops completely and then call current endpoint.
=> Wait till the workflow stop before calling the current endpoint.

cdap-ui/app/features/streams/templates/tabs/status.html
This is now consistent with the datasets page, which shows 0b (as opposed to a dash), when there isn't a non-zero metric value for that metric:
https://github.com/caskdata/cdap/blob/feature-ui/stream-page-show-0/cdap-ui/app/features/datasets/templates/tabs/status.html#L17
Before:
Now:
=> Show 0 instead of a dash, when there are 0 stream events

cdap-api/src/main/java/co/cask/cdap/api/flow/FlowSpecification.java, cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowSpecification.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/DefaultFlowConfigurer.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
The code was using `UserErrors.INVALID_STREAM_NAME`, where it should've been using
`UserErrors.INVALID_STREAM_NULL`.
Also, some places, it was using `UserErrors.INVALID_FLOWLET_NAME`, but didn't specify the string of the requested flowlet name, so the error message was getting logged/outputted with a `%s` in it:
`java.lang.IllegalArgumentException: Your FlowSpecification attempts to connect from an invalid Flowlet; "%s" does not exist`
http://builds.cask.co/browse/CDAP-DUT2478-1
=> Improved flowlet error messages.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
This is already a limitation of the plugin system, but it was not
being enforced by the artifact framework. We want to keep things
simple so that an artifact can extend another artifact, but only
to one level. This makes it simpler for our framework, but also
prevents users from creating complicated dependency trees that
are hard for them to manage as well.
=> CDAP-3319 make sure artifacts cant have grandparents

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java, cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java, cdap-proto/src/main/java/co/cask/cdap/proto/artifact/CreateAppRequest.java
Modifies the current PUT /apps/<appid> api so that requests with
a json content type are interpreted as a request to create an app
based on an artifact that already exists.
=> CDAP-3224 add api for creating an app from an artifact

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java
Use case is that the system services need to be checked for `OK` status from subclass (cdap-integration-test repo, for instance), and this functionality is already implemented in here.
=> make IntegrationTestBase#checkSystemServices private --> protected

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
Make changes so that when the framework is inspecting an artifact
for plugins it has access to spark packages in case the artifact
contains spark programs. The classloader is only used when
inspecting artifacts and is closed right after inspection finishes.
=> CDAP-3343 make sure plugin inspector has spark access

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginClassDeserializer.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/SystemArtifactConfig.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/SystemArtifactLoader.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/StandaloneAppFabricServer.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRangeTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/SystemArtifactConfigTest.java, cdap-common/src/main/java/co/cask/cdap/common/ArtifactRangeNotFoundException.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/resources/cdap-default.xml, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java, cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactRange.java, cdap-standalone/src/main/resources/cdap-site.xml
Adding a method to ArtifactRepository to scan a directory for
system artifacts to add. This will be done when AppFabricServer
starts up, and can also be called on command through a RESTful
call in case system artifacts need to be added without restarting
AppFabric.
=> CDAP-2780 add a way to scan a directory for system artifacts

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/StructuredRecordStringConverter.java, cdap-app-templates/cdap-etl/pom.xml, cdap-watchdog/pom.xml, pom.xml
- Replace the unnecessary usage of fastutil in etl-lib
- Do proper exclusion and dependency management in etl-lib
- Fix duplicated dependency in cdap-watchdog
Built standalone using command in BUILD.rst. No out of memory issue.
=> Cleaning up dependencies. Specifically

cdap-distributions/bin/build_artifact_upload.sh
turns off hostkey checking on the initial ssh attempt.  This needs to be ported to release branches as well.
=> turn off host key check on initial ssh

cdap-docs/_common/_themes/cdap/layout.html
Staged at: [CDAP docs](http://docs-staging.cask.co/staging/cdap/3.2.0-SNAPSHOT-feature-3.2_amazon_sqs_logging/en/index.html)
=> Add link to SQS logging to documentation template

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
Move the check for Program ID for program type and run id early to avoid excessive logging for invalid run records with wrong program type for the run records.
Previously for each program type we have 2 checks, one at the beginning to filter run records with RUNNING status and actually does not have container running for that program type, and then later check if the run record id is actually belong to that program type.
=> [CDAP-3374] Warning messages indicating that the Runrecords with status running

cdap-docs/admin-manual/source/installation/installation.rst
A check was made in the documentation for other cases of this error, and this was the only instance found.
Fixes https://issues.cask.co/browse/CDAP-3404.
=> Correct the name of the property used to enable CDAP Explore service.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/LocalizeResource.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkSubmitter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/DistributedSparkSubmitter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/ExecutionFuture.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/LocalSparkSubmitter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SettableExecutionFuture.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkContextConfig.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunner.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkSubmitter.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/metrics/SparkMetricsSink.java
- A new interface, SparkSubmitter, is created for abstracting out submission
- Provide two implementations, Local and Distributed SparkSubmitter
- Currently they are implemented the same way
- Will diverge when using yarn-cluster mode
=> (CDAP-3008) Refactor the way of how to submit Spark program

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java
Without this fix, Explore was using Hive14ExploreService for CDH 5.[2,3], which uses Hive 0.13, thus causing NoSuchMethodErrors due to incompatibilities.
Jira: [CDAP-3408](https://issues.cask.co/browse/CDAP-3408)
Tested ran explore integration test on a cluster with CDH5.3. CDH 5.2 test pending.
=> [CDAP-3408] Fixed Hive/Explore version detection logic for CDH 5.[2,3].

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ArtifactClientTestRun.java
Use the Bundle-Version from the jar manifest as the artifact
version if a version is not explicitly given. Otherwise, use
whatever is explicitly given.
Also now that http-netty version has been updated, simplifying
add artifact endpoint by letting the exception handler handle
exceptions rather than handling them in the method.
=> CDAP-3310 pick up artifact version from manifest if not specified

cdap-docs/reference-manual/source/http-restful-api/stream.rst
Fixes [CDAP-1914](https://issues.cask.co/browse/CDAP-1914).
Staged at: [Getting and Setting Stream Properties](http://docs-staging.cask.co/staging/cdap/3.2.0-SNAPSHOT-feature-3.2_1914_Stream_API_docs/en/reference-manual/http-restful-api/stream.html#getting-and-setting-stream-properties)
=> Add retrieving of stream properties to RESTful API.

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/kafka/KafkaSimpleApiConsumer.java, cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/KafkaSource.java, cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java, cdap-common/src/main/java/co/cask/cdap/common/guice/ZKClientModule.java, cdap-common/src/main/java/co/cask/cdap/common/resource/ResourceBalancerService.java, cdap-docs/admin-manual/source/installation/installation.rst, cdap-docs/admin-manual/source/installation/quick-start.rst, cdap-docs/admin-manual/source/installation/security.rst, cdap-docs/application-templates/source/etl/templates/sources/real-time/kafka.rst, cdap-docs/integrations/source/partners/cloudera/configuring.rst, cdap-docs/introduction/source/index.rst, cdap-docs/reference-manual/source/faq.rst, cdap-docs/reference-manual/source/licenses/index.rst, cdap-docs/reference-manual/source/release-notes.rst, cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterMain.java, cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TransactionServiceTwillRunnable.java, cdap-security/src/main/java/co/cask/cdap/security/auth/DistributedKeyManager.java, cdap-ui/templates/ETLRealtime/Kafka.json, cdap-watchdog/src/main/java/co/cask/cdap/logging/run/LogSaverTwillRunnable.java
In most cases, it should be spelt "ZooKeeper". This corrects it in both the documentation and the application template. It adds Apache ZooKeeper as trademark of the Apache Foundation.
Fixes https://issues.cask.co/browse/CDAP-3375
=> Correct the spelling of "ZooKeeper".

cdap-master/pom.xml
https://issues.cask.co/browse/CDAP-3427
Built cdap-master and verified that the expected classes are in the jar.
=> CDAP-3427: Fix cdap-master packaging

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/SystemArtifactConfig.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ArtifactClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java
Through the RESTful API, explicit plugins are given through a
header. For system artifacts, the list of plugins can be placed
in a json config file similar to how it is done for
ApplicationTemplate now.
=> CDAP-3272 add ability to explicitly specify artifact classes

cdap-docs/admin-manual/source/installation/installation.rst
Fix for https://issues.cask.co/browse/CDAP-3403
Adds to the description of the upgrade tool an example output (created with a parsed literal block so that it will use the current CDAP version string) and explains use of the ``--force`` option.
Building at : [Installation#upgrading-an-existing-version](http://docs-staging.cask.co/staging/cdap/3.2.0-SNAPSHOT-feature-3.2_3403_Installation/en/admin-manual/installation/installation.html#upgrading-an-existing-version)
=> Upgrade tool output example and --force option.

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/AbstractSchedulerService.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
- Uses rescheduleJob() from Scheduler to update schedules
- Earlier approach of deleting the schedule and creating new one was not safe for concurrency. For example, thread A calls updateSchedule() and deletes the schedule() and before new one is added thread B calls checkStatus() or some other function which will fail to find the trigger even though the key is valid and exists.
- The rescheduleJob() function perform the reschedule synchronously which guarantees that while the schedule is being updated all other threads have to wait and hence will not lead to any concurrent access issues.
- Added a unit tests in SchedulerService to test updateSchedule.
Issue: https://issues.cask.co/browse/CDAP-1618
Build: http://builds.cask.co/browse/CDAP-DUT2449-1
=> CDAP-1618: Do schedule updates in proper way

cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java, cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java, cdap-client/src/main/java/co/cask/cdap/client/exception/DisconnectedException.java
https://issues.cask.co/browse/CDAP-3138
http://builds.cask.co/browse/CDAP-DUT2496
With this change, connection refused messages are nicer.
Without specifying -u:
```
CDAP instance at 'http://myhost:10000/default' could not be reached: Connection refused
Specify the CDAP instance URI with the -u command line argument.
```
With specifying -u:
```
CDAP instance at 'http://myhost:10000/default' could not be reached: Connection refused
```
=> CDAP-3138: CLI shouldn't stack trace on unable to connect at startup

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java, cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java, cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java, cdap-test/src/main/java/co/cask/cdap/test/TestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java, cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/internal/ApplicationManagerFactory.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Adding methods to add an application artifact or a plugin artifact
to TestManager and its implementations. Also adding a method to
deploy an application from an artifact.
=> CDAP-3065 add artifact methods to TestBase for unit tests

cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java, cdap-master/src/main/java/co/cask/cdap/data/tools/SimpleHBaseQueueDebugger.java, cdap-master/src/test/java/co/cask/cdap/data/tools/flow/HBaseQueueDebuggerTest.java
https://issues.cask.co/browse/CDAP-3419
Output looks like this:
```
Running class co.cask.cdap.data.tools.SimpleHBaseQueueDebugger
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cdap/master/lib/ch.qos.logback.logback-classic-1.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/zookeeper/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2015-08-19 20:34:04,485 - WARN …
```
=> CDAP-3419: Record min write pointer in HBaseQueueDebugger

cdap-docs/reference-manual/source/faq.rst
Fixes the link to the IRC channel (it was being rendered as HTTP rather than IRC) and moves a period outside of an HTTP link.
=> Correct IRC link.

cdap-ui/app/styles/themes/cdap/theme.less, cdap-ui/app/styles/variables.less
*  Changes popover arrow border color to white to fix Firefox styling inconsistency
=> adds white border to popover arrow

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
Otherwise, it'll use whatever is CDAP cookbook default. Same as #3668 for 3.1
=> Use 3.1.1-2 release artifacts

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
- Specify our own plugin list for Eclipse
- Specify HDP 2.1 version for Flume
=> Backport fixes from release/3.1

cdap-ui/app/features/admin/routes.js, cdap-ui/app/features/dashboard/controllers/dashboard-ctrl.js, cdap-ui/app/features/dashboard/routes.js
*  Removes "Home" and dashboard names from Operations. Breadcrumb now always shows namespace dropdown + "Operations," regardless of the active tab showing system or user dashboard
*  Removes "Home" from Management breadcrumbs - base parent is now always "Management"
=> modifies breadcrumb text for ops and mgmt

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileReader.java, cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/AbstractStreamFileConsumer.java
- If the exception is EOFException, the StreamDataFileReader won’t get closed, hence the reopening of the underlying input stream should just resume from where it left off
- If the exception is other type of IOException, it will get propagated outside, which the expected behavior is to close and create a new StreamDataFileReader, which the initial position will be passed from the caller, hence resetting of position to 0 is not need.
=> (CDAP-3458) Don’t reset the position to 0 on IOException

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java, cdap-client-tests/src/main/java/co/cask/cdap/client/app/ConfigurableProgramsApp.java, cdap-client-tests/src/main/java/co/cask/cdap/client/app/ConfigurableProgramsApp2.java, cdap-client-tests/src/test/java/co/cask/cdap/client/ApplicationClientTestRun.java, cdap-client/src/main/java/co/cask/cdap/client/ApplicationClient.java, cdap-client/src/main/java/co/cask/cdap/client/ArtifactClient.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java, cdap-proto/src/main/java/co/cask/cdap/proto/artifact/AppRequest.java
An application's config can be updated, as well as the artifact
version it uses. Changing artifact name is invalid. If no config
is given, the existing config will be used. Otherwise, the
existing config is completely overwritten by the requested config.
=> CDAP-3282 api to update an existing application

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/DelayedHttpServiceResponder.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGenerator.java, cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
JIRA: https://issues.cask.co/browse/CDAP-1892
Before the fix service always returned the same message `Error: 500: Transaction failure when committing changes. Aborted transaction.` irrespective of the root cause.
After the fix, we return the stack trace of the root cause, so that it is easier for the user to pin point the reason for the exception through UI as well as through CLI without checking the master log files.
=> Updated code to return the root cause of the exception through the service handler.

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java, cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java, cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
Some refactoring to move logic out of the AppLifecycleHttpHandler
into AppLifecycleService. Http handlers should contain as little
logic as possible, with most logic residing in the services since
they can be re-used in different places. For example, CDAP upgrade
may need to make use of this logic when upgrading existing apps to
the new artifact framework.
=> CDAP-3450 move app deploy logic from http handler into service

cdap-standalone/bin/cdap.sh
Standalone loads all JARs from CDAP_HOME/lib/* which relies on the
underlying file-system's ordering, which is not guaranteed. This
was causing instability due to the differences between Mac OS X
file-system (HFS+) and Linux (Ext3/4).
=> CDAP-3482 Sort CLASSPATH in Standalone

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java, cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java, cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactRange.java
Fixes a bug where information about version inclusivity is dropped
in the artifact store which can cause bugs if the version range
originally used non-default inclusive flags.
=> CDAP-3501 store artifact range inclusive information

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java, cdap-test/src/main/java/co/cask/cdap/test/TestManager.java, cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java, cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
This is needed if an app would normally export packages for
plugins to implement.
=> CDAP-3497 add a way in unit tests to export packages in an app

cdap-distributions/bin/build_artifact_upload.sh
When doing if [ A == B ] string variable comparisons in bash, safest thing is to force both sides to be string.
This will be ported back to 3.1, 3.0 and 2.8 as well.
=> CDAP-3437 need the quotes to force string comparison
