caskdata/cdap

cdap-explore/src/main/java/co/cask/cdap/explore/executor/QueryExecutorHttpHandler.java

QueryParam annotation for params contained in a POST body.

CDAP-1107 revert parts of refactor that mistakenly used the

---

cdap-standalone/bin/cdap.sh
cdap-standalone/src/main/resources/cdap-site.xml

Same changes... different target branch... I need this to build a new Docker container and upload it.

Backport #884 to release/2.5.0 branch

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/DashboardHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/DashboardHttpHandlerTest.java

Bamboo : https://builds.cask.co/browse/CDAP-DUT408

Fix dashboard endpoint - store json blob directly and retrieve it

---

cdap-cli/src/main/java/co/cask/cdap/cli/ProgramIdArgument.java
cdap-cli/src/main/java/co/cask/cdap/cli/completer/element/HttpEndpointPrefixCompleter.java
cdap-cli/src/main/java/co/cask/cdap/cli/completer/element/HttpMethodPrefixCompleter.java
cdap-cli/src/main/java/co/cask/cdap/cli/util/ArgumentParser.java
cdap-cli/src/test/java/co/cask/cdap/cli/util/ArgumentParserTest.java

Added util for parsing params from user input. @jwang47, @sreevatsanraman Please take a look.

CDAP-506: Allow CLI completers to access context

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsRequestParser.java
cdap-web-app/client/core/application.js
cdap-web-app/client/core/controllers/analyze.js
cdap-web-app/client/core/controllers/overview.js
cdap-web-app/client/core/controllers/resources.js
cdap-web-app/client/core/partials/timeselector.html
cdap-web-app/client/core/util.js

the REST API will return 1 sec resolution by default.
The REST API will adjust resolution automatically if you specify resolution=auto param

Metrics - use second resolution by default 

---

cdap-docs/reference-manual/source/release-notes.rst

Staged at:
http://stg-web101.sw.joyent.continuuity.net/cdap/2.6.0-SNAPSHOT-r2.6.0_known_issue/en/reference-manual/release-notes.html#known-issues

Logging CDAP-1124 as a known issue.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java

instead of always the yarn user.

CDAP-1131 run mapreduce as the user that we use to talk with hdfs

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletRuntimeService.java

https://issues.cask.co/browse/CDAP-1137

CDAP-1137: Set LoggingContext for a Flow during FlowRuntimeService startUp

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/program/DefaultProgram.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/program/Program.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/services/AbstractServiceDiscoverer.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/services/SerializableServiceDiscoverer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/ForwardingProgram.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/FlowTwillApplication.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/MapReduceTwillApplication.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/ProcedureTwillApplication.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/ServiceTwillApplication.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillApplication.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/BasicFlowletContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowUtils.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/procedure/BasicProcedureContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/procedure/ProcedureProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/BasicServiceWorkerContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/BasicSparkContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/webapp/WebappProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/AbstractWorkflowProgram.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramController.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceHttpServer.java

Part 2 of replacing ``accountId`` with ``namespaceId``.
This PR replaces ``getAccountId`` method in ``Program`` with ``getNamespaceId``

[CDAP-1006] Replaced Program.getAccountId with Program.getNamespaceId

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsMessageCallback.java

https://issues.cask.co/browse/CDAP-745

log metric value decode error as info with no stacktrace (CDAP-745)

---

cdap-common/src/main/java/co/cask/cdap/common/stream/StreamEventDataCodec.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamDataFileTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileConstants.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileReader.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamDataFileWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamEventBuffer.java

- Added support for uni timestamp that uses file close time as event timestamp
- Added support for default headers

(CDAP-876) Upgrade Stream file to v2 format

---

cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseHistoryBuilder.java

CDAP-1144 allow setting mapper and reducer resources at runtime

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/AbstractStreamCoordinator.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/DistributedStreamCoordinator.java

Ran ``mvn clean package -DskipTests`` locally.

Fix checkstyle errors

---

cdap-docs/examples-manual/source/examples/purchase.rst

commands listed in the "stopping" section would start the flow, not stop

fixing stop instructions

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamFetchHandler.java

This change only affect the get stream events REST API.
The improvement is mainly for the case when a fetch request comes with
a startTime, and the first event with the given startTime is in higher
stream file sequence. The old logic will return no events, as the 
live stream reader expects one to keep polling for events (when
switching to new file, it will return 0 events and expect caller to call
read again. This works well for Flow). 
The new logic is simply to honor that behavior by keep
polling as long as there is events being read/skipped.

Better stream events fetch logic.

---

cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTableTest.java

Disable failing tests. CDAP-1186 has details

Disable failing tests. CDAP-1186 has details

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DefaultSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithSchedule.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java

1. Implementation of merging schedule properties with program's runtime arguments.
2. Unit test case.

Merge schedule properties with the program's runtime arguments.

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamFileJanitorTestBase.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriterTestBase.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/DFSConcurrentStreamWriterTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/LocalConcurrentStreamWriterTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/LocationStreamFileWriterFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/InMemoryStreamCoordinator.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriter.java

The only important change is in the ConcurrentStreamWriter class (and its test case). All other changes are just moving class around.

(CDAP-960) Added appendFile method to ConcurrentStreamWriter

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java

fix for metrics hbase table

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/java/co/cask/cdap/common/io/ByteBuffers.java
cdap-common/src/main/resources/cdap-default.xml
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/BufferedContentWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/BufferedContentWriterFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/ContentWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/ContentWriterFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/FileContentWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/FileContentWriterFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/StreamBodyConsumerFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/TextStreamBodyConsumer.java
cdap-data-fabric/src/test/java/co/cask/cdap/data/stream/service/upload/StreamBodyConsumerTestBase.java
cdap-data-fabric/src/test/java/co/cask/cdap/data/stream/service/upload/TextStreamBodyConsumerTest.java

- Added support for line separated text content

(CDAP-960) Added batch endpoint for stream

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeploymentInfo.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/LocalArchiveLoaderStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricTestHelper.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/LocalManagerTest.java

Modify deployment pipeline to reuse deploy code between Applications and Adapters

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/services/AbstractServiceDiscoverer.java
cdap-common/src/main/java/co/cask/cdap/common/discovery/ServiceDiscoveries.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultServiceManager.java

See JIRA https://issues.cask.co/browse/CDAP-1218 for details.

(CDAP-1218) Fix service discovery getURL logic to remove possible race condition.

---

cdap-docs/developers-manual/source/building-blocks/spark-programs.rst

https://issues.cask.co/browse/CDAP-1069
@awholegunch Does this limitation/known issue be documented here? Or should it be documented somewhere else?
@anew Can you please review the content?

CDAP-1069: Document a limitation in using Datasets in Spark

---

cdap-unit-test/src/test/java/net/fake/test/app/TestBundleJarApp.java

- Also combine two test into one as they are unnecessarily separated.

Fix the misspell to properly use the waitFor call instead of blindly sleep 3 seconds.

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/AbstractGetPreferencesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/AbstractSetPreferencesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/DeletePreferencesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/LoadPreferencesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/PreferencesCommandSet.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/SetPreferencesCommand.java

JIRA : https://issues.cask.co/browse/CDAP-1223
Bamboo : https://builds.cask.co/browse/CDAP-RBT59

CDAP-1223: New CLI command for Preferences to set preferences from a config file

---

cdap-client-tests/src/test/java/co/cask/cdap/client/QueryClientTestRun.java
cdap-explore-client/src/main/java/co/cask/cdap/explore/client/AbstractExploreClient.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreExtensiveSchemaTableTestRun.java

CDAP-1164 fix the way we decode query results from hive for

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/AbstractStreamService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/AbstractStreamFileAdmin.java

Also removed use of notification manager for the local stream service, which doesn't need it.
Build https://builds.cask.co/browse/CDAP-RBT71

Change notification feeds names in streams. 

---

cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java

already has exploration enabled should not be an error.

CDAP-1114 enabling exploration on a stream or dataset that

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-proto/src/main/java/co/cask/cdap/proto/AdapterConfig.java

and namespace dataset framework so that datasets are actually
usable.

CDAP-1252 actually use adapter defaults when creating an adapter,

---

cdap-adapters/src/main/java/co/cask/cdap/conversion/app/AdapterArguments.java
cdap-api/src/main/java/co/cask/cdap/api/data/schema/Schema.java
cdap-api/src/main/java/co/cask/cdap/internal/io/SQLSchemaParser.java
cdap-common/src/test/java/co/cask/cdap/io/SchemaTest.java

which is more SQL-like, in preparation for use in the CLI.

CDAP-1247 add support for an alternative way to specify schema

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/main/java/co/cask/cdap/hive/datasets/DatasetAccessor.java

This PR is for https://issues.cask.co/browse/CDAP-71

Not caching Dataset classloader in DatasetAccessor when running in Explore Service

---

cdap-distributions/src/parcel/meta/parcel.json

setting the minimum CDH version for parcel, as recommended

set minimum CDH version to 5

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ConsoleSettingsHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ConsoleSettingsHttpHandlerTest.java
cdap-common/src/main/java/co/cask/cdap/common/http/SecurityRequestContext.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java

For ConsoleSettingsHandler, get the user id from the SecurityRequestContext.
Also rename the endpoints from usersettings to consolesettings.

Retrieve userId from SecurityRequestContext

---

cdap-adapters/src/main/java/co/cask/cdap/conversion/app/AdapterArguments.java
cdap-adapters/src/main/java/co/cask/cdap/conversion/app/StreamConversionMapReduce.java
cdap-adapters/src/main/resources/META-INF/MANIFEST.MF
cdap-adapters/src/test/java/co/cask/cdap/conversion/app/StreamConversionAdapterTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateStreamConversionAdapterCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/AdapterCommands.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamConfig.java

a time partitioned fileset. This includes adding default
properties for sinks, and adding a CLI command that puts together
an adapter config with reasonable defaults.

CDAP-1252 simplify adding an adapter for converting a stream to

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/HelpCommand.java

This is some sample output
```
call service <app-id.service-id> <http-method> <endpoint> [headers <headers>]
[body <body>]
Calls a Service endpoint. The header is formatted as "{'key':'value', ...}"
and the body is a String.
connect <cdap-instance-uri>
Connects to a CDAP instance. <credential(s)> parameter(s) could be used if
authentication is enabled in the gateway server.
create adapter <adapter-name> type <adapter-type> [props <adapter-props>]
src <adapter-source> [src-props <adapter-source-config>] sink
<adapter-sink> [sink-props <adapter-sink-config>]
Creates a Adapter
get spark status <app-id.spark-id>
Gets the status of a Spark
get stream <stream-id> [<start-time>] [<end-time>] [<limit>]
Gets events from a Stream. The time format for <start-time> and <end-time> can
be a timestamp …
```

Better formatting for the CLI help output with auto-line wrap and alignment

---

cdap-web-app/client/core/controllers/workflow-status.js
cdap-web-app/client/core/models/workflow.js

addresses https://issues.cask.co/browse/CDAP-1271

changing api endpoints for schedules

---

cdap-docs/developers-manual/source/building-blocks/index.rst

Changing a Mapreduce Job to a Mapreduce Program

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricRecordsWrapper.java

Build: https://builds.cask.co/browse/CDAP-RBT115-2
Fixes 7/16 failing audi tests on standalone.

[CDAP-1284] Added dataset metric tag to tag prefix part of aggregation rules

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/AbstractHttpHandlerDelegator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/DefaultHttpServiceResponder.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/DelayedHttpServiceResponder.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGenerator.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithServices.java

(CDAP-1274) Postpone the service response till the transaction has

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/main/java/co/cask/cdap/hive/datasets/DatasetAccessor.java

Also fixing disable/enable explore order during Datset creation.
Fix for https://issues.cask.co/browse/CDAP-71

Caching Dataset classloader per query in Explore. 

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletRuntimeService.java

Bamboo : https://builds.cask.co/browse/CDAP-RBT117

Setting logging context to get logs during flowlet shutdown

---

cdap-docs/developers-manual/source/building-blocks/services.rst

Fixes https://issues.cask.co/browse/CDAP-1270

(CDAP-1270) Document that handler classes and methods must be public

---

cdap-distributions/pom.xml
pom.xml

Added release iteration to facilitate creating RCs

Add a release iteration

---

cdap-api/src/main/java/co/cask/cdap/api/service/http/HttpServiceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/BasicServiceWorkerContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/ServiceComponentProgramControllerAdapter.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/ServiceComponentProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/ServiceProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceHttpServer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceWorkerDriver.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppUsingGetServiceURL.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

https://builds.cask.co/browse/CDAP-RBT88-3

(CDAP-743) Update instance counts in Service contexts

---

cdap-web-app/client/assets/css/new/main.css
cdap-web-app/client/core/controllers/flow-history.js
cdap-web-app/client/core/controllers/workflow-history.js
cdap-web-app/client/index.html

address https://issues.cask.co/browse/CDAP-1292

fix history page, remove loadrun on click which was a no-op

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/VerificationStage.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithMultipleScheduledWorkflows.java
cdap-app-fabric/src/test/java/co/cask/cdap/ScheduleAppWithMissingWorkflow.java
cdap-app-fabric/src/test/java/co/cask/cdap/runtime/WorkflowTest.java

Fix for jira: https://issues.cask.co/browse/CDAP-1306

Added validation for the workflow name.

---

cdap-adapters/src/main/java/co/cask/cdap/conversion/app/StreamConversionMapReduce.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/CreateStreamConversionAdapterCommand.java

name so that you can tell what conversion is running.

CDAP-1309 fix default schema to something valid and set the job

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/AbstractStreamFileAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamConfig.java

- Also has small refactoring on the `StreamConfig` class to distinguish the case whether it's using a default format spec or using a user set one.

Moved enable stream exploration to StreamAdmin.

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java

This fixes the stream resource coordination not working correctly.

(CDAP-1364) Guard against interim failure

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java

Build: https://builds.cask.co/browse/CDAP-RBT130

Fix creation of stream not showing up in stream coordination requirement

---

cdap-docs/admin-manual/source/installation/integrations.txt

Fix typo in integration doc

---

cdap-docs/build.sh

Release 2.7.1 Docs build for GitHub pages

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
cdap-notifications-api/src/main/java/co/cask/cdap/notifications/feeds/NotificationFeedManager.java
cdap-notifications-api/src/main/java/co/cask/cdap/notifications/feeds/NotificationFeedNotFoundException.java
cdap-notifications-api/src/main/java/co/cask/cdap/notifications/feeds/client/RemoteNotificationFeedManager.java
cdap-notifications-api/src/main/java/co/cask/cdap/notifications/feeds/service/NoOpNotificationFeedManager.java
cdap-notifications-api/src/main/java/co/cask/cdap/notifications/service/NotificationService.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/feeds/service/NotificationFeedService.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/AbstractNotificationService.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/kafka/KafkaNotificationService.java

Build: https://builds.cask.co/browse/CDAP-DUT723

Make NotificationFeedNotFoundException extend NotFoundException

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactCodec.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/TagValue.java
cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactTableTest.java

https://issues.cask.co/browse/CDAP-1406

FactTable - search next available tags and metric names

---

cdap-common/src/main/java/co/cask/cdap/common/zookeeper/ReentrantDistributedLock.java
cdap-common/src/test/java/co/cask/cdap/common/zookeeper/ReentrantDistributedLockTest.java

It is needed for distributed coordination for resource update (e.g. stream config update that get written to disk).

Implementation of Distributed lock through ZooKeeper.

---

cdap-docs/_common/common-build.sh

Implementation of the [PR-1244](https://github.com/caskdata/cdap/pull/1244)

Add memory to both parts of the SDK build.

---

cdap-common/src/main/java/co/cask/cdap/common/io/LocationStatus.java
cdap-common/src/main/java/co/cask/cdap/common/io/Locations.java
cdap-common/src/main/java/co/cask/cdap/common/io/Processor.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/StreamFileSizeFetcherTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamAdmin.java

This API will be used by the new ``DataScheduler`` to poll for the size of a stream, when notifications are not received.
Build: https://builds.cask.co/browse/CDAP-DUT718

[CDAP-850] New API in StreamAdmin to get the size of data written to a stream

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/NamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricClient.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/stream/store/MDSStreamMetaStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/stream/store/StreamMetaStoreTestBase.java
cdap-client/src/main/java/co/cask/cdap/client/NamespaceClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/InMemoryStreamMetaStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/MDSStreamMetaStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamMetaStore.java
cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceMeta.java

Clone of #1199 with squashed commits.

[CDAP-1169] Adding NamespaceAdmin for namespace admin operations

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/FieldTypes.java

fixes an issue introduced with cdap-938. sorry.

fix build break

---

cdap-api/src/main/java/co/cask/cdap/api/data/format/Formats.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/format/CombinedLogRecordFormat.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/format/RecordFormats.java
cdap-data-fabric/src/test/java/co/cask/cdap/data/format/CombinedLogRecordFormatTest.java
cdap-explore/src/main/java/co/cask/cdap/hive/serde/ObjectTranslator.java

* Added combined log format for streams and unit tests

Add CLF format for streams

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsDiscoveryHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/MetricStore.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/Cube.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/CubeExploreQuery.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/DefaultCube.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java
cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactTableTest.java

Follow up on: #1251
Addresses:
metrics discovery

metrics discovery V3 API Implementation and V2 - API support 

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/GetStreamStatsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/StreamCommands.java

Sample output:
```
cdap (http://localhost:10000)> get stream-stats test
Analyzing 100 Stream events in the time range [1423272965338, 9223372036854775807]...
column: name, type: STRING
Unique elements: 1
column: age, type: INT
Unique elements: 1
Histogram:
[200, 299]: 1
```

GetStreamStatsCommand

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClientTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/InMemoryStreamCoordinatorClientTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/StreamCoordinatorTestBase.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriterTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/AbstractStreamCoordinatorClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/CoordinatorStreamProperties.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/DistributedStreamCoordinatorClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/InMemoryStreamCoordinatorClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamCoordinatorClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamUtils.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamServiceRuntimeModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamConfig.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/StreamHandlerTestRun.java
cdap-proto/src/main/java/co/cask/cdap/proto/StreamProperties.java

- Use lock to simplify coordination logic
- Remove circular dependencies between FileStreamAdmin and AbstractStreamCoordinatorClient

(CDAP-1402) Refactor stream admin and stream coordinator

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithPartitionedFileSet.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithTimePartitionedFileSet.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceWithPartitionedTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-explore-client/src/main/java/co/cask/cdap/explore/client/AbstractExploreClient.java
cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreClient.java
cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreFacade.java
cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreHttpClient.java
cdap-explore-jdbc/src/test/java/co/cask/cdap/explore/jdbc/MockExploreClient.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/AvroHelper.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTest.java

[CDAP-941] register partitioned file sets in hive; unit tests for M/R and Explore

---

cdap-adapters/src/main/java/co/cask/cdap/conversion/app/StreamConversionWorkflow.java
cdap-api/src/main/java/co/cask/cdap/api/app/AbstractApplication.java
cdap-api/src/main/java/co/cask/cdap/api/app/ApplicationConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/service/AbstractService.java
cdap-api/src/main/java/co/cask/cdap/api/worker/AbstractWorker.java
cdap-api/src/main/java/co/cask/cdap/api/worker/Worker.java
cdap-api/src/main/java/co/cask/cdap/api/worker/WorkerConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/worker/WorkerContext.java
cdap-api/src/main/java/co/cask/cdap/api/worker/WorkerSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/worker/DefaultWorkerConfigurer.java

Bamboo : http://builds.cask.co/browse/CDAP-DUT758
JIRA : https://issues.cask.co/browse/CDAP-1450

Move Worker API to App Level and deprecating old ServiceWorker API

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactCodec.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java

Follow up on https://github.com/caskdata/cdap/pull/1251

reserve byte in metric records row format

---

cdap-app-fabric/src/main/java/co/cask/cdap/test/RuntimeStats.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTable.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/hooks/MetricsReporterHookTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-unit-test/src/test/java/co/cask/cdap/spark/metrics/SparkMetricsIntegrationTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java
cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactTableTest.java

Follow up on https://github.com/caskdata/cdap/pull/1251, addresses:
* all unit-tests to run

fixing delete and some other unit-tests wrt metric store

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java

Fix for the issue: https://issues.cask.co/browse/CDAP-1482
`ProgramLifeCycleHttpHandlerTest.testWorkflowRuns()` fails intermittently. This was because of the race condition mentioned in the above jira. Fix is to override the `init` method of the listener appropriately so that even if the Workflow execution happens before attaching listeners all the run information will get updated in the mds appropriately.

Implemented init method for the listeners.

---

cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java

procedures do not have v3 apis

---

cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandlerV2.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreMetadataHttpHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreMetadataHttpHandlerV2.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreStatusHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreStatusHandlerV2.java
cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java

Only pass the `namespaceId` to each API, but adds no additional functionality.
http://builds.cask.co/browse/CDAP-DUT802-3

(CDAP-1490) Namespace Explore APIs

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java

add groupBy support in metrics handler v3 API.
https://issues.cask.co/browse/CDAP-1243

metrics groupby support

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/ExecuteQueryCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/LoadStreamCommand.java

Missed these two files in the last PR: 1338 (https://github.com/caskdata/cdap/pull/1338)

Missed two files in the last commit.

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java

Build: http://builds.cask.co/browse/CDAP-DUT814

Fix CDAP-1502 and improve the logic of subscribing to stream heartbeats

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java

- Fix wrong counting logic in notification for stream, in distributed. 
- Handle false truncation of stream when starting CDAP
- Logging here and there
Build: http://builds.cask.co/browse/CDAP-DUT831

Couple of fixes for notifications on streams

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java

now, when you search for metric context, streams appear near apps and datasets

fix aggregation for stream metrics

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/StreamConsumerTestBase.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamServiceRuntimeModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/inmemory/InMemoryStreamConsumerFactory.java

- Remove test no long valid
- Fix the wrong assumption in the InMemoryStreamConsumerFactory
- Improve stream service in memory module to avoid exception due to service not started

Fix broken tests

---

cdap-client/src/main/java/co/cask/cdap/client/NamespaceClient.java

Clean up namespace client.
resolves: https://issues.cask.co/browse/CDAP-1136
http://builds.cask.co/browse/CDAP-DUT853-2

cleanup ns client

---

cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceStreamTest.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/WritableDatasetTestRun.java

* Hive-0.12 supports only _ other than alphanumeric - replacing '-' with '_'
* will document this in another PR

Replace - with _ for creating hive tables

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java

Helps resolve: https://issues.cask.co/browse/CDAP-1517
Build: http://builds.cask.co/browse/CDAP-DUT860-1

show default ns upon cli startup

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-client-tests/src/test/java/co/cask/cdap/client/DatasetClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetClient.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetModuleClient.java
cdap-client/src/main/java/co/cask/cdap/client/DatasetTypeClient.java

Build: http://builds.cask.co/browse/CDAP-DUT862-4

namespaced dataset clients (and cli)

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DatasetTypeManager.java

Currently the metadata for system dataset modules and types is never updated after it is first created.  Ultimately, I don't think we should be persisting the metadata for these system types at all.  But as a first step this change will delete the metadata for system datasets (those in system namespace, with no jar location) so that the latest metadata is recreated on each startup.

CDAP-1449 Delete and recreate system dataset modules on startup

---

cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java
cdap-cli/src/main/java/co/cask/cdap/cli/ElementType.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/GetProgramInstancesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/SetProgramInstancesCommand.java

Final PR for Workers support.
Bamboo : http://builds.cask.co/browse/CDAP-DUT773-16

CLI for Workers

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AbstractMonitorHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MonitorHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MonitorHandlerV2.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AbstractMonitorHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTestV2.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/MonitorHandlerTestV3.java

http://builds.cask.co/browse/CDAP-DUT875-1

Monitor Handler V3

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueEntryRow.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseStreamAdmin.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/util/hbase/HBaseTableUtilTest.java
cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase94/HBaseQueueRegionObserver.java
cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase96/HBaseQueueRegionObserver.java
cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/transaction/queue/coprocessor/hbase98/HBaseQueueRegionObserver.java

- Instead of hardcoded to 1, allowing being set throw table property

(CDAP-1204) Make HBase queue entry row key prefix size dynamic

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/feeds/service/MDSNotificationFeedStore.java

Jira: https://issues.cask.co/browse/CDAP-1578
Build: http://builds.cask.co/browse/CDAP-DUT889-1

[CDAP-1578] Reduce log level when connecting to notification service

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/TransactionHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/TransactionHttpHandlerTest.java
cdap-common/src/main/java/co/cask/cdap/common/http/RESTMigrationUtils.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandlerV2.java

Current PR
http://builds.cask.co/browse/CDAP-DUT886
Previous PR

Non Namespaced endpoints

---

cdap-cli/src/main/java/co/cask/cdap/cli/util/AsciiTable.java
cdap-cli/src/test/java/co/cask/cdap/cli/util/AsciiTableTest.java

```
new AsciiTable<String>(
new String[] {"c1", "c2", "c3333"},
ImmutableList.of(
"r1zz" + Strings.repeat("z", 300) + "456,r11,r1",
"r2,r2222 zzzzzzz z z z zzzzzz z zzzzzzzzz zzzzzzz zzzzzzz zzzzzzz zzzzz zzz123,r",
"r3333,r3,r3\n1"
),
new RowMaker<String>() {
@Override
public Object[] makeRow(String object) {
return object.split(",");
}
}
).print(System.out);
```
now outputs the following table:
```
+========================================================================================+
| c1                         | c2                         | c3333                        |
+========================================================================================+
| r1zzzzzzzzzzzzzzzzzzzzzzzz | r11                        | r1                           |
| zzzzzzzzzzzzzzzzzzzzzzzzzz | …
```

CDAP-1495: Max table width for AsciiTable

---

cdap-app-fabric/src/main/java/co/cask/cdap/test/RuntimeStats.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsDiscoveryQueryTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsQueryTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsDiscoveryHandler.java

So old dashboard expects v2 metrics API to only return user metrics...

fix metrics discovery for old dashboard

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/ElementType.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/GetProgramInstancesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/SetProgramInstancesCommand.java
cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/lifecycle.rst

JIRA : https://issues.cask.co/browse/CDAP-388
Bamboo : http://builds.cask.co/browse/CDAP-DUT911

Service Instances => Service Handler Instances; Remove reference to runnable

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkerTwillProgramController.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorker.java
cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandlerTest.java

Bamboo : http://builds.cask.co/browse/CDAP-DUT907

Fix Distributed mode instance update

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalManager.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ApplicationWithPrograms.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/CreateSchedulesStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/LocalArchiveLoaderStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/VerificationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/AbstractSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleNotFoundException.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/Scheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerException.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/guice/AppFabricTestModule.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/LocalManagerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/ProgramGenerationStageTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java

The deployment of an app has been tested manually, as well as the updating of a schedule.
Build: http://builds.cask.co/browse/CDAP-DUT916-1

Add exceptions to the Scheduler interface, and add the creation of schedules to the app deployment pipeline

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/MetricHBaseTableUtilTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/hbase/AbstractHBaseDataSetAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTableAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/MetricHBaseTableUtil.java

https://issues.cask.co/browse/CDAP-1522

util to figure out cdap version of metric's hbase table

---

cdap-ui/app/directives/navbar/namespace.html
cdap-ui/app/directives/navbar/navbar.html
cdap-ui/app/directives/navbar/navbar.less
cdap-ui/app/features/admin/admin.less
cdap-ui/app/features/admin/templates/admin.html
cdap-ui/app/features/admin/templates/namespace/apps.html
cdap-ui/app/filters/ellipsis.js

add myEllipsis filter and change long namespace truncation method

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/upgrade/MetricsDataMigrator.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/upgrade/MetricsEntityCodec.java

develop is broken because of this.

enityTable import fix

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java

https://issues.cask.co/browse/CDAP-1645

handling dots in metric tag names and values in rest api

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/kv/HBaseKVTableDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTableAdmin.java
cdap-master/src/main/java/co/cask/cdap/data/tools/Main.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java

https://issues.cask.co/browse/CDAP-1652

CDAP-1652: Do not store unlimited number of versions in meta tables

---

cdap-ui/app/features/workflows/controllers/tabs/runs/flow-ctrl.js

Minor fix for json structure change in workflow v3 api.

Fixes workflows view based on '/workflows/workflowId' API changes

---

cdap-api/src/main/java/co/cask/cdap/internal/batch/DefaultMapReduceSpecification.java
cdap-app-fabric/src/test/java/co/cask/cdap/AppWithMR.java
cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandlerTest.java

* Store all the dataset used by Mapreduce job in the spec. Related JIRA: [CDAP-1677](https://issues.cask.co/browse/CDAP-1677)

Add all datasets used by MapReduce job in the specification

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/ApplicationSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/AppFabricClient.java

remove the {runnable} from our APIs where appropriate

---

cdap-ui/app/features/operation28/ops.html

uncomment link to dashboard from operations

---

cdap-web-app/client/core/controllers/flow-flowlet.js
cdap-web-app/client/core/controllers/procedure-status.js
cdap-web-app/client/core/controllers/services.js
cdap-web-app/client/core/controllers/userservice.js
cdap-web-app/client/core/util.js
cdap-web-app/client/index.html

https://issues.cask.co/browse/CDAP-1672

remove client side validation for instances

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/program/DefaultProgram.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/program/ManifestFields.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/PreferencesHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/CreateSchedulesStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/ProgramBundle.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DefaultSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/AbstractWorkflowProgram.java
cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/DefaultId.java
cdap-app-fabric/src/test/java/co/cask/cdap/archive/ArchiveBundlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
cdap-proto/src/main/java/co/cask/cdap/proto/ProgramType.java

First part of several large refactoring PRs to enable a clean implementation of application authorization.

CDAP-1663: Refactor Id.Program to include ProgramType

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/resources/cdap-default.xml
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/DefaultDatasetNamespace.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DatasetNamespace.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/file/FileAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/file/FileSetDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/file/FileSetDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDefinition.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/FileSetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTest.java

This PR namespaces filesets under ``/cdap/[ns-id]/data`` directory.
This also suffers from the drawback mentioned in [CDAP-1593](https://issues.cask.co/browse/CDAP-1593)

[CDAP-1519] Namespaced Filesets

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/ObjectMappedTableProperties.java

Fix javadocs build.

---

cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTableTest.java

Fix for failing test in develop, Build Running here
http://builds.cask.co/browse/CDAP-DUT969-1

MetricsTable test case fix

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java

for aggregate resolution , we skip adding TTL
https://issues.cask.co/browse/CDAP-1626

no ttl for aggregates

---

cdap-master/src/main/java/co/cask/cdap/data/tools/AbstractUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/ArchiveUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgraderMain.java

- Renames the stream files for namespace
- Renames the log files for namespace
Review done here: https://github.com/caskdata/cdap/pull/1461
Have fixed all comments.
This PR is against develop.
Build : http://builds.cask.co/browse/CDAP-DUT950-4

Upgrade tool: Archive/file upgrade

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFrameworkTest.java

for upcoming changes to v3 dataset apis. Also fixing bugs around
namespaces, where remove all and get all operations were across
all namespaces instead of local to a namespace.

CDAP-1650 refactoring in memory dataset framework in preparation

---

cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java
cdap-client/src/main/java/co/cask/cdap/client/util/RESTClient.java

Forgot to push the commit that addressed comments in https://github.com/caskdata/cdap/pull/1480

Addressed comments

---

cdap-cli/src/main/java/co/cask/cdap/cli/util/table/AltStyleTableRenderer.java
cdap-cli/src/test/java/co/cask/cdap/cli/util/table/TableRendererTest.java

https://issues.cask.co/browse/CDAP-1707

CDAP-1707: Fix AltStyleTableRenderer when there are long headers

---

cdap-proto/src/main/java/co/cask/cdap/proto/Id.java

https://issues.cask.co/browse/CDAP-1486
http://builds.cask.co/browse/CDAP-DUT1003-2

Id.Stream to store Id.Namespace instead of String

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/directives/flow-graph/flow.less
cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/detail-ctrl.js
cdap-ui/app/features/flows/controllers/tabs/runs/streams/detail-ctrl.js
cdap-ui/app/features/flows/flows.less
cdap-ui/app/features/flows/routes.js
cdap-ui/app/features/flows/templates/tabs/runs/streams/detail.html
cdap-ui/app/filters/bytes.js
cdap-ui/test/unit/filters/bytes-test.js

- inject into streams
- use variables in flow diagram / calculate positions dynamically / center align 
https://issues.cask.co/browse/CDAP-1679

inject on streams, better flow diagrams

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/NamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceConfig.java
cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceMeta.java

* Added properties for namespace

Namespace properties

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
cdap-explore/src/main/java/co/cask/cdap/explore/table/CreateStatementBuilder.java
cdap-explore/src/main/java/co/cask/cdap/explore/table/SchemaConverter.java
cdap-explore/src/test/java/co/cask/cdap/explore/table/CreateStatementBuilderTest.java
cdap-explore/src/test/java/co/cask/cdap/explore/table/SchemaConverterTest.java

preparation for upgrade work. Also did some refactoring to move
logic around building the create statement for hive tables into
one class.

CDAP-1628 add cdap version as a property to all hive tables in

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/MDSUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgraderMain.java

- Upgrades app.meta table 
- Also upgrades stream meta for streams which does not belong to any app.
Issues: 
- CDAP-1510
- CDAP-1579

AppMeta table upgrade

---

cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/timeseries/FactTableTest.java

test coverage for factTable search 
build running : http://builds.cask.co/browse/CDAP-DUT1031-1

factTable search test case

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryQueueService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBStreamAdmin.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/QueueTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java

- QueueAdmin should always take QueueName instead of String to operate on

Cleanup of QueueAdmin interface

---

cdap-ui/server/config/auth-address.js

try for 1000 times, then change ping timeout to 60 seconds

change ping attempts behavior

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java

JIRA: https://issues.cask.co/browse/CDAP-1728

[CDAP-1728] Prevent stream size scheduler from crashing with NPE when stopped

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/features/apps/templates/tabs/status.html
cdap-ui/app/features/workflows/templates/tabs/runs.html

Fixes individual nodes in workflow diagram be un-clickable. (for 2.8.0 alone)

Fixes workflow diagram click handler for individual nodes in workflows

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDS.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDSUpgrader.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/TableId.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java

https://issues.cask.co/browse/CDAP-1511
http://builds.cask.co/browse/CDAP-DUT1048-6

Upgrade/Migrate dataset instances mds.

---

cdap-master/pom.xml
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgraderMain.java

- Upgrade tool creates system namespace in hbase if does not exists.
Issues: 
https://issues.cask.co/browse/CDAP-1725
Build : http://builds.cask.co/browse/CDAP-DUT1004-4

CDAP-1725 Upgrade tool creates system ns in hbase

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/DistributedStreamService.java
cdap-notifications-api/src/main/java/co/cask/cdap/notifications/service/NotificationHandler.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/AbstractNotificationService.java
cdap-notifications/src/test/java/co/cask/cdap/notifications/NotificationTest.java

Build: http://builds.cask.co/browse/CDAP-DUT1055-1

Fix wrong API name in NotificationHandler class getNotificationFeedType -> getNotificationType

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AbstractMonitorHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/TransactionHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/TransactionHttpHandlerTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceClientTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/DequeueScanAttributes.java
pom.xml

https://issues.cask.co/browse/CDAP-1540
Also updating tephra version to 0.3.5-SNAPSHOT for now. Will replace the version when tephra release is done.

Exposing transaction manager APIs to truncate invalid list through Router

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/queue/ConsumerConfig.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/queue/ConsumerGroupConfig.java

- ConsumerConfig and ConsumerGroupConfig

Split ConsumerConfig into two classes.

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDSUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java

Upgraded Filesets base paths:
Issue: https://issues.cask.co/browse/CDAP-1763
This PR was reviewed here: #1576
Opening this against develop and waiting for final approval.
Build : https://builds.cask.co/browse/CDAP-DUT1067-1

CDAP-1763 fileset upgrade

---

pom.xml

For bug fix in https://issues.cask.co/browse/TEPHRA-76

Upgrade to Tephra 0.4.1-SNAPSHOT

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java
cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml
cdap-explore/src/main/java/co/cask/cdap/explore/service/HiveStreamRedirector.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive12ExploreService.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive13ExploreService.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/HiveCDH4ExploreService.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/HiveCDH5ExploreService.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveStreamRedirectorTest.java
cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterMain.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java

Had a couple of merge conflicts that I had to fix - mostly around namespaces.
Still need to test against 2.6, but waiting for Albert's beamer PR to get merged.

Port (CDAP-1395) Log rotation of containers to 2.6

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java

I don't know why it can ever pass before. Maybe by pure luck.

Fix the broken Map reduce unit-test

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/AbstractSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DefaultSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DistributedSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/LocalSchedulerService.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
pom.xml

Reopening https://github.com/caskdata/cdap/pull/1593

CDAP-1417 Port to 2.6 - Capabilities to submit programs in non-default yarn Queues

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/DatasetSpecification.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metrics/HBaseDatasetMetricsReporter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/metrics/LevelDBDatasetMetricsReporter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/leveldb/LevelDBNameConverter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HTableNameConverter.java
cdap-data-fabric/src/test/java/co/cask/cdap/api/dataset/DatasetSpecificationTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableServiceTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBNameConverterTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/util/hbase/AbstractHBaseTableUtilTest.java
cdap-hbase-compat-0.94/src/main/java/co/cask/cdap/data2/util/hbase/HBase94TableUtil.java
cdap-hbase-compat-0.96/src/main/java/co/cask/cdap/data2/util/hbase/HBase96TableUtil.java
cdap-hbase-compat-0.98/src/main/java/co/cask/cdap/data2/util/hbase/HBase98TableUtil.java

reviewed here : #1326
opening against release.

storage metrics fix

---

cdap-docs/admin-manual/source/operations/index.rst
cdap-docs/admin-manual/source/operations/logback.rst
cdap-docs/developers-manual/source/advanced/application-logback.rst
cdap-docs/developers-manual/source/advanced/index.rst
cdap-docs/reference-manual/source/glossary.rst

Re-opening https://github.com/caskdata/cdap/pull/1597 against release with addressed comments.

(CDAP-1741) Docs for app logbacks

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java

https://issues.cask.co/browse/CDAP-1820
http://builds.cask.co/browse/CDAP-RBT154

CDAP-1820: Treat ! as plain char in CLI commands

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/pom.xml
cdap-cli/src/main/java/co/cask/cdap/cli/command/LoadPreferencesCommand.java
pom.xml

JIRA : https://issues.cask.co/browse/CDAP-1762
Reopening - https://issues.cask.co/browse/CDAP-1575
Bamboo : http://builds.cask.co/browse/CDAP-DUT1110

Removing external XML dependency

---

cdap-master/src/main/java/co/cask/cdap/data/tools/QueueConfigUpgrader.java

If the queue config table does  not exists just skip the upgrade as its not  needed. 
JIRA: https://issues.cask.co/browse/CDAP-1814

don't try to upgrade queue config table if does not exists

---

cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v2/index.rst
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v2/transactions.rst
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/index.rst
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/transactions.rst

Part 2 of #1626 . The v2 and v3 versions are identical - so if you review one of them I can address comments in both versions.

Transaction REST documentation

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/Partition.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionOutput.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionedFileSet.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimePartition.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimePartitionOutput.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimePartitionedFileSet.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceWithPartitionedTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java
cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst
cdap-docs/developers-manual/source/building-blocks/datasets/index.rst
cdap-docs/examples-manual/source/examples/sport-results.rst
cdap-examples/SportResults/src/main/java/co/cask/cdap/examples/sportresults/SportResults.java
cdap-examples/SportResults/src/main/java/co/cask/cdap/examples/sportresults/UploadService.java
cdap-examples/SportResults/src/test/java/co/cask/cdap/examples/sportresults/SportResultsTest.java
cdap-examples/StreamConversion/src/test/java/co/cask/cdap/examples/streamconversion/StreamConversionTest.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreUpgradeTest.java

This was meant to be a pure docs PR. But while writing, I realized that the PartitionedFileSet API can be improved, talked to Terence, and we came up with a better API. So this PR ends up having changes for the dataset API as well as the documentation for it.

[CDAP-1001] Feature/pfs docs

---

cdap-master/src/main/java/co/cask/cdap/data/tools/AbstractUpgrader.java

Fix log statement

---

cdap-explore-client/src/main/java/co/cask/cdap/explore/client/ExploreFacade.java

https://issues.cask.co/browse/CDAP-1604

(CDAP-1604) Don't enable explore on system datasets

---

cdap-master/src/main/java/co/cask/cdap/data/tools/DataMigration.java
cdap-master/src/test/java/co/cask/cdap/data/tools/DataMigrationTest.java

http://builds.cask.co/browse/CDAP-RBT163-1

removed unwanted binding and added test case for testing injector

---

cdap-docs/admin-manual/source/index.rst
cdap-docs/admin-manual/source/operations/index.rst
cdap-docs/admin-manual/source/operations/tx-maintenance.rst
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/transactions.rst

Sending out the PR early to get feedback for Operations section. Still need to document the Transaction Manager REST APIs.

Transaction manager maintenance doc

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java

https://issues.cask.co/browse/CDAP-1750
http://builds.cask.co/browse/CDAP-RBT159

CDAP-1750: Use different port in CLIMainTest

---

cdap-docs/admin-manual/source/installation/installation.rst
cdap-docs/developers-manual/source/getting-started/standalone/index.rst
cdap-docs/integrations/source/partners/cloudera/configuring.rst
cdap-docs/reference-manual/source/faq.rst

Associated JIRA: https://issues.cask.co/browse/CDAP-1804

Fix/ui nodesjs version doc update 2.8.0

---

cdap-docs/admin-manual/source/installation/installation.txt
cdap-docs/developers-manual/source/getting-started/standalone/index.rst
cdap-docs/reference-manual/source/faq.rst

Associated JIRA: https://issues.cask.co/browse/CDAP-1804

Fix/ui nodesjs version doc update 2.7.0 

---

cdap-docs/admin-manual/source/installation/installation.rst
cdap-docs/developers-manual/source/getting-started/standalone/index.rst
cdap-docs/reference-manual/source/faq.rst

Associated JIRA: https://issues.cask.co/browse/CDAP-1804

Fix/ui node.js version doc update 2.6.0 

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppFabricHttpHandlerTest.java

Jira - https://issues.cask.co/browse/CDAP-1669

v2 Workflow spec api returns the specifications in pre 2.8 format

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsQueryTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java

https://issues.cask.co/browse/CDAP-1591

bug fix-v2 API : use tag-value "any" for program-type when type name is missing 

---

cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java

Jira: [CDAP-1761](https://issues.cask.co/browse/CDAP-1761)
Build: http://builds.cask.co/browse/CDAP-RBT175-1

[CDAP-1761] Read table prefix from configuration instead of hard-coding cdap

---

cdap-app-fabric/src/main/java/co/cask/cdap/test/RuntimeStats.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

fix for issue describer here : https://issues.cask.co/browse/CDAP-1846
build running : http://builds.cask.co/browse/CDAP-RBT177-1

fix for runtime stats reset

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/TransactionManagerDebuggerMain.java

JIRA: https://issues.cask.co/browse/CDAP-1694

Fix default port for tx debugger

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ApplicationSpecificationAdapter.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-master/src/main/java/co/cask/cdap/data/tools/MDSUpgrader.java

Make the usage of it more convenient

Small refactoring of ApplicationSpecicificationAdapter

---

pom.xml

http://builds.cask.co/browse/CDAP-RBT178

Unsnapshot dependencies

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java

- This fixes the issues with filter and enables us to read log files.
- But there is another bigger problem with logs from Kafka due to namespace changes for which I will open another Jira.

CDAP-1842 fix log filters for namespaces

---

cdap-common/src/main/java/co/cask/cdap/gateway/handlers/ConfigHandler.java

And fixes a bug where it was return for "hbase" and JSON, the CDAP config.
Build: http://builds.cask.co/browse/CDAP-DUT1167-1

Adds a "v3" to the endpoint

---

cdap-api/src/main/java/co/cask/cdap/api/data/stream/StreamWriter.java
cdap-docs/developers-manual/source/building-blocks/workers.rst

Document the stream writer feature. Marked StreamWriter API as Beta to allow easy API evolution.

Stream Writer Docs

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDSUpgrader.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetTypeMDSUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/DatasetUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/MDSUpgrader.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Guice fixes required to enable queue config upgrade in upgrade tool.
Build: http://builds.cask.co/browse/CDAP-RBT190-1

Improve guice bindings in upgrade tool

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java

https://issues.cask.co/browse/CDAP-1850
build running : http://builds.cask.co/browse/CDAP-RBT187

groupBy friendly tagname fix

---

cdap-ui/app/features/flows/routes.js
cdap-ui/app/features/mapreduce/routes.js
cdap-ui/app/features/workflows/routes.js
cdap-ui/app/styles/themes/cdap.less

new breadcrumb design

---

cdap-docs/_common/_source/index.rst
cdap-docs/developers-manual/source/index.rst

Removes mention of packaging info that never completed; adds mention of the custom logbook documentation.

Fix bullet points et al

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Issue: https://issues.cask.co/browse/CDAP-1883
Build: http://builds.cask.co/browse/CDAP-RBT195-4

CDAP-1883 upgrade tool also creates default dir on hdfs

---

cdap-standalone/bin/cdap.sh
cdap-standalone/pom.xml
cdap-ui/pom.xml
cdap-web-app/conf/web-app-env.sh
cdap-web-app/pom.xml

Cdap-ui packaging fixes

---

cdap-docs/_common/_source/index.rst
cdap-docs/developers-manual/source/index.rst
cdap-docs/developers-manual/source/testing/index.rst
cdap-docs/developers-manual/source/testing/troubleshooting.rst

Fix for https://issues.cask.co/browse/CDAP-1432
Staged at: [Troubleshooting](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_classloading/en/developers-manual/testing/troubleshooting.html)
Additional altered page:
- [Index page](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-SNAPSHOT-r2.8_doc_classloading/en/developers-manual/testing/index.html)

Document classloading

---

cdap-examples/SportResults/src/main/java/co/cask/cdap/examples/sportresults/ScoreCounter.java

Workaround for JIRA: https://issues.cask.co/browse/CDAP-1887

Use Text as map output for the SportResults app

---

cdap-common/src/main/resources/cdap-default.xml

Build: http://builds.cask.co/browse/CDAP-RBT199-1

set kafka partition for logs back to 10

---

cdap-ui/app/features/backendstatus/errorModal.html
cdap-ui/app/main.js
cdap-ui/server/config/auth-address.js
cdap-ui/server/express.js

Showing modal to disable UI when backend is not running. 
Ping backend every minute

show modal when backend stops running

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceMDSUpgrader.java

Issue: https://issues.cask.co/browse/CDAP-1882
Build: http://builds.cask.co/browse/CDAP-RBT200-1

CDAP-1882 do not upgrade system dataset meta in instances

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

List what all will be upgraded 
and ask for confirmation.

Ask user for confirmation before upgrade 

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java

Jira - https://issues.cask.co/browse/CDAP-1898

Fixed the program controller state transition.

---

cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricStore.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsMessageCallback.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/Cube.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/cube/DefaultCube.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/timeseries/FactTable.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/upgrade/MetricsDataMigrator.java
cdap-watchdog/src/test/java/co/cask/cdap/metrics/store/cube/AbstractCubeTest.java

https://issues.cask.co/browse/CDAP-1899

CDAP-1899: batch writing metric values to MetricStore

---

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/NettyRouter.java

http://builds.cask.co/browse/CDAP-RBT212

Fix NettyRouter binding

---

cdap-ui/app/directives/metric-picker/metric-picker.html
cdap-ui/app/features/dashboard/widget.js
cdap-ui/app/features/flows/controllers/tabs/runs/status-ctrl.js
cdap-ui/app/features/flows/templates/tabs/runs.html
cdap-ui/app/features/mapreduce/controllers/detail-ctrl.js
cdap-ui/app/features/mapreduce/templates/tabs/runs.html
cdap-ui/app/features/workflows/templates/tabs/runs.html

- Updates bower dependencies (related PR merged to develop 2 days ago https://github.com/caskdata/cdap/pull/1733/commits)
- Fixes metrics to be updated in flow diagram in relatime.

Fix/ui ng strap modal 2.8

---

cdap-common/src/main/java/co/cask/cdap/gateway/handlers/VersionHandler.java

* Added v3/version endpoint
http://builds.cask.co/browse/CDAP-DUT1237

Update v3 version endpoint

---

cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableConcurrentTest.java
cdap-examples/FileSetExample/src/test/java/co/cask/cdap/examples/fileset/FileSetWordCountTest.java
cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankProgram.java
cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java
cdap-examples/UserProfiles/src/test/java/co/cask/cdap/examples/profiles/UserProfilesTest.java
cdap-test/src/main/java/co/cask/cdap/test/AbstractServiceManager.java
cdap-test/src/main/java/co/cask/cdap/test/ServiceManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java

Plus some cleanup of test classes

Some moderate speed up of unit tests

---

Dockerfile

This includes all of the Dockerfile fixes. Other commits on `release/2.8` have already been merged to `develop` via other PRs.

Merge release/2.8 to develop

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive13ExploreService.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceTestRun.java

query if there were no results returned.

CDAP-1895 fixing a bug where previewing a query would close the

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java

https://issues.cask.co/browse/CDAP-64

MR metrics availability in secure cluster

---

cdap-docs/_common/common_conf.py
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/metrics.rst

Fixes error in the v3 Metrics RESTful API
Staged at: [Metrics](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_metrics_docs/en/reference-manual/http-restful-api/http-restful-api-v3/metrics.html)
In particular:
- [Search for Contexts](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_metrics_docs/en/reference-manual/http-restful-api/http-restful-api-v3/metrics.html#search-for-contexts)
- [Search for Metrics](http://stg-web101.sw.joyent.continuuity.net/cdap/2.8.0-r2.8_fix_metrics_docs/en/reference-manual/http-restful-api/http-restful-api-v3/metrics.html#search-for-metrics)
et al.

Fix metrics docs

---

cdap-security/src/main/java/co/cask/cdap/security/server/ExternalAuthenticationServer.java
cdap-security/src/test/java/co/cask/cdap/security/server/ExternalAuthenticationServerSSLTest.java
cdap-security/src/test/java/co/cask/cdap/security/server/ExternalAuthenticationServerTest.java

http://builds.cask.co/browse/CDAP-DUT1282

CDAP-614: Support port 0 for ExternalAuthenticationServer

---

cdap-docs/examples-manual/build.sh

Fixes a broken doc build in develop branch.

Fix the doc build in the develop branch.

---

cdap-cli/src/main/java/co/cask/cdap/cli/util/ArgumentParser.java
cdap-cli/src/test/java/co/cask/cdap/cli/util/ArgumentParserTest.java

http://builds.cask.co/browse/CDAP-DUT1313

Allow quotes to be used for keys and values in CLI map arguments

---

cdap-ui/app/features/apps/templates/list.html

remove Version, Deployed, and Owner columns

remove columns in all apps view

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/MetricsConstants.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java

https://issues.cask.co/browse/CDAP-1910
https://issues.cask.co/browse/CDAP-1922

interpolator support and auto resolutions fix in metrics v3 api

---

cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
cdap-common/src/main/java/co/cask/cdap/common/http/AuthenticationChannelHandler.java
cdap-common/src/main/java/co/cask/cdap/common/http/CommonNettyHttpServiceBuilder.java

http://builds.cask.co/browse/CDAP-DUT1284

Parse user ID header when security is enabled

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java
cdap-cli/src/main/java/co/cask/cdap/cli/CLIMainArgs.java
cdap-cli/src/test/java/co/cask/cdap/cli/CLIMainArgsTest.java

http://builds.cask.co/browse/CDAP-RBT214
From https://github.com/caskdata/cdap/pull/1885

Treat options and command as two separate sections of args from main()

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/ExecuteQueryCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/GetStreamStatsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/util/table/AltStyleTableRenderer.java

http://builds.cask.co/browse/CDAP-DUT1312

Minor improvements to CLI execute and table rendering

---

cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/detail-ctrl.js
cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/input-ctrl.js
cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/output-ctrl.js
cdap-ui/app/features/flows/templates/tabs/runs/flowlets/detail.html

Metrics for Inputs and Outputs

Flowlet Details Metrics

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/ApplicationSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/program/ManifestFields.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ApplicationSpecificationCodec.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultApplicationSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ForwardingApplicationSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryConfigurator.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/ApplicationDetail.java
cdap-proto/src/main/java/co/cask/cdap/proto/ApplicationRecord.java

http://builds.cask.co/browse/CDAP-DUT1354

CDAP-2012: Add application version in the ApplicationSpec

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetServiceModules.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/MDSStreamMetaStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetMetaTableUtil.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/MDSDatasetsRegistry.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryFixedModulesDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetadataStoreDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/feeds/service/MDSNotificationFeedStore.java

@chtyim @abaranau:
I'm going to merge this PR into branch `hotfix/temp-fix-flow-change-instances` to start performance testing. Please still review the changes.

Performance improvements for dataset load

---

cdap-ui/app/features/dashboard/controllers/dashboard-ctrl.js
cdap-ui/app/features/dashboard/model/dashboards-model.js

Fixes dashboard creation & deletion in sync between backend and user settings store.

Fixes dashboard remove and adding in sync with backend and user settings

---

cdap-docs/admin-manual/source/installation/cdap-site.rst
cdap-docs/developers-manual/source/advanced/adapters.rst
cdap-standalone/src/main/resources/cdap-site.xml

places where it should have been renamed.

renamed the setting in the code earlier, but missed a couple

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamService.java

https://issues.cask.co/browse/CDAP-2032
http://builds.cask.co/browse/CDAP-DUT1363

CDAP-2032: Ensure stream exists according to streamAdmin before processing its config in LocalStreamService

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/RunIds.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-docs/reference-manual/source/http-restful-api/http-restful-api-v3/lifecycle.rst
cdap-proto/src/main/java/co/cask/cdap/proto/RunRecord.java

JIRA - https://issues.cask.co/browse/CDAP-1968
Also fixes the following bugs -
1. Fix fetch of run records for a running program when time range is specified.
2. Make start time inclusive and end time exclusive when fetching run records.

Adding an endpoint to fetch run record for a run

---

cdap-examples/StreamConversion/src/test/java/co/cask/cdap/examples/streamconversion/StreamConversionTest.java

https://issues.cask.co/browse/CDAP-2031
http://builds.cask.co/browse/CDAP-DUT1364

CDAP-2031: Retry for StreamConversionTest

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java

https://issues.cask.co/browse/CDAP-1792
http://builds.cask.co/browse/CDAP-DUT1368

CDAP-1792: Fix AppFabricTestBase cleanup

---

cdap-ui/app/directives/navbar/namespace.html
cdap-ui/app/index.html

Add text "Copyright". 
Change namespace text to "No other namespaces" and removed styling, as it should be styled in CSS, not hard-coded.

Two UI text changes

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Filter.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Scan.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/BufferingTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/FuzzyRowFilter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTable.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/BufferingTableTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableTest.java

This PR is for discussing mergint MetricsTable and Table classes hierarchies. At minimum, it lacks unit-tests for the added scan method.
UPDATE: was finished up

Adding Table.scan(Scan)

---

cdap-ui/app/features/flows/flows.less
cdap-ui/app/features/flows/templates/tabs/flowlets.html
cdap-ui/app/features/flows/templates/tabs/runs.html

Removes the use of angular bootstrap accordion and uses a simple panel-group to achieve the same thing.
TODO: 
- Use the same in other program types too.
- Enable injecting through streams in flows.

Ditches angular bootstrap accordion and uses a panel group in simpler way

---

cdap-ui/app/features/admin/admin.less
cdap-ui/app/features/admin/controllers/PreferencesController.js
cdap-ui/app/features/admin/templates/preferences.html

change styling of system preferences

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTable.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTableTest.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/upgrade/MetricsDataMigrator.java

Cleaning up MetricsTable interface makes it easier to implement (CDAP-2047) and later integrate into Table (CDAP-1193)

CDAP-2047: First step: Cleanup MetricsTable interface of all unused methods

---

cdap-ui/app/directives/log-viewer/log-viewer.less

fix Log Viewer styling for better readability

---

cdap-ui/pom.xml

* Remove - dist, node and node_modules directories

Clean up cdap-ui build directories on mvn clean

---

cdap-ui/app/features/admin/routes.js

force namespace list reload after creating a new namespace

reload namespace list after creating namespace

---

cdap-ui/app/features/flows/controllers/detail-ctrl.js
cdap-ui/app/features/flows/controllers/tabs/runs/tabs/status-ctrl.js

fix to reload current state when starting a new run.
ToDo:
- research ways to achieve this without wrapping $state.go in a $timeout

reload current state when starting and stopping run

---

cdap-api/src/main/java/co/cask/cdap/api/Predicate.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/AbstractWorkflow.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConditionConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConditionNode.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowNodeType.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConditionConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowForkConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/WorkflowConditionAdder.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowNodeCodec.java

Jira: https://issues.cask.co/browse/CDAP-1928
This PR contains the implementation of the interface for Condition node in the Workflow. 
Following example illustrates the API for the condition:
```java
@Override
public void configure() {
setName("PurchaseHistoryWorkflow");
setDescription("PurchaseHistoryWorkflow description");
addMapReduce("PurchaseHistoryBuilder");
condition(new MyPredicate())
.addMapReduce("UserProfileBuilder")
.otherwise()
.addMapReduce("CustomBuilder")
.end();
}
```
where `MyPredicate` is the public class which implements the `Predicate` interface as
```java
public static class MyPredicate implements Predicate<Map<String, String>> {
@Override
public boolean apply(@Nullable Map<String, String> input) {
if (input != null && input.containsKey("someKey")) {
return true;
} …
```

CDAP-1928 Interface for the Condition node in the Workflow.

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogLine.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java
cdap-ui/app/features/admin/controllers/ServiceLogController.js
cdap-ui/app/features/flows/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/mapreduce/controllers/tabs/log-ctrl.js
cdap-ui/app/features/mapreduce/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/services/controllers/tabs/logs-ctrl.js
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandlerV2.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogReaderCallback.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/AvroFileReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/DistributedLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/LogEvent.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/LogOffset.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/LogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/StandaloneLogReader.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LoggingTester.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestResilientLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java

This will allow us to move between Kafka source and HDFS source while querying for logs.
JIRA https://issues.cask.co/browse/CDAP-2053

Refactoring to allow passing both Kafka offset and log event time as LogOffset

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MockETLHandler.java

Real source, sink, transform. For UI testing.

Some real stage names for UI testing

---

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLMapReduceTest.java

Bamboo : http://builds.cask.co/browse/CDAP-DT11

Use TypeToken isAssignableFrom check to validate connections between ETL Stages

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/BasicFlowletContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/procedure/BasicProcedureContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/BasicServiceWorkerContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/BasicSparkContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceHttpServer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/worker/BasicWorkerContext.java
cdap-common/src/main/java/co/cask/cdap/common/logging/ApplicationLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/FlowletLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/GenericLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/MapReduceLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/ProcedureLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/SparkLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/UserServiceLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/WorkerLoggingContext.java
cdap-watchdog/src/test/java/co/cask/cdap/common/logging/logback/TestLoggingContext.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LoggingTester.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestResilientLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/serialize/LoggingEventSerializerTest.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/serialize/LoggingEventTest.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/write/LogCleanupTest.java

Adding runId and instanceId to logging context when publishing logs. Also removed some unnecessary code.
JIRA - https://issues.cask.co/browse/CDAP-2052

Publish runId and instanceId in log messages

---

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/Tweet.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/TwitterStreamSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/TwitterStreamSourceTest.java
pom.xml

* Adds twitter real time source to ingest data from twitterStream source. Uses Twitter4j libraries.

Add Twitter source

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/CubeDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/CubeDatasetDefinition.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultAggregation.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/MetricsTableOnTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/CubeModule.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/AbstractCubeTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/CubeDatasetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/MetricsTableOnTableTest.java

Initial CubeDataset implementation based on existing Cube APIs (no changes there).

CDAP-1961: Initial cube dataset implementation

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/Cube.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/CubeDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultCube.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/MetricsTableOnTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTable.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/CubeDatasetTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/MetricsTableOnTableTest.java

To be consistent with Dataset APIs

CDAP-1961: Remove Exception from Cube and related classes APIs

---

cdap-api/src/main/java/co/cask/cdap/api/templates/plugins/PluginVersion.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/plugins/PluginVersionTest.java

This is the first PR for CDAP-1917 by adding a new class in API to represent version information for template plugin.

(CDAP-1917) Added classes for representing plugin version.

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/MapReduceCounterCollectionService.java

escape dots with tilde and replace it with dots before adding to metric system
Jira : https://issues.cask.co/browse/CDAP-2075

mapreduce metrics context fix, 

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/Cube.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultCube.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/EntityTable.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTable.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/CubeDatasetTest.java

CDAP-1961: Cube to extend Dataset interface

---

cdap-ui/app/features/admin/templates/namespace/app-metadata.html
cdap-ui/app/features/admin/templates/namespace/apps.html
cdap-ui/app/features/apps/templates/list.html

Change data binding to bind once

[CDAP-2029] UI should display the version of the application

---

cdap-docs/examples-manual/build.sh

and using the downloaded version rather than using a local copy.

Fix documentation build by downloading images from Github

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLMapReduceTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/BatchReadableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/TableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/RowToStructuredRecordTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/common/MockEmitter.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/MockTransformContext.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/RowToStructuredRecordTransformTest.java

a BatchReadableSource that the others extend so that there is a
catch-all for advanced users.

CDAP-2088 Adding a TableSource for the ETL template. Also adding

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HTableNameConverter.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/util/hbase/AbstractHBaseTableUtilTest.java

JIRA - https://issues.cask.co/browse/CDAP-2110

CDAP-2110 Fix check to allow underscore in namespace names.

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AbstractMonitorHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/MonitorHandler.java
cdap-client-tests/src/test/java/co/cask/cdap/client/MonitorClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/MonitorClient.java
cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractDistributedMasterServiceManager.java
cdap-common/src/main/java/co/cask/cdap/common/twill/AbstractInMemoryMasterServiceManager.java
cdap-common/src/main/java/co/cask/cdap/common/twill/MasterServiceManager.java
cdap-proto/src/main/java/co/cask/cdap/proto/Containers.java
cdap-proto/src/main/java/co/cask/cdap/proto/SystemServiceLiveInfo.java

https://issues.cask.co/browse/CDAP-2086
http://builds.cask.co/browse/CDAP-DUT1437

CDAP-2086: System service live-info

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTests.java

Bamboo : http://builds.cask.co/browse/CDAP-DUT1375-10
JIRA : https://issues.cask.co/browse/CDAP-2112 [Partial solution since automatic deletion of app is not addressed by this PR]

CDAP-2112 Allow deleting Template cdap app when all adapters of that template type are deleted

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetServiceModules.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/StaticDatasetFramework.java

Continuing from https://github.com/caskdata/cdap/pull/1924

Review comments

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/LoadStreamCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/util/table/AltStyleTableRenderer.java
cdap-cli/src/main/java/co/cask/cdap/cli/util/table/CsvTableRenderer.java
cdap-cli/src/main/java/co/cask/cdap/cli/util/table/Table.java
cdap-cli/src/test/java/co/cask/cdap/cli/util/table/TableRendererTest.java

https://issues.cask.co/browse/CDAP-2076
http://builds.cask.co/browse/CDAP-DUT1439

CDAP-2076: Fix CLI table renderers for nulls

---

cdap-cli/src/main/java/co/cask/cdap/cli/util/InstanceURIParser.java
cdap-cli/src/test/java/co/cask/cdap/cli/util/InstanceURIParserTest.java

https://issues.cask.co/browse/CDAP-1973
http://builds.cask.co/browse/CDAP-DUT1452

CDAP-1973: Fix InstanceURIParser for URIs with trailing slash

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/StructuredRecordSerializer.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ScriptFilterTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ScriptFilterTransformTest.java

a javascript snippet that determines whether or not a record
should be filtered or not.

CDAP-2069 adding a filter transform that lets the user provide

---

cdap-ui/app/features/admin/routes.js
cdap-ui/app/features/dashboard/routes.js
cdap-ui/app/features/streams/controllers/detail-ctrl.js
cdap-ui/app/features/streams/routes.js
cdap-ui/app/features/streams/templates/detail.html

Adding actions under stream:
- Edit Properties
- Truncate

add actions under stream

---

cdap-ui/app/features/etlapps/controllers/create-ctrl.js
cdap-ui/app/features/overview/controllers/overview-ctrl.js
cdap-ui/app/features/overview/templates/data-apps.html
cdap-ui/app/features/workflows/controllers/tabs/schedule-ctrl.js

Add buttons to Dev Screen:
- Add ETL Apps
- Add Stream
Show Total number of Data and Apps
Defaulting First Accordion to open

Dev Screen Fixes + Accordion fixes

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-common/src/main/java/co/cask/cdap/common/conf/Configuration.java
cdap-common/src/main/java/co/cask/cdap/gateway/handlers/CommonHandlers.java
cdap-common/src/main/java/co/cask/cdap/gateway/handlers/ConfigHandler.java
cdap-common/src/main/java/co/cask/cdap/gateway/handlers/ConfigService.java
cdap-common/src/test/java/co/cask/cdap/gateway/handlers/ConfigServiceTest.java

https://issues.cask.co/browse/CDAP-1897
http://builds.cask.co/browse/CDAP-DUT1295

CDAP-1897: Show config entry source in JSON for ConfigHandler

---

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java

https://issues.cask.co/browse/CDAP-2021
http://builds.cask.co/browse/CDAP-DUT1453

CDAP-2021: Add v3 routing rule for system service logs

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/AbstractCubeHttpHandler.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/CubeFact.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/Measurement.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultAggregation.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultCube.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/Fact.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTable.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/AbstractCubeTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTableTest.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestAppWithCube.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java

* CubeFact to contain multiple measurements
* CubeFact has nicer API (and closer to Table ops) to construct

CDAP-1961: Cube dataset APIs minor improvements

---

cdap-ui/app/directives/epoch/charts.js
cdap-ui/app/directives/metric-picker/metric-picker.html
cdap-ui/app/directives/metric-picker/metric-picker.js
cdap-ui/app/directives/metric-picker/metric-picker.less
cdap-ui/app/features/dashboard/controllers/addwdgt-ctrl.js
cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/dashboard/templates/partials/addwdgt.html
cdap-ui/app/features/dashboard/templates/partials/wdgt-head.html
cdap-ui/app/styles/themes/cdap/theme.less

This lets you choose multiple metrics when creating a widget. It uses the new metrics batch endpoint to query for all the metrics of the chart in one http request.
http://g.recordit.co/E6lzHDiwK6.gif
Not implemented (yet):
There is no legend/key (identification for which color is which metric) currently.
You can not modify the list of metrics for the chart after creating it.

Multiple metrics per chart.

---

cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BatchETLDBAdapterTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/resources/logback-test.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/DBSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/DBRecord.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/ETLDBInputFormat.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/Properties.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/DBRecordToStructuredRecordTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToPutTransform.java
cdap-app-templates/cdap-etl/pom.xml

Added RDBMS Batch Source
Mostly done apart from the following:
1. Testing on a cluster - DONE
2. Test with a secure database (Do username, password need to be passed separately)
Want to get the review started as I work on the above.
Outside the scope of this PR, but we probably need to think of these things nonetheless:
1. Importing multiple tables
2. Packaging driver class jars
Jira: [CDAP-2064](https://issues.cask.co/browse/CDAP-2064)
Build: https://builds.cask.co/browse/CDAP-DUT1424

[CDAP-2064] Added RDBMS Batch source

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/files/preseed.cfg
cdap-distributions/src/packer/scripts/apt-cleanup.sh
cdap-distributions/src/packer/scripts/apt-setup.sh
cdap-distributions/src/packer/scripts/cookbook-dir.sh
cdap-distributions/src/packer/scripts/cookbook-setup.sh
cdap-distributions/src/packer/scripts/firefox.sh
cdap-distributions/src/packer/scripts/fluxbox.sh
cdap-distributions/src/packer/scripts/random-root-password.sh
cdap-distributions/src/packer/scripts/remove-chef.sh
cdap-distributions/src/packer/scripts/slim.sh
cdap-distributions/src/packer/scripts/vbox-guest-additions.sh
cdap-distributions/src/packer/scripts/xorg.sh
cdap-distributions/src/packer/scripts/zero-disk.sh

- Import preseed [file](https://help.ubuntu.com/12.04/installation-guide/example-preseed.txt) from Ubuntu and configure
- JSON template for [packer](http://packer.io)
- Small scripts for setting up the VM (X.org, Firefox, fluxbox, CDAP SDK, etc)

CDAP-2030 Automate VM build

---

cdap-ui/app/features/datasets/controllers/detail-ctrl.js
cdap-ui/app/features/datasets/routes.js
cdap-ui/app/features/datasets/templates/detail.html

adding truncate to dataset

---

cdap-distributions/src/packer/files/preseed.cfg
cdap-distributions/src/packer/scripts/apt-cleanup.sh
cdap-distributions/src/packer/scripts/apt-setup.sh
cdap-distributions/src/packer/scripts/cookbook-dir.sh
cdap-distributions/src/packer/scripts/cookbook-setup.sh
cdap-distributions/src/packer/scripts/firefox.sh
cdap-distributions/src/packer/scripts/fluxbox.sh
cdap-distributions/src/packer/scripts/random-root-password.sh
cdap-distributions/src/packer/scripts/remove-chef.sh
cdap-distributions/src/packer/scripts/slim.sh
cdap-distributions/src/packer/scripts/vbox-guest-additions.sh
cdap-distributions/src/packer/scripts/xorg.sh
cdap-distributions/src/packer/scripts/zero-disk.sh

I broke the RAT check! Oh noes! Fixing. :smile:

Add Cask headers to shell scripts

---

cdap-adapters/src/main/java/co/cask/cdap/conversion/app/StreamConversionAdapter.java
cdap-api/src/main/java/co/cask/cdap/api/templates/ApplicationTemplate.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationTemplateManager.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ApplicationTemplateVerificationStage.java
cdap-app-fabric/src/test/java/co/cask/cdap/DataTemplate.java
cdap-app-fabric/src/test/java/co/cask/cdap/DummyBatchTemplate.java
cdap-app-fabric/src/test/java/co/cask/cdap/DummyWorkerTemplate.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTests.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterServiceTests.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java
cdap-client-tests/src/main/java/co/cask/cdap/client/app/TemplateApp.java

CDAP-2142 : ApplicationTemplate implements Application.
Application Template can now add datasets (and streams).

Application Template implements Application

---

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java

fix router rules for /v3/system/services/streams/logs; add unit test

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceClassLoader.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/LocalApplicationManagerTest.java
cdap-common/src/main/java/co/cask/cdap/common/lang/CombineClassLoader.java
cdap-common/src/main/java/co/cask/cdap/common/lang/PackageFilterClassLoader.java
cdap-common/src/main/java/co/cask/cdap/common/lang/ProgramClassLoader.java
cdap-common/src/main/java/co/cask/cdap/internal/test/AppJarHelper.java
cdap-common/src/test/java/co/cask/cdap/common/lang/ClassLoaderTest.java

This is to prepare for the ClassLoading needs for app template plugin class loading.
- Added a PackageFilterClassLoader
- Generalize MapReduceClassLoader to CombineClassLoader

(CDAP-1917) ClassLoader enhancement

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Does the necessary work needed to upgrade Adapters from 2.8 and 3.0 by removing stream-conversion adapter.
There are two places from where the entries need to be removed. 
1. DatasetBasedTimeScheduleStore: Stores all the schedules (triggers) and jobs. 
2. Store (App MetaData Store): Stores the meta data of the adapter.
So, we delete these entries for the stream-conversion adapter across all namespaces.
Build: http://builds.cask.co/browse/CDAP-DT20-1

CDAP-2133: Upgrade tool deletes stream conversion adapters

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/KeyValueListParser.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ProjectionTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ProjectionTransformTest.java

dropping fields, renaming fields, and casting types.

CDAP-2067 projection transform for the etl template, which allows

---

README.md

Copy text from documentation overview to README to remove references to abstraction.

Clean up of README

---

cdap-ui/Gulpfile.js
cdap-ui/app/main.js
cdap-ui/app/services/data/datasource.js
cdap-ui/bower.json
cdap-ui/package.json
cdap-ui/server/aggregator.js

Creating PR for @anwar6953 
One can now specify an interval from FE to the backend NodeJS server the frequency with which the nodejs server can poll. 
Added a new node-uuid to generate a unique request/response ID for the FE. Added the node-uuid to bower.json & Gulpfile. Also, included the same in package.json. 
*  [TESTED] Chrome
*  [TESTED] Safari
*  [TESTED] FireFox

Variable Frequency Polling from FE on WebSocket. 

---

cdap-common/src/main/resources/cdap-default.xml

Removed the remnant configuration from accounts when we had sandbox.

Removing the configurations that are no more used.

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BatchETLDBAdapterTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLMapReduceTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLStreamConversionTest.java

give all batch etl configs a schedule since there is now a check

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/config/ETLBatchConfig.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLRealtimeTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/config/ETLRealtimeConfig.java

Bamboo : http://builds.cask.co/browse/CDAP-DT35

Make sure that the ETLRealtimeTemplate gets a non-zero value for instances

---

cdap-ui/app/directives/instance-control/instance-control.html
cdap-ui/app/directives/instance-control/instance-control.less

Change instance controller styling to be the same as flowlets

changing instance controller for services to be the same as flowlets

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLBatchTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToCubeFactTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToCubeFactTransformTest.java

Missed a piece: adding sink and transform to ETLBatchTemplate registry.
Also: fixed bug with passing ms instead of sec

CDAP-1966: dding cube sink and transform to ETLBatchTemplate

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryAdapterConfigurator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/main/java/co/cask/cdap/templates/AdapterSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/templates/DefaultAdapterConfigurer.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java

Build: http://builds.cask.co/browse/CDAP-DT27-1

Add ProgramName and Type in AdapterSpecification

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/StringPartitioner.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/KafkaLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/AbstractKafkaLogProcessor.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckPointWriter.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/Checkpoint.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointManager.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointingLogFileWriter.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/KafkaLogProcessor.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/KafkaLogWriterPlugin.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogMetricsPlugin.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaver.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java

Also contains minor refactoring in https://github.com/caskdata/cdap/commit/b7ed0b8a8ed604abc97d00319318ee01ae2aa7f9. It may be easier to review the commits separately.
JIRA https://issues.cask.co/browse/CDAP-2053

Introducing Checkpoint class to represent checkpoints

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointManager.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/CheckpointManagerFactory.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/KafkaLogWriterPlugin.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogMetricsPlugin.java

Same PR as https://github.com/caskdata/cdap/pull/2195

Using checkpoint manager factory to create checkpoint manager.

---

cdap-ui/Gulpfile.js
cdap-ui/app/main.js
cdap-ui/bower.json
cdap-ui/package.json
cdap-ui/server/express.js

This cookie is needed even in non secured or logged in mode to avoid to storing preferences of the user efficiently.

Adding support for bcookie - Browser cookie

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BatchETLDBAdapterTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/TableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/RealtimeTableSink.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLRealtimeTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/templates/etl/realtime/ETLWorkerTest.java

Adds Realtime Table Sink.
Jira: [CDAP-2068](https://issues.cask.co/browse/CDAP-2068)
Build: http://builds.cask.co/browse/CDAP-DT44-4

[CDAP-2068] Added realtime Table Sink

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamWriter.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/StreamWriterFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/LocalStreamWriter.java

http://builds.cask.co/browse/CDAP-DUT1587
Addresses unaddressed comments from https://github.com/caskdata/cdap/pull/2188

Improve stream usage registry integration

---

cdap-common/src/main/resources/cdap-default.xml
cdap-standalone/src/main/resources/cdap-site.xml

Dir to place template jars is plugins

---

cdap-ui/Gulpfile.js
cdap-ui/app/directives/c3/charts.js
cdap-ui/app/features/dashboard/controllers/addwdgt-ctrl.js
cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/dashboard/templates/userdashboard.html
cdap-ui/app/features/dashboard/templates/widgets/c3-bar.html
cdap-ui/app/features/dashboard/templates/widgets/c3-donut.html
cdap-ui/app/features/dashboard/templates/widgets/c3-line.html
cdap-ui/app/features/dashboard/templates/widgets/c3-pie.html
cdap-ui/app/features/dashboard/templates/widgets/json.html
cdap-ui/bower.json

Removed debug chart type. Will be replaced by Table chart type in a separate PR.
Click on the gif for a potentially larger view:

c3 Charting Integration - Line, Bar (stacked), Pie. Can easily add more.

---

cdap-standalone/bin/cdap.sh

I didn't commit the change before merging. My bad. Minor change.

Minor fix on my previous fix for removing old UI

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java

adapter-id is passed as query parameter to the handlers.
If the request is not for adapter logs the adapter-id is null

CDAP-2107 Add next and prev log handler for Adapter logs

---

cdap-standalone/src/main/java/co/cask/cdap/UserInterfaceService.java

There was issue with running standalone from IDE due to the path to UI. So, in this PR this issue for resolved. 
Test

Fixed issue with running from IDE

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnerModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java

``StreamWriterFactory`` binding was missing from ``AbstractTwillRunnable``
Jira: [CDAP-2238](https://issues.cask.co/browse/CDAP-2238)
Build: https://builds.cask.co/browse/CDAP-DUT1593

[CDAP-2238] Add StreamWriterFactory binding to AbstractTwillRunnable

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppFabricDataHttpHandler.java

http://builds.cask.co/browse/CDAP-DUT1602

Fix HTTP endpoint for listing streams

---

cdap-standalone/src/main/java/co/cask/cdap/UserInterfaceService.java
cdap-ui/app/features/streams/controllers/detail-ctrl.js
cdap-ui/app/features/streams/streams.less
cdap-ui/app/features/streams/templates/detail.html

Send Events to Stream without Flows

---

cdap-ui/app/features/admin/controllers/NamespaceDatasetMetadataController.js
cdap-ui/app/features/admin/routes.js
cdap-ui/app/features/admin/templates/namespace/dataset-metadata.html
cdap-ui/app/features/admin/templates/namespace/datasets.html

Add ability to delete a dataset

add functionality to delete dataset

---

cdap-api/src/main/java/co/cask/cdap/api/templates/AdapterContext.java
cdap-api/src/main/java/co/cask/cdap/api/templates/AdapterSpecification.java
cdap-api/src/main/java/co/cask/cdap/api/templates/ApplicationTemplate.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryAdapterConfigurator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/adapter/AdapterVerificationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/templates/AdapterDefinition.java
cdap-app-fabric/src/main/java/co/cask/cdap/templates/DefaultAdapterConfigurer.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/AdapterConfig.java

- Define the AdapterSpecification interface in cdap-api
- Make AdapterDefinition to implement AdapterSpecification
- Also piggy back to fix a small bug in DefaultAdapterConfigurer for wrong check on plugin usage.

Expose AdapterSpecification through AdapterContext.

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterServiceTest.java

* Fix randomness in test failure by testing with retries.

Check Runrecord with retries

---

BUILD.md
LICENSE.txt
README.md
cdap-standalone/src/dist/README

This fixes minor errors in the READMEs, both in the source, in the Standalone, and on the web at GitHub.

Fix READMEs

---

cdap-ui/app/features/admin/controllers/PreferencesController.js
cdap-ui/app/features/admin/routes.js
cdap-ui/app/features/admin/templates/namespace/app-metadata.html
cdap-ui/app/features/admin/templates/partials/app-dd.html
cdap-ui/app/features/admin/templates/preferences.html
cdap-ui/app/features/apps/templates/detail.html

Application Level Preferences
^ Link to the admin page preferences

add Application level preferences

---

cdap-app-fabric/src/main/java/co/cask/cdap/archive/ArchiveBundler.java

- Copy all existing manifest from the user JAR into program jar
- It is needed for adapter to run correctly since it relies on the Export-Package attribute

Fix program archive creation

---

cdap-ui/app/features/admin/controllers/DatasetsController.js
cdap-ui/app/features/data/list-ctrl.js
cdap-ui/app/features/datasets/controllers/tabs/metadata-ctrl.js
cdap-ui/app/features/datasets/controllers/tabs/status-ctrl.js
cdap-ui/app/features/datasets/datasets.less
cdap-ui/app/features/datasets/templates/detail.html
cdap-ui/app/features/datasets/templates/tabs/metadata.html
cdap-ui/app/features/datasets/templates/tabs/status.html
cdap-ui/app/features/overview/controllers/overview-ctrl.js
cdap-ui/app/features/overview/templates/data-apps.html
cdap-ui/app/features/streams/controllers/tabs/metadata-ctrl.js
cdap-ui/app/features/streams/streams.less
cdap-ui/app/features/streams/templates/detail.html
cdap-ui/app/features/streams/templates/tabs/metadata.html

- Fix bug where type stream is no longer returned by the backend
- Add Metadata page on Data detail
- Add Status page on Dataset

Dataset Status View, fix Streams Type bug, Data Metadata tab

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/ListStreamsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/completer/element/StreamIdCompleter.java
cdap-client/src/main/java/co/cask/cdap/client/StreamClient.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java

http://builds.cask.co/browse/CDAP-DUT1594

Fix StreamClient to adapt to /streams change

---

cdap-ui/app/directives/c3/charts.js
cdap-ui/app/features/dashboard/controllers/addwdgt-ctrl.js
cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/dashboard/templates/widgets/table.html

Introduce Table Widget.
Also decrease number of widgets per row to 2 from 3.

Table Widget - Metrics

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/LogAppenderInitializer.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/ChunkedLogReaderCallback.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogReaderCallback.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/kafka/KafkaConsumer.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/AvroFileReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/Callback.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/DistributedLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/FileLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/KafkaLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/LogOffset.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/KafkaLogWriterPlugin.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LoggingTester.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestDistributedLogReader.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverTest.java

JIRA https://issues.cask.co/browse/CDAP-2053

Adding ability to move between Kafka source and file source for log queries

---

cdap-ui/app/features/streams/streams.less

Fix unclosed bracket in stream.less

Gulp would not build

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/DistributedLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/FileLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/KafkaLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/LogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/ReadRange.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LoggingTester.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestDistributedLogReader.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestResilientLogging.java
cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java

Same as PR https://github.com/caskdata/cdap/pull/2247

Re-factor to allow run id time ranges

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunner.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java

Build: http://builds.cask.co/browse/CDAP-DT42-1

add adapter name in worker context for metric and logging

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/PluginTest.java

- Help configuring external plugin easier.

Enhancement to allow external plugin to omit the properties field

---

cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/StreamSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/TwitterSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/realtime/sources/TwitterSourceTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/pom.xml

Changes to pom files and modified Twitter Source, Stream Sink to use plugins framework. Tested manually.

Sample Plugin Source and Sink using Plugin support

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/ProgramRunnableResourceReporter.java

JIRA : https://issues.cask.co/browse/CDAP-2252

bugfix : add namespace to ProgramRunnableResourceReporter metrics context

---

cdap-ui/app/styles/themes/cdap/theme.less

change width to 100% for dashboard state

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamWriter.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/StreamWriterFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/DynamicMapReduceContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/ConsumerSupplier.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/AbstractSparkContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceWithPartitionedTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/spark/SparkProgramRunnerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/runtime/MultiConsumerTest.java
cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/NoopStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/dataset/DatasetInstantiator.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetContext.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/InMemoryDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/StaticDatasetFramework.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/StreamAdmin.java
cdap-notifications/src/main/java/co/cask/cdap/notifications/service/BasicNotificationContext.java
cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultApplicationManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/LocalStreamWriter.java

https://issues.cask.co/browse/CDAP-2237
http://builds.cask.co/browse/CDAP-RBT215
Reopened https://github.com/caskdata/cdap/pull/2241 against release/3.0

CDAP-2237: Adapter<->{Dataset,Stream} integration for usage registry

---

cdap-ui/app/features/admin/templates/namespace/app-metadata.html

Add programs list under Apps Metadata page

add programs list on app metadata page

---

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/StreamSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/TwitterSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/IdentityTransform.java

Build : http://builds.cask.co/browse/CDAP-RT0-2

Converting Identity Transform

---

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java

http://builds.cask.co/browse/CDAP-RBT221

Add routing rule for dataset usage

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java

Adding filter log test for adapter to bigger change going through @poornachandra PR to not have conflicts.

Add filter log test for adapters

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/StreamBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/ETLUtils.java

Jira: [CDAP-2265](https://issues.cask.co/browse/CDAP-2265)
Build: http://builds.cask.co/browse/CDAP-RT1
Tested that the plugin gets recognized. Need a batch sink to test end-to-end. Will do that after I convert DBSink or something else.

[CDAP-2265] Convert StreamBatchSource into a plugin

---

cdap-master/pom.xml

* Add maven dependency plugin to package dependencies in master package

Add Maven dependency plugin

---

cdap-ui/app/features/dashboard/controllers/dashboard-ctrl.js
cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/dashboard/model/dashboards-model.js
cdap-ui/app/features/dashboard/style.less
cdap-ui/app/features/dashboard/templates/partials/tab-dd.html
cdap-ui/app/features/dashboard/templates/userdashboard.html

Multiple Columns in Dashboard

---

cdap-ui/app/directives/data-list/data-list.html
cdap-ui/app/directives/data-list/data-list.js
cdap-ui/app/features/apps/templates/detail.html
cdap-ui/app/features/apps/templates/tabs/data.html
cdap-ui/app/features/flows/routes.js
cdap-ui/app/features/flows/templates/detail.html
cdap-ui/app/features/flows/templates/tabs/data.html
cdap-ui/app/features/mapreduce/routes.js
cdap-ui/app/features/mapreduce/templates/detail.html
cdap-ui/app/features/mapreduce/templates/tabs/data.html
cdap-ui/app/features/services/templates/detail.html
cdap-ui/app/features/services/templates/tabs/data.html

add dataset and streams list under apps and programs

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/FormattedLogEvent.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/AppMdsTableUtil.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/AppMetadataStore.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/ProgramStore.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/read/ReadRange.java
pom.xml

JIRA - https://issues.cask.co/browse/CDAP-2053

Using runid time range to limit log retrival

---

cdap-ui/app/features/mapreduce/controllers/tabs/runs/tabs/log-ctrl.js

Change logs for mapreduce to use runid

CDAP-1347: change mapreduce logs to be using runid

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/StreamBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/Properties.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/StreamSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/TestSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ScriptFilterTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ScriptFilterTransformTest.java

Jira: 
[CDAP-2285](https://issues.cask.co/browse/CDAP-2285)
[CDAP-2217](https://issues.cask.co/browse/CDAP-2217)
Build:
http://builds.cask.co/browse/CDAP-RT5

Ported TestSource and ScriptFilterTransform to plugin framework. Standardized on 'body' as the field name for stream source and sink

---

cdap-ui/app/directives/duration-picker/duration-picker.html
cdap-ui/app/directives/duration-picker/duration-picker.js
cdap-ui/app/features/dashboard/controllers/dashboard-ctrl.js
cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/dashboard/style.less
cdap-ui/app/features/dashboard/templates/userdashboard.html
cdap-ui/app/features/dashboard/templates/widgets/table.html
cdap-ui/app/features/spark/templates/detail.html

A couple of styling changes are still needed, but otherwise its good to go.

Feature ui/dashboard polling frequency

---

cdap-ui/app/features/admin/templates/namespace/app-metadata.html
cdap-ui/app/features/admin/templates/system/service-detail.html
cdap-ui/app/features/apps/templates/detail.html
cdap-ui/app/features/data/list.html
cdap-ui/app/features/datasets/routes.js
cdap-ui/app/features/datasets/templates/list.html
cdap-ui/app/features/etlapps/templates/list.html
cdap-ui/app/features/flows/templates/detail.html
cdap-ui/app/features/flows/templates/tabs/runs/flowlets/detail.html
cdap-ui/app/features/mapreduce/templates/detail.html
cdap-ui/app/features/services/templates/detail.html
cdap-ui/app/features/spark/templates/detail.html
cdap-ui/app/features/streams/routes.js
cdap-ui/app/features/streams/templates/list.html
cdap-ui/app/features/workflows/templates/detail.html

Remove capitalizations on title for Programs, Apps, Dataset, Streams

remove capitalization for apps dataset streams programs

---

cdap-ui/app/directives/widget-container/widget-container.js
cdap-ui/app/features/etlapps/etlapps.less
cdap-ui/app/features/etlapps/templates/create.html
cdap-ui/app/features/etlapps/templates/create/tabs/sinkPropertyEdit.html
cdap-ui/app/features/etlapps/templates/create/tabs/sourcePropertyEdit.html

Removes Save/Close buttons from Source/Sink Property views

Removes Save/Close buttons from Source/Sink Property views

---

cdap-ui/app/features/admin/templates/overview.html

Removing systemwide security on Admin overview page.

remove systemwide security on enterprise

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sources/TwitterSource.java

http://builds.cask.co/browse/CDAP-DT60
https://issues.cask.co/browse/CDAP-2290

Disable twitter4j logs

---

cdap-api/src/main/java/co/cask/cdap/internal/workflow/ProgramWorkflowAction.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseHistoryWorkflow.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/WorkflowLoggingContext.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java

Jira: https://issues.cask.co/browse/CDAP-1089

Added logging context for the Workflow.

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java

JIRA : https://issues.cask.co/browse/CDAP-2291
Bamboo : http://builds.cask.co/browse/CDAP-RBT232-1

CDAP-2291 return null if RunRecord is not present

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ScriptTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ScriptTransformTest.java

allow arbitrary transformations.

CDAP-2268 add a general javascript transform as a catch-all to

---

cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/src/main/java/Source.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/pom.xml
cdap-app-templates/cdap-etl/pom.xml

Archetype for ETL sources and sinks and transforms 
Upcoming PRs
Tests:
a> Install archetype locally
`mvn clean install -DskipTests -P templates`
b> Create realtime source archetype
`mvn -o archetype:generate -DarchetypeRepository=local -DarchetypeGroupId=co.cask.cdap -DarchetypeArtifactId=cdap-etl-realtime-source-archetype -DarchetypeVersion=3.0.0-SNAPSHOT`

Add Realtime source archetype

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/AbstractSchedulerService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/Scheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/StreamSizeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/TimeScheduler.java
cdap-app-fabric/src/main/java/co/cask/cdap/test/internal/guice/AppFabricTestModule.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseApp.java
cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Jira - https://issues.cask.co/browse/CDAP-2077

Added implementation of the previous runtime api for the Workflow.

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BatchETLDBAdapterTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLMapReduceTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/BatchCubeSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/KVTableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/TableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/TimePartitionedFileSetDatasetAvroSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/KVTableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/TableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/Properties.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/RealtimeCubeSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/RealtimeTableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/ProjectionTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/transforms/StructuredRecordToGenericRecordTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/templates/etl/transforms/ProjectionTransformTest.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/test/java/co/cask/cdap/templates/etl/realtime/ETLWorkerTest.java

This ports the following:
1. TimePartitionedFileSetDatasetAvroSink (All ready reviewed here: https://github.com/caskdata/cdap/pull/2271 skip reviewing it if you want to.
2. KVTableSink: Partially reviewed here: https://github.com/caskdata/cdap/pull/2281 Have fixed the comments.
3. TableSink
4. TableSource
5. KVTableSource
6. RealtimeTableSink
7. RealtimeCubeSink
8. ProjectionTransform
9. BatchCubeSink
10. StructuredRecordToGenericRecordTransform
I am currently testing all of these manually.

Porting various source, sink and transforms to use Plugin Framework

---

cdap-ui/app/features/admin/controllers/StreamPropertiesController.js
cdap-ui/app/features/admin/templates/namespace/streamproperties.html

fix bugs with set stream properties.

[CDAP-2240] Set stream properties fails in UI

---

cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/src/main/java/Sink.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/src/main/java/Source.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/src/main/java/Sink.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/src/main/java/Transform.java
cdap-app-templates/cdap-etl/cdap-etl-archetypes/pom.xml

Tests
`mvn -o archetype:generate -DarchetypeRepository=local -DarchetypeGroupId=co.cask.cdap -DarchetypeArtifactId=cdap-etl-realtime-sink-archetype -DarchetypeVersion=3.0.0-SNAPSHOT`
`mvn -o archetype:generate -DarchetypeRepository=local -DarchetypeGroupId=co.cask.cdap -DarchetypeArtifactId=cdap-etl-transform-archetype -DarchetypeVersion=3.0.0-SNAPSHOT`
`mvn -o archetype:generate -DarchetypeRepository=local -DarchetypeGroupId=co.cask.cdap -DarchetypeArtifactId=cdap-etl-batch-source-archetype -DarchetypeVersion=3.0.0-SNAPSHOT`
`mvn -o archetype:generate -DarchetypeRepository=local -DarchetypeGroupId=co.cask.cdap -DarchetypeArtifactId=cdap-etl-batch-sink-archetype -DarchetypeVersion=3.0.0-SNAPSHOT`

Archetypes for ETL 

---

cdap-ui/app/features/adapters/controllers/list-ctrl.js
cdap-ui/app/features/adapters/templates/list.html

Opening it against release/3.0 > https://github.com/caskdata/cdap/pull/2363

Fixes delete adapter with a confirm modal

---

cdap-distributions/bin/build_parcel.sh

read scp vars from environment

---

cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/templates/etl/common/ETLTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/DBSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/DBSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/DBConfig.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/ETLDBInputFormat.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/ETLDBOutputFormat.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/JDBCDriverShim.java
cdap-app-templates/cdap-etl/pom.xml

Jira: [CDAP-2286](https://issues.cask.co/browse/CDAP-2286)
Build: http://builds.cask.co/browse/CDAP-RT6

Feature adapter/pluginize db source

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json

This is the same as #2378 but against the `release/3.0` branch.

Split sections into VM-only and common... prep for Docker

---

cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLRealtimeTemplate.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/config/ETLRealtimeConfig.java

JIRA : https://issues.cask.co/browse/CDAP-2267

CDAP-2267 set instances to 1 if null, if user provides then assert > 0

---

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/BatchCubeSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/DBSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sinks/TableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/batch/sources/TableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/realtime/sinks/StreamSink.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLWorker.java

Adding destroy methods to BatchSource/BatchSink; 
BatchSource/BatchSink initialize should get PluginProperties instead of ETLStage
JIRA : https://issues.cask.co/browse/CDAP-2300

CDAP-2300 BatchSource and BatchSink needs destroy method

---

cdap-ui/app/features/workflows/controllers/tabs/schedule-ctrl.js
cdap-ui/app/features/workflows/templates/tabs/schedules.html

add lastrun for time schedule

---

cdap-ui/app/directives/widget-container/widget-factory.js
cdap-ui/app/directives/widget-container/widget-number/widget-number.js

ETL Number Widget

---

cdap-ui/app/directives/widget-container/widget-container.less
cdap-ui/app/directives/widget-container/widget-factory.js

The icon for tooltip will be moved to a different location globally

ETL add datetime widget

---

cdap-ui/app/directives/widget-container/widget-container.less
cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.html
cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.js
cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.less
cdap-ui/app/directives/widget-container/widget-factory.js

ETL CSV Widget

---

cdap-ui/app/features/flows/templates/tabs/runs/run-detail.html
cdap-ui/app/features/mapreduce/templates/tabs/runs/run-detail.html
cdap-ui/app/features/services/templates/tabs/status.html
cdap-ui/app/features/workflows/templates/tabs/runs/run-detail.html
cdap-ui/app/styles/themes/cdap/buttons.less

add colors to program status

---

cdap-ui/app/directives/program-history/program-history.html
cdap-ui/app/directives/program-history/program-history.js
cdap-ui/app/features/flows/templates/tabs/history.html
cdap-ui/app/features/mapreduce/templates/tabs/history.html
cdap-ui/app/features/services/templates/tabs/history.html
cdap-ui/app/features/workflows/templates/tabs/history.html

link history to runid

---

cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/Destroyable.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSink.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/batch/BatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/realtime/RealtimeSink.java
cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/templates/etl/api/realtime/RealtimeSource.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/templates/etl/batch/ETLMapReduce.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/templates/etl/common/Destroyables.java
cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/templates/etl/common/TransformExecutor.java
cdap-app-templates/cdap-etl/cdap-etl-realtime/src/main/java/co/cask/cdap/templates/etl/realtime/ETLWorker.java

- Introduced Destroyable to unify destroy call.

(CDAP-2366) call destroy() appropriately

---

cdap-ui/app/features/adapters/etlapps.less

@astewes Sorry about that. Incorrectly overrode your changes.

Fixes incorrect merge resolution in etlapps styling changes

---

cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/src/main/java/Source.java

* Batch source archetype uses realtime. This PR addresses that.

Fix batch source archetype

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AdapterHttpHandler.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterLifecycleTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-client/src/main/java/co/cask/cdap/client/AdapterClient.java

JIRA : https://issues.cask.co/browse/CDAP-2346

CDAP-2346 status endpoint should return json

---

cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java
cdap-cli/src/main/java/co/cask/cdap/cli/DefaultCompleters.java
cdap-cli/src/main/java/co/cask/cdap/cli/ElementType.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/apptemplate/DescribeAppTemplateCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/apptemplate/GetAppTemplatePluginsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/apptemplate/ListAppTemplatesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ApplicationTemplateCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DefaultCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/completer/element/AppTemplateIdCompleter.java
cdap-client-tests/src/test/java/co/cask/cdap/client/AdapterClientTest.java
cdap-client/src/main/java/co/cask/cdap/client/ApplicationTemplateClient.java

https://issues.cask.co/browse/CDAP-2315
https://builds.cask.co/browse/CDAP-RBT238

CDAP-2315: Applcation Template client and CLI

---

cdap-api/src/main/java/co/cask/cdap/api/templates/AdapterPluginRegistry.java
cdap-api/src/main/java/co/cask/cdap/api/templates/AdapterSpecification.java
cdap-api/src/main/java/co/cask/cdap/api/templates/ApplicationTemplate.java
cdap-proto/src/main/java/co/cask/cdap/proto/AdapterConfig.java
cdap-proto/src/main/java/co/cask/cdap/proto/AdapterDetail.java
cdap-proto/src/main/java/co/cask/cdap/proto/AdapterStatus.java

javadocs to the ApplicationTemplate class.

CDAP-2345 mark all adapter related apis as beta and add some more

---

cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.html
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.less

modify styling for schema widget

---

cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.html
cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.js
cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.less

modify styling for keyvalue widget

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java

- Add the YARN queue only if the queue name is not empty

Do not pass in queue names if they are empty

---

cdap-ui/app/features/adapters/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/adapters/templates/tabs/runs/run-detail.html
cdap-ui/app/features/adapters/templates/tabs/runs/tabs/status.html

fix styling for adapters status view

---

cdap-ui/app/directives/widget-container/widget-factory.js
cdap-ui/app/directives/widget-container/widget-schedule/widget-schedule.html
cdap-ui/app/directives/widget-container/widget-schedule/widget-schedule.js

add schedule widget

---

cdap-distributions/bin/build_parcel.sh

update list of components to include in the parcel (web-app -> ui)

update component list for 3.0 ui

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/AppMetadataStore.java

Also, fixed getting suspended run records for a program.
JIRA - https://issues.cask.co/browse/CDAP-2170

CDAP-2170 Fetch run record for a suspened program

---

cdap-distributions/src/parcel/meta/cdap_env.sh
cdap-distributions/src/parcel/meta/parcel.json

updates the parcel metadata, renaming``web-app`` to ``ui``

rename webapp to ui in parcel

---

BUILD.md
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-sink-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-batch-source-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-sink-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-realtime-source-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-etl-transform-archetype/src/main/resources/archetype-resources/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-archetypes/pom.xml
cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/pom.xml
cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml
cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml

Update version in pom.xml for archetype after the merge

---

cdap-common/src/main/java/co/cask/cdap/common/collect/AllPairCollector.java
cdap-common/src/main/java/co/cask/cdap/common/collect/PairCollector.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/queue/ConsumerConfig.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/AbstractQueueConsumer.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueEntryRow.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseConsumerStateStore.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueClientFactory.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/QueueBarrier.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/ShardedHBaseQueueStrategy.java
cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java

Same as https://github.com/caskdata/cdap/pull/2290 (merged).
Continued from https://github.com/caskdata/cdap/pull/2078
https://issues.cask.co/browse/CDAP-2105
http://builds.cask.co/browse/CDAP-RBT219

CDAP-2105: Queue introspection

---

cdap-ui/app/directives/error/error-popover.html
cdap-ui/app/directives/error/error.less

change location of clear all button

---

cdap-watchdog/src/main/java/co/cask/cdap/logging/run/LogSaverTwillRunnable.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/save/LogSaver.java

JIRA https://issues.cask.co/browse/CDAP-2387

CDAP-2387 Register shutdown hook to stop Log Saver before Hadoop Filesystem

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java

Jira: [CDAP-2192](https://issues.cask.co/browse/CDAP-2192)
Build: http://builds.cask.co/browse/CDAP-RBT250

[CDAP-2192] Aggregate adapter metrics by run id

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ProgramGenerationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/type/DatasetTypeManager.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java

[CDAP-1990] Delete dataset module archives upon module delete
Jira:
[CDAP-2405](https://issues.cask.co/browse/CDAP-2405)
[CDAP-1990](https://issues.cask.co/browse/CDAP-1990)
Build: http://builds.cask.co/browse/CDAP-RBT256

[CDAP-2405] Fix archive location in ApplicationMeta

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/test/java/co/cask/cdap/WorkflowAppWithFork.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java

Jira: https://issues.cask.co/browse/CDAP-2397
Fixed to catch the `InterruptedException` when the Workflow is stopped explicitly. This was done for the fork, but should also be done for the Workflow which does not contain the fork.

cdap-2397 Fixed bug in stopping of the Workflow.

---

cdap-ui/app/features/adapters/templates/tabs/runs/run-detail.html
cdap-ui/app/features/flows/templates/tabs/runs/run-detail.html
cdap-ui/app/features/mapreduce/templates/tabs/runs/run-detail.html
cdap-ui/app/features/spark/templates/tabs/runs/run-detail.html
cdap-ui/app/features/workflows/templates/tabs/runs/run-detail.html

change formatting of start time on runs

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConditionConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowConfigurer.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowForkConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/ApplicationVerificationStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConditionConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowForkConfigurer.java
cdap-app-fabric/src/test/java/co/cask/cdap/ConditionalWorkflowApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/GoodWorkflowApp.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/verification/WorkflowVerificationTest.java

Fir for the Jira: https://issues.cask.co/browse/CDAP-2425

Added ability to nest fork inside condition and condition inside fork.

---

cdap-ui/app/directives/navbar/navbar.html
cdap-ui/app/styles/themes/cdap/header.less

change cdap logo

---

cdap-ui/app/features/admin/admin.less
cdap-ui/app/features/admin/templates/overview.html

Admin Namespace name ellipsis

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BaseETLBatchTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/BatchETLDBAdapterTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/templates/etl/batch/ETLStreamConversionTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/DBConfig.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/templates/etl/common/Properties.java
cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
cdap-test/src/main/java/co/cask/cdap/test/TestManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java
cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java

json config file for a template plugin.
Also updating the db etl test case to make use of the ability
and re-enabling the test.

CDAP-2400 adding method to test adapter framework to add a

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTestRun.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/MockLogReader.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java
cdap-watchdog/src/main/java/co/cask/cdap/logging/context/WorkflowLoggingContext.java

Jira: [CDAP-2426](https://issues.cask.co/browse/CDAP-2426)
Build: http://builds.cask.co/browse/CDAP-RBT269

[CDAP-2426] Add adapter name to workflow logging context

---

cdap-common/src/main/java/co/cask/cdap/common/http/CommonNettyHttpServiceBuilder.java

https://issues.cask.co/browse/CDAP-2416
http://builds.cask.co/browse/CDAP-RBT268

CDAP-2416: Make SecurityRequestContext.getUserId() consistent

---

cdap-cli/src/main/java/co/cask/cdap/cli/CommandCategory.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/GetServiceEndpointsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/ListAllProgramsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/PreferencesCommandSet.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/AdapterCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ApplicationCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ApplicationTemplateCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ProgramCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ScheduleCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/StreamCommands.java

https://issues.cask.co/browse/CDAP-2442

Add a section for adapter lifecycle

---

cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/templates/create/plugins.html

Adds description to plugins list in adapter create view

---

cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.html
cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.js
cdap-ui/app/directives/widget-container/widget-factory.js
cdap-ui/templates/common/Cube.json
cdap-ui/templates/common/Projection.json
cdap-ui/templates/etlRealtime/Cube.json
cdap-ui/templates/etlRealtime/Kafka.json

csv widget to hide delimiter field

---

cdap-ui/app/directives/data-list/data-list.html
cdap-ui/app/directives/program-history/program-history.html
cdap-ui/app/features/apps/templates/tabs/datasets.html
cdap-ui/app/styles/themes/cdap/theme.less

- Fixes font-weight of global tables 
- Fixes datasets list view to have a margin top from the tab header
- Fixes font-weight on datasets list view in datasets tab of programs

Fixes global table header font-weight + datasets list styling fixes

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java
cdap-docs/reference-manual/source/cli-api.rst

http://builds.cask.co/browse/CDAP-DUT1778
https://issues.cask.co/browse/CDAP-1682

CDAP-1682: CLI option to provide a script containing CLI commands

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java

Previous fix on CDAP-2202 did not cover case the runtime info contain info about program based on invalid run record id.
Need to cross check it against the actual list of programs across apps and namesapces to get the right program id.

Check against all programs and cross check it against the run record Store to get the right program id to update

---

pom.xml

* Rename directories to a more user friendly name

Rename adapter directories

---

cdap-ui/app/features/admin/admin.less
cdap-ui/app/features/admin/templates/namespace/apps.html
cdap-ui/app/features/admin/templates/namespace/datasets.html

fix the icon getting underlined in admin datasets and apps

---

cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathTest.java

This is #2569 against release/3.0. Trying again~

[CDAP-2450] Fixed stream usage routing

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java

Does not completely resolve CDAP-2441, so will leave the issue open.
https://issues.cask.co/browse/CDAP-2441
http://builds.cask.co/browse/CDAP-RBT281-1

CDAP-2441 - Override MR job name in case user set it in beforeSubmit.

---

cdap-docs/integrations/source/partners/cloudera/configuring.rst
cdap-docs/integrations/source/partners/cloudera/step-by-step-cloudera.rst

adding csd upgrade instructions for 3.0

---

cdap-ui/app/features/home/routes.js
cdap-ui/app/services/namespace.js

set namespace to default when there is no session storage

---

cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java

This also contains fix for JMS plugin to set the right class loader when using external
dependencies.

Fix the ETLTemplate.configureAdapter to set the right sourcePluginId and sinkPluginId

---

cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/status-ctrl.js

Fixes workflows start & end nodes with forks

---

cdap-distributions/bin/build_artifact_upload.sh

Redirect snapshot artifacts to where they should go on remote server.

modify remote incoming dir for snapshot artifacts only

---

cdap-docs/examples-manual/build.sh
cdap-docs/examples-manual/source/how-to-guides/cdap-etl-adapter-guide.rst
cdap-docs/examples-manual/source/how-to-guides/index.rst
cdap-docs/reference-manual/source/release-notes.rst

Staged at: [Release Notes: Deprecated and Removed Features](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-r3.0_release_notes_v2/en/reference-manual/release-notes.html#deprecated-and-removed-features)

Deprecate Java 6.

---

cdap-docs/application-templates/source/etl/custom.rst

Staged at: [Creating a Transformation Plugin](http://stg-web101.sw.joyent.continuuity.net/cdap/3.0.0-r3.0_fix_java_example/en/application-templates/etl/custom.html#creating-a-transformation-plugin)

Correct Java code example

---

pom.xml

Build : http://builds.cask.co/browse/CDAP-DT91-1

Fix ETL App Template names in pom.xml

---

cdap-ui/app/index.html

Adding livereload back to gulp

add livereload for gulp

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/directives/flow-graph/flow.less

move instance count into flowlet circle

---

cdap-ui/app/features/admin/controllers/DatasetsController.js
cdap-ui/app/features/admin/templates/namespace/datasets.html

Consolidate Streams and Datasets array into one dataList array so that sorting will work properly in admin page.

consolidate streams and datasets array

---

cdap-ui/app/directives/program-history/program-history.html
cdap-ui/app/features/admin/templates/namespace/app-metadata.html
cdap-ui/app/features/apps/templates/tabs/status.html
cdap-ui/app/features/datasets/templates/tabs/programs.html
cdap-ui/app/features/programs/module.js
cdap-ui/app/features/spark/templates/tabs/history.html
cdap-ui/app/features/streams/templates/tabs/programs.html
cdap-ui/app/features/workers/controllers/detail-ctrl.js
cdap-ui/app/features/workers/controllers/tabs/runs-ctrl.js
cdap-ui/app/features/workers/controllers/tabs/runs/runs-detail-ctrl.js
cdap-ui/app/features/workers/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/workers/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/workers/module.js
cdap-ui/app/features/workers/routes.js
cdap-ui/app/features/workers/templates/detail.html
cdap-ui/app/features/workers/templates/tabs/history.html
cdap-ui/app/features/workers/templates/tabs/runs.html
cdap-ui/app/features/workers/templates/tabs/runs/run-detail.html
cdap-ui/app/features/workers/templates/tabs/runs/tabs/log.html
cdap-ui/app/features/workers/templates/tabs/runs/tabs/status.html

Worker had no page in the UI. Adding the most basic functionalities to it.
Start, stop, status, runs, history, logs.
---------------------
Note: The code duplication is an issue across all program types. It will be resolved in a follow up PR that touches all program types.

Worker pages.

---

cdap-docs/introduction/source/index.rst

Staged at: [Introduction](http://docs-staging.cask.co/cdap/3.0.0-r3.0_fix_examples/en/introduction/index.html)
There are a number of errors in the Introduction. This fixes them, including providing instructions on downloading a pre-built version of the Wise App.

Feature/r3.0 fix Introduction example

---

cdap-docs/examples-manual/build.sh

This changes the examples-manual build to replace any local references to image files with a reference to a downloaded image file. After an rst file is downloaded, all image references in it are extracted, downloaded and adjusted.
Tested on both Mac OS X and CentOS 6, with no other directories but cdap available.

Add downloading of any image files referenced in the docs.

---

cdap-ui/app/styles/themes/cdap/theme.less

fix table header color in modals

---

cdap-ui/app/features/flows/flows.less
cdap-ui/app/styles/themes/cdap/theme.less

- Fixes modal(s) to have a fixed offset from the top of the viewport.
- Fixes uppercase stream name in stream ingestion modal.

Fixes uppercase title in stream ingestion + fixed top offset for modal everywhere

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/input-ctrl.js

Fix the arrival rate metrics for input flowlet. 
Fix handleShowTip not showing up for Flows on hover.

[CDAP-2494] Fix/ui flowlet input metrics

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java

This PR is for cherry-pick against release/3.0 branch for CDAP-2490 JIRA to be included inn 3.0.1 release.

CDAP-2490 Check invalid run records for workflow children programs. Cherry pick for release 3.0.1

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Upgrade queues through admin. 
Currently testing it on a cluster with Purchase app.

CDAP-2502 call upgrade on QueueAdmin

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/sdk-cleanup.sh

- Stop CDAP SDK
- Delete data and logs directories
- Set ownership on `/opt/cdap`

CDAP-2506 SDK VM requires writable /opt/cdap

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/fluxbox.sh
cdap-distributions/src/packer/scripts/motd.sh

These settings improve performance and properly display a help menu in the first xterm.

Change name and add more vboxmanage settings

---

cdap-docs/_common/_source/index.rst
cdap-docs/application-templates/source/etl/custom.rst
cdap-docs/application-templates/source/etl/index.rst
cdap-docs/application-templates/source/index.rst

Fixes a title: "Creating Custom ETL Plugins and Adapters" becomes "Creating Custom ETL Plugins"

Fixes a title.

---

cdap-docs/deploy.sh

Merging PR 2694 (cdap doc deployment) change to develop

make sure feature branches docs do not get deployed to docs servers

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/KVTableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/TableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TwitterSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ProjectionTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ScriptFilterTransform.java

Build : http://builds.cask.co/browse/CDAP-RT35-1

Check if the Plugin config params are null or empty

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/KVTableSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/TableSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TwitterSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ProjectionTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/ScriptFilterTransform.java

Same PR as https://github.com/caskdata/cdap/pull/2686 but against develop instead of release/3.0.
Build : http://builds.cask.co/browse/CDAP-DT93-1

Check if the config param is null or empty

---

cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
cdap-unit-test-standalone/src/main/java/co/cask/cdap/test/standalone/StandaloneTestBase.java

- Need to consolidate the StandaloneTestBase and StandaloneContainer.

Replicating the fixes for Standalone related tests to run with no UI

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/features/flows/controllers/tabs/runs/tabs/status-ctrl.js

Polling for flowlet instances for flow graph

[CDAP-2534] number of flowlet instances does not update automatically in UI

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/program/Programs.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
cdap-common/src/main/java/co/cask/cdap/common/queue/QueueName.java
cdap-common/src/test/java/co/cask/cdap/common/queue/QueueNameTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/AbstractQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/QueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBQueueAdmin.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/inmemory/InMemoryStreamConsumerFactory.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/LocalQueueTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/QueueTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java

https://issues.cask.co/browse/CDAP-1483
http://builds.cask.co/browse/CDAP-DUT1859-6

CDAP-1483 QueueAdmin to use Id.Namespace instead of String

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java

http://builds.cask.co/browse/CDAP-DUT1867-2
https://issues.cask.co/browse/CDAP-2549

CDAP-2549 Delete suspended workflow run record

---

cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestBase.java

http://builds.cask.co/browse/CDAP-DUT1871
Also make instanceUri and accessToken overridable by subclasses.

Un-static IntegrationTestBase

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLStreamConversionTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/StreamBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/ETLUtils.java

Build : http://builds.cask.co/browse/CDAP-DT96-1

CDAP-2520 allow zero for delay and duration

---

cdap-ui/Gulpfile.js
cdap-ui/app/features/dashboard/controllers/widget.js
cdap-ui/app/features/dashboard/model/dashboards-model.js
cdap-ui/app/features/workflows/controllers/detail-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/history-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/runs/runs-detail-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/schedule-ctrl.js
cdap-ui/app/features/workflows/routes.js
cdap-ui/app/features/workflows/service/graph-helpers.js
cdap-ui/app/features/workflows/templates/detail.html
cdap-ui/app/features/workflows/templates/tabs/history.html
cdap-ui/app/features/workflows/templates/tabs/status.html
cdap-ui/app/main.js
cdap-ui/app/services/data/datasource.js
cdap-ui/app/services/data/socket.js
cdap-ui/app/services/mypromise.js
cdap-ui/app/services/settings.js
cdap-ui/app/services/workflows/myworkflowapi.js

Finishing up what was started here (https://github.com/caskdata/cdap/pull/1498)
The last update from me in PR#1498 (https://github.com/caskdata/cdap/pull/1498#issuecomment-82712166) is still valid except for 1st TODO.
In addition: 
- We need to modify ```BuildUrl``` function in datasource.js to parse params for metrics (tags based url.)
The reasoning behind this is that the metrics url will have the same query string (tags) and we cannot pass a json map with same key as property multiple times.
```
{ 
tag: 'apps:PurchaseHistory',
tag: 'workflows:PurchaseHistoryWorkflow',
tag: 'metric:Something'
} 
```
the snippet is not a valid json. We need to find way to pass an array of objects to construct query string.( For further details check …

Feature/ui data modeling post3.0

---

cdap-ui/templates/common/Projection.json

Change projection transform 'Rename' field to use KeyValue widget

[CDAP-2525] Inconsistent Projection Transform properties in UI

---

cdap-ui/app/main.js
cdap-ui/app/services/data/datasource.js

TODO:
Need to replace auto refresh on backend start which involves one single API from backend to query for backend status.

Fixes js error + cyclic dependency between MyDataSource,  and  modules

---

cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java
cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java
cdap-client/src/main/java/co/cask/cdap/client/config/AuthenticatedConnectionConfig.java

Build - http://builds.cask.co/browse/CDAP-DUT1866
JIRA - https://issues.cask.co/browse/CDAP-1584
Added username into cli prompt.

[CDAP-1584] show username in cli prompt

---

cdap-client-tests/src/test/java/co/cask/cdap/client/MetricsClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/MetricsClient.java
cdap-common/src/main/java/co/cask/cdap/common/metrics/MetricsTags.java
cdap-proto/src/main/java/co/cask/cdap/proto/Id.java
cdap-unit-test/src/main/java/co/cask/cdap/test/RuntimeStats.java

http://builds.cask.co/browse/CDAP-DUT1841
https://issues.cask.co/browse/CDAP-2515

CDAP-2515: MetricsClient changes for query and search by tags

---

cdap-cli/src/main/java/co/cask/cdap/cli/CLIMain.java

http://builds.cask.co/browse/CDAP-DUT1924

println instead of print for failed autoconnect output

---

cdap-client-tests/src/test/java/co/cask/cdap/client/MetaClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/MetaClient.java
cdap-common/src/main/java/co/cask/cdap/gateway/handlers/ConfigService.java
cdap-common/src/test/java/co/cask/cdap/gateway/handlers/ConfigServiceTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/ConfigEntry.java

http://builds.cask.co/browse/CDAP-DUT1917-4

getCDAPConfig and getHadoopConfig in MetaClient

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/DescribeStreamCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/adapter/DescribeAdapterCommand.java

https://issues.cask.co/browse/CDAP-2355

CDAP-2355: Fix adaper CLI descriptions

---

cdap-ui/app/features/datasets/controllers/detail-ctrl.js
cdap-ui/app/features/streams/controllers/detail-ctrl.js
cdap-ui/app/services/helpers.js
cdap-ui/app/services/streams/my-streams-service.js
cdap-ui/app/services/streams/mystreamapi.js

- truncate having errors on datasets and streams
- providing options to specify json or interval on a $resource request

fix truncate and json false

---

cdap-docs/developers-manual/source/building-blocks/streams.rst
cdap-docs/developers-manual/source/getting-started/building-apps.rst
cdap-docs/reference-manual/source/http-restful-api/stream.rst

https://issues.cask.co/browse/CDAP-2554

Adding documentation about deleting streams.

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/directives/flow-graph/flow.less
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/services/workflows/myworkflowapi.js

[CDAP-2615] add feature to highlight currently running workflow

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/StreamBatchSource.java

Build : http://builds.cask.co/browse/CDAP-DT94-1

Check if null or empty for format and schema

---

cdap-distributions/src/Dockerfile

Make sure we stop the SDK and clean up after it.

Run sdk-cleanup.sh in Dockerfile

---

cdap-data-fabric/src/test/java/co/cask/cdap/api/dataset/lib/IndexedTableTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/TableAssert.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/BufferingTableTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/TableTest.java

http://builds.cask.co/browse/CDAP-DUT1905

Removed unnecessary class that duplicates the name of another class

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/directives/flow-graph/flow.less
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js

Action nodes now polling for the particular status:
- Running node will show Green outline
- Completed node will show Green background
- Failed node will show Red background
Modified the color of condition node

[CDAP-2629] Workflow Diagrams Improvements

---

cdap-ui/app/features/adapters/controllers/create-ctrl.js
cdap-ui/app/features/adapters/services/AdapterCreateModel.js
cdap-ui/app/features/adapters/templates/create/configuration.html

[CDAP-2610] add instance config to etl realtime

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/AdapterService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java
cdap-standalone/bin/cdap.bat

* Fix CDAP startup bat script
* Log warning if exception is thrown while deleting temp dir during plugin registration
Build : http://builds.cask.co/browse/CDAP-DUT1930

CDAP-2504 Fix CDAP startup on Windows

---

cdap-ui/app/features/adapters/controllers/create-ctrl.js
cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/services/AdapterCreateModel.js
cdap-ui/app/features/adapters/templates/create/etlcanvas.html
cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html

- Adds check for required fields in plugins
- Indicates specific plugins missing required fields
- Fixes empty values being sent if they are not required.

[CDAP-2599 , CDAP-2499 , CDAP-2575] Fix/ui adapter mandatory params

---

cdap-ui/app/directives/metric-picker/metric-picker.js

Fix metric-picker issue where latest tag was replacing entire tags string.

Fix metric-picker issue where latest tag was replacing entire tags string

---

cdap-docs/application-templates/source/etl/custom.rst

JIRA : https://issues.cask.co/browse/CDAP-2503

CDAP-2503 etl plugin doc fix - reflecting api changes

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/CallServiceCommand.java

https://issues.cask.co/browse/CDAP-2007
http://builds.cask.co/browse/CDAP-DUT1885
```
cdap (http://localhost:10000/default)> call service PurchaseHistory.PurchaseHistoryService GET /history/joe
< 200 OK
< Content-Length: 33
< Connection: keep-alive
< Content-Type: text/plain; charset=UTF-8
{"aslkdjfjklad":"lksjdfklsdf"}
```

CDAP-2007: Render CLI output for CallServiceCommand in a copy-pastable way

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/FileSet.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/FileSetArguments.java
cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/FileSetProperties.java
cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst

Remove beta annotation and import, and remove "experimental" description in documentation.

Remove @beta from Filesets

---

cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java

Cherry-picking the bugfix commit from this PR:
https://github.com/caskdata/cdap/pull/2814
https://issues.cask.co/browse/CDAP-2635
http://builds.cask.co/browse/CDAP-RBT299-3

CDAP-2635 Utilize the config in the json of the metadata upon namespace create

---

cdap-ui/app/directives/navbar/namespace.html

Fixes namespace switch to go to dev or dashboard home page based on user context

---

cdap-ui/app/features/adapters/templates/create/configuration.html

change to **Schedule: Cron Expression**

[CDAP-2607] Change heading for ETLBatch configuration

---

cdap-ui/app/directives/data-list/data-list.html
cdap-ui/app/features/admin/templates/namespace/app-metadata.html
cdap-ui/app/features/admin/templates/namespace/dataset-metadata.html
cdap-ui/app/features/admin/templates/namespace/stream-metadata.html
cdap-ui/app/features/apps/routes.js
cdap-ui/app/features/apps/templates/detail.html
cdap-ui/app/features/apps/templates/list.html
cdap-ui/app/features/data/list-ctrl.js
cdap-ui/app/features/datasets/controllers/detail-ctrl.js
cdap-ui/app/features/datasets/controllers/tabs/status-ctrl.js
cdap-ui/app/features/datasets/routes.js
cdap-ui/app/features/datasets/templates/detail.html
cdap-ui/app/features/datasets/templates/list.html
cdap-ui/app/features/datasets/templates/tabs/programs.html
cdap-ui/app/features/datasets/templates/tabs/status.html
cdap-ui/app/features/flows/routes.js
cdap-ui/app/features/flows/templates/tabs/runs/flowlets/detail.html
cdap-ui/app/features/mapreduce/routes.js
cdap-ui/app/features/overview/templates/data-apps.html
cdap-ui/app/features/services/routes.js
cdap-ui/app/features/spark/routes.js
cdap-ui/app/features/streams/routes.js
cdap-ui/app/features/streams/templates/detail.html
cdap-ui/app/features/streams/templates/list.html
cdap-ui/app/features/streams/templates/tabs/programs.html
cdap-ui/app/features/workers/routes.js
cdap-ui/app/features/workflows/routes.js

Fixes going from app detailed status view to home page

---

cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/data-ctrl.js

removing faulty modulei injection

fix flowlet data tab

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/realtime/source/JmsSourceTest.java
cdap-ui/templates/etlRealtime/Jms.json

Make the JMS source to accept type and name of the JMS provider plugin.
Add 2 new JMS source configuration to set the dependent plugin for JMS Connection initial context.

Cherry pick to 3.0 branch: CDAP-2475 Make the JMS source to accept type and name of the JMS provider plugin.

---

cdap-distributions/src/Dockerfile

Add sdk-cleanup.sh to Dockerfile

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/network-cleanup.sh

CDAP-2640 Remove persistent network rules on VM

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/StartDebugProgramCommand.java
cdap-client-tests/src/test/java/co/cask/cdap/client/PreferencesClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ProgramClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/ProgramClient.java
cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteApplicationManager.java

https://issues.cask.co/browse/CDAP-2016
http://builds.cask.co/browse/CDAP-DUT1883-4

CDAP-2016: CLI support for starting programs in debug mode

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/cookbook-setup.sh

CDAP-2612 Add Flume agent to VM

---

cdap-distributions/src/packer/files/preseed.cfg

The `motd` mentions Subversion and it's still very, very common. Adding it to the VM.

Install Subversion into VM

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TwitterSource.java

fields. Also updating the plugin description to give information
about the output of the source, indicating field types and whether
or not they are nullable.

CDAP-2653 fix the twitter schema to correctly account for nullable

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/TwitterSource.java

CDAP-2648 fix the description to have the twitter schema fields

---

cdap-ui/app/directives/navbar/navbarCtrl.js
cdap-ui/app/features/admin/controllers/NamespaceCreateController.js
cdap-ui/app/features/admin/controllers/NamespaceSettingsController.js
cdap-ui/app/features/home/routes.js

2 fixes:
- updating namespace dropdown after namespace delete
- handle bug when deleting current active namespace

[CDAP-2646] Fix/ui namespace list dropdown

---

cdap-ui/app/index.html
cdap-ui/app/main.js

adds dynamic version number to CDAP footer

---

cdap-ui/app/directives/widget-container/widget-container.js
cdap-ui/app/directives/widget-container/widget-factory.js
cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.html
cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.js
cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.less
cdap-ui/app/features/adapters/templates/create/configuration.html
cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
cdap-ui/templates/etlBatch/Stream.json
cdap-ui/templates/etlRealtime/Twitter.json

- Fix Instance typo in ETL Realtime
- Twitter source Consumer secret becomes password widget
- Add different properties for Stream source

[CDAP-2605] [CDAP-2647] [CDAP-2649] add stream properties widget

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLStreamConversionTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/StreamBatchSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/ETLUtils.java

PRs #2729, #2721 merged into develop. Same changes for release/3.0 branch.

Changes in PR 2729 for CDAP-2520

---

cdap-ui/app/features/adapters/controllers/create-ctrl.js
cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/services/AdapterCreateModel.js
cdap-ui/app/features/adapters/templates/create/metadata.html
cdap-ui/app/main.js
cdap-ui/app/styles/common.less
cdap-ui/templates/ETLBatch/Stream.json
cdap-ui/templates/ETLBatch/TPFSAvro.json
cdap-ui/templates/ETLRealtime/Cube.json
cdap-ui/templates/ETLRealtime/Jms.json
cdap-ui/templates/ETLRealtime/Kafka.json
cdap-ui/templates/ETLRealtime/Stream.json
cdap-ui/templates/ETLRealtime/Table.json
cdap-ui/templates/ETLRealtime/Twitter.json

- Make sure adapter name is entered before making a backend call.

CDAP-2600 - Makes adapter name mandatory and checks for it before making backend call while creating adapter

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java

Fix the external plugin id due to fix to support multiple JMS providers.

Fix the external plugin id due to fix to support multiple JMS providers.

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/realtime/source/JmsSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/realtime/source/JmsSourceTest.java
cdap-ui/templates/ETLRealtime/Jms.json

Add custom properties in the JMSSource config for custom JMS properties since the UI does not have ability to add custom properties.

Add custom properties in the JMSSource config for custom JMS properties.

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/ConcurrentStreamWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/BufferedContentWriter.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/upload/FileContentWriter.java

http://builds.cask.co/browse/CDAP-DUT1895-4

CDAP-2422: Remove unnecessary catch clauses in StreamHandler

---

cdap-ui/app/features/apps/templates/list.html
cdap-ui/app/features/overview/controllers/overview-ctrl.js
cdap-ui/app/features/overview/templates/data-apps.html

Skips jumping to admin view when uploading app from dev section

---

cdap-ui/app/features/admin/controllers/NamespaceDatasetMetadataController.js
cdap-ui/app/features/datasets/controllers/tabs/explore-ctrl.js
cdap-ui/app/features/datasets/controllers/tabs/metadata-ctrl.js
cdap-ui/app/features/datasets/controllers/tabs/status-ctrl.js
cdap-ui/app/features/datasets/routes.js
cdap-ui/app/features/explore/explore.js

Cluster being created: edwin1698-1000.dev.continuuity.net

[CDAP-2663] fix dataset name with dot

---

cdap-ui/pom.xml

Shouldn't be SNAPSHOT, nor 3.1.0...

Correct CDAP parent version.

---

cdap-distributions/src/packer/cdap-sdk-ubuntu12.json
cdap-distributions/src/packer/scripts/fill-maven-cache.sh

This is the same as #2871 cherry-picked for develop

CDAP-2613 Cache dependencies to build CDAP examples

---

cdap-ui/app/directives/view-queries/view-queries.html

[CDAP-2654] fix explore view queries

---

cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/index.html

Preventing user to go to the mapreduce job when the action run has not started.

[CDAP-2435] Workflow Nodes click handler 

---

cdap-ui/app/features/overview/controllers/overview-ctrl.js

Fixes typo to show system services' status in overview page

---

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java

that queries over streams will have access to the classes.

CDAP-2678 include record formats in the explore classpath so

---

cdap-ui/app/directives/log-viewer/log-viewer.html
cdap-ui/app/directives/log-viewer/log-viewer.less

[CDAP-2344] include indentation in logs

---

cdap-ui/app/directives/app-level-loading-icon/loading.js
cdap-ui/app/features/admin/controllers/NamespaceDatasetMetadataController.js
cdap-ui/app/features/admin/controllers/NamespaceSettingsController.js
cdap-ui/app/features/admin/controllers/StreamPropertiesController.js
cdap-ui/app/features/admin/templates/namespace/stream-metadata.html
cdap-ui/app/services/streams/mystreamapi.js

- Add ability to delete stream
- Change the loading state for deleting dataset, stream, and namespace to show the loading icon modal
Cluster being created: deletestreamcluster1717-1000.dev.continuuity.net:9999

[CDAP-2691] add ability to delete stream and add loading icon

---

cdap-docs/examples-manual/build.sh

Changes made to guarded files; the changes don't affect the HTML output, so merely an update of the MD5 hashes.
[Built successfully.](http://builds.cask.co/browse/CDAP-DDBD228-2/log)

Fix Documentation Build in Develop

---

cdap-cli/src/main/java/co/cask/cdap/cli/CommandCategory.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/metrics/GetMetricCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/metrics/SearchMetricNamesCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/metrics/SearchMetricTagsCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/DefaultCommands.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/MetricsCommands.java
cdap-client/src/main/java/co/cask/cdap/client/MetricsClient.java
cdap-docs/reference-manual/source/cli-api.rst

https://issues.cask.co/browse/CDAP-2466
http://builds.cask.co/browse/CDAP-DUT1923-4
```
cdap (http://localhost:10000/default)> search metric tags "namespace=default"
app=CountRandom
app=HelloWorld
app=Netlens
app=PurchaseHistory
app=TwitterSentiment
app=Wise
app=WordCount
app=etlBatch
component=gateway
dataset=TimeSeriesTable
dataset=TotalCounts
dataset=anomalies
dataset=anomalyCounters
dataset=bounceCountStore
dataset=cloudera
dataset=converted_stream
dataset=counters
dataset=frequentCustomers
dataset=history
dataset=pageViewStore
dataset=purchases
dataset=randomTable
dataset=system.queue
dataset=topN
dataset=trafficCounters
dataset=uniqueCount
dataset=uniqueCounters
dataset=userProfiles
dataset=whom
dataset=wordAssocs
dataset=wordCounts
dataset=wordStats
stream=boo
stream=cloudwick …
```

CDAP-2466: CLI for metrics search and query

---

cdap-cli/src/main/java/co/cask/cdap/cli/command/GetProgramLogsCommand.java

fixed concurrent merge issue

---

cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/input-ctrl.js

catch() is not a function defined in myPromise.
cluster: http://developtest1732-1000.dev.continuuity.net:9999/

remove catch function in promise chain

---

cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/StreamFetchHandler.java

Fix StreamHandlerTest failure

---

cdap-ui/app/features/data/list-ctrl.js
cdap-ui/app/features/data/list.html

[CDAP-2689] add programs list to all datasets view

---

cdap-ui/app/features/adapters/etlapps.less

fix styling for create adapter header

---

cdap-ui/app/features/datasets/templates/detail.html

Fixes navigating to non-explorable datasets. Instead of mixing up states we just go to a static tab (programs) for non-explorable datasets.

Fixes view of non-explorable dataset (makes it static instead of dynamic states)

---

cdap-distributions/src/packer/scripts/lxde.sh

Use solid neutral grey background

---

cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java
cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java

Build: http://builds.cask.co/browse/CDAP-RBT305-1

Use POST in RanksServiceHandler for better UI integration

---

cdap-ui/app/directives/error/error-popover.html
cdap-ui/app/directives/error/error.less
cdap-ui/app/services/alert.js

consolidate same error message to one line with counter

---

cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js

Fixing the problem where the list of nodes have not been resolved yet, but the polling of status for each nodes have started.

[CDAP-2781] fix workflow diagram not consistently getting nodes status

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/DatasetSpecification.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
cdap-proto/src/main/java/co/cask/cdap/proto/DatasetSpecificationSummary.java

http://builds.cask.co/browse/CDAP-DUT2050

Add back DatasetInstanceHandlerTest

---

cdap-ui/app/directives/view-queries/view-queries.html
cdap-ui/app/directives/view-queries/view-queries.less

[CDAP-2707] change running query indicator color to yellow

---

cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
cdap-proto/src/main/java/co/cask/cdap/proto/MetricQueryResult.java
cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsHandler.java

Commit aims to get resolutions in the JSON response. Also test case coverage.

Commit aims to get resolutions in the JSON response for Metrics. CDAP-2158

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java

Simple refactor to move checking program type early for invalid run records. 
Add DEBUG log level for any exception thrown in the cleaner thread.

Refactor to move check program type early for run records cleaner

---

cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/data-ctrl.js
cdap-ui/app/features/flows/controllers/tabs/runs/flowlets/output-ctrl.js
cdap-ui/app/features/flows/templates/tabs/runs/flowlets/output.html

fix controller as syntax

---

cdap-ui/app/features/datasets/routes.js

Fixes non-explorable secure environments to show datasets even though its not explorable

---

cdap-docs/examples-manual/source/examples/spark-page-rank.rst

Staged at: http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_fix_example/en/examples-manual/examples/spark-page-rank.html

Fix including of Spark example.

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java
cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java

https://issues.cask.co/browse/CDAP-2811
http://builds.cask.co/browse/CDAP-DUT2070
* Works in standalone and distributed

CDAP-2811: Improve Hive version detection

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/BaseHiveExploreService.java
cdap-explore/src/main/java/co/cask/cdap/explore/service/hive/Hive14ExploreService.java

https://issues.cask.co/browse/CDAP-2798
http://builds.cask.co/browse/CDAP-DUT2074
Depends on https://github.com/caskdata/cdap/pull/2996 and https://github.com/caskdata/cdap/pull/2989

CDAP-2798: Hive 0.14 support

---

cdap-docs/developers-manual/source/building-blocks/datasets/fileset.rst
cdap-docs/reference-manual/source/release-notes.rst

Subject to review and change.
Staged at: [Release Notes](http://docs-staging.cask.co/cdap/3.0.1-feature-r3.0.1_release_notes/en/reference-manual/release-notes.html#release-3-0-1)

Release notes for Release 3.0.1

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionMetadata.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/BasicPartitionDetail.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDataset.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetTest.java

https://issues.cask.co/browse/CDAP-2746
http://builds.cask.co/browse/CDAP-DUT2080-5

Record creationTime of partitions

---

cdap-ui/app/features/spark/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/spark/routes.js
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/services/spark/mysparkapi.js

Adding $resource program type.
Cluster: http://singlenodecluster1813-1000.dev.continuuity.net:9999/
PS: the cluster will not fully illustrate the entirety of Spark. Spark still not fully supported in Distributed yet. 
TODO (in separate PR): 
- Refactor code using Controller-As syntax
- Refactor to make consistent with other program types

add spark data modelling and refactor

---

cdap-ui/app/features/streams/controllers/tabs/status-ctrl.js
cdap-ui/app/features/streams/templates/tabs/status.html

Beautifying Total Stream Events Count

---

cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/BaseETLBatchTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLStreamConversionTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLTPFSTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/TimePartitionedFileSetDatasetAvroSource.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/Properties.java
cdap-ui/templates/ETLBatch/TPFSAvro.json
cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java

https://issues.cask.co/browse/CDAP-2733
http://builds.cask.co/browse/CDAP-DUT2071
#2999 
Have an LGTM on this PR... Created this branch to squash commits. 
http://builds.cask.co/browse/CDAP-DUT2106

Adding TPFSAvro as Source

---

cdap-ui/app/features/spark/controllers/detail-ctrl.js
cdap-ui/app/features/spark/controllers/tabs/runs-ctrl.js
cdap-ui/app/features/spark/controllers/tabs/runs/runs-detail-ctrl.js
cdap-ui/app/features/spark/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/spark/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/spark/routes.js
cdap-ui/app/features/spark/templates/detail.html
cdap-ui/app/features/spark/templates/tabs/history.html
cdap-ui/app/features/spark/templates/tabs/runs.html
cdap-ui/app/features/spark/templates/tabs/runs/run-detail.html
cdap-ui/app/features/spark/templates/tabs/runs/tabs/log.html
cdap-ui/app/features/spark/templates/tabs/runs/tabs/status.html

Refactor Spark programs to use Controller As syntax.
Cannot test Spark in Cluster. Need to pull locally.

Spark Refactor using Controller As

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java
cdap-data-fabric/src/test/java/co/cask/cdap/api/dataset/lib/IndexedTableTest.java

https://issues.cask.co/browse/CDAP-2822
http://builds.cask.co/browse/CDAP-DUT2089-8

CDAP-2822 IndexedTable should support scans on the indexed field.

---

cdap-ui/app/features/flows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/schedule-ctrl.js
cdap-ui/app/features/workflows/templates/tabs/schedules.html
cdap-ui/app/services/workflows/myworkflowapi.js

- Change polling interval for Flows Metrics (for flow diagrams)
- Change polling interval for Workflow Schedule status
- Add transition disabled button when Workflow Schedule is on status transition

[CDAP-2932] [CDAP-2660] [CDAP-2833] Fix/ui polling intervals

---

cdap-docs/developers-manual/source/getting-started/standalone/docker.rst

Unfortunately, this does not render as expected. Seeking help... @awholegunch ?

Use version for Docker commands

---

cdap-ui/app/directives/breadcrumb/breadcrumb.html
cdap-ui/app/directives/breadcrumb/breadcrumb.js
cdap-ui/app/features/mapreduce/controllers/tabs/run-ctrl.js
cdap-ui/app/features/mapreduce/routes.js
cdap-ui/app/features/mapreduce/templates/detail.html
cdap-ui/app/features/spark/routes.js
cdap-ui/app/features/spark/templates/detail.html
cdap-ui/app/features/workflows/controllers/tabs/runs-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js

Creates custom directive that will handle special case of breadcrumb
Cluster: http://singlenode1852-1000.dev.continuuity.net:9999/ns/default

[CDAP-2628] Fix/ui workflow mapreduce breadcrumb

---

cdap-ui/templates/ETLBatch/TPFSParquet.json

Add the UI for parquet sink, it is basically the same as TPFSAvro.

add UI json for TPFSParquet

---

cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetService.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java

http://builds.cask.co/browse/CDAP-DUT1915-11

CDAP-2557: Move out non-handler logic from DatasetInstanceHandler

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java

- Job.submit will copy it to HDFS
- Need this in order to work on both local, HDFS and MapR FS

Always create MapReduce job jar on local fs.

---

cdap-ui/app/directives/app-level-loading-icon/loading.html
cdap-ui/app/directives/app-level-loading-icon/loading.js
cdap-ui/app/features/login/routes.js
cdap-ui/app/main.js
cdap-ui/app/services/auth.js
cdap-ui/app/services/namespace.js
cdap-ui/server/express.js

Cluster: 
http://securecluster1870-1000.dev.continuuity.net:9999/
http://nodejsfix1872-1000.dev.continuuity.net:9999/

[CDAP-2740] [CDAP-2830] Fix/ui node server crash

---

cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowActionSpecification.java
cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowContext.java
cdap-api/src/main/java/co/cask/cdap/internal/workflow/DefaultWorkflowActionSpecification.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/ProgramWorkflowRunnerFactory.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java
cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowActionSpecificationCodec.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetWithCustomActionApp.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

Issue: https://issues.cask.co/browse/CDAP-2752
Build: http://builds.cask.co/browse/CDAP-DUT2075-1

Refactored workers, custom actions. Custom actions now have dataset, service, stream support

---

cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreServiceUtils.java

https://issues.cask.co/browse/CDAP-2801
http://builds.cask.co/browse/CDAP-DUT2171
Works in distributed.

CDAP-2801: Support CDH 5.4 Hive 1.1

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java

There was a bug in the test case where the final writer was
being determined incorrectly. Writers add themselves to a list
after they finish writing, and the last writer was assumed to be
the last writer in the list. This is wrong,
since writerX can write after writerY, but writerX may add itself
to the list before writerY adds itself to the list.

CDAP-2940 fix bug in artifact concurrent write test case

---

cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimePartitionedFileSet.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetDataset.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java
cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTestRun.java

that legacy format has not been supported since 2.8. Time to remove it.

[CDAP 2921] remove all backward compatibility support from tpfs

---

cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java

https://issues.cask.co/browse/CDAP-2569
http://builds.cask.co/browse/CDAP-DUT2176-1

Create root ZK node right after connected to ZK.

---

cdap-ui/app/directives/view-queries/view-queries.html
cdap-ui/app/features/datasets/templates/tabs/explore.html
cdap-ui/app/features/streams/templates/tabs/explore.html

[CDAP-2690] change View Queries to View Results

---

cdap-ui/app/features/admin/templates/overview.html

* For the namespaces table in Admin overview

adds sorting to Datasets and Streams columns

---

cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java

Simply add test case for unused methods, even though the implementation is simple.
http://builds.cask.co/browse/CDAP-DUT2183-2

Add test case for TimePartitionedFileSet#addMetadata methods

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractDistributedProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedSparkProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkUtils.java

- Support direct location through $SPARK_ASSEMBLY_JAR
- Support search in $SPARK_HOME/lib
- Localize the spark jar to the spark client container in distributed mode

(CDAP-2931) Get location of spark-assembly.jar from environment

---

cdap-examples/CountRandom/src/main/java/co/cask/cdap/examples/countrandom/CountRandomFlow.java
cdap-examples/HelloWorld/src/main/java/co/cask/cdap/examples/helloworld/HelloWorld.java
cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseFlow.java
cdap-examples/SparkKMeans/src/main/java/co/cask/cdap/examples/sparkkmeans/SparkKMeansApp.java
cdap-examples/UserProfiles/src/main/java/co/cask/cdap/examples/profiles/ActivityFlow.java
cdap-examples/WebAnalytics/src/main/java/co/cask/cdap/examples/webanalytics/WebAnalyticsFlow.java
cdap-examples/WordCount/src/main/java/co/cask/cdap/examples/wordcount/WordCounter.java

Build : http://builds.cask.co/browse/CDAP-DUT2186-1
JIRA : https://issues.cask.co/browse/CDAP-380

Porting CDAP examples to use new Flow configurer API

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java
cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/Transactions.java

- Added Transactions.execute methods to help execute
function through a TransactionContext
- Simplify file/location cleanup
- No need to generate/copy jar files in local mode

Refactor MapReduceRuntimeService

---

cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.html
cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.html
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.html
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js
cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.js
cdap-ui/app/features/adapters/controllers/create/plugin-property-edit-ctrl.js
cdap-ui/app/features/adapters/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/templates/create/tabs/edit-sink-properties.html
cdap-ui/app/features/adapters/templates/create/tabs/edit-transform-properties.html
cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
cdap-ui/app/services/plumber/my-plumb-service.js
cdap-ui/templates/ETLBatch/FileBatchSource.json
cdap-ui/templates/ETLBatch/Stream.json
cdap-ui/templates/ETLRealtime/Jms.json
cdap-ui/templates/ETLRealtime/Kafka.json
cdap-ui/templates/ETLRealtime/Twitter.json
cdap-ui/templates/common/KVTable.json

Schema Propagation in Adapter Create

---

cdap-docs/examples-manual/build.sh

Build : http://builds.cask.co/browse/CDAP-DDBD491-1

Updating md5 hash for examples

---

cdap-app-fabric/src/test/java/co/cask/cdap/AppWithWorkflow.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java
cdap-cli/src/main/java/co/cask/cdap/cli/DefaultCompleters.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/GetWorkflowTokenCommand.java
cdap-cli/src/main/java/co/cask/cdap/cli/command/WorkflowCommandSet.java
cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ProgramCommands.java
cdap-client-tests/src/main/java/co/cask/cdap/client/app/FakeWorkflow.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ClientTestsSuite.java
cdap-client-tests/src/test/java/co/cask/cdap/client/DatasetClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/ScheduleClientTestRun.java
cdap-client-tests/src/test/java/co/cask/cdap/client/WorkflowClientTestRun.java
cdap-client/src/main/java/co/cask/cdap/client/WorkflowClient.java
cdap-proto/src/main/java/co/cask/cdap/proto/WorkflowTokenDetail.java

Java Client APIs:
```
public WorkflowTokenDetail getWorkflowToken(Id.Run workflowRunId) throws UnauthorizedException, IOException, NotFoundException
public WorkflowTokenDetail getWorkflowToken(Id.Run workflowRunId, WorkflowToken.Scope scope) throws UnauthorizedException, IOException, NotFoundException
public WorkflowTokenDetail getWorkflowToken(Id.Run workflowRunId, String key) throws UnauthorizedException, IOException, NotFoundException
public WorkflowTokenDetail getWorkflowToken(Id.Run workflowRunId, @Nullable WorkflowToken.Scope scope, @Nullable String key) throws IOException, UnauthorizedException, NotFoundException
public WorkflowTokenNodeDetail getWorkflowTokenAtNode(Id.Run workflowRunId, String nodeName) throws UnauthorizedException, IOException, NotFoundException
public …
```

Java Client and CLI for WorkflowToken

---

cdap-api/src/main/java/co/cask/cdap/api/app/AbstractApplication.java
cdap-app-fabric/src/test/java/co/cask/cdap/ConfigTestApp.java
cdap-client-tests/src/main/java/co/cask/cdap/client/app/ConfigTestApp.java
cdap-test/src/main/java/co/cask/cdap/test/TestManager.java

Build : http://builds.cask.co/browse/CDAP-DUT2226-1

Add a method in AbstractApplication to get the config object

---

cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillApplication.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillRunnable.java

- Setup Workflow container size with Spark driver resources requirement

- Localize Spark assembly jar to Workflow container

---

cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/src/main/java/HelloWorld.java
cdap-archetypes/cdap-app-archetype/src/main/resources/archetype-resources/src/test/java/HelloWorldTest.java
cdap-unit-test/src/main/java/co/cask/cdap/test/ConfigurableTestBase.java

Also replace the usage of deprecated methods in the Unit test
Build : http://builds.cask.co/browse/CDAP-DUT2237

Update cdap app archetype to adhere to new Flow configurer API

---

cdap-ui/app/directives/flow-graph/flow.js

Fix for dragging svg elements (flow-graph directive)

fix deprecated size methods on svg elements

---

cdap-ui/app/directives/infinite-scroll/infinite-scroll.js
cdap-ui/app/directives/log-viewer/log-viewer.html
cdap-ui/app/directives/log-viewer/log-viewer.js
cdap-ui/app/features/flows/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/flows/templates/tabs/runs/tabs/log.html
cdap-ui/app/features/mapreduce/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/mapreduce/templates/tabs/runs/tabs/log.html
cdap-ui/app/features/services/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/services/templates/tabs/runs/tabs/log.html
cdap-ui/app/features/spark/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/spark/templates/tabs/runs/tabs/log.html
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/workflows/templates/tabs/runs/tabs/log.html
cdap-ui/app/services/flows/my-flows-api.js
cdap-ui/app/services/mapreduce/my-mapreduce-api.js
cdap-ui/app/services/service/my-service-api.js
cdap-ui/app/services/spark/my-spark-api.js
cdap-ui/app/services/workflows/my-workflow-api.js
cdap-ui/server/config/development/cdap.json

Add Infinite Scrolling to Logs
Add Loading indicator
Cluster: http://dashboard1869-1000.dev.continuuity.net:9999/
note: try out PurchaseHistoryBuilder program. It should have more than 150 lines of logs

[CDAP-2692] Feature/ui show more logs

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/SchedulerServiceTest.java

- The test only test whether the schedules get store/retrieve successfully, but never need the program to run

(CDAP-2081) Use schedules that are far in future to avoid program being triggered

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/transform/LogParserTransform.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/transform/LogParserTransformTest.java

Issue: https://issues.cask.co/browse/CDAP-3022
Build: http://builds.cask.co/browse/CDAP-DUT2254-1

added Cloudfront format for LogParser transform

---

cdap-data-fabric-tests/src/test/java/co/cask/cdap/data/stream/service/DFSStreamHeartbeatsTest.java
cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/service/LocalStreamFileJanitorService.java

- It shares variable from multiple threads without using correct memory visibility construct
- It didn’t start dataset service, which causes issue in creating the metrics table, which is needed by the test instance, potentially causing test hang due to infinite retry inside metrics table.

(CDAP-3027) Fix the DFSStreamHeartbeatsTest

---

cdap-ui/bower.json

cluster: http://singlenode2012-1000.dev.continuuity.net:9999
Please help test before merging this...

upgrade angular bootstrap to version 0.13.0

---

cdap-ui/app/directives/flow-graph/flow.js

[CDAP-3023] fix flowlet instance default in diagram to 1

---

cdap-ui/app/directives/flow-graph/flow.js
cdap-ui/app/directives/flow-graph/flow.less
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/log-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/features/workflows/controllers/tabs/schedule-ctrl.js
cdap-ui/app/services/workflows/my-workflow-api.js

- Fix cursor on nodes that have not run yet (not-allowed)
- add status color to Killed status (red border)
- Making WorkFlow resources to be consistent with other program types (adding namespace to params). This was causing issue when you switch namespace, the program was still trying to fetch information from the previous namespace for some reason, thus throwing 404.
Cluster: singlenode2012-1000

[CDAP-2870] Feature/ui workflow diagram cursor fixes

---

cdap-watchdog/src/main/java/co/cask/cdap/metrics/runtime/KafkaMetricsProcessorService.java

the problem was in using same discoverable name for kafka consumer service and status service

CDAP-3040: fix metrics server reporting notok

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/FileBatchSource.java

JIRA - https://issues.cask.co/browse/CDAP-3066
BUILD - http://builds.cask.co/browse/CDAP-DUT2289-1
Local variable aliased class variable blocking functionality.

CDAP-3066 fix FileBatchSource

---

cdap-data-fabric/src/test/java/co/cask/cdap/data/hbase/HBaseTestBase.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java
cdap-data-fabric/src/test/java/co/cask/cdap/data2/util/hbase/AbstractHBaseTableUtilTest.java
cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data/hbase/HBase96Test.java
cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data/hbase/HBase98Test.java
cdap-hbase-compat-1.0-cdh/src/test/java/co/cask/cdap/data/hbase/HBase10CDHTest.java
cdap-hbase-compat-1.0/src/test/java/co/cask/cdap/data/hbase/HBase10Test.java

About 6-7 mins faster in bamboo

Make QueueTest and HBaseTableTest runs faster

---

cdap-docs/examples-manual/source/examples/index.rst
cdap-docs/examples-manual/source/examples/spark-page-rank.rst
cdap-examples/README.rst
cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java

- We added a MapReduce, Workflow and a Service in the SparkPageRank example earlier. 
- All the new curl and cli commands have been tested to work.

Update SparkPageRank example documentation for the latest changes

---

cdap-app-fabric/pom.xml
cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamBatchWriter.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamWriter.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/DefaultFlowConfigurer.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/spark/SparkRuntimeService.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/adapter/AdapterServiceTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ConsoleSettingsHttpHandlerTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/DashboardHttpHandlerTest.java
cdap-common/src/main/java/co/cask/cdap/common/lang/ClassLoaders.java
cdap-standalone/pom.xml
cdap-unit-test/pom.xml
cdap-unit-test/src/test/java/co/cask/cdap/spark/service/TestSparkServiceIntegrationApp.java
pom.xml

- Spark should be available from the cluster, with $SPARK_HOME pointing to it
- For standalone, we package with spark-core and spark-sql (we don’t support spark-streaming yet)
- Also fix an annoying error message in standalone by doing proper cleanup of System properties that are set by spark-submit.

Spark improvements and fixes

---

cdap-ui/app/features/adapters/etlapps.less

fix adapter detail subheading styles

---

cdap-api/src/main/java/co/cask/cdap/api/artifact/ApplicationClass.java
cdap-api/src/main/java/co/cask/cdap/api/artifact/ArtifactClasses.java
cdap-api/src/main/java/co/cask/cdap/api/artifact/ArtifactDescriptor.java
cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ArtifactHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginInstantiator.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/adapter/PluginRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactMeta.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRange.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepository.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/InvalidArtifactRangeException.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/PluginSelector.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRangeTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/Plugin1.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/plugin/Plugin2.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
cdap-common/src/main/java/co/cask/cdap/common/namespace/DefaultNamespacedLocationFactory.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactInfo.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/ArtifactSummary.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/PluginInfo.java
cdap-proto/src/main/java/co/cask/cdap/proto/artifact/PluginSummary.java

Adding restful endpoints to add artifacts and get metadata
about the artifacts. Also adding a few missing methods to
ArtifactRepository to expose some more get functions from the
ArtifactStore.

CDAP-2763 adding rest apis for adding and getting artifacts

---

cdap-ui/app/features/adapters/controllers/create/plugin-property-edit-ctrl.js
cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
cdap-ui/app/services/plumber/my-plumb-service.js

Fixes plugin properties modal to show textboxes when no config is provided.

Fixes to show plugin properties as textbox when no config provided in nodeproxy

---

cdap-ui/pom.xml
pom.xml

JIRA - https://issues.cask.co/browse/CDAP-1967

CDAP-1967 Excluding org.codehaus.jackson from getting packaged in CDAP artifacts

---

cdap-ui/app/features/services/services.less
cdap-ui/app/features/services/templates/tabs/runs/tabs/status.html

*  Changes layout of the endpoint table to prevent endpoint path from overlapping with the Make Request button

adds new table markup to prevent endpoint path overlap issues

---

cdap-docs/_common/common-build.sh
cdap-docs/admin-manual/source/installation/installation.rst
cdap-docs/examples-manual/build.sh

Fix for https://issues.cask.co/browse/CDAP-2891

Add configuration information for HDP 2.2.

---

cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java

Currently testing on cluster. Opening PR for review.

CDAP-3009 remove stream conversion adapter upgrade

---

cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js
cdap-ui/app/features/admin/controllers/namespace/app-ctrl.js
cdap-ui/app/features/admin/templates/namespace/apps.html
cdap-ui/app/features/apps/controllers/list-ctrl.js

Fixes adapter delete to be part of admin (part 2 of unifying app and adapters under one view)

Fixes adapter delete to be part of admin (without metadata view)

---

cdap-ui/app/directives/widget-container/widget-dsv/widget-dsv.js
cdap-ui/app/directives/widget-container/widget-keyvalue/widget-keyvalue.js
cdap-ui/app/directives/widget-container/widget-schedule/widget-schedule.js
cdap-ui/app/directives/widget-container/widget-schema-editor/widget-schema-editor.js
cdap-ui/app/directives/widget-container/widget-stream-properties/widget-stream-properties.js
cdap-ui/app/features/adapters/controllers/create/plugin-property-edit-ctrl.js
cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html
cdap-ui/app/services/plumber/my-plumb-service.js

Revert "Feature/ui adapter save reset"

---

cdap-data-fabric/src/test/java/co/cask/cdap/data/hbase/HBaseTestBase.java
cdap-data-fabric/src/test/java/co/cask/cdap/hbase/wd/RowKeyDistributorTestBase.java

- Still have a small chance, but very small.

Tries to use random port to minimize chance for port clashing.

---

cdap-docs/developers-manual/source/getting-started/standalone/docker.rst

Fixes https://issues.cask.co/browse/CDAP-2854

Correct docker instructions.

---

cdap-ui/app/features/adapters/templates/create/tabs/plugin-edit-form.html

only show close button on already created adapter

---

cdap-explore/src/main/java/co/cask/cdap/explore/guice/ExploreRuntimeModule.java

when hive runs a local mapred task, it cannot find 'org.apache.hadoop.hive.serde2.SerDe' due to missing hive-exec jar in this classpath, adding it to hiveAuxJars and using it to set the LocalMapreduceClasspathSetter classpath
https://issues.cask.co/browse/CDAP-3033
build : http://builds.cask.co/browse/CDAP-RBT343-1/log

explore classpath fix 

---

cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/BaseETLBatchTest.java
cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/co/cask/cdap/template/etl/batch/ETLESSinkTest.java
cdap-app-templates/cdap-etl/cdap-etl-lib/pom.xml
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/ElasticsearchSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/Properties.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/common/StructuredRecordStringConverter.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/test/java/co/cask/cdap/template/etl/common/StructuredRecordStringConverterTest.java
cdap-ui/templates/ETLBatch/Elasticsearch.json
pom.xml

http://builds.cask.co/browse/CDAP-DUT2319-1

Feature/es sink plugin Allows elasticsearch as a batch sink for an ETL Adapter

---

cdap-ui/app/features/admin/controllers/namespace/create-ctrl.js

[CDAP-2862] surface message from backend on namespace create success

---

cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java
cdap-integration-test/src/main/java/co/cask/cdap/test/remote/RemoteStreamManager.java
cdap-test/src/main/java/co/cask/cdap/test/StreamManager.java
cdap-unit-test/src/main/java/co/cask/cdap/test/internal/DefaultStreamManager.java
cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java

Build: http://builds.cask.co/browse/CDAP-RBT346

[CDAP-1983] Added capability for batch upload to stream in TestBase

---

cdap-ui/app/features/admin/controllers/system/service-log-ctrl.js
cdap-ui/app/features/admin/routes.js
cdap-ui/app/features/admin/templates/partials/service-detail-log.html

[CDAP-3024] infinite scroll on system services logs

---

cdap-ui/app/features/adapters/adapters.less
cdap-ui/app/features/adapters/controllers/list-ctrl.js
cdap-ui/app/features/adapters/etlapps.less
cdap-ui/app/features/adapters/routes.js
cdap-ui/app/features/adapters/templates/list.html

- Fixes the url for adapter drafts,
- Fixes title and alignment
- Fixes the message to be shown when no drafts have been created

Fixes url, alignment & messaging in adapters list view to be drafts

---

cdap-ui/app/directives/plumb/my-plumb-ctrl.js
cdap-ui/app/directives/plumb/my-plumb.html
cdap-ui/app/directives/plumb/my-plumb.less
cdap-ui/app/features/adapters/controllers/create-new-ctrl.js
cdap-ui/app/features/adapters/controllers/create/canvas-ctrl.js
cdap-ui/app/features/adapters/controllers/tabs/runs/tabs/status-ctrl.js
cdap-ui/app/services/plumber/my-plumb-service.js

- Double click to open properties
- Close Canvas Errors
- Canvas errors stick to bottom of screen
- Destroy modal on scope destroy

[CDAP-3086] Feature/ui adapter create double click

---

cdap-ui/app/features/admin/admin.less
cdap-ui/app/features/admin/templates/namespace/apps.html
cdap-ui/app/features/apps/templates/list.html
cdap-ui/app/features/overview/overview.less
cdap-ui/app/features/overview/templates/data-apps.html

*  Removes box shadow when Add App button is open
*  Changes Add App button and dropdown text (Dev Start, All Apps, Admin > Namespace > Apps)
*  Center aligns trash icon in Admin > Namespace > Apps

[CDAP-3086] Feature/ui add app option text

---

cdap-ui/app/directives/plumb/my-plumb-factory.js

Fixes the arrow styles (thickness, color and arrow head)

Fixes arrow head, thickness and color in my-plumb directive

---

cdap-ui/app/directives/flow-graph/flow.js

Fix deprecated function within flow-graph 'fit to screen' method.

fix fit to screen button function

---

cdap-standalone/bin/cdap.bat
cdap-standalone/bin/cdap.sh

- Verified on Mac and Windows.

Check for node.js min version

---

cdap-docs/admin-manual/source/installation/installation.rst

Change the example XML to be correct XML, and highlight the replacements required.
Fix for https://issues.cask.co/browse/CDAP-2838

Fix Security Configuration example

---

cdap-watchdog/src/test/java/co/cask/cdap/logging/save/LogSaverPluginTest.java

* JIRA: https://issues.cask.co/browse/CDAP-2177
* Test: http://builds.cask.co/browse/CDAP-RBT361

Enable the Ignored tests

---

cdap-ui/app/features/adapters/adapters.less
cdap-ui/app/features/adapters/templates/create.html

*  Replaces floats from metadata box
*  Sets min-width on metadata box
*  Adds placeholder description for metadata description
*  Adds myEllipsis to adapter name

changes layout of adapter metadata box

---

cdap-ui/app/directives/navbar/navbarCtrl.js
cdap-ui/app/services/namespace.js

[CDAP-3087] fix the updating of namespace when getList is called

---

cdap-ui/app/directives/group-side-panel/group-side-panel.html
cdap-ui/app/features/adapters/services/adapter-error-factory.js

- Fix error messages
- Fix tooltips inconsistencies

[CDAP-3098] Fix/ui adapter inconsistencies fix

---

cdap-ui/app/features/adapters/templates/create/metadata.html
cdap-ui/app/features/adapters/templates/create/settings.html

*  Updates buttons icons in Metadata + Settings modal headers

updates modal header button icons

---

cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java

[CDAP-2258] some refactoring to return better HTTP codes

---

cdap-ui/app/features/adapters/etlapps.less

*  Modifies CSS selector for plugin modals to prevent unwanted styling of the down modal

changes selector for plugin modal styling

---

cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/sink/DBSink.java
cdap-app-templates/cdap-etl/cdap-etl-lib/src/main/java/co/cask/cdap/template/etl/batch/source/DBSource.java

Fixed bad error messages
